import './news.css';
import Link from 'next/link';
import Segmented from '@/components/Segmented';
import {getNewsV1,getNewsSettings} from '@/lib/news-v1';
import {countryLabel} from '@/lib/country-display';
import {addManualCandidateAction,enrichNewsCandidateAction,excludeNewsCandidateAction,removeManualCandidateAction,restoreAndAddManualAction,requestNewsDiscoveryAction} from './actions';
export const dynamic='force-dynamic';
function qs(p,patch={}){const x=new URLSearchParams();for(const[k,v]of Object.entries({...p,...patch}))if(v!==undefined&&v!==null&&v!=='')x.set(k,String(v));return x.toString()}
function label(rule){return rule==='spain'?'Rescate España 🇪🇸':rule==='manual'?'Manual':'Cumple criterio'}
function typeLabel(type){return type==='movie'?'Película':type==='tvMiniSeries'?'Miniserie':type==='tvSeries'?'Serie':'—'}
function fmtDate(v){if(!v)return '—';try{return new Intl.DateTimeFormat('es-ES',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}catch{return String(v)}}
function countries(r){const c=Array.isArray(r.countries)?r.countries:[];return c.length?c.slice(0,2).map(countryLabel).join(' · '):countryLabel(null)}
function poster(r){const s=r.source_snapshot||{};return s.posterPath?`https://image.tmdb.org/t/p/w500${s.posterPath}`:(s.posterUrl||null)}
function ratingText(r){return r.imdb_rating==null?'Resolviendo…':Number(r.imdb_rating).toFixed(1)}
function votesText(r){return r.imdb_votes==null?'Datos IMDb pendientes':`${Number(r.imdb_votes).toLocaleString('es-ES')} votos`}
function Actions({r}){const manual=r.matched_rule==='manual'||r.source_snapshot?.manual===true;return <div className="card-actions"><form action={enrichNewsCandidateAction}><input type="hidden" name="imdbId" value={r.imdb_id}/><button className="add">＋ Añadir</button></form><form action={excludeNewsCandidateAction}><input type="hidden" name="imdbId" value={r.imdb_id}/><button className="exclude">× Excluir</button></form><a className="imdb-link" href={`https://www.imdb.com/title/${r.imdb_id}/`} target="_blank" rel="noreferrer">IMDb ↗</a>{manual?<form action={removeManualCandidateAction}><input type="hidden" name="imdbId" value={r.imdb_id}/><button className="withdraw">Retirar</button></form>:null}</div>}
function Card({r}){const manual=r.matched_rule==='manual'||r.source_snapshot?.manual===true,p=poster(r);return <article className="news-card"><div className={`news-poster ${p?'has-image':''}`}>{p?<img src={p} alt=""/>:null}<span className={`type-chip ${r.candidate_type==='movie'?'movie':'series'}`}>{typeLabel(r.candidate_type)}</span><span className={`rule-chip ${r.matched_rule==='spain'?'rescue':manual?'manual':''}`}>{label(r.matched_rule)}</span>{!p?<><div className="poster-letter">{String(r.title||'?').slice(0,1)}</div><div className="poster-title">{r.title}</div></>:null}</div><div className="news-card-body"><div className="card-title">{r.title}</div><div className="card-meta">{r.year||'—'} · {countries(r)}</div><div className="card-rating"><b>★ {ratingText(r)}</b><span>IMDb</span></div><div className="card-votes">{votesText(r)}</div>{r.source_snapshot?.overview?<details className="card-more"><summary>Más info</summary><p>{r.source_snapshot.overview}</p></details>:null}<Actions r={r}/></div></article>}
export default async function Novedades({searchParams}){const p=await searchParams||{},type=['all','movie','series'].includes(p.type)?p.type:'all',sort=['new','rating','votes','year'].includes(p.sort)?p.sort:'new',view=p.view==='list'?'list':'grid';const [{rows,stats,excludedCount,latestRun,nextAllowedAt,discoveryAllowed,testOverrideAvailable,page,pageSize},settings]=await Promise.all([getNewsV1({...p,type,sort}),getNewsSettings()]);const canDispatch=discoveryAllowed||testOverrideAvailable;const notices={exists:'Ese IMDb ya está en el catálogo.',excluded:'Ese IMDb está excluido. Puedes restaurarlo explícitamente.',manual_added:'IMDb añadido manualmente. La tarjeta aparece ya identificada y los datos IMDb oficiales se completan con el mismo criterio del Discovery semanal.',manual_resolve_error:'Se añadió el IMDb, pero la resolución inicial falló. El resolver oficial seguirá intentando completar los datos.',restored:'Exclusión retirada y candidato añadido a Novedades.',excluded_now:'Título excluido. No volverá a aparecer hasta restaurarlo.',manual_removed:'Candidato manual retirado de Novedades.',enrich_error:'No se pudo establecer identidad mínima suficiente. Sigue en Novedades para reintentar.',discovery_dispatched:'Discovery solicitado. GitHub Actions lo ejecutará una sola vez.',discovery_dispatched_override:'Discovery de prueba solicitado.',dispatch_not_configured:'Falta configurar la credencial segura de GitHub en Vercel.',dispatch_failed:'GitHub no aceptó la solicitud de discovery.',discovery_blocked:'Discovery bloqueado por la regla semanal.'};return <div className="news-page">
<div className="news-head"><div><div className="eyebrow">✦ DESCUBRIMIENTO</div><h1>Novedades</h1><p>Descubre y revisa títulos que todavía no están en tu catálogo.</p></div><div className="discovery-box"><div><span>✓ Último discovery</span><b>{latestRun?fmtDate(latestRun.finished_at||latestRun.started_at):'Sin ejecución'}</b></div><div><span>◷ Próximo disponible</span><b>{discoveryAllowed?'Ahora':fmtDate(nextAllowedAt)}</b></div>{canDispatch?<form action={requestNewsDiscoveryAction}><button>{discoveryAllowed?'Buscar novedades':'Prueba única'}</button></form>:null}</div></div>
{p.notice&&notices[p.notice]?<div className="info-banner">{notices[p.notice]}{p.imdb?` · ${p.imdb}`:''}</div>:null}{p.notice==='excluded'&&p.imdb?<form action={restoreAndAddManualAction}><input type="hidden" name="imdbId" value={p.imdb}/><button className="button">Restaurar y añadir</button></form>:null}
<div className="news-kpis"><div><b>{stats.total}</b><span>Pendientes de revisar</span></div><div><b>{stats.movies}</b><span>Películas</span></div><div><b>{stats.series}</b><span>Series</span></div><div><b>{stats.spanish_rescues||0}</b><span>Rescates España 🇪🇸</span></div><div><b>{stats.manual||0}</b><span>Añadidos manuales</span></div></div>
<div className="news-toolbar"><div className="news-type"><Segmented value={type} items={[{value:'all',label:`Todas · ${stats.total}`,href:'/novedades?'+qs(p,{type:'all',page:undefined})},{value:'movie',label:`Películas · ${stats.movies}`,href:'/novedades?'+qs(p,{type:'movie',page:undefined})},{value:'series',label:`Series · ${stats.series}`,href:'/novedades?'+qs(p,{type:'series',page:undefined})}]}/></div><form className="news-filter" method="get"><input type="hidden" name="type" value={type}/><input type="hidden" name="pageSize" value={pageSize}/><input type="hidden" name="view" value={view}/><input name="q" defaultValue={p.q||''} placeholder="Buscar por título…"/><select name="sort" defaultValue={sort}><option value="new">Recién detectadas</option><option value="rating">Mejor IMDb</option><option value="votes">Más votos</option><option value="year">Más recientes</option></select><button>Aplicar</button></form><div className="news-view-switch" aria-label="Vista"><span>Vista</span><div><Link className={view==='grid'?'active':''} href={'/novedades?'+qs(p,{view:'grid',page:1})} title="Carátulas">▦</Link><Link className={view==='list'?'active':''} href={'/novedades?'+qs(p,{view:'list',page:1})} title="Tabla">☷</Link></div></div></div>
<div className="news-secondary"><form action={addManualCandidateAction} className="news-manual"><input name="imdbId" required pattern="tt[0-9]+" placeholder="Añadir manualmente · tt1234567"/><button>＋ Añadir</button></form><div><Link href="/novedades/criterios">Ver criterios IMDb →</Link><Link href="/catalogo/excluidas">Excluidas · {excludedCount}</Link></div></div>
{rows.length===0?<div className="empty-state"><b>No hay propuestas con estos filtros</b></div>:view==='grid'?<div className="news-grid">{rows.map(r=><Card key={r.imdb_id} r={r}/>)}</div>:<div className="news-table-wrap"><table className="news-data-table"><thead><tr><th>Título</th><th>Año</th><th>Tipo</th><th>País</th><th>IMDb</th><th>Votos</th><th>Entrada</th><th>Detectada</th><th>Acciones</th></tr></thead><tbody>{rows.map(r=><tr key={r.imdb_id}><td className="news-table-title"><b>{r.title}</b><small>{r.imdb_id}</small></td><td>{r.year||'—'}</td><td>{typeLabel(r.candidate_type)}</td><td>{countries(r)}</td><td className="num">{ratingText(r)}</td><td className="num">{r.imdb_votes==null?'Pendiente':Number(r.imdb_votes).toLocaleString('es-ES')}</td><td><span className={`status ${r.matched_rule==='spain'?'warn':'ok'}`}>{label(r.matched_rule)}</span></td><td>{fmtDate(r.became_eligible_at||r.first_seen_at)}</td><td className="news-table-actions"><Actions r={r}/></td></tr>)}</tbody></table></div>}
<div className="news-pagination"><div>{page>1?<Link className="button secondary" href={'/novedades?'+qs(p,{page:page-1})}>← Anterior</Link>:null}{rows.length===pageSize?<Link className="button secondary" href={'/novedades?'+qs(p,{page:page+1})}>Siguiente →</Link>:null}</div><div className="page-sizes">Por página: {[24,48,96].map(n=><Link key={n} className={n===pageSize?'active':''} href={'/novedades?'+qs(p,{pageSize:n,page:1})}>{n}</Link>)}</div></div>
<div className="news-foot">ⓘ Discovery semanal y altas manuales usan los mismos datasets oficiales de IMDb para tipo, año, puntuación y votos.</div></div>}
