import Link from 'next/link';
import Segmented from '@/components/Segmented';
import {getNewsV1,getNewsSettings} from '@/lib/news-v1';
import {addManualCandidateAction,enrichNewsCandidateAction,excludeNewsCandidateAction,removeManualCandidateAction,requestNewsDiscoveryAction,restoreAndAddManualAction} from './actions';
export const dynamic='force-dynamic';

function qs(p,patch={}){const x=new URLSearchParams();for(const[k,v]of Object.entries({...p,...patch}))if(v!==undefined&&v!==null&&v!=='')x.set(k,String(v));return x.toString()}
function label(rule){return rule==='spain'?'Rescate España 🇪🇸':rule==='manual'?'Añadido manualmente':'Cumple criterio general'}
function typeLabel(type){return type==='movie'?'Película':type==='tvMiniSeries'?'Miniserie':type==='tvSeries'?'Serie':'Tipo pendiente'}
function fmtDate(v){if(!v)return '—';try{return new Intl.DateTimeFormat('es-ES',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}catch{return String(v)}}

export default async function Novedades({searchParams}){
  const p=await searchParams||{},type=['all','movie','series'].includes(p.type)?p.type:'all',sort=['new','rating','votes','year'].includes(p.sort)?p.sort:'new';
  const [{rows,stats,latestRun,latestRequest,page},settings]=await Promise.all([getNewsV1({...p,type,sort}),getNewsSettings()]);
  const notices={queued:'Búsqueda IMDb solicitada. El worker la recogerá en la siguiente ejecución.',exists:'Ese IMDb ya está en el catálogo.',excluded:'Ese IMDb está excluido. Puedes restaurarlo explícitamente.',manual_added:'IMDb añadido manualmente a Novedades.',restored:'Exclusión retirada y candidato añadido a Novedades.',excluded_now:'Título excluido. No volverá a aparecer hasta restaurarlo.',manual_removed:'Candidato manual retirado de Novedades.',enrich_error:'No se pudo ampliar ese título. Sigue en Novedades para reintentar.',settings_saved_queued:'Criterios guardados y nueva búsqueda solicitada.'};
  return <>
    <div className="page-head"><div><div className="eyebrow">Descubrimiento continuo</div><h1>Novedades</h1><p>IMDb detecta nuevos candidatos; tú decides cuáles entran al catálogo.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Link className="button secondary" href="/novedades/criterios">Criterios IMDb</Link><form action={requestNewsDiscoveryAction}><button className="button">Buscar novedades ahora</button></form></div></div>
    {p.notice&&notices[p.notice]?<div className="info-banner">{notices[p.notice]}{p.imdb?` · ${p.imdb}`:''}</div>:null}
    {p.notice==='excluded'&&p.imdb?<form action={restoreAndAddManualAction} style={{marginBottom:16}}><input type="hidden" name="imdbId" value={p.imdb}/><button className="button">Restaurar y añadir a Novedades</button></form>:null}
    <div className="kpi-grid">
      <div className="kpi"><span>Propuestas</span><b>{stats.total}</b></div><div className="kpi"><span>Películas</span><b>{stats.movies}</b></div><div className="kpi"><span>Series</span><b>{stats.series}</b></div><div className="kpi"><span>Rescate España</span><b>{stats.spanish_rescues}</b></div><div className="kpi"><span>Manuales</span><b>{stats.manual}</b></div>
    </div>
    <div className="info-banner">Criterios: películas {settings.movie.general.minRating}+ / {Number(settings.movie.general.minVotes).toLocaleString('es-ES')} votos · series {settings.series.general.minRating}+ / {Number(settings.series.general.minVotes).toLocaleString('es-ES')} · España: {settings.movie.spain.minVotes.toLocaleString('es-ES')} / {settings.series.spain.minVotes.toLocaleString('es-ES')} votos · países excluidos: {settings.excludedCountries.join(', ')}</div>
    <div className="card" style={{marginBottom:18}}><h3>Añadir IMDb manualmente</h3><p>Fuerza un título a Novedades aunque no cumpla los umbrales automáticos.</p><form action={addManualCandidateAction} className="filters ux-filters compact"><input name="imdbId" required pattern="tt[0-9]+" placeholder="tt1234567"/><button>Añadir</button></form></div>
    <div className="filter-bar"><div><span className="filter-label">Tipo</span><Segmented value={type} items={[{value:'all',label:'Todas',href:'/novedades?'+qs(p,{type:'all',page:undefined})},{value:'movie',label:'Películas',href:'/novedades?'+qs(p,{type:'movie',page:undefined})},{value:'series',label:'Series',href:'/novedades?'+qs(p,{type:'series',page:undefined})}]}/></div></div>
    <form className="filters ux-filters compact" method="get"><input type="hidden" name="type" value={type}/><input name="q" defaultValue={p.q||''} placeholder="Buscar título…"/><select name="sort" defaultValue={sort}><option value="new">Recién detectadas</option><option value="rating">Mejor IMDb</option><option value="votes">Más votos</option><option value="year">Más recientes</option></select><button>Aplicar</button><Link className="filter-reset" href="/novedades">Limpiar</Link></form>
    <div className="info-banner">Último discovery: {latestRun?`${latestRun.status} · ${fmtDate(latestRun.finished_at||latestRun.started_at)}`:'todavía sin ejecución V1'}{latestRequest?` · última solicitud ${latestRequest.status} (${fmtDate(latestRequest.requested_at)})`:''}</div>
    {rows.length===0?<div className="empty-state"><b>No hay propuestas con estos filtros</b><p>Puedes solicitar una búsqueda IMDb o añadir un IMDb manualmente.</p></div>:<div className="series-grid">{rows.map(r=>{const manual=r.matched_rule==='manual'||r.source_snapshot?.manual===true;return <article className="series-card" key={r.imdb_id} style={{display:'block'}}><div className="series-body"><div className="eyebrow">{label(r.matched_rule)}</div><h3>{r.title}</h3><p>{r.year||'—'} · {typeLabel(r.candidate_type)}</p><div className="series-stats"><span><b>{r.imdb_rating??'—'}</b> IMDb</span><span><b>{Number(r.imdb_votes||0).toLocaleString('es-ES')}</b> votos</span><span><b>{fmtDate(r.became_eligible_at||r.first_seen_at)}</b> detectada</span></div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}><a className="button secondary" href={`https://www.imdb.com/title/${r.imdb_id}/`} target="_blank" rel="noreferrer">IMDb</a><form action={enrichNewsCandidateAction}><input type="hidden" name="imdbId" value={r.imdb_id}/><button className="button">Añadir y ampliar datos</button></form><form action={excludeNewsCandidateAction}><input type="hidden" name="imdbId" value={r.imdb_id}/><button className="button secondary">Excluir</button></form>{manual?<form action={removeManualCandidateAction}><input type="hidden" name="imdbId" value={r.imdb_id}/><button className="button secondary">Retirar</button></form>:null}</div></div></article>})}</div>}
    <div style={{display:'flex',justifyContent:'space-between',marginTop:20}}>{page>1?<Link className="button secondary" href={'/novedades?'+qs(p,{page:page-1})}>← Anterior</Link>:<span/>}{rows.length===48?<Link className="button secondary" href={'/novedades?'+qs(p,{page:page+1})}>Siguiente →</Link>:null}</div>
  </>
}
