import Link from 'next/link';
import Segmented from '@/components/Segmented';
import {getNewsV1,getNewsSettings} from '@/lib/news-v1';
import {addManualCandidateAction,enrichNewsCandidateAction,excludeNewsCandidateAction,removeManualCandidateAction,restoreAndAddManualAction} from './actions';
export const dynamic='force-dynamic';
const WORKFLOW_URL='https://github.com/pikolugo-a11y/imdb-catalog/actions/workflows/imdb-discovery.yml';
function qs(p,patch={}){const x=new URLSearchParams();for(const[k,v]of Object.entries({...p,...patch}))if(v!==undefined&&v!==null&&v!=='')x.set(k,String(v));return x.toString()}
function label(rule){return rule==='spain'?'Rescate España 🇪🇸':rule==='manual'?'Manual':'General'}
function typeLabel(type){return type==='movie'?'Película':type==='tvMiniSeries'?'Miniserie':type==='tvSeries'?'Serie':'—'}
function fmtDate(v){if(!v)return '—';try{return new Intl.DateTimeFormat('es-ES',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}catch{return String(v)}}
function countries(r){const c=Array.isArray(r.countries)?r.countries:[];return c.length?c.join(', '):'—'}
export default async function Novedades({searchParams}){
 const p=await searchParams||{},type=['all','movie','series'].includes(p.type)?p.type:'all',sort=['new','rating','votes','year'].includes(p.sort)?p.sort:'new';
 const [{rows,stats,excludedCount,latestRun,nextAllowedAt,discoveryAllowed,page,pageSize},settings]=await Promise.all([getNewsV1({...p,type,sort}),getNewsSettings()]);
 const notices={exists:'Ese IMDb ya está en el catálogo.',excluded:'Ese IMDb está excluido. Puedes restaurarlo explícitamente.',manual_added:'IMDb añadido manualmente a Novedades.',restored:'Exclusión retirada y candidato añadido a Novedades.',excluded_now:'Título excluido. No volverá a aparecer hasta restaurarlo.',manual_removed:'Candidato manual retirado de Novedades.',enrich_error:'No se pudo establecer identidad mínima suficiente. Sigue en Novedades para reintentar.'};
 return <div className="news-page">
  <div className="news-head"><div><div className="eyebrow">Descubrimiento IMDb</div><h1>Novedades</h1><p>Candidatos nuevos para decidir rápido qué entra en PikoFilm.</p></div><div className="news-actions"><Link className="button secondary" href="/novedades/criterios">Criterios IMDb</Link><Link className="button secondary" href="/catalogo/excluidas">Excluidas · {excludedCount}</Link><a className={`button ${discoveryAllowed?'':'disabled'}`} href={discoveryAllowed?WORKFLOW_URL:undefined} target={discoveryAllowed?'_blank':undefined} rel="noreferrer">{discoveryAllowed?'Buscar novedades ahora':'Discovery bloqueado 7 días'}</a></div></div>
  {p.notice&&notices[p.notice]?<div className="info-banner">{notices[p.notice]}{p.imdb?` · ${p.imdb}`:''}</div>:null}
  {p.notice==='excluded'&&p.imdb?<form action={restoreAndAddManualAction} className="inline-action"><input type="hidden" name="imdbId" value={p.imdb}/><button className="button">Restaurar y añadir a Novedades</button></form>:null}
  <div className="news-kpis"><div><span>Propuestas</span><b>{stats.total}</b></div><div><span>Películas</span><b>{stats.movies}</b></div><div><span>Series</span><b>{stats.series}</b></div><div><span>Último discovery</span><b className="small">{latestRun?`${latestRun.status} · ${fmtDate(latestRun.finished_at||latestRun.started_at)}`:'Sin ejecución'}</b></div></div>
  <div className="news-meta"><span>General: pelis {settings.movie.general.minRating}+ / {Number(settings.movie.general.minVotes).toLocaleString('es-ES')} votos · series {settings.series.general.minRating}+ / {Number(settings.series.general.minVotes).toLocaleString('es-ES')}</span><span>{discoveryAllowed?'Disponible para ejecución manual':`Próxima ejecución permitida: ${fmtDate(nextAllowedAt)}`}</span></div>
  <div className="news-toolbar"><form action={addManualCandidateAction} className="news-manual"><input name="imdbId" required pattern="tt[0-9]+" placeholder="Añadir IMDb · tt1234567"/><button>Añadir</button></form><div className="news-type"><Segmented value={type} items={[{value:'all',label:`Todas ${stats.total}`,href:'/novedades?'+qs(p,{type:'all',page:undefined})},{value:'movie',label:`Películas ${stats.movies}`,href:'/novedades?'+qs(p,{type:'movie',page:undefined})},{value:'series',label:`Series ${stats.series}`,href:'/novedades?'+qs(p,{type:'series',page:undefined})}]}/></div><form className="news-filter" method="get"><input type="hidden" name="type" value={type}/><input type="hidden" name="pageSize" value={pageSize}/><input name="q" defaultValue={p.q||''} placeholder="Buscar…"/><select name="sort" defaultValue={sort}><option value="new">Recién detectadas</option><option value="rating">Mejor IMDb</option><option value="votes">Más votos</option><option value="year">Más recientes</option></select><button>Aplicar</button></form></div>
  {rows.length===0?<div className="empty-state"><b>No hay propuestas con estos filtros</b></div>:<div className="news-table-wrap"><table className="news-table"><thead><tr><th>Título</th><th>Año</th><th>Tipo</th><th>IMDb</th><th>Votos</th><th>País</th><th>Entrada</th><th>Detectada</th><th>Acciones</th></tr></thead><tbody>{rows.map(r=>{const manual=r.matched_rule==='manual'||r.source_snapshot?.manual===true;return <tr key={r.imdb_id}><td><Link className="title" href={`/novedades/${r.imdb_id}`}>{r.title}</Link><span className="sub">{r.imdb_id}</span></td><td>{r.year||'—'}</td><td>{typeLabel(r.candidate_type)}</td><td><b>{r.imdb_rating??'—'}</b></td><td>{Number(r.imdb_votes||0).toLocaleString('es-ES')}</td><td>{countries(r)}</td><td><span className={`status ${r.matched_rule==='spain'?'warn':'ok'}`}>{label(r.matched_rule)}</span></td><td>{fmtDate(r.became_eligible_at||r.first_seen_at)}</td><td><div className="row-actions"><Link className="button secondary tiny" href={`/novedades/${r.imdb_id}`}>Ver</Link><a className="button secondary tiny" href={`https://www.imdb.com/title/${r.imdb_id}/`} target="_blank" rel="noreferrer">IMDb</a><form action={enrichNewsCandidateAction}><input type="hidden" name="imdbId" value={r.imdb_id}/><button className="button tiny">Añadir</button></form><form action={excludeNewsCandidateAction}><input type="hidden" name="imdbId" value={r.imdb_id}/><button className="button secondary tiny danger-soft">Excluir</button></form>{manual?<form action={removeManualCandidateAction}><input type="hidden" name="imdbId" value={r.imdb_id}/><button className="button secondary tiny">Retirar</button></form>:null}</div></td></tr>})}</tbody></table></div>}
  <div className="news-pagination"><div>{page>1?<Link className="button secondary" href={'/novedades?'+qs(p,{page:page-1})}>← Anterior</Link>:null}{rows.length===pageSize?<Link className="button secondary" href={'/novedades?'+qs(p,{page:page+1})}>Siguiente →</Link>:null}</div><div className="page-sizes">Por página: {[24,48,96].map(n=><Link key={n} className={n===pageSize?'active':''} href={'/novedades?'+qs(p,{pageSize:n,page:1})}>{n}</Link>)}</div></div>
 </div>
}
