import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const source=fs.readFileSync(new URL('../lib/data-quality-unitary.js',import.meta.url),'utf8');
const mdblist=fs.readFileSync(new URL('../lib/ratings-provider-mdblist.js',import.meta.url),'utf8');
const apiLog=fs.readFileSync(new URL('../lib/data-quality-api-log.js',import.meta.url),'utf8');
const dataQuality=fs.readFileSync(new URL('../lib/data-quality.js',import.meta.url),'utf8');
const dataQualityPage=fs.readFileSync(new URL('../lib/data-quality-page.js',import.meta.url),'utf8');
const lifecycleData=fs.readFileSync(new URL('../lib/lifecycle-data-stage.mjs',import.meta.url),'utf8');
const lifecycle=fs.readFileSync(new URL('../lib/lifecycle.js',import.meta.url),'utf8');
const piko=fs.readFileSync(new URL('../lib/pikoscore-v3.js',import.meta.url),'utf8');
const manual=fs.readFileSync(new URL('../lib/data-quality-manual.js',import.meta.url),'utf8');
const page=fs.readFileSync(new URL('../app/calidad/datos/page.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../app/calidad/datos/quality-data.css',import.meta.url),'utf8');

test('CALIDAD Datos recorre fuentes en orden TMDb → OMDb → MDBList',()=>{const tmdb=source.indexOf("['TMDb',refreshTmdb]"),omdb=source.indexOf("['OMDb',refreshOmdb]"),mdb=source.indexOf("['MDBList',refreshMdblist]");assert.ok(tmdb>=0&&omdb>tmdb&&mdb>omdb)});
test('cada proveedor recibe IMDb ID y solo campos pendientes y soportados',()=>{assert.match(source,/wantedFor\(row,source\)/);assert.match(source,/missingFields\(row\)\.filter\(k=>supported\.has\(k\)\)/);assert.match(source,/shouldRun\(row,source\)/);assert.match(source,/fn\(imdbId,new Set\(attempted\)\)/)});
test('Completar datos respeta el tipo validado y no reidentifica ni cambia de medio',()=>{assert.match(source,/mediaFromType\(m\.type\)/);assert.doesNotMatch(source,/\/find\//);assert.doesNotMatch(source,/ensureTmdbIdentity/);assert.doesNotMatch(source,/recoverMediaTypeIfNeeded/);const runs=[...source.matchAll(/await runCascade\(imdbId,/g)];assert.equal(runs.length,1)});
test('TMDb profundiza en episodios, créditos e imágenes cuando el tipo validado es serie',()=>{assert.match(source,/seriesEpisodeFacts/);assert.match(source,/\/episode\/\$\{ref\.episode\}\/credits/);assert.match(source,/\/images\?include_image_language=es,null,en/)});
test('MDBList mantiene separados ratings y metadatos',()=>{assert.match(mdblist,/fetchMDBListRatings/);assert.match(mdblist,/fetchMDBListMetadata/)});
test('CALIDAD conserva logging mínimo solo para errores',()=>{assert.match(apiLog,/provider_http_transport_error/);assert.match(apiLog,/provider_http_error/);assert.doesNotMatch(apiLog,/provider_http_request/);assert.doesNotMatch(apiLog,/provider_http_response/)});
test('la revisión permanece disponible tras avanzar Lifecycle',()=>{assert.match(dataQuality,/MOVIE_FILE_PENDING/);assert.match(dataQuality,/SERIES_REVIEW/);assert.match(dataQuality,/TECH_PENDING/);assert.match(dataQuality,/COMPLETE/)});
test('expires_at nulo usa la frescura calculada',()=>{assert.match(dataQuality,/explicit=r\.expires_at\?new Date\(r\.expires_at\)\.getTime\(\):NaN/)});
test('duración de serie cuenta para cobertura pero no bloquea el avance',()=>{assert.match(dataQuality,/effectiveSeverity=\(k,r\)=>k==='runtime'&&isSeries\(r\)\?'optional'/)});
test('CALIDAD clasifica una sola vez, pagina 25 e hidrata solo visibles',()=>{assert.match(dataQualityPage,/const PAGE_SIZE=25/);assert.match(dataQualityPage,/getDataQualityView/);assert.match(dataQualityPage,/count\(\*\) OVER\(\)/);assert.match(dataQualityPage,/async function hydrate\(ids\)/);assert.match(dataQualityPage,/m\.imdb_id=ANY\(\$1::text\[\]\)/);assert.match(dataQualityPage,/overview AS/);assert.match(page,/getDataQualityView/)});
test('Datos no crea un main anidado y respeta el ancho del shell',()=>{assert.doesNotMatch(page,/return <main className="dq-page"/);assert.match(page,/return <div className="dq-page"/);assert.match(css,/\.dq-page\{[^}]*width:100%/);assert.doesNotMatch(css,/100vw|translateX\(|margin-left:50%/)});
test('decisión manual de datos atraviesa evaluación y Lifecycle',()=>{assert.match(dataQuality,/manualDataAccepted/);assert.match(lifecycleData,/accepted_incomplete/);assert.match(lifecycle,/manual_data_decision/);assert.match(manual,/acceptIncompleteData/)});
test('ratings manuales y cierre fijo a 5 quedan persistentes',()=>{assert.match(manual,/saveManualRating/);assert.match(manual,/fixRatingsAtFive/);assert.match(manual,/final_rating=5/);assert.match(dataQuality,/manualRatingsFixed/);assert.match(piko,/manual_rating_decision/);assert.match(page,/DataQualityManualControls/)});
test('la pantalla incorpora contexto Plex, mejora y exclusión existente',()=>{assert.match(dataQualityPage,/in_plex/);assert.match(page,/En Plex/);assert.match(page,/Fuera de Plex/);assert.match(page,/Mejorar datos/);assert.match(page,/IdentityExcludeButton/)});
test('la identidad muestra accesos externos fiables y mantiene IMDb visible',()=>{assert.match(page,/providerUrl\('imdb'/);assert.match(page,/providerUrl\('tmdb'/);assert.match(page,/providerUrl\('mdblist'/);assert.match(page,/providerUrl\('trakt'/);assert.match(page,/<code>\{r\.imdb_id\}<\/code>/);assert.doesNotMatch(page,/FilmAffinity|filmaffinity|FA ↗/i)});
