import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(p,import.meta.url),'utf8');
const orchestration=read('../lib/identity-validation-batch.js');
const canonical=read('../lib/identity-validation-canonical.mjs');
const apiWorker=read('../worker/batch-api-worker.mjs');
const fastWorker=read('../worker/batch-fast-worker.mjs');
const individual=read('../lib/identity-validation.js');
const lifecycle=read('../lib/lifecycle.js');
const lifecycleCore=read('../lib/lifecycle-recompute-core.mjs');
const layout=read('../app/calidad/validacion-identidad/layout.js');
const panel=read('../components/IdentityValidationBatchPanel.js');
test('IV-001 Batch usa pool API y sólo selecciona evidencia pendiente',()=>{assert.match(orchestration,/'PROC-IV-001':\{pool:'api',concurrency:2/);assert.match(orchestration,/m\.tmdb_id IS NOT NULL AND NOT \(v\.tmdb_id=m\.tmdb_id/);assert.match(orchestration,/lifecycle_state='IDENTITY_VALIDATION'/)});
test('IV-002 Batch usa pool FAST y sólo selecciona evidencia lista',()=>{assert.match(orchestration,/'PROC-IV-002':\{pool:'fast',concurrency:8/);assert.match(orchestration,/JOIN identity_validation v/);assert.match(orchestration,/AND v\.tmdb_id=m\.tmdb_id AND \(\(v\.imdb_original_title IS NOT NULL/)});
test('elegibilidad IV usa SQL ejecutable y no intenta interpolar un query result como fragmento',()=>{assert.doesNotMatch(orchestration,/readySql|\$\{ready\}/)});
test('Batch IV nunca se inicia automáticamente',()=>{assert.doesNotMatch(orchestration,/setInterval|cron|schedule/i);assert.match(panel,/Nunca|sólo arranca cuando lo ordenas/i);assert.match(panel,/startIv001BatchAction/);assert.match(panel,/startIv002BatchAction/)});
test('IV-001 manual y Batch comparten exactamente el núcleo funcional',()=>{assert.match(individual,/refreshIdentityEvidenceCanonical/);assert.match(apiWorker,/refreshIdentityEvidenceCanonical/);assert.match(apiWorker,/'PROC-IV-001'/)});
test('IV-002 manual y Batch comparten exactamente el núcleo funcional',()=>{assert.match(individual,/validateIdentityCanonical/);assert.match(fastWorker,/validateIdentityCanonical/);assert.match(fastWorker,/'PROC-IV-002'/)});
test('IV-001 usa gobierno compartido TMDb y OMDb y cuenta tres llamadas TMDb',()=>{assert.match(apiWorker,/createApiGate\(sql,\{batchRunId:item\.batch_run_id\}\)/);assert.match(canonical,/externalCall\?\.\(3\)/);assert.match(canonical,/gatedJson\(apiGate,'tmdb'/);assert.match(canonical,/gatedJson\(apiGate,'omdb'/)});
test('IV-002 no realiza llamadas externas',()=>{const body=canonical.slice(canonical.indexOf('export async function validateIdentityCanonical'));assert.doesNotMatch(body,/gatedJson|externalCall/)});
test('Individual y workers comparten el mismo recomputador Lifecycle',()=>{assert.match(lifecycle,/recomputeLifecycleWithSql/);assert.match(apiWorker,/recomputeLifecycleWithSql/);assert.match(fastWorker,/recomputeLifecycleWithSql/);assert.match(lifecycleCore,/export async function recomputeLifecycleWithSql/)});
test('UI monta ambos Batch y refresca mientras alguno esté activo',()=>{assert.match(layout,/IdentityValidationBatchPanel/);assert.match(layout,/IdentityBatchAutoRefresh/);assert.match(layout,/state\.iv001\.active\|\|state\.iv002\.active/)});
test('Legacy FilmAffinity no forma parte del nuevo núcleo ni adapters',()=>{assert.doesNotMatch(canonical,/FilmAffinity|faEvidence/);assert.doesNotMatch(apiWorker,/faEvidence|lifecycle-validation-executor/);assert.doesNotMatch(fastWorker,/faEvidence|lifecycle-validation-executor/)});
