import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(p,import.meta.url),'utf8');
const batch=read('../lib/batch-control.js');
const metrics=read('../lib/batch-ui-metrics.js');
const actions=read('../app/calidad/validacion-identidad/actions.js');
const page=read('../app/calidad/validacion-identidad/page.js');
const model=read('../lib/identity-validation-page.js');
const validation=read('../lib/identity-validation.js');
const display=read('../lib/process-display.js');
test('BATCH conserva IDENTITY_VALIDATION como etapa canónica',()=>{assert.match(batch,/['"]IDENTITY_VALIDATION['"]/);assert.match(metrics,/cl\.lifecycle_state=\$1/)});
test('CALIDAD individual recomputa Lifecycle tras evidencia, validación e IDs',()=>{assert.ok((actions.match(/recomputeLifecycleForIds/g)||[]).length>=5)});
test('IV-001 usa el runtime común sin mezclar IV-002',()=>{const start=actions.indexOf('export async function refreshIdentityEvidenceAction');const end=actions.indexOf('export async function revalidateIdentityAction');const body=actions.slice(start,end);assert.match(body,/executeObservedProcess/);assert.match(body,/processCode:'PROC-IV-001'/);assert.match(body,/refreshIdentityEvidence\(imdbId,trace\)/);assert.doesNotMatch(body,/validateOne\(/);assert.doesNotMatch(body,/audit\(/)});
test('IV-001 distingue evidencia preparada de evidencia pendiente',()=>{assert.match(actions,/functionalResult:r\.complete\?'updated':'pending'/);assert.match(actions,/status:'duplicate'/)});
test('IV-001 cuenta fuentes externas y mantiene OMDb como fallback',()=>{assert.match(validation,/trace\?\.externalCall\?\.\(3\)/);assert.match(validation,/trace\?\.externalCall\?\.\(1\)/);assert.match(validation,/imdb_omdb_fallback/);assert.match(validation,/tmdb_evidence/)});
test('IV-001 aparece con nombre humano en Operaciones',()=>{assert.match(display,/'PROC-IV-001':\{name:'Obtener evidencia de identidad'\}/);assert.match(display,/calidad_validacion_identidad_manual:'Manual desde Validación de identidad'/)});
test('IV-002 usa el runtime común sin volver a obtener evidencia',()=>{const start=actions.indexOf('export async function revalidateIdentityAction');const end=actions.indexOf('export async function saveIdentityIdsAction');const body=actions.slice(start,end);assert.match(body,/executeObservedProcess/);assert.match(body,/processCode:'PROC-IV-002'/);assert.match(body,/validateOne\(imdbId,trace\)/);assert.doesNotMatch(body,/refreshIdentityEvidence\(/);assert.doesNotMatch(body,/audit\(/)});
test('IV-002 separa resultado técnico y funcional',()=>{assert.match(actions,/v\.status==='valid'\?'updated':v\.status==='insufficient'\?'pending':'blocked'/);assert.match(actions,/technicalStatus:'succeeded'/);assert.match(actions,/status:'duplicate'/)});
test('IV-002 puntúa evidencia guardada sin llamadas externas',()=>{assert.match(validation,/export async function validateOne\(imdbId,trace=null\)/);assert.match(validation,/step:'score_identity'/);const start=validation.indexOf('export async function validateOne');const body=validation.slice(start);assert.doesNotMatch(body,/externalCall/)});
test('IV-002 preserva decisión manual compatible y la deja visible en la traza',()=>{assert.match(validation,/manualApplied=validManual/);assert.match(validation,/manual_applied:manualApplied/);assert.match(actions,/manual_applied:Boolean\(v\.manualApplied\)/)});
test('IV-002 aparece con nombre humano en Operaciones',()=>{assert.match(display,/'PROC-IV-002':\{name:'Validar identidad'\}/)});
test('editar IDs invalida evidencia y preserva detección de cambio de contexto BATCH',()=>{assert.match(actions,/validation_status='pending_data'/);assert.match(actions,/validation_details='\{\}'::jsonb/);assert.match(metrics,/COALESCE\(m\.tmdb_id,''\)/)});
test('resolver manualmente limpia manual_review de BATCH para evitar estado paralelo',()=>{assert.match(actions,/stage='IDENTITY_VALIDATION'/);assert.match(actions,/manual_review=false/)});
test('Validación reutiliza la exclusión canónica y no implementa batch masivo',()=>{assert.match(page,/IdentityExcludeButton/);assert.doesNotMatch(page,/createBatch|createFlexibleStageRun|seleccionar.*todos/i)});
test('read model usa Lifecycle canónico, exclusiones y Plex local',()=>{assert.match(model,/IDENTITY_VALIDATION/);assert.match(model,/catalog_exclusions/);assert.match(model,/catalog_read_model/);assert.match(model,/effective_status/)});
