import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
test('SER-003 manual y Batch comparten core canónico',()=>{const manual=read('lib/series-unitary.js'),worker=read('worker/batch-api-worker.mjs');assert.match(manual,/refreshSeriesUnitaryCanonical/);assert.match(worker,/refreshSeriesUnitaryCanonical/);assert.match(worker,/'PROC-SER-003'/)});
test('SER-004 manual y Batch comparten core canónico',()=>{const manual=read('lib/series-es-availability.js'),worker=read('worker/batch-api-worker.mjs'),core=read('lib/series-es-availability-core.mjs');assert.match(manual,/confirmSeriesEsAvailabilityCanonical/);assert.match(worker,/confirmSeriesEsAvailabilityCanonical/);assert.match(worker,/'PROC-SER-004'/);assert.match(core,/tmdb_season_watch_providers/);assert.match(core,/watchmode_episode_witness_es/)});
test('Series Batch usa pool API, concurrencia 2 y escalado 1 5 25 todas',()=>{const batch=read('lib/series-batch.js'),ui=read('components/SeriesBatchPanel.js');assert.match(batch,/pool:'api',concurrency:2/);for(const x of ['value="1"','value="5"','value="25"','value=""'])assert.match(ui,new RegExp(x));assert.match(ui,/batch-hub/);assert.match(ui,/batch-process/);assert.match(ui,/sólo arranca cuando lo ordenas/)});
test('SER-004 selecciona sólo UNKNOWN vencidos y SER-003 respeta next_check_at',()=>{const batch=read('lib/series-batch.js');assert.match(batch,/availability_unknown/);assert.match(batch,/series_season_availability/);assert.match(batch,/a\.checked_at IS NULL OR a\.checked_at<=now\(\)-interval '14 days'/);assert.match(batch,/next_check_at<=now\(\)/);assert.match(batch,/plex_invalidated_at IS NOT NULL/)});
test('SER-003 y SER-004 liberan el permiso real del API gate',()=>{for(const path of ['lib/series-unitary-core.mjs','lib/series-es-availability-core.mjs']){const core=read(path);assert.match(core,/release\?\.\(permit\)/);assert.doesNotMatch(core,/release\?\.\('tmdb'/)}});
test('Batch persiste errores observables con INSERT SQL cerrado',()=>{const runtime=read('lib/batch-worker-runtime.mjs');assert.match(runtime,/\$\{json\(detail\)\}::jsonb\)`/)});
test('SER-003 y SER-004 refrescan el read model visible al terminar cada item Batch',()=>{const worker=read('worker/batch-api-worker.mjs'),projection=read('lib/series-quality-read-model-core.mjs');assert.match(worker,/rebuildSeriesQualityReadModelForRatingKey/);assert.equal((worker.match(/rebuildSeriesQualityReadModelForRatingKey\(sql,r\.ratingKey\)/g)||[]).length,2);assert.match(projection,/WHERE p\.active AND p\.item_type='show' AND p\.rating_key=\$\{key\}/);assert.match(projection,/ON CONFLICT\(show_rating_key\) DO UPDATE/)});
