import Link from 'next/link';
import {Poster} from '@/components/MediaCard';
import {getMovieQualityDashboard} from '@/lib/movie-quality-dashboard';
import {qualityAction,validateMovieFileAction} from '@/app/actions';
import {saveMovieQualitySettingsAction,correctedMovieResetAction} from './actions';
import './movie-quality.css';
export const dynamic='force-dynamic';

const labels={duration:'Duración sospechosa',filename:'Nombre sospechoso',duplicate:'Varias versiones'};
const tone={duration:'duration',filename:'filename',duplicate:'duplicate'};
const nf=n=>Number(n||0).toLocaleString('es-ES');
const size=n=>n?`${(Number(n)/1073741824).toFixed(2)} GB`:'—';
function qs(p,patch={}){const x=new URLSearchParams();for(const[k,v]of Object.entries({...p,...patch}))if(v!==undefined&&v!==null&&v!=='')x.set(k,String(v));return x.toString()}
function riskLabel(r){return r>=85?'CRÍTICO':r>=65?'ALTO':r>=40?'MEDIO':'BAJO'}
function typeCount(types,key){return types.find(x=>x.finding_type===key)?.total||0}
function tech(r){return [r.resolution||((r.width||r.height)?`${r.width||'—'}×${r.height||'—'}`:null),r.video_codec?.toUpperCase(),r.audio_codec?.toUpperCase(),r.bitrate?`${nf(r.bitrate)} kbps`:null,size(r.file_size_bytes)].filter(Boolean).join(' · ')}
function Diagnostic({r}){const d=r.details||{};if(r.finding_type==='duration')return <div className="mq-diagnostic"><div className="mq-compare"><div><span>PLEX</span><strong>{d.plex_minutes??'—'} min</strong></div><b>→</b><div><span>REFERENCIA</span><strong>{d.catalog_minutes??'—'} min</strong></div></div><p className="mq-warning">⚠ {d.direction==='shorter'?'El archivo es más corto':'El archivo es más largo'} en aproximadamente <b>{d.diff_minutes??'—'} minutos</b> ({d.diff_pct??'—'}%).</p></div>;if(r.finding_type==='filename')return <div className="mq-diagnostic"><dl><div><dt>PLEX</dt><dd>{d.plex_title||r.plex_title}</dd></div><div><dt>ARCHIVO</dt><dd>{String(d.file||r.file_path||'—').split('/').pop()}</dd></div><div><dt>SIMILITUD</dt><dd>{Math.round(Number(d.best_similarity||0)*100)}%</dd></div></dl><p className="mq-warning">⚠ El nombre del archivo no parece corresponder suficientemente con el título{d.year_mismatch?' y además el año no coincide.':'.'}</p></div>;const versions=Array.isArray(d.versions)?d.versions:[];return <div className="mq-diagnostic"><b>{d.media_count||versions.length} archivos/versiones asociados</b><div className="mq-version-list">{versions.slice(0,5).map((v,i)=><div key={`${v.rating_key}-${v.media_index}-${i}`}><span>{String(v.file||'Archivo').split('/').pop()}</span><b>{v.resolution||'—'}</b><small>{size(v.size)}</small></div>)}</div><p className="mq-warning">⚠ {d.recommendation||'Revisa si son duplicados reales o montajes diferentes.'}</p></div>}

export default async function CalidadPeliculas({searchParams}){
 const p=await searchParams,type=p.type||'',d=await getMovieQualityDashboard({...p,type}),s=d.summary,settings=d.settings;
 return <div className="movie-quality-v3">
  <div className="breadcrumbs"><Link href="/calidad">Calidad</Link><span>›</span><b>Películas</b></div>
  <div className="mq-head"><div><div className="eyebrow">Paso de ciclo · archivo físico</div><h1>Validación de películas</h1><p>Primero se analizan las películas pendientes, una a una. Si no hay incidencias pasan a PikoQuality; si aparece una incidencia, queda aquí para decidir.</p></div></div>
  <section className="mq-overview"><div className="mq-attention"><strong>{nf(s.affected)}</strong><span>casos abiertos</span></div><div className="mq-priority"><b>{nf(s.pending_analysis)} pendientes de analizar</b><small>{nf(s.review_affected)} con incidencia pendiente de decisión</small></div></section>
  <section className="mq-kpis"><div className="mq-kpi"><strong>{nf(s.pending_analysis)}</strong><span>Pendientes de análisis</span><small>pulsa Analizar película</small></div>{Object.keys(labels).map(k=><Link key={k} href={'/calidad/peliculas?'+qs(p,{type:k,page:1})} className={`mq-kpi mq-${tone[k]}`}><strong>{nf(typeCount(s.types,k))}</strong><span>{labels[k]}</span><small>incidencias de esta fase</small></Link>)}</section>
  <div className="mq-toolbar"><div className="mq-type-links"><Link className={!type?'active':''} href={'/calidad/peliculas?'+qs(p,{type:'',page:1})}>Todos</Link>{Object.entries(labels).map(([k,v])=><Link className={type===k?'active':''} key={k} href={'/calidad/peliculas?'+qs(p,{type:k,page:1})}>{v}</Link>)}</div><form method="get" className="mq-search"><input type="hidden" name="type" value={type}/><input name="q" defaultValue={p.q||''} placeholder="Buscar película…"/><select name="risk" defaultValue={p.risk||''}><option value="">Todos los riesgos</option><option value="high">Solo alto y crítico</option></select><button>Filtrar</button></form></div>
  <details className="mq-settings"><summary>⚙ Criterios de análisis</summary><form action={saveMovieQualitySettingsAction}><label>Diferencia mínima de duración<input name="durationMinMinutes" type="number" min="1" max="180" step="1" defaultValue={settings.duration.minMinutes}/><small>minutos</small></label><label>Diferencia mínima de duración<input name="durationMinPercent" type="number" min="1" max="100" step="1" defaultValue={settings.duration.minPercent}/><small>%</small></label><label>Similitud mínima del nombre<input name="filenameMinSimilarityPct" type="number" min="10" max="100" step="1" defaultValue={Math.round(settings.filename.minSimilarity*100)}/><small>%</small></label><label>Versiones casi idénticas<input name="duplicateVerySimilarPercent" type="number" min="0" max="50" step="0.5" defaultValue={settings.duplicates.verySimilarPercent}/><small>% diferencia duración</small></label><label>Montaje distinto a partir de<input name="duplicateDifferentCutPercent" type="number" min="0" max="100" step="0.5" defaultValue={settings.duplicates.differentCutPercent}/><small>% diferencia duración</small></label><button>Guardar criterios</button></form></details>
  {d.rows.length===0?<div className="empty-state"><b>No hay películas pendientes en esta fase</b><p>Las que ya pasaron correctamente continúan a PikoQuality.</p></div>:<div className="mq-list">{d.rows.map(r=>r.case_kind==='pending_analysis'?<article key={`pending-${r.imdb_id}`} className="mq-card"><div className="mq-media"><Poster path={r.poster_path} title={r.plex_title}/><div><h2>{r.plex_title||r.rating_key}</h2><span>{r.plex_year||'—'}</span><b className="mq-badge">Pendiente de análisis</b><small>{tech(r)||'Archivo físico localizado en Plex'}</small></div></div><div className="mq-body"><p>Esta película todavía no ha pasado la validación del archivo actual. Se comprobarán duración, nombre/año del archivo y posibles versiones duplicadas usando los mismos criterios del proceso masivo anterior.</p>{r.file_path&&<details className="mq-file"><summary>Ver archivo</summary><code>{r.file_path}</code></details>}</div><div className="mq-actions"><form action={validateMovieFileAction}><input type="hidden" name="imdbId" value={r.imdb_id}/><button className="ok">Analizar película</button><small>Proceso unitario · una película cada vez</small></form></div></article>:<article key={r.id} className={`mq-card severity-${r.severity}`}><div className="mq-media"><Poster path={r.poster_path} title={r.plex_title}/><div><h2>{r.plex_title||r.rating_key}</h2><span>{r.plex_year||'—'}</span><b className={`mq-badge mq-${tone[r.finding_type]}`}>{labels[r.finding_type]||r.finding_type}</b><small>Riesgo <strong>{riskLabel(r.risk_score)}</strong> · {r.risk_score}/100</small></div></div><div className="mq-body"><Diagnostic r={r}/>{r.finding_type!=='duplicate'&&<div className="mq-tech">{tech(r)}</div>}{r.file_path&&<details className="mq-file"><summary>Ver archivo</summary><code>{r.file_path}</code></details>}</div><div className="mq-actions"><form action={qualityAction}><input type="hidden" name="id" value={r.id}/><input type="hidden" name="action" value="exception"/><button className="ok">✓ Es correcta</button><small>Acepta la incidencia y pasa a PikoQuality</small></form><form action={correctedMovieResetAction}><input type="hidden" name="id" value={r.id}/><button className="fixed">Ya la corregí</button><small>Sale del catálogo y volverá por Novedades tras sincronizar Plex</small></form></div></article>)}</div>}
  <div className="mq-foot"><span>Mostrando {d.total?((d.page-1)*d.pageSize+1):0}–{Math.min(d.page*d.pageSize,d.total)} de {d.total}</span><nav>{d.page>1&&<Link href={'/calidad/peliculas?'+qs(p,{page:d.page-1})}>←</Link>}<b>{d.page}</b><span>de {d.pages}</span>{d.page<d.pages&&<Link href={'/calidad/peliculas?'+qs(p,{page:d.page+1})}>→</Link>}</nav></div>
 </div>
}
