import crypto from 'node:crypto';
import {db} from '@/lib/db';
import {resolveTmdbOnly,wikidataFaBatch,wikidataFaByTmdbBatch,wikidataFaRetryBatch,searchFaBrave,saveIdentity} from '@/lib/identity-resolver';
export const dynamic='force-dynamic';
export const maxDuration=60;
const workerToken=()=>crypto.createHash('sha256').update(String(process.env.DATABASE_URL||'')).digest('hex');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function searchFaPython(origin,row){const c=new AbortController(),t=setTimeout(()=>c.abort(),25000),started=Date.now();try{const r=await fetch(`${origin}/api/fa-search`,{method:'POST',headers:{'content-type':'application/json','x-pikofilm-worker':workerToken()},body:JSON.stringify({imdb_id:row.imdb_id,type:row.type,title:row.title,title_es:row.title_es,original_title:row.original_title,year:row.year}),signal:c.signal,cache:'no-store'}),raw=await r.text();let data={};try{data=JSON.parse(raw)}catch{data={ok:false,status:'error',error:raw.slice(0,240)}}if(!r.ok&&!data.status)data.status='error';return{...data,http_status:r.status,elapsed_ms:Number(data.elapsed_s||0)*1000||Date.now()-started}}catch(e){return{ok:false,status:/abort/i.test(String(e?.name||e?.message))?'timeout':'error',fa_id:null,error:e?.message||String(e),http_status:null,elapsed_ms:Date.now()-started}}finally{clearTimeout(t)}}
export async function POST(req){
 if(!process.env.DATABASE_URL||req.headers.get('x-pikofilm-worker')!==workerToken())return Response.json({ok:false,error:'unauthorized'},{status:401});
 const body=await req.json().catch(()=>({})),runId=Number(body.runId||0),ids=Array.isArray(body.ids)?body.ids.map(String).filter(x=>/^tt\d+$/.test(x)).slice(0,8):[],mode=String(body.mode||'auto'),origin=new URL(req.url).origin;
 if(!runId||!ids.length)return Response.json({ok:false,error:'invalid_batch'},{status:400});const sql=db(),[run]=await sql`SELECT status,summary FROM pipeline_runs WHERE id=${runId} AND job_type='identity_scan'`;
 if(!run||run.status!=='running'||run.summary?.cancel_requested)return Response.json({ok:false,cancelled:true},{status:409});
 const rows=await sql`SELECT imdb_id,type,title,title_es,original_title,year,tmdb_id,fa_id FROM movies WHERE imdb_id=ANY(${ids})`,by=new Map(rows.map(x=>[x.imdb_id,x])),out=[];
 let wi={map:{},error:null,ms:0},wt={map:{},error:null,ms:0,requests:0},wr={map:{},error:null,ms:0};
 if(mode==='fa'||mode==='fa_test'){
   const pending=rows.filter(x=>!x.fa_id);wi=await wikidataFaBatch(pending.map(x=>x.imdb_id));
   const afterImdb=pending.filter(x=>!wi.map[x.imdb_id]&&x.tmdb_id);wt=await wikidataFaByTmdbBatch(afterImdb);
   const afterTmdb=afterImdb.filter(x=>!wt.map[String(x.tmdb_id)]);if(afterTmdb.length&&!(wi.error||wt.error)?.includes?.('429'))wr=await wikidataFaRetryBatch(afterTmdb.map(x=>x.imdb_id));
 }
 let braveHits=0,braveBlocked=0,braveNoCandidate=0,pythonHits=0,pythonAmbiguous=0,pythonNotFound=0,pythonErrors=0,pythonBlocked=0,pythonCalls=0,notFound=0,pythonCircuit=false;
 for(const imdbId of ids){const [state]=await sql`SELECT status,summary FROM pipeline_runs WHERE id=${runId}`;if(!state||state.status!=='running'||state.summary?.cancel_requested)return Response.json({ok:true,cancelled:true,results:out});const row=by.get(imdbId);if(!row){out.push({imdbId,ok:false,error:'Título no encontrado'});continue}try{let tmdbId=null,faId=null,method=[],brave=null,pythonFa=null;
   if(mode==='tmdb'&&!row.tmdb_id){tmdbId=await resolveTmdbOnly(imdbId,row.type);if(tmdbId)method.push('tmdb_imdb')}
   if((mode==='fa'||mode==='fa_test')&&!row.fa_id){faId=wi.map[imdbId]||null;if(faId)method.push('wikidata_imdb');if(!faId&&row.tmdb_id){faId=wt.map[String(row.tmdb_id)]||null;if(faId)method.push('wikidata_tmdb')}if(!faId){faId=wr.map[imdbId]||null;if(faId)method.push('wikidata_retry')}
     if(!faId&&mode==='fa'){
       if(pythonCircuit){pythonFa={ok:false,status:'circuit_open',fa_id:null,error:'Python FA detenido por bloqueo previo en este bloque'};pythonErrors++;notFound++;method.push('fa_python_circuit_open')}
       else{if(pythonCalls>0)await sleep(2500);pythonFa=await searchFaPython(origin,row);pythonCalls++;faId=pythonFa.fa_id?String(pythonFa.fa_id):null;if(faId){method.push(`fa_python_${pythonFa.status||'high'}`);pythonHits++}else if(pythonFa.status==='ambiguous'){method.push('fa_python_ambiguous');pythonAmbiguous++;notFound++}else if(pythonFa.status==='not_found'){method.push('fa_python_not_found');pythonNotFound++;notFound++}else if(pythonFa.status==='blocked'){method.push('fa_python_blocked');pythonBlocked++;notFound++;pythonCircuit=true}else{method.push('fa_python_error');pythonErrors++;notFound++}}
     }
     if(!faId&&mode==='fa_test'){brave=await searchFaBrave(row,{singleQuery:true});faId=brave.faId;if(faId){method.push('fa_brave');braveHits++}else if(brave.blocked){method.push('fa_brave_blocked');braveBlocked++}else{method.push('fa_brave_not_found');braveNoCandidate++;notFound++}}
   }
   if(tmdbId||faId)await saveIdentity(imdbId,{tmdbId,faId,method:method.join('+')});out.push({imdbId,ok:true,updated:Boolean(tmdbId||faId),tmdbId,faId,method:method.join('+')||'already_complete',python:pythonFa?{status:pythonFa.status||null,confidence:Number(pythonFa.confidence||0),margin:Number(pythonFa.margin||0),candidates:Array.isArray(pythonFa.candidates)?pythonFa.candidates.slice(0,5):[],verified:pythonFa.verified||null,error:pythonFa.error||null,http_status:pythonFa.http_status??null,elapsed_ms:Number(pythonFa.elapsed_ms||0),fa_id:pythonFa.fa_id||null}:null,brave:brave?{blocked:Boolean(brave.blocked),blocked_reason:brave.blockedReason||null,status:brave.status||null,error:brave.error||null,requests:Number(brave.requests||0),query:brave.query||null,elapsed_ms:Number(brave.elapsedMs||0),candidates:Number(brave.candidates||0),fa_id:brave.faId||null}:null});
 }catch(e){out.push({imdbId,ok:false,error:e?.message||String(e)})}}
 const py={python_fa:pythonHits,python_ambiguous:pythonAmbiguous,python_not_found:pythonNotFound,python_errors:pythonErrors,python_blocked:pythonBlocked,python_calls:pythonCalls,python_delay_ms:2500};
 if(mode==='fa'&&(pythonCalls||pythonCircuit)){await sql`UPDATE pipeline_runs SET summary=COALESCE(summary,'{}'::jsonb)||jsonb_build_object('fa_strategy','wikidata_then_python','python_fa',COALESCE((summary->>'python_fa')::int,0)+${pythonHits},'python_ambiguous',COALESCE((summary->>'python_ambiguous')::int,0)+${pythonAmbiguous},'python_not_found',COALESCE((summary->>'python_not_found')::int,0)+${pythonNotFound},'python_errors',COALESCE((summary->>'python_errors')::int,0)+${pythonErrors},'python_blocked',COALESCE((summary->>'python_blocked')::int,0)+${pythonBlocked},'python_calls',COALESCE((summary->>'python_calls')::int,0)+${pythonCalls},'python_delay_ms',2500),updated_at=now() WHERE id=${runId}`;await sql`INSERT INTO admin_events(event_type,entity_type,entity_id,action,payload,created_at) VALUES('identity','identity_refresh',${String(runId)},'fa_python_batch',${JSON.stringify({...py,items:out.filter(x=>x.python).map(x=>({imdb_id:x.imdbId,status:x.python.status,fa_id:x.python.fa_id,confidence:x.python.confidence})).slice(0,8)})}::jsonb,now())`}
 if(pythonBlocked){await sql`UPDATE pipeline_runs SET summary=COALESCE(summary,'{}'::jsonb)||jsonb_build_object('cancel_requested',true,'stage','python_blocked','current_block','FilmAffinity · Python detenido por bloqueo','python_blocked_at',now()),updated_at=now() WHERE id=${runId}`;await sql`INSERT INTO admin_events(event_type,entity_type,entity_id,action,payload,created_at) VALUES('identity','identity_refresh',${String(runId)},'fa_python_blocked',${JSON.stringify({python_blocked:pythonBlocked,python_calls:pythonCalls})}::jsonb,now())`}
 return Response.json({ok:true,results:out,stats:{wikidata_imdb:Object.keys(wi.map).length,wikidata_tmdb:Object.keys(wt.map).length,wikidata_retry:Object.keys(wr.map).length,...py,brave_fa:braveHits,brave_blocked:braveBlocked,brave_no_candidate:braveNoCandidate,not_found:notFound},wikidata:{imdb_error:wi.error,tmdb_error:wt.error,retry_error:wr.error,ms:Number(wi.ms||0)+Number(wt.ms||0)+Number(wr.ms||0)}});
}
