import Link from '@/components/NoPrefetchLink';
import {getActivityTimeline,getActivityCalendar,getActivitySummary,getActivityRunDetail} from '@/lib/activity-v4';
import {reschedulePlan,setPlanPriority,togglePlanProtection,toggleDeliberatePeak,recalculatePlanningNow} from './actions';
import ActivityRefresh from './ActivityRefresh';
import './actividad-v4.css';

export const dynamic='force-dynamic';
const TZ='Europe/Madrid';
const FILTERS=[['todo','Todo'],['catalogo','Catálogo'],['plex','Plex'],['calidad','Calidad'],['personas','Personas'],['sagas','Sagas'],['novedades','Novedades'],['errores','Errores']];
const fmtDate=v=>new Intl.DateTimeFormat('es-ES',{timeZone:TZ,day:'2-digit',month:'short',year:'numeric'}).format(new Date(v));
const fmtTime=v=>new Intl.DateTimeFormat('es-ES',{timeZone:TZ,hour:'2-digit',minute:'2-digit'}).format(new Date(v));
const dateKey=v=>new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(v));
function madridInputValue(v){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(v)).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return `${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}`;}
function dayLabel(value){const key=dateKey(value),today=dateKey(Date.now()),yesterday=dateKey(Date.now()-86400000);return key===today?'Hoy':key===yesterday?'Ayer':fmtDate(value)}
function href(base,params){const q=new URLSearchParams(Object.entries(params).filter(([,v])=>v!==undefined&&v!==null&&v!==''));return `${base}?${q}`;}
function groupTimeline(items){const groups=[];for(const item of items){const label=dayLabel(item.requested_at);let group=groups.at(-1);if(!group||group.label!==label){group={label,items:[]};groups.push(group)}group.items.push(item)}return groups;}
function entityImdbId(item){if(String(item.entity_id||'').startsWith('tt'))return item.entity_id;const id=item.after_compact?.imdb_id;return String(id||'').startsWith('tt')?id:null;}
function CalendarCard({plan}){return <article className={`av4-plan ${plan.attention?'attention':''}`}>
  <div className="av4-plan-head"><div><b>{plan.title}</b><small>{plan.statusLabel} · {plan.planned_volume} tareas · carga {plan.loadLabel.toLowerCase()}</small></div><span className={`av4-load ${plan.loadLabel.toLowerCase()}`}>{plan.loadLabel}</span></div>
  <div className="av4-plan-meta">{plan.planned_at?<span>{fmtDate(plan.planned_at)} · {fmtTime(plan.planned_at)}</span>:<span>Sin fecha asignada</span>}<span>Prioridad {plan.priority}</span>{plan.protected&&<span>Fijado</span>}{plan.deliberate_peak&&<span>Pico deliberado</span>}</div>
  <details><summary>Planificar</summary><div className="av4-plan-actions">
    <form action={reschedulePlan}><input type="hidden" name="planId" value={plan.plan_id}/><input name="plannedAt" type="datetime-local" defaultValue={plan.planned_at?madridInputValue(plan.planned_at):''}/><button>Reprogramar</button></form>
    <form action={setPlanPriority}><input type="hidden" name="planId" value={plan.plan_id}/><input name="priority" type="number" min="0" max="100" defaultValue={plan.priority}/><button>Cambiar prioridad</button></form>
    <form action={togglePlanProtection}><input type="hidden" name="planId" value={plan.plan_id}/><input type="hidden" name="value" value={plan.protected?'false':'true'}/><button>{plan.protected?'Permitir redistribución':'Fijar planificación'}</button></form>
    <form action={toggleDeliberatePeak}><input type="hidden" name="planId" value={plan.plan_id}/><input type="hidden" name="value" value={plan.deliberate_peak?'false':'true'}/><button>{plan.deliberate_peak?'Quitar pico deliberado':'Mantener como pico'}</button></form>
  </div></details>
</article>}

export default async function ActivityPage({searchParams}){
  const sp=await searchParams,view=sp?.vista==='calendario'?'calendario':'cronologia',domain=sp?.filtro||'todo',q=sp?.q||'',page=Math.max(1,Number(sp?.pagina)||1),detailId=sp?.run||null;
  const [summary,calendar,timeline,detail]=await Promise.all([getActivitySummary(),getActivityCalendar(),getActivityTimeline({domain,q,page}),detailId?getActivityRunDetail(detailId):null]);
  const groups=groupTimeline(timeline.items),dated=calendar.plans.filter(x=>x.planned_at),pending=calendar.plans.filter(x=>!x.planned_at),today=Date.now(),week=today+7*86400000,near=dated.filter(x=>new Date(x.planned_at).getTime()<=week),later=dated.filter(x=>new Date(x.planned_at).getTime()>week);
  return <main className="av4-shell"><ActivityRefresh/>
    <header className="av4-title"><div><p>ACTIVIDAD</p><h1>Qué está haciendo PikoFilm</h1><span>Pasado, presente y próximos 30 días en una misma historia funcional.</span></div><nav className="av4-modes"><Link href={href('/actividad',{vista:'cronologia',filtro:domain,q})} className={view==='cronologia'?'active':''}>Cronología</Link><Link href={href('/actividad',{vista:'calendario'})} className={view==='calendario'?'active':''}>Calendario</Link></nav></header>
    <section className="av4-kpis"><div><small>En curso</small><strong>{summary.active}</strong></div><div className={summary.attention+calendar.counts.attention?'attention':''}><small>Requiere atención</small><strong>{summary.attention+calendar.counts.attention}</strong></div><div><small>Próximos 7 días</small><strong>{calendar.counts.next7}</strong></div><div><small>Pendiente de planificar</small><strong>{calendar.counts.pending}</strong></div></section>
    {view==='cronologia'?<>
      <section className="av4-tools"><form><input type="hidden" name="vista" value="cronologia"/><input type="hidden" name="filtro" value={domain}/><input name="q" defaultValue={q} placeholder="Buscar título, persona, saga o actividad…"/><button>Buscar</button></form><div className="av4-filters">{FILTERS.map(([key,label])=><Link key={key} href={href('/actividad',{vista:'cronologia',filtro:key,q})} className={domain===key?'active':''}>{label}</Link>)}</div></section>
      <section className="av4-timeline">{groups.length?groups.map(group=><div className="av4-day" key={group.label}><h2>{group.label}</h2>{group.items.map(item=>{const imdbId=entityImdbId(item);return <article className={`av4-entry ${item.attention?'attention':''}`} key={item.run_id}><div className="av4-entry-time">{fmtTime(item.requested_at)}</div><div className="av4-entry-body"><div className="av4-entry-top"><b>{item.title}</b><span>{item.statusLabel}</span></div><p>{item.resultLabel}</p><small>{item.originLabel}{item.entityLabel?` · ${item.entityLabel}`:''}{item.duration_ms?` · ${Math.max(1,Math.round(Number(item.duration_ms)/60000))} min`:''}</small><div className="av4-entry-links">{imdbId&&<Link href={`/catalogo/${imdbId}`}>Ver ficha</Link>}<Link href={href('/actividad',{vista:'cronologia',filtro:domain,q,pagina:page,run:item.run_id})}>Ver detalle</Link></div></div></article>})}</div>):<div className="av4-empty">No hay actividad que coincida con estos filtros.</div>}</section>
      <nav className="av4-pagination">{page>1&&<Link href={href('/actividad',{vista:'cronologia',filtro:domain,q,pagina:page-1})}>← Más reciente</Link>}{timeline.hasMore&&<Link href={href('/actividad',{vista:'cronologia',filtro:domain,q,pagina:page+1})}>Más antiguo →</Link>}</nav>
    </>:<section className="av4-calendar"><div className="av4-calendar-note"><div><b>Planificación automática activa</b><span>PikoFilm reparte trabajo flexible dentro de su ventana segura. Las prioridades, fechas límite y picos que fijes no se moverán. Horas mostradas en Madrid.</span></div><form action={recalculatePlanningNow}><button className="av4-recalculate">Recalcular planificación ahora</button></form></div>{calendar.overloads.length>0&&<div className="av4-calendar-alerts"><h2>Carga que merece revisión</h2>{calendar.overloads.map(item=><div className={`av4-calendar-warning ${item.deliberatePeak?'deliberate':''}`} key={item.day}><b>{fmtDate(`${item.day}T12:00:00Z`)} · {item.volume} tareas</b><span>{item.reason} {item.deliberatePeak?'PikoFilm respetará este pico.':'Puedes posponer trabajo no prioritario o fijar el pico si es intencionado.'}</span></div>)}</div>}{pending.length>0&&<div className="av4-calendar-block"><h2>Pendiente de planificar <span>{pending.reduce((n,x)=>n+Number(x.planned_volume),0)}</span></h2>{pending.map(plan=><CalendarCard key={plan.plan_id} plan={plan}/>)}</div>}<div className="av4-calendar-block"><h2>Próximos 7 días <span>{near.reduce((n,x)=>n+Number(x.planned_volume),0)}</span></h2>{near.length?near.map(plan=><CalendarCard key={plan.plan_id} plan={plan}/>):<div className="av4-empty">No hay trabajo planificado en los próximos 7 días.</div>}</div><div className="av4-calendar-block compact"><h2>Días 8–30 <span>{later.reduce((n,x)=>n+Number(x.planned_volume),0)}</span></h2>{later.length?later.map(plan=><CalendarCard key={plan.plan_id} plan={plan}/>):<div className="av4-empty">Sin carga prevista en este tramo.</div>}</div></section>}
    {detail&&<aside className="av4-detail"><Link className="av4-detail-close" href={href('/actividad',{vista:'cronologia',filtro:domain,q,pagina:page})}>×</Link><p>DETALLE FUNCIONAL</p><h2>{detail.run.title}</h2><strong>{detail.run.statusLabel}</strong><p>{detail.run.resultLabel}</p><dl><div><dt>Origen</dt><dd>{detail.run.originLabel}</dd></div><div><dt>Fecha</dt><dd>{fmtDate(detail.run.requested_at)} · {fmtTime(detail.run.requested_at)}</dd></div>{detail.run.entityLabel&&<div><dt>Afectado</dt><dd>{detail.run.entityLabel}</dd></div>}</dl>{detail.children.length>0&&<div className="av4-detail-list"><h3>Efectos relacionados</h3>{detail.children.map(x=><div key={x.run_id}><b>{x.title}{x.entityLabel?` · ${x.entityLabel}`:''}</b><span>{x.resultLabel}</span></div>)}</div>}{detail.errors.length>0&&<div className="av4-detail-list attention"><h3>Incidencias</h3>{detail.errors.map(x=><div key={x.error_id}><b>{x.functionalMessage}</b><span>{x.nextStep}</span></div>)}</div>}<Link className="av4-technical" href={detail.run.technicalHref}>Ver detalle técnico en Operaciones</Link></aside>}
  </main>;
}
