'use server';
import {revalidatePath} from 'next/cache';
import {db} from '@/lib/db';
import {refreshIdentityEvidence,validateOne} from '@/lib/identity-validation';
import {saveIdentity} from '@/lib/identity';
import {recomputeLifecycleForIds} from '@/lib/lifecycle';
import {audit,errorInfo} from '@/lib/runlog';
function refresh(imdbId){revalidatePath('/calidad/validacion-identidad');revalidatePath('/calidad');revalidatePath('/admin');revalidatePath('/catalogo');if(imdbId)revalidatePath(`/catalogo/${imdbId}`)}
const idFrom=f=>{const id=String(f.get('imdbId')||'').trim();if(!/^tt\d+$/.test(id))throw new Error('IMDb ID inválido');return id};
export async function refreshIdentityEvidenceAction(_prev,formData){let imdbId;try{imdbId=idFrom(formData);const r=await refreshIdentityEvidence(imdbId);await recomputeLifecycleForIds([imdbId]);await audit('identity_validation','title',imdbId,'single_evidence_refreshed',{complete:r.complete,validation_version:'2.0.0'});refresh(imdbId);return{ok:true,message:r.complete?'Cruce IMDb ↔ TMDb actualizado. Ya puedes validar la identidad.':'Se actualizó TMDb, pero falta evidencia suficiente para validar automáticamente.'}}catch(e){if(imdbId)await audit('identity_validation','title',imdbId,'single_evidence_refresh_failed',{error:errorInfo(e)});return{ok:false,message:e?.message||'No se pudieron actualizar los datos'}}}
export async function revalidateIdentityAction(_prev,formData){let imdbId;try{imdbId=idFrom(formData);const v=await validateOne(imdbId);const lifecycle=await recomputeLifecycleForIds([imdbId]);const next=lifecycle.get(imdbId)?.label||'siguiente fase';await audit('identity_validation','title',imdbId,'single_revalidated',{status:v.status,score:v.score,next,validation_version:'2.0.0'});refresh(imdbId);if(v.status==='valid')return{ok:true,message:`Identidad validada (${v.score}/100). Pasa a ${next}.`};if(v.status==='insufficient')return{ok:true,message:'Evidencia insuficiente: permanece pendiente de validación.'};return{ok:true,message:`Resultado: ${v.status==='doubtful'?'Dudosa':'Probable error'} (${v.score??'—'}/100). Pasa a revisión.`}}catch(e){if(imdbId)await audit('identity_validation','title',imdbId,'single_revalidation_failed',{error:errorInfo(e)});return{ok:false,message:e?.message||'No se pudo validar'}}}
export async function saveIdentityIdsAction(arg1,arg2){const formData=arg2&&typeof arg2.get==='function'?arg2:arg1,oldId=idFrom(formData),sql=db();try{const[before]=await sql`SELECT imdb_id,tmdb_id,fa_id FROM movies WHERE imdb_id=${oldId}`;if(!before)throw new Error('Título no encontrado');const newImdb=String(formData.get('newImdbId')||oldId).trim(),newTmdb=String(formData.get('tmdbId')||'').trim()||null;const newId=await saveIdentity(oldId,{imdbId:newImdb,tmdbId:newTmdb,faId:before.fa_id||null});if(newId!==oldId)await sql`DELETE FROM identity_validation WHERE imdb_id=${oldId}`;await sql`INSERT INTO identity_validation(imdb_id,validation_status,validation_details,created_at,updated_at) VALUES(${newId},'pending_data','{}'::jsonb,now(),now()) ON CONFLICT(imdb_id) DO UPDATE SET validation_status='pending_data',validation_score=NULL,validation_details='{}'::jsonb,suspected_source=NULL,validated_at=NULL,imdb_title=NULL,imdb_original_title=NULL,imdb_year=NULL,imdb_extracted_at=NULL,tmdb_id=NULL,tmdb_title_es=NULL,tmdb_original_title=NULL,tmdb_year=NULL,tmdb_extracted_at=NULL,updated_at=now()`;await recomputeLifecycleForIds([newId]);await audit('identity_validation','title',newId,'ids_corrected_pending',{previous_imdb_id:oldId,tmdb_id:newTmdb});refresh(oldId);refresh(newId);return{ok:true,message:'IMDb/TMDb guardados. La evidencia se recalculará con el nuevo cruce de IDs.'}}catch(e){return{ok:false,message:e?.message||'No se pudieron guardar los IDs'}}}
export async function setManualIdentityDecisionAction(_prev,formData){const sql=db();let imdbId;try{imdbId=idFrom(formData);const decision=String(formData.get('decision')||'');if(!['valid','doubtful','invalid'].includes(decision))throw new Error('Decisión manual inválida');const[m]=await sql`SELECT m.imdb_id,m.tmdb_id,v.validation_status,v.validation_score FROM movies m LEFT JOIN identity_validation v USING(imdb_id) WHERE m.imdb_id=${imdbId}`;if(!m)throw new Error('Título no encontrado');const manual={status:decision,automatic_status:m.validation_status,automatic_score:m.validation_score,imdb_id:String(m.imdb_id),tmdb_id:String(m.tmdb_id||''),reviewed_at:new Date().toISOString()};const[r]=await sql`UPDATE identity_validation SET validation_details=COALESCE(validation_details,'{}'::jsonb)||jsonb_build_object('manual',${JSON.stringify(manual)}::jsonb),validation_status=${decision},updated_at=now() WHERE imdb_id=${imdbId} RETURNING imdb_id`;if(!r)throw new Error('La identidad todavía no tiene datos de validación');await recomputeLifecycleForIds([imdbId]);await audit('identity_validation','title',imdbId,'manual_decision_set',{decision});refresh(imdbId);return{ok:true,message:decision==='valid'?'Marcada como correcta manualmente y enviada a la siguiente fase.':decision==='doubtful'?'Marcada como dudosa manualmente.':'Marcada como probable error manualmente.'}}catch(e){return{ok:false,message:e?.message||'No se pudo guardar la revisión manual'}}}
export async function clearManualIdentityDecisionAction(_prev,formData){const sql=db();let imdbId;try{imdbId=idFrom(formData);const[v]=await sql`SELECT validation_details FROM identity_validation WHERE imdb_id=${imdbId}`;const manual=v?.validation_details?.manual,restore=manual?.automatic_status||'pending_data',score=manual?.automatic_score??null;await sql`UPDATE identity_validation SET validation_details=COALESCE(validation_details,'{}'::jsonb)-'manual',validation_status=${restore},validation_score=${score},updated_at=now() WHERE imdb_id=${imdbId}`;await recomputeLifecycleForIds([imdbId]);await audit('identity_validation','title',imdbId,'manual_decision_cleared',{});refresh(imdbId);return{ok:true,message:'Decisión manual eliminada. Vuelve a aplicarse el resultado automático anterior.'}}catch(e){return{ok:false,message:e?.message||'No se pudo quitar la decisión manual'}}}
