'use server';
import {revalidatePath} from 'next/cache';
import {db} from '@/lib/db';
import {dispatchIdentityValidation,dispatchIdentityRecalculation,cancelIdentityValidation} from '@/lib/identity-validation-run-control';
import {validateOne} from '@/lib/identity-validation';
import {saveIdentity} from '@/lib/identity';
import {refreshKnownIdentity} from '@/lib/identity-refresh';
import {audit,errorInfo} from '@/lib/runlog';
function refresh(imdbId){revalidatePath('/calidad/validacion-identidad');revalidatePath('/calidad');revalidatePath('/admin');if(imdbId){revalidatePath('/catalogo');revalidatePath(`/catalogo/${imdbId}`)}}
const idFrom=f=>{const id=String(f.get('imdbId')||'').trim();if(!/^tt\d+$/.test(id))throw new Error('IMDb ID inválido');return id};
export async function startIdentityValidationAction(){const r=await dispatchIdentityValidation('identity_validation_page');refresh();if(!r.ok)return r;if(r.alreadyRunning)return{ok:true,message:`Ya hay una sesión en curso: ${Number(r.processed||0).toLocaleString('es-ES')} procesados.`};return{ok:true,message:r.total?'Sesión segura lanzada. Solo repescará evidencia que no esté cacheada.':'No hay títulos pendientes de validar.'}}
export async function stopIdentityValidationAction(_prev,formData){const r=await cancelIdentityValidation(formData.get('runId'));refresh();return r}
export async function recalculateCachedIdentityValidationAction(){const sql=db();const[running]=await sql`SELECT id FROM pipeline_runs WHERE job_type='identity_validation' AND status='running' LIMIT 1`;if(running)return{ok:false,message:'Hay una validación en curso. Deténla antes de recalcular.'};const rows=await sql`UPDATE identity_validation v SET validation_status='revalidation_pending',updated_at=now() FROM movies m LEFT JOIN catalog_exclusions ex USING(imdb_id) WHERE m.imdb_id=v.imdb_id AND ex.imdb_id IS NULL AND v.tmdb_id=m.tmdb_id AND v.fa_id=m.fa_id AND v.imdb_original_title IS NOT NULL AND v.imdb_year IS NOT NULL AND v.tmdb_original_title IS NOT NULL AND v.tmdb_year IS NOT NULL AND v.fa_original_title IS NOT NULL AND v.fa_year IS NOT NULL RETURNING v.imdb_id`;await audit('identity_validation','cache','all','cached_recalculation_requested',{count:rows.length,external_sources:false});const r=await dispatchIdentityRecalculation('identity_validation_recalculate');refresh();if(!r.ok)return r;if(r.alreadyRunning)return{ok:false,message:'Se detectó otra validación en curso. No se ha iniciado el recálculo.'};return{ok:true,message:`${rows.length.toLocaleString('es-ES')} validaciones cacheadas preparadas. El recálculo no consultará IMDb, TMDb ni FilmAffinity.`}}
async function fullRefreshIfValid(imdbId,v){let refreshed=false,refreshError=null;if(v.status==='valid'){const sql=db();try{await refreshKnownIdentity(imdbId);refreshed=true;await sql`UPDATE identity_validation SET full_refresh_state='refreshed',full_refresh_error=NULL,full_refreshed_at=now(),updated_at=now() WHERE imdb_id=${imdbId}`}catch(e){refreshError=e?.message||String(e);await sql`UPDATE identity_validation SET full_refresh_state='failed',full_refresh_error=${refreshError},updated_at=now() WHERE imdb_id=${imdbId}`}}return{refreshed,refreshError}}
export async function revalidateIdentityAction(_prev,formData){let imdbId;try{imdbId=idFrom(formData);const v=await validateOne(imdbId),{refreshed,refreshError}=await fullRefreshIfValid(imdbId,v);await audit('identity_validation','title',imdbId,'single_revalidated',{status:v.status,score:v.score,refreshed,refresh_error:refreshError});refresh(imdbId);return{ok:true,message:v.status==='valid'?(refreshed?'Identidad correcta y datos completos actualizados.':`Identidad correcta, pero falló el refresco completo: ${refreshError}`):`Revalidada: ${v.status==='doubtful'?'dudosa':v.status==='invalid'?'probable asignación incorrecta':'datos insuficientes'} (${v.score??'—'}/100).`}}catch(e){if(imdbId)await audit('identity_validation','title',imdbId,'single_revalidation_failed',{error:errorInfo(e)});return{ok:false,message:e?.message||'No se pudo revalidar'}}}
export async function setManualIdentityDecisionAction(_prev,formData){const sql=db();let imdbId;try{imdbId=idFrom(formData);const decision=String(formData.get('decision')||'');if(!['valid','doubtful','invalid'].includes(decision))throw new Error('Decisión manual inválida');const[m]=await sql`SELECT imdb_id,tmdb_id,fa_id FROM movies WHERE imdb_id=${imdbId}`;if(!m)throw new Error('Título no encontrado');const manual={status:decision,imdb_id:String(m.imdb_id),tmdb_id:String(m.tmdb_id||''),fa_id:String(m.fa_id||''),reviewed_at:new Date().toISOString()};const[r]=await sql`UPDATE identity_validation SET validation_details=COALESCE(validation_details,'{}'::jsonb)||jsonb_build_object('manual',${JSON.stringify(manual)}::jsonb),updated_at=now() WHERE imdb_id=${imdbId} RETURNING imdb_id`;if(!r)throw new Error('La identidad todavía no tiene datos de validación');await audit('identity_validation','title',imdbId,'manual_decision_set',{decision,tmdb_id:m.tmdb_id,fa_id:m.fa_id});refresh(imdbId);return{ok:true,message:decision==='valid'?'Marcada como correcta manualmente. No volverá a aparecer como error mientras no cambien los IDs.':decision==='doubtful'?'Marcada como dudosa manualmente.':'Marcada como ID incorrecto manualmente.'}}catch(e){return{ok:false,message:e?.message||'No se pudo guardar la revisión manual'}}}
export async function clearManualIdentityDecisionAction(_prev,formData){const sql=db();let imdbId;try{imdbId=idFrom(formData);await sql`UPDATE identity_validation SET validation_details=COALESCE(validation_details,'{}'::jsonb)-'manual',updated_at=now() WHERE imdb_id=${imdbId}`;await audit('identity_validation','title',imdbId,'manual_decision_cleared',{});refresh(imdbId);return{ok:true,message:'Decisión manual eliminada. Vuelve a aplicarse el resultado automático.'}}catch(e){return{ok:false,message:e?.message||'No se pudo quitar la decisión manual'}}}
export async function saveAndRevalidateIdentityAction(arg1,arg2){const formData=arg2&&typeof arg2.get==='function'?arg2:arg1;const oldId=idFrom(formData),sql=db();try{const[before]=await sql`SELECT m.imdb_id AS movie_imdb_id,m.tmdb_id AS movie_tmdb_id,m.fa_id AS movie_fa_id,v.imdb_title,v.imdb_original_title,v.imdb_year,v.imdb_extracted_at,v.tmdb_id AS cached_tmdb_id,v.tmdb_title_es,v.tmdb_original_title,v.tmdb_year,v.tmdb_extracted_at,v.fa_id AS cached_fa_id,v.fa_title_es,v.fa_original_title,v.fa_year,v.fa_extracted_at FROM movies m LEFT JOIN identity_validation v USING(imdb_id) WHERE m.imdb_id=${oldId}`,newTmdb=String(formData.get('tmdbId')||'').trim()||null,newFa=String(formData.get('faId')||'').trim()||null,newImdb=String(formData.get('newImdbId')||oldId).trim(),newId=await saveIdentity(oldId,{imdbId:newImdb,tmdbId:newTmdb,faId:newFa});
 const sameTmdb=String(before?.movie_tmdb_id||'')===String(newTmdb||''),sameFa=String(before?.movie_fa_id||'')===String(newFa||'');
 if(newId!==oldId){await sql`DELETE FROM identity_validation WHERE imdb_id=${newId}`;await sql`INSERT INTO identity_validation(imdb_id,tmdb_id,tmdb_title_es,tmdb_original_title,tmdb_year,tmdb_extracted_at,fa_id,fa_title_es,fa_original_title,fa_year,fa_extracted_at,validation_status,created_at,updated_at) VALUES(${newId},${sameTmdb?newTmdb:null},${sameTmdb?before?.tmdb_title_es:null},${sameTmdb?before?.tmdb_original_title:null},${sameTmdb?before?.tmdb_year:null},${sameTmdb?before?.tmdb_extracted_at:null},${sameFa?newFa:null},${sameFa?before?.fa_title_es:null},${sameFa?before?.fa_original_title:null},${sameFa?before?.fa_year:null},${sameFa?before?.fa_extracted_at:null},'revalidation_pending',now(),now()) ON CONFLICT(imdb_id) DO NOTHING`;await sql`DELETE FROM identity_validation WHERE imdb_id=${oldId}`}else{if(!sameTmdb)await sql`UPDATE identity_validation SET tmdb_id=NULL,tmdb_title_es=NULL,tmdb_original_title=NULL,tmdb_year=NULL,tmdb_extracted_at=NULL,validation_status='revalidation_pending',validation_score=NULL,validation_details='{}'::jsonb,suspected_source=NULL,updated_at=now() WHERE imdb_id=${newId}`;if(!sameFa)await sql`UPDATE identity_validation SET fa_id=NULL,fa_title_es=NULL,fa_original_title=NULL,fa_year=NULL,fa_extracted_at=NULL,validation_status='revalidation_pending',validation_score=NULL,validation_details='{}'::jsonb,suspected_source=NULL,updated_at=now() WHERE imdb_id=${newId}`}
 await audit('identity_validation','title',newId,'ids_corrected',{previous_imdb_id:oldId,tmdb_id:newTmdb,fa_id:newFa});const v=await validateOne(newId),{refreshed,refreshError}=await fullRefreshIfValid(newId,v);refresh(oldId);refresh(newId);return{ok:true,message:v.status==='valid'?(refreshed?'IDs corregidos, identidad validada y datos completos actualizados.':`IDs corregidos y validados; falló la actualización completa: ${refreshError}`):`IDs guardados y revalidados: ${v.status}. Revisa de nuevo la asignación.`}}catch(e){return{ok:false,message:e?.message||'No se pudieron corregir y revalidar los IDs'}}}
