import Link from 'next/link';
import ActionButton from '@/components/ActionButton';
import {getIdentityValidationPage,getIdentityValidationStats} from '@/lib/identity-validation-page';
import {revalidateIdentityAction,saveAndRevalidateIdentityAction} from './actions';
import './validation.css';
export const dynamic='force-dynamic';
const nf=n=>Number(n||0).toLocaleString('es-ES');
const img=p=>p?`https://image.tmdb.org/t/p/w92${p}`:null;
function qs(p,patch={}){const x=new URLSearchParams();for(const[k,v]of Object.entries({...p,...patch}))if(v!==undefined&&v!==null&&v!=='')x.set(k,String(v));return x.toString()}
function Evidence({name,id,title,year,url}){return <div className="iv-source"><div className="iv-source-top"><span>{name}</span>{url?<a href={url} target="_blank" rel="noreferrer">{id} ↗</a>:<b>{id||'—'}</b>}</div><strong>{title||'Pendiente de validar'}</strong><small>Año: {year||'—'}</small></div>}
function Pager({p,page,pages}){if(pages<=1)return null;return <div className="iv-pager"><Link className={page<=1?'disabled':''} href={'/calidad/validacion-identidad?'+qs(p,{page:Math.max(1,page-1)})}>← Anterior</Link><span>Página <b>{page}</b> de <b>{pages}</b></span><Link className={page>=pages?'disabled':''} href={'/calidad/validacion-identidad?'+qs(p,{page:Math.min(pages,page+1)})}>Siguiente →</Link></div>}
export default async function ValidacionIdentidad({searchParams}){const p=await searchParams,type=p.type||'',q=p.q||'',year=p.year||'',page=Math.max(1,Number(p.page)||1),[stats,data]=await Promise.all([getIdentityValidationStats(),getIdentityValidationPage({type,q,year,page,pageSize:50})]);return <div className="iv-page"><div className="breadcrumbs"><Link href="/calidad">Calidad</Link><span>›</span><b>Validación de Identidad</b></div><header className="iv-head"><div><div className="eyebrow">Estado · Validación de identidad</div><h1>Validación de Identidad</h1><p>Solo aparecen títulos cuyo lifecycle está en esta fase. Aquí se comprueba que IMDb, TMDb y FilmAffinity corresponden realmente al mismo título.</p></div></header>
<section className="iv-kpis"><div><span>Pendientes en esta fase</span><strong>{nf(stats.total)}</strong><small>IDENTITY_VALIDATION</small></div><div><span>IMDb con evidencia</span><strong>{nf(stats.imdb_cached)}</strong><small>de {nf(stats.total)}</small></div><div><span>TMDb con evidencia</span><strong>{nf(stats.tmdb_cached)}</strong><small>de {nf(stats.total)}</small></div><div><span>FilmAffinity con evidencia</span><strong>{nf(stats.fa_cached)}</strong><small>de {nf(stats.total)}</small></div><div><span>Listas para decidir</span><strong>{nf(stats.ready_three)}</strong><small>evidencia de las 3 fuentes</small></div></section>
<section className="iv-toolbar"><form method="get"><input name="q" defaultValue={q} placeholder="Buscar título, IMDb, TMDb o FA…"/><select name="type" defaultValue={type}><option value="">Películas y series</option><option value="movie">Películas</option><option value="series">Series</option></select><input name="year" defaultValue={year} placeholder="Año" inputMode="numeric"/><button>Filtrar</button><Link href="/calidad/validacion-identidad">Limpiar</Link></form></section>
<section className="iv-table-wrap"><div className="iv-panel-head"><div><b>Pendientes de validación</b><span>{nf(data.total)} títulos · 50 por página</span></div></div><table className="iv-table"><thead><tr><th>Título</th><th>IMDb</th><th>TMDb</th><th>FilmAffinity</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{data.rows.map(r=><tr key={r.imdb_id}><td><div className="iv-title">{img(r.poster_path)?<img src={img(r.poster_path)} alt=""/>:<div className="iv-poster"/>}<div><b>{r.display_title}</b><small>{r.type} · {r.year||'—'}</small></div></div></td><td><Evidence name="IMDb" id={r.imdb_id} title={r.imdb_original_title||r.imdb_title} year={r.imdb_year} url={`https://www.imdb.com/title/${r.imdb_id}/`}/></td><td><Evidence name="TMDb" id={r.tmdb_id} title={r.tmdb_original_title} year={r.tmdb_year} url={`https://www.themoviedb.org/${r.type==='Película'?'movie':'tv'}/${r.tmdb_id}`}/></td><td><Evidence name="FA" id={r.fa_id} title={r.fa_original_title} year={r.fa_year} url={`https://www.filmaffinity.com/es/film${r.fa_id}.html`}/></td><td><div className="iv-status neutral"><b>Pendiente</b><small>Debe validarse para avanzar de fase.</small></div></td><td><div className="iv-actions"><ActionButton action={revalidateIdentityAction} fields={{imdbId:r.imdb_id}} label="Validar identidad" pendingLabel="Validando…"/><details><summary>✎ Corregir IDs</summary><form action={saveAndRevalidateIdentityAction} className="iv-edit"><input type="hidden" name="imdbId" value={r.imdb_id}/><label>IMDb<input name="newImdbId" defaultValue={r.imdb_id}/></label><label>TMDb<input name="tmdbId" defaultValue={r.tmdb_id||''}/></label><label>FilmAffinity<input name="faId" defaultValue={r.fa_id||''}/></label><button>Guardar + validar</button></form></details><Link href={`/catalogo/${r.imdb_id}?from=${encodeURIComponent('/calidad/validacion-identidad')}`}>Abrir ficha</Link></div></td></tr>)}</tbody></table></section><Pager p={{type,q,year}} page={data.page} pages={data.pages}/></div>}
