'use server';
import {revalidatePath} from 'next/cache';
import {updateDataQualityTitle} from '@/lib/data-quality-unitary';
import {refreshRatingsForTitle} from '@/lib/ratings-refresh';
import {calculatePikoScoreForTitle} from '@/lib/pikoscore';
import {recomputeLifecycleForIds} from '@/lib/lifecycle';

function refresh(imdbId){revalidatePath('/calidad/datos');revalidatePath('/calidad');if(imdbId)revalidatePath(`/catalogo/${imdbId}`)}
function id(formData){const v=String(formData.get('imdbId')||'').trim();if(!/^tt\d+$/.test(v))throw new Error('IMDb ID inválido');return v}
export async function updateDataAction(_prev,formData){try{const imdbId=id(formData),r=await updateDataQualityTitle(imdbId),lifecycle=(await recomputeLifecycleForIds([imdbId])).get(imdbId);refresh(imdbId);const failed=(r.results||[]).filter(x=>!x.ok),recovered=[...new Set((r.results||[]).flatMap(x=>x.changed||[]))],missing=r.after?.missingCritical||[];if(missing.length)return{ok:true,message:`Actualización parcial · cobertura ${r.after?.coverage??'—'}% · faltan ${missing.length}: ${missing.slice(0,5).join(', ')}${failed.length?` · ${failed.length} fuente(s) con error`:''}`};return{ok:true,message:`Datos estructurales completos · ${recovered.length} campos actualizados${failed.length?` · ${failed.length} fuente(s) con error no bloqueante`:''} · ratings se gestionan aparte · estado: ${lifecycle?.label||lifecycle?.state||'actualizado'}.`}}catch(e){return{ok:false,message:e?.message||'No se pudieron actualizar los datos'}}}
export async function refreshRatingsAction(_prev,formData){try{const imdbId=id(formData),r=await refreshRatingsForTitle(imdbId),lifecycle=(await recomputeLifecycleForIds([imdbId])).get(imdbId);refresh(imdbId);if(!r.verified)return{ok:false,message:'MDBList no devolvió ningún rating utilizable para este título.'};const available=(r.ratings||[]).filter(x=>x.status==='available'&&Number(x.normalized_rating)>0);return{ok:true,message:`Ratings actualizados · ${r.saved} fuente(s) guardadas · ${available.length} disponibles · proveedor ${r.provider} · PikoScore 3.0 se calculará en la fase local siguiente · estado: ${lifecycle?.label||lifecycle?.state||'actualizado'}.`}}catch(e){return{ok:false,message:e?.message||'No se pudieron actualizar los ratings'}}}
export async function calculatePikoScoreAction(_prev,formData){try{const imdbId=id(formData),r=await calculatePikoScoreForTitle(imdbId),lifecycle=(await recomputeLifecycleForIds([imdbId])).get(imdbId);refresh(imdbId);return{ok:true,message:`PikoScore ${r.score.toFixed(2)} · confianza ${r.confidence.toFixed(1)}% · versión ${r.version||'legacy'} · siguiente estado: ${lifecycle?.label||lifecycle?.state||'actualizado'}.`}}catch(e){return{ok:false,message:e?.message||'No se pudo calcular PikoScore'}}}
