'use server';
import {revalidatePath} from 'next/cache';
import {updateDataQualityTitle} from '@/lib/data-quality-unitary';
import {refreshRatingsForTitle} from '@/lib/ratings-refresh';
import {calculateAndSavePikoScoreV3ForTitle} from '@/lib/pikoscore-v3';
import {recomputeLifecycleForIds} from '@/lib/lifecycle';

function refresh(imdbId){revalidatePath('/calidad/datos');revalidatePath('/calidad');if(imdbId)revalidatePath(`/catalogo/${imdbId}`)}
function id(formData){const v=String(formData.get('imdbId')||'').trim();if(!/^tt\d+$/.test(v))throw new Error('IMDb ID inválido');return v}
export async function updateDataAction(_prev,formData){try{const imdbId=id(formData),r=await updateDataQualityTitle(imdbId),lifecycle=r.lifecycle;refresh(imdbId);const results=r.results||[],failed=results.filter(x=>!x.ok),recovered=[...new Set(results.flatMap(x=>x.changed||[]))],missing=r.missing||[],sources=results.map(x=>`${x.source}${x.ok?'':' ⚠'}`).join(' → ');if(missing.length)return{ok:true,message:`Actualización parcial · ${recovered.length} campo(s) recuperados · faltan ${missing.length}: ${missing.slice(0,6).join(', ')}${sources?` · fuentes: ${sources}`:''}${failed.length?` · ${failed.length} fuente(s) con error`:''}`};return{ok:true,message:`Datos completados · ${recovered.length} campo(s) actualizados${sources?` · fuentes: ${sources}`:''}${failed.length?` · ${failed.length} fuente(s) con error no bloqueante`:''} · ratings se gestionan aparte · estado: ${lifecycle?.label||lifecycle?.state||'actualizado'}.`}}catch(e){return{ok:false,message:e?.message||'No se pudieron actualizar los datos'}}}
export async function refreshRatingsAction(_prev,formData){try{const imdbId=id(formData),r=await refreshRatingsForTitle(imdbId),lifecycle=(await recomputeLifecycleForIds([imdbId])).get(imdbId);refresh(imdbId);if(!r.verified)return{ok:false,message:'MDBList no devolvió ningún rating utilizable para este título.'};const available=(r.ratings||[]).filter(x=>x.status==='available'&&Number(x.normalized_rating)>0);return{ok:true,message:`Ratings actualizados · ${r.saved} fuente(s) guardadas · ${available.length} disponibles · proveedor ${r.provider} · estado: ${lifecycle?.label||lifecycle?.state||'actualizado'}.`}}catch(e){return{ok:false,message:e?.message||'No se pudieron actualizar los ratings'}}}
export async function calculatePikoScoreV3Action(_prev,formData){try{const imdbId=id(formData),r=await calculateAndSavePikoScoreV3ForTitle(imdbId),lifecycle=(await recomputeLifecycleForIds([imdbId])).get(imdbId);refresh(imdbId);const familyText=(r.contributions||[]).map(x=>`${x.family} ${x.score.toFixed(2)}`).join(' · ');return{ok:true,message:`PikoScore 3.0 ${r.score.toFixed(2)} · confianza ${r.confidence.toFixed(1)}% · ${r.sourceCount} fuentes · ${r.familyCount} familias${familyText?` · ${familyText}`:''} · mercado ${r.market} · guardado · estado: ${lifecycle?.label||lifecycle?.state||'actualizado'}.`}}catch(e){return{ok:false,message:e?.message||'No se pudo calcular PikoScore 3.0'}}}
