import Link from 'next/link';
import ActionButton from '@/components/ActionButton';
import IdentityExcludeButton from '@/components/IdentityExcludeButton';
import DataQualityManualControls from '@/components/DataQualityManualControls';
import {DATA_FIELDS} from '@/lib/data-quality';
import {getDataQualityView} from '@/lib/data-quality-page';
import {providerUrl} from '@/lib/provider-links';
import {updateDataAction,refreshRatingsAction,calculatePikoScoreV3Action} from './actions';
import './quality-data.css';

export const dynamic='force-dynamic';
const nf=n=>Number(n||0).toLocaleString('es-ES');
const pct=n=>`${Number(n||0).toLocaleString('es-ES',{maximumFractionDigits:1})}%`;
const date=d=>d?new Date(d).toLocaleDateString('es-ES'):'Nunca';
const sourceLabel={imdb:'IMDb',tmdb:'TMDb',trakt:'Trakt',letterboxd:'Letterboxd',rt_critics:'RT críticos',rt_audience:'RT audiencia',metacritic:'Metacritic',metacritic_user:'Metacritic usuarios',roger_ebert:'Roger Ebert'};
const stateLabel={RESUELTO:'Resuelto',REVISION_PENDIENTE:'Resuelto · mejorable',REQUIERE_ATENCION:'Requiere atención',ESTADO_NO_FIABLE:'Estado no fiable'};
function qs(base,patch){const x={...base,...patch};Object.keys(x).forEach(k=>(x[k]===undefined||x[k]===null||x[k]===''||x[k]==='all'||x[k]===false)&&delete x[k]);const query=new URLSearchParams(Object.fromEntries(Object.entries(x).map(([k,v])=>[k,String(v)]))).toString();return query?`/calidad/datos?${query}`:'/calidad/datos'}
function Pager({base,page,pages}){if(pages<=1)return null;return <nav className="dq-pager" aria-label="Paginación"><Link className={page<=1?'disabled':''} href={qs(base,{page:Math.max(1,page-1)})}>← Anterior</Link><span>Página <b>{page}</b> de <b>{pages}</b></span><Link className={page>=pages?'disabled':''} href={qs(base,{page:Math.min(pages,page+1)})}>Siguiente →</Link></nav>}
function Missing({r}){return <details className="dq-details"><summary>{r.missing.length?`${r.missing.length} campos ausentes`:'Sin campos ausentes'}</summary><div className="dq-detail-grid">{r.missing.map(k=>{const sev=r.fieldSeverity?.[k]||DATA_FIELDS[k]?.severity||'optional';return <span key={k} className={`sev ${sev}`}><b>{DATA_FIELDS[k]?.label||k}</b><small>{sev==='critical'?'Crítico':sev==='important'?'Importante':'Opcional'}</small></span>})}</div></details>}
function Ratings({r}){if(r.manualRatingsFixed)return <div className="dq-ratings"><b className="ok">✓ Decisión manual</b><small>PikoScore fijado en 5,0 · no requiere refrescos automáticos</small></div>;return <div className="dq-ratings"><b>{r.freshRatingCount}/{r.ratingCount} fuentes válidas</b><small className="dq-rating-dates">Último refresco: {date(r.ratings_refreshed_at||r.latestRatingFetchedAt)} · Próxima revisión: {date(r.nextRatingRefreshAt)}</small><div className="source-chips">{r.ratings.map(x=><span key={x.source} className={x.freshnessState}>{sourceLabel[x.source]||x.source} <b>{Number(x.rating).toLocaleString('es-ES',{maximumFractionDigits:2})}</b></span>)}</div><details className="dq-details"><summary>Detalle de fuentes</summary>{r.ratings.length?r.ratings.map(x=><div className="source-detail" key={x.source}><b>{sourceLabel[x.source]||x.source}</b><span>{Number(x.rating).toLocaleString('es-ES',{maximumFractionDigits:2})} · {x.votes==null?'sin votos':`${nf(x.votes)} votos`} · consultado {date(x.fetched_at)} · refresco {date(x.refreshDueAt)} · {x.freshnessState==='fresh'?'Fresco':x.freshnessState==='aging'?'Envejeciendo':'Caducado'}</span></div>):<p>Sin ratings normalizados.</p>}</details></div>}
function MainAction({r}){if(r.nextAction==='UPDATE_DATA')return <ActionButton action={updateDataAction} fields={{imdbId:r.imdb_id}} label="Actualizar datos" pendingLabel="Actualizando datos…" className="button"/>;if(r.nextAction==='REFRESH_RATINGS')return <ActionButton action={refreshRatingsAction} fields={{imdbId:r.imdb_id}} label={r.ratingCount?'Actualizar ratings':'Obtener ratings'} pendingLabel="Actualizando ratings…" className="button"/>;if(r.nextAction==='CALCULATE_PIKOSCORE')return <ActionButton action={calculatePikoScoreV3Action} fields={{imdbId:r.imdb_id}} label="Calcular PikoScore" pendingLabel="Calculando…" className="button"/>;if(r.coverage<100)return <ActionButton action={updateDataAction} fields={{imdbId:r.imdb_id}} label="Mejorar datos" pendingLabel="Buscando datos…" className="button ghost"/>;return <span className="dq-done">✓ Sin acción pendiente</span>}
function ProviderLinks({r}){const links=[['IMDb',providerUrl('imdb',r.imdb_id,r.type)],['TMDb',providerUrl('tmdb',r.tmdb_id,r.type)],['MDBList',providerUrl('mdblist',r.imdb_id,r.type)],['Trakt',providerUrl('trakt',r.imdb_id,r.type)]].filter(([,url])=>url);return <div className="dq-provider-links">{links.map(([label,url])=><a key={label} href={url} target="_blank" rel="noreferrer">{label} ↗</a>)}</div>}
export default async function DataQuality({searchParams}){const p=await searchParams;const base={q:String(p.q||''),state:String(p.state||'all'),type:String(p.type||'all'),plex:String(p.plex||'all'),completion:String(p.completion||'all'),sort:String(p.sort||'priority'),stuck:String(p.stuck||'')};const page=Math.max(1,Number(p.page)||1),view=await getDataQualityView({...base,page}),o=view.overview,d=view.page;const cards=[['data_incomplete','Datos incompletos',o.incomplete,'Faltan requisitos obligatorios'],['ratings_pending','Ratings pendientes',o.ratingsPending,'Faltan fuentes o toca refrescarlas'],['score_ready','Listos para PikoScore',o.scoreReady,'Materia prima preparada'],['resolved','Sin acción pendiente',o.resolved,`${nf(o.resolvedComplete)} al 100 % · ${nf(o.resolvedImprovable)} mejorables`]],returnTo=qs(base,{page:d.page});return <div className="dq-page">
<div className="breadcrumbs"><Link href="/calidad">Calidad</Link><span>›</span><b>Datos</b></div>
<header className="dq-head"><div className="eyebrow">Calidad · Datos</div><h1>Salud de datos y ratings</h1><p>Diagnóstico individual de datos estructurales, fuentes de rating y vigencia de PikoScore. Los procesos masivos se ejecutan exclusivamente desde BATCH.</p><div className="dq-meta">{nf(o.total)} títulos revisables · cobertura media {pct(o.averageCoverage)} · {nf(o.inPlex)} en Plex{o.stuck>0&&<> · <b>⚠ {o.stuck} potencialmente atascados</b></>}</div></header>
<section className="dq-status-grid">{cards.map(([s,label,n,help])=><Link key={s} href={qs(base,{state:s,completion:'all',page:1})} className={`dq-status ${base.state===s?'active':''}`}><span>{label}</span><strong>{nf(n)}</strong><small>{help}</small></Link>)}</section>
<section className="dq-toolbar"><form className="dq-search"><span aria-hidden="true">⌕</span><input name="q" defaultValue={base.q} placeholder="Buscar por título, título original o IMDb ID…" aria-label="Buscar títulos"/><input type="hidden" name="state" value={base.state}/><input type="hidden" name="type" value={base.type}/><input type="hidden" name="plex" value={base.plex}/><input type="hidden" name="completion" value={base.completion}/><input type="hidden" name="sort" value={base.sort}/><input type="hidden" name="stuck" value={base.stuck}/><button type="submit">Buscar</button>{base.q&&<Link className="clear" aria-label="Limpiar búsqueda" href={qs(base,{q:'',page:1})}>×</Link>}</form><div className="dq-filters"><Link className={base.type==='all'?'active':''} href={qs(base,{type:'all',page:1})}>Todos</Link><Link className={base.type==='Película'?'active':''} href={qs(base,{type:'Película',page:1})}>Películas</Link><Link className={base.type==='Serie'?'active':''} href={qs(base,{type:'Serie',page:1})}>Series</Link><span className="dq-filter-sep"/><Link className={base.plex==='all'?'active':''} href={qs(base,{plex:'all',page:1})}>Plex: todos</Link><Link className={base.plex==='in'?'active':''} href={qs(base,{plex:'in',page:1})}>En Plex</Link><Link className={base.plex==='out'?'active':''} href={qs(base,{plex:'out',page:1})}>Fuera de Plex</Link><Link className={base.stuck==='1'?'active warn':''} href={qs(base,{stuck:base.stuck==='1'?'':'1',page:1})}>⚠ Solo atascados</Link><form><input type="hidden" name="q" value={base.q}/><input type="hidden" name="state" value={base.state}/><input type="hidden" name="type" value={base.type}/><input type="hidden" name="plex" value={base.plex}/><input type="hidden" name="completion" value={base.completion}/><input type="hidden" name="stuck" value={base.stuck}/><select name="sort" defaultValue={base.sort}><option value="priority">Prioridad</option><option value="title">Título</option><option value="coverage">Cobertura</option><option value="updated">Antigüedad</option></select><button>Ordenar</button></form></div>{base.state==='resolved'&&<div className="dq-subfilters"><span>Sin acción pendiente:</span><Link className={base.completion==='all'?'active':''} href={qs(base,{completion:'all',page:1})}>Todos</Link><Link className={base.completion==='improvable'?'active':''} href={qs(base,{completion:'improvable',page:1})}>Mejorables</Link><Link className={base.completion==='complete'?'active':''} href={qs(base,{completion:'complete',page:1})}>100 % completos</Link></div>}<div className="dq-active"><b>{nf(d.total)} resultados · 25 por página</b>{(base.q||base.state!=='all'||base.type!=='all'||base.plex!=='all'||base.completion!=='all'||base.stuck)&&<Link href="/calidad/datos">Restablecer filtros</Link>}</div></section>
<section className="dq-list">{d.rows.length===0?<div className="dq-empty"><h2>No hay resultados</h2><p>No hay títulos que coincidan con los filtros actuales.</p></div>:d.rows.map(r=>{const poster=r.poster_path?`https://image.tmdb.org/t/p/w92${r.poster_path}`:r.external_poster_url||null,title=r.title_es||r.original_title||r.imdb_id;return <article className={`dq-row state-${r.state.toLowerCase()}`} key={r.imdb_id}><div className="dq-identity">{poster?<img src={poster} alt=""/>:<div className="dq-poster-mini">🎬</div>}<div><Link className="dq-title" href={`/catalogo/${r.imdb_id}?from=${encodeURIComponent(returnTo)}`}>{title}</Link><small>{r.year||'—'} · {r.type||'—'} · <code>{r.imdb_id}</code></small><div className="dq-identity-status"><span className={`plex-badge ${r.in_plex?'in':'out'}`}>{r.in_plex?'✓ En Plex':'Fuera de Plex'}</span><span>Cobertura {pct(r.coverage)}</span>{r.manualDataAccepted&&<span>✓ Datos aceptados manualmente</span>}</div><ProviderLinks r={r}/>{r.original_title&&r.original_title!==r.title_es&&<small>{r.original_title}</small>}</div></div><div className="dq-dimension"><span className="cap">Datos</span><b className={r.dataReady?'ok':'bad'}>{!r.dataReady?`⚠ ${r.missingBlocking.length} obligatorios`:r.coverage===100?'✓ 100 % completos':r.manualDataAccepted?'✓ Aceptados manualmente':'◐ Mejorables'}</b><small>Cobertura {pct(r.coverage)}</small><Missing r={r}/></div><div className="dq-dimension"><span className="cap">Ratings</span><Ratings r={r}/></div><div className="dq-state"><span className="cap">Estado / acción</span><b className={`business ${r.state}`}>{r.state==='RESUELTO'?'✓ ':r.state==='REVISION_PENDIENTE'?'◐ ':r.state==='REQUIERE_ATENCION'?'⚠ ':''}{stateLabel[r.state]}</b><p>{r.reason}</p>{r.stuck&&<small className="stuck">⚠ Posible atasco · {r.stuckReason}</small>}<div className="score-line">PikoScore <b>{r.final_rating??'—'}</b> · {r.manualRatingsFixed?'fijo manual':r.pikoScoreCurrent?'vigente':'pendiente'}</div><MainAction r={r}/><DataQualityManualControls r={r}/><details className="dq-details actions"><summary>Más acciones</summary><div><ActionButton action={updateDataAction} fields={{imdbId:r.imdb_id}} label={r.coverage<100?'Mejorar datos':'Revisar datos'} pendingLabel="Actualizando…" className="button ghost"/><ActionButton action={refreshRatingsAction} fields={{imdbId:r.imdb_id}} label="Forzar ratings" pendingLabel="Actualizando…" className="button ghost"/>{r.ratingsReady&&!r.manualRatingsFixed&&<ActionButton action={calculatePikoScoreV3Action} fields={{imdbId:r.imdb_id}} label="Recalcular PikoScore" pendingLabel="Calculando…" className="button ghost"/>}<IdentityExcludeButton imdbId={r.imdb_id} title={title} inPlex={Boolean(r.in_plex)} returnTo={returnTo}/></div></details></div></article>})}</section><Pager base={base} page={d.page} pages={d.pages}/></div>}
