'use client';
import Link from 'next/link';
import {useState} from 'react';
import {nf,pct,score,decadeLabel} from '@/lib/home-format';
const tabs=[['dna','ADN'],['plex','Plex'],['score','PikoScore'],['countries','Países'],['sagas','Sagas'],['profile','Perfil'],['composition','Composición']];
const gh=x=>`/catalogo?genres=${encodeURIComponent(x)}`,ch=x=>`/catalogo?country=${encodeURIComponent(x)}`;
function Bars({rows=[],value='total',href}){const max=Math.max(1,...rows.map(x=>Math.abs(Number(x?.[value]||0))));return <div className="home-bars">{rows.map((r,i)=>{const label=r.label||r.band||(r.bucket!=null?decadeLabel(r.bucket):'—'),v=Number(r?.[value]||0),body=<><span>{label}</span><div><i style={{width:`${Math.max(3,Math.abs(v)/max*100)}%`}}/></div><b>{value==='total'?nf(v):`${v>0?'+':''}${v.toFixed(1)} pp`}</b></>;return href?<Link className="home-bar navigable" href={href(r)} key={`${label}-${i}`}>{body}</Link>:<div className="home-bar" key={`${label}-${i}`}>{body}</div>})}</div>}
function Facts({items}){return <div className="stat-insights">{items.map(x=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b>{x[2]&&<small>{x[2]}</small>}</article>)}</div>}
export default function StatisticsExplorerV4({data}){const[tab,setTab]=useState('dna'),genres=data.genres||[],countries=data.countries||[],saga=data.sagas||{},p=data.profile||{},bands=data.scoreBands||[],runtime=Number(p.movie_runtime_known||0)>0,genreBalance=[...(data.balance?.genres||[])].sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta)).slice(0,8),countryBalance=[...(data.balance?.countries||[])].sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta)).slice(0,8),heatGenres=genres.slice(0,7).map(x=>x.label),heatDecades=[...new Set((data.genreDecades||[]).map(x=>Number(x.bucket)))].sort((a,b)=>a-b).slice(-8),heat=new Map((data.genreDecades||[]).map(x=>[`${x.label}|${x.bucket}`,x])),durations=[{label:'< 90 min',total:p.runtime_lt90},{label:'90–119 min',total:p.runtime_90_119},{label:'120–149 min',total:p.runtime_120_149},{label:'150–179 min',total:p.runtime_150_179},{label:'180+ min',total:p.runtime_180_plus}];return <section className="stats-explorer"><div className="section-head home-section-head"><div><div className="eyebrow">Explorador</div><h2>Estadísticas</h2><p>Composición, puntuaciones y presencia física de la colección.</p></div></div><div className="stats-tabs" role="tablist">{tabs.map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div><div className={`stats-stage signature-${tab}`}>
{tab==='dna'&&<div className="stats-grid compact-editorial"><div><h3>ADN de la colección</h3><p className="stats-lead">Los géneros con mayor presencia en PikoFilm.</p><Bars rows={genres.slice(0,8)} href={r=>gh(r.label)}/></div><Facts items={[["Género dominante",genres[0]?.label||'—',genres[0]?`${nf(genres[0].total)} títulos`:null],["Década central",p.median_year?`${Math.floor(Number(p.median_year)/10)*10}–${Math.floor(Number(p.median_year)/10)*10+9}`:'—'],["PikoScore mediano",score(p.median_score)]]}/></div>}
{tab==='plex'&&<div><h3>Presencia física en Plex</h3><p className="stats-lead">Distribución descriptiva por género y década. No representa visionado.</p><div className="genre-heatmap"><div className="heat-head"><span/>{heatDecades.map(d=><b key={d}>{decadeLabel(d)}</b>)}</div>{heatGenres.map(g=><div className="heat-row" key={g}><strong>{g}</strong>{heatDecades.map(d=>{const r=heat.get(`${g}|${d}`);return <Link key={d} className={!r||Number(r.total)<20?'low-sample':''} href={`${gh(g)}&yearFrom=${d}&yearTo=${d+9}`} style={{'--heat':`${Math.max(5,Number(r?.coverage||0))}%`}}>{r?pct(r.coverage):'—'}</Link>})}</div>)}</div></div>}
{tab==='score'&&<div><h3>PikoScore</h3><p className="stats-lead">Distribución de puntuaciones de la colección.</p><Bars rows={bands}/><Facts items={[["Media PikoFilm",score(data.kpi.avg_score)],["Media de títulos en Plex",score(data.kpi.avg_score_plex)],["Con PikoScore",pct(p.score_coverage)]]}/></div>}
{tab==='countries'&&<div className="stats-grid compact-editorial"><div><h3>Cinematografías</h3><p className="stats-lead">Países con mayor presencia en la colección.</p><Bars rows={countries.slice(0,10)} href={r=>ch(r.label)}/></div><Facts items={countries.slice(0,4).map(r=>[r.label,nf(r.total),`${pct(r.coverage)} presentes en Plex`])}/></div>}
{tab==='sagas'&&<div className="stats-grid compact-editorial"><div><h3>Sagas y universos</h3><p className="stats-lead">Cobertura conocida en PikoFilm y presencia física en Plex.</p><div className="saga-dual compact"><div className="saga-orbit"><strong>{nf(saga.all)}</strong><span>sagas conocidas</span></div><div className="saga-orbit secondary"><strong>{pct(saga.coverage)}</strong><span>títulos en Plex</span></div></div></div><Facts items={[["Sagas conocidas",nf(saga.all)],["Títulos conocidos",nf(saga.movies)],["Títulos en Plex",nf(saga.owned_movies)]]}/></div>}
{tab==='profile'&&<div className="stats-grid compact-editorial"><div><h3>Perfil temporal y duración</h3><div className="profile-line compact"><span>{p.oldest_year||'—'}</span><i/><b>{Math.round(Number(p.median_year||0))||'—'}</b><i/><span>{p.newest_year||'—'}</span></div>{runtime?<Bars rows={durations}/>:<div className="metric-unavailable"><b>Duración no disponible</b></div>}</div><Facts items={[["Duración mediana",runtime?`${Math.round(p.median_runtime)} min`:'—'],["Películas de 180+ min",runtime?nf(p.runtime_180_plus):'—'],["Horas físicas en Plex",runtime?nf(p.plex_movie_hours):'—']]}/></div>}
{tab==='composition'&&<div className="stats-grid compact-editorial"><div><h3>Composición relativa · géneros</h3><p className="stats-lead">Diferencia descriptiva entre el peso en PikoFilm y entre los títulos presentes en Plex.</p><Bars rows={genreBalance} value="delta" href={r=>gh(r.label)}/></div><div><h3>Países</h3><Bars rows={countryBalance} value="delta" href={r=>ch(r.label)}/></div></div>}
</div></section>}
