'use client';
import {useEffect,useMemo,useState} from 'react';

const tabs=[['dna','ADN'],['coverage','Cobertura'],['score','PikoScore'],['countries','Países'],['sagas','Sagas'],['profile','Perfil'],['balance','Balance']];
const nf=n=>Number(n||0).toLocaleString('es-ES');
const fmt=n=>Number(n||0).toLocaleString('es-ES',{minimumFractionDigits:1,maximumFractionDigits:1});

function Bars({rows,value='total',suffix=''}){const max=Math.max(...rows.map(r=>Math.abs(Number(r[value]||0))),1);return <div className="home-bars">{rows.map((r,i)=><div className="home-bar" key={`${r.label||r.bucket}-${i}`}><span>{r.label||`${r.bucket}s`}</span><div><i style={{width:`${Math.max(3,Math.round(Math.abs(Number(r[value]||0))/max*100))}%`}}/></div><b>{fmt(r[value])}{suffix}</b></div>)}</div>}

export default function StatisticsExplorer({data}){
  const [tab,setTab]=useState('dna');
  useEffect(()=>{const saved=window.localStorage.getItem('pikofilm-home-stat');if(tabs.some(([id])=>id===saved))setTab(saved)},[]);
  const choose=id=>{setTab(id);window.localStorage.setItem('pikofilm-home-stat',id)};
  const gap=useMemo(()=>[...(data.genres||[])].sort((a,b)=>a.coverage-b.coverage).slice(0,6),[data.genres]);
  const country=(data.countries||[]).slice(0,8);
  const balance=[...(data.balance?.genres||[])].sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta)).slice(0,7);
  return <section className="dashboard-panel stats-explorer">
    <div className="section-head home-section-head"><div><div className="eyebrow">Mi filmoteca</div><h2>Explorador estadístico</h2><p>Una sola superficie para explorar la colección sin convertir Home en un muro de gráficos.</p></div></div>
    <div className="stats-tabs" role="tablist">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>choose(id)}>{label}</button>)}</div>
    <div className="stats-stage">
      {tab==='dna'&&<div className="stats-grid"><div><h3>ADN de la colección</h3><p className="stats-lead">Tus géneros más representados, con cobertura y PikoScore como contexto.</p><Bars rows={(data.genres||[]).slice(0,8)}/></div><div className="stat-insights"><article><span>Género dominante</span><b>{data.genres?.[0]?.label||'—'}</b><small>{nf(data.genres?.[0]?.total)} títulos</small></article><article><span>Mejor cobertura</span><b>{[...(data.genres||[])].sort((a,b)=>b.coverage-a.coverage)[0]?.label||'—'}</b><small>{fmt([...(data.genres||[])].sort((a,b)=>b.coverage-a.coverage)[0]?.coverage)}%</small></article></div></div>}
      {tab==='coverage'&&<div className="stats-grid"><div><h3>Mapa de cobertura</h3><p className="stats-lead">Dónde están los huecos más visibles del catálogo objetivo.</p><Bars rows={gap} value="coverage" suffix="%"/></div><div className="stat-insights"><article><span>Mayor hueco</span><b>{gap[0]?.label||'—'}</b><small>{fmt(gap[0]?.coverage)}% en Plex</small></article><article><span>Década más cubierta</span><b>{[...(data.decades||[])].sort((a,b)=>b.coverage-a.coverage)[0]?.bucket||'—'}s</b><small>{fmt([...(data.decades||[])].sort((a,b)=>b.coverage-a.coverage)[0]?.coverage)}%</small></article></div></div>}
      {tab==='score'&&<div className="stats-grid"><div><h3>PikoScore Observatory</h3><p className="stats-lead">Calidad cinematográfica del catálogo y cobertura de los títulos mejor puntuados.</p><Bars rows={data.scoreBands||[]} value="coverage" suffix="%"/></div><div className="stat-insights"><article><span>PikoScore medio</span><b>{fmt(data.kpi.avg_score)}</b><small>catálogo objetivo</small></article><article><span>En Plex</span><b>{fmt(data.kpi.avg_score_plex)}</b><small>media de tu biblioteca</small></article><article><span>Cobertura de score</span><b>{fmt(data.profile?.score_coverage)}%</b><small>títulos con PikoScore válido</small></article></div></div>}
      {tab==='countries'&&<div className="stats-grid"><div><h3>Cinematografías</h3><p className="stats-lead">Títulos asociados a cada país; las coproducciones pueden pertenecer a más de uno.</p><Bars rows={country}/></div><div className="stat-insights"><article><span>Más representada</span><b>{country[0]?.label||'—'}</b><small>{nf(country[0]?.total)} títulos asociados</small></article><article><span>Mejor cubierta</span><b>{[...country].sort((a,b)=>b.coverage-a.coverage)[0]?.label||'—'}</b><small>{fmt([...country].sort((a,b)=>b.coverage-a.coverage)[0]?.coverage)}%</small></article></div></div>}
      {tab==='sagas'&&<div className="stats-grid"><div><h3>Sagas & universos</h3><div className="saga-orbit"><strong>{fmt(data.sagas?.complete_pct)}%</strong><span>sagas completas</span></div></div><div className="stat-insights"><article><span>Completas</span><b>{nf(data.sagas?.complete)}</b><small>de {nf(data.sagas?.total_sagas)}</small></article><article><span>A una película</span><b>{nf(data.sagas?.one_missing)}</b><small>victorias rápidas</small></article><article><span>Cobertura de universos</span><b>{fmt(data.sagas?.coverage)}%</b><small>por títulos de saga</small></article></div></div>}
      {tab==='profile'&&<div className="stats-grid"><div><h3>Perfil de tu filmoteca</h3><div className="profile-line"><span>{data.profile?.oldest_year||'—'}</span><i/><b>{Math.round(Number(data.profile?.median_year||0))||'—'}</b><i/><span>2026</span></div><p className="stats-lead">Año mediano de la colección: {Math.round(Number(data.profile?.median_year||0))||'—'}.</p></div><div className="stat-insights"><article><span>Duración mediana</span><b>{Math.round(Number(data.profile?.median_runtime||0))||'—'} min</b><small>{fmt(data.profile?.runtime_coverage)}% con runtime conocido</small></article><article><span>Más de 3 horas</span><b>{nf(data.profile?.over_180)}</b><small>películas</small></article><article><span>Horas en Plex</span><b>{nf(data.profile?.plex_movie_hours)}</b><small>películas con runtime válido</small></article></div></div>}
      {tab==='balance'&&<div className="stats-grid"><div><h3>Balance de colección</h3><p className="stats-lead">Diferencia entre el peso de cada género en el catálogo objetivo y en Plex. Es descriptivo, no una meta.</p><Bars rows={balance} value="delta" suffix=" pp"/></div><div className="stat-insights"><article><span>Mayor desviación</span><b>{balance[0]?.label||'—'}</b><small>{Number(balance[0]?.delta||0)>0?'+':''}{fmt(balance[0]?.delta)} pp</small></article></div></div>}
    </div>
  </section>
}
