'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {nf,one,pct,score,decadeLabel} from '@/lib/home-format';
import {eligibleRows,mostCovered,bestScore} from '@/lib/home-statistics';
const tabs=[['dna','ADN'],['plex','Plex'],['score','PikoScore'],['countries','Países'],['sagas','Sagas'],['profile','Perfil'],['composition','Composición']];
const genreHref=l=>`/catalogo?genres=${encodeURIComponent(l)}`,countryHref=l=>`/catalogo?country=${encodeURIComponent(l)}`;
function Bars({rows,value='total',suffix='',hrefFor}){const safe=(rows||[]).filter(Boolean),max=Math.max(...safe.map(r=>Math.abs(Number(r?.[value]||0))),1);return <div className="home-bars">{safe.map((r,i)=>{const raw=Number(r?.[value]||0),label=r.label||r.band||(r.bucket!=null?decadeLabel(r.bucket):'—'),body=<><span>{label}</span><div><i style={{width:`${Math.max(3,Math.round(Math.abs(raw)/max*100))}%`}}/></div><b>{value==='total'?nf(raw):one(raw)}{suffix}</b></>;return hrefFor?<Link className="home-bar navigable" href={hrefFor(r)} key={`${label}-${i}`}>{body}</Link>:<div className="home-bar" key={`${label}-${i}`}>{body}</div>})}</div>}
function Fact({label,value,help,href}){const body=<><span>{label}</span><b>{value}</b>{help&&<small>{help}</small>}</>;return href?<Link href={href}>{body}</Link>:<article>{body}</article>}
export default function StatisticsExplorerV4({data}){const[tab,setTab]=useState('dna');useEffect(()=>{const x=localStorage.getItem('pikofilm-home-stat-v4');if(tabs.some(([id])=>id===x))setTab(x)},[]);const choose=x=>{setTab(x);localStorage.setItem('pikofilm-home-stat-v4',x)};const genres=data.genres||[],countries=data.countries||[],profile=data.profile||{},saga=data.sagas||{},scoreBands=data.scoreBands||[],genreEligible=useMemo(()=>eligibleRows(genres,'genre'),[genres]),countryEligible=useMemo(()=>eligibleRows(countries,'country'),[countries]),topGenre=genres[0],bestPlex=mostCovered(genres,'genre'),topScore=bestScore(genres,'genre'),runtimeValid=Number(profile.movie_runtime_known||0)>0,durations=[{label:'< 90 min',total:profile.runtime_lt90},{label:'90–119 min',total:profile.runtime_90_119},{label:'120–149 min',total:profile.runtime_120_149},{label:'150–179 min',total:profile.runtime_150_179},{label:'180+ min',total:profile.runtime_180_plus}],genreBalance=[...(data.balance?.genres||[])].filter(r=>genreEligible.some(g=>g.label===r.label)).sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta)).slice(0,8),countryBalance=[...(data.balance?.countries||[])].filter(r=>countryEligible.some(c=>c.label===r.label)).sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta)).slice(0,8),heatGenres=genres.slice(0,7).map(x=>x.label),heatDecades=[...new Set((data.genreDecades||[]).map(x=>Number(x.bucket)))].sort((a,b)=>a-b).slice(-8),heat=new Map((data.genreDecades||[]).map(x=>[`${x.label}|${x.bucket}`,x]));return <section className="stats-explorer"><div className="section-head home-section-head"><div><div className="eyebrow">Explorador</div><h2>Estadísticas</h2><p>Composición, puntuaciones y presencia física de la colección.</p></div></div><div className="stats-tabs" role="tablist">{tabs.map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} className={tab===id?'active':''} onClick={()=>choose(id)}>{label}</button>)}</div><div className={`stats-stage signature-${tab}`}>
{tab==='dna'&&<div className="stats-grid compact-editorial"><div><h3>ADN de la colección</h3><p className="stats-lead">Los géneros que más definen PikoFilm.</p><Bars rows={genres.slice(0,8)} hrefFor={r=>genreHref(r.label)}/></div><div className="stat-insights"><Fact label="Género dominante" value={topGenre?.label||'—'} help={topGenre?`${nf(topGenre.total)} títulos`:null}/><Fact label="Mayor presencia en Plex" value={bestPlex?.label||'—'} help={bestPlex?`${pct(bestPlex.coverage)} · ${nf(bestPlex.total)} títulos`:null}/><Fact label="Mejor PikoScore medio" value={topScore?.label||'—'} help={topScore?score(topScore.avg_score):null}/></div></div>}
{tab==='plex'&&<div><h3>Presencia física en Plex</h3><p className="stats-lead">Distribución descriptiva por género y década; no representa progreso de visionado.</p><div className="genre-heatmap"><div className="heat-head"><span/>{heatDecades.map(d=><b key={d}>{decadeLabel(d)}</b>)}</div>{heatGenres.map(g=><div className="heat-row" key={g}><strong>{g}</strong>{heatDecades.map(d=>{const r=heat.get(`${g}|${d}`),small=!r||Number(r.total)<20;return <Link key={d} className={small?'low-sample':''} href={`${genreHref(g)}&yearFrom=${d}&yearTo=${d+9}`} title={r?`${nf(r.owned)} de ${nf(r.total)} presentes en Plex`:'Sin muestra'} style={{'--heat':`${Math.max(5,Number(r?.coverage||0))}%`}}>{r?pct(r.coverage):'—'}</Link>})}</div>)}</div></div>}
{tab==='score'&&<div><h3>PikoScore</h3><p className="stats-lead">Distribución de puntuaciones de la colección.</p><Bars rows={scoreBands} hrefFor={r=>`/catalogo?scoreBand=${encodeURIComponent(r.label)}`}/><div className="score-comparison"><article><span>Media PikoFilm</span><b>{score(data.kpi.avg_score)}</b></article><article><span>Media en Plex</span><b>{score(data.kpi.avg_score_plex)}</b></article><article><span>Con PikoScore</span><b>{pct(profile.score_coverage)}</b></article></div></div>}
{tab==='countries'&&<div className="stats-grid compact-editorial"><div><h3>Cinematografías</h3><p className="stats-lead">Países con mayor presencia en la colección.</p><Bars rows={countries.slice(0,10)} hrefFor={r=>countryHref(r.label)}/></div><div className="stat-insights">{countries.slice(0,4).map(r=><Fact key={r.label} label={r.label} value={nf(r.total)} help={`${pct(r.coverage)} presentes en Plex`}/>)}</div></div>}
{tab==='sagas'&&<div className="stats-grid compact-editorial"><div><h3>Sagas y universos</h3><p className="stats-lead">Cobertura conocida en PikoFilm y presencia física en Plex.</p><div className="saga-dual compact"><div className="saga-orbit"><strong>{nf(saga.all)}</strong><span>sagas conocidas</span></div><div className="saga-orbit secondary"><strong>{pct(saga.coverage)}</strong><span>títulos en Plex</span></div></div></div><div className="stat-insights"><Fact label="Sagas conocidas" value={nf(saga.all)} href="/sagas"/><Fact label="Títulos conocidos" value={nf(saga.movies)}/><Fact label="Títulos en Plex" value={nf(saga.owned_movies)}/></div></div>}
{tab==='profile'&&<div className="stats-grid compact-editorial"><div><h3>Perfil temporal y duración</h3><div className="profile-line compact"><span>{profile.oldest_year||'—'}</span><i/><b>{Math.round(Number(profile.median_year||0))||'—'}</b><i/><span>{profile.newest_year||'—'}</span></div>{runtimeValid?<Bars rows={durations}/>:<div className="metric-unavailable"><b>Duración no disponible</b><span>No existe una muestra válida.</span></div>}</div><div className="stat-insights"><Fact label="Duración mediana" value={runtimeValid?`${Math.round(profile.median_runtime)} min`:'—'}/><Fact label="Películas de 180+ min" value={runtimeValid?nf(profile.runtime_180_plus):'—'}/><Fact label="Horas físicas en Plex" value={runtimeValid?nf(profile.plex_movie_hours):'—'}/></div></div>}
{tab==='composition'&&<div className="stats-grid compact-editorial"><div><h3>Composición relativa · géneros</h3><p className="stats-lead">Diferencia descriptiva entre el peso en PikoFilm y entre los títulos presentes en Plex.</p><Bars rows={genreBalance} value="delta" suffix=" pp" hrefFor={r=>genreHref(r.label)}/></div><div><h3>Países</h3><Bars rows={countryBalance} value="delta" suffix=" pp" hrefFor={r=>countryHref(r.label)}/></div></div>}
</div></section>}
