'use server';
import {revalidatePath} from 'next/cache';
import {redirect} from 'next/navigation';
import {db} from '@/lib/db';
import {enrichTitle} from '@/lib/enrich-title';
import {ensureImdbRating} from '@/lib/imdb-rating-on-demand';
import {syncPlexFast} from '@/lib/plex-sync';
import {seedPlexNewsCandidates} from '@/lib/plex-news-seed';
import {startRun,finishRun,audit,errorInfo} from '@/lib/runlog';
import {setMovieQualityFindingAction} from '@/lib/movie-quality-actions';
import {validateMovieFile} from '@/lib/movie-file-validation';
import {recomputeLifecycleForIds} from '@/lib/lifecycle';
import {setSeasonAvailability} from '@/lib/series-v2';
import {refreshSagas} from '@/lib/sagas-v2';
import {retryIdentity,reanalyzeIdentity,saveIdentity,setPlexIdentity} from '@/lib/identity';
import {captureDashboardSnapshot} from '@/lib/dashboard-v2';
function idOf(formData){const id=String(formData.get('imdbId')||'');if(!/^tt\d+$/.test(id))throw new Error('IMDb ID inválido');return id}
function safeReturn(v,fallback='/catalogo'){const s=String(v||'');return s.startsWith('/')&&!s.startsWith('//')?s:fallback}
function refresh(id){revalidatePath('/');revalidatePath('/catalogo');revalidatePath(`/catalogo/${id}`);revalidatePath('/catalogo/excluidas');revalidatePath('/novedades');revalidatePath('/sagas');revalidatePath('/plex');revalidatePath('/calidad');revalidatePath('/calidad/peliculas');revalidatePath('/calidad/pikoquality');revalidatePath('/calidad/series');revalidatePath('/calidad/identidad');revalidatePath('/calidad/validacion-identidad');revalidatePath('/calidad/datos');revalidatePath('/admin')}
async function plexMinimumIdentity(imdbId){const sql=db();const[row]=await sql`SELECT p.rating_key,p.plex_title,p.plex_year,p.item_type FROM plex_items p JOIN plex_external_ids x ON x.rating_key=p.rating_key AND x.provider='imdb' WHERE p.active AND p.item_type IN('movie','show') AND x.external_id=${imdbId} ORDER BY p.added_at DESC NULLS LAST LIMIT 1`;if(!row)return null;const title=String(row.plex_title||'').trim();if(!title)return null;return{ratingKey:row.rating_key,title,year:row.plex_year||null,type:row.item_type==='show'?'Serie':'Película'}}
export async function processTitle(_prevState,formData){let imdbId='';const run=await startRun('single_title','web',{stage:'start'});const sql=db();let insertedStaging=false;let minimum=null;try{imdbId=idOf(formData);const[existing]=await sql`SELECT imdb_id FROM movies WHERE imdb_id=${imdbId} LIMIT 1`;if(!existing){minimum=await plexMinimumIdentity(imdbId);if(minimum){await sql`INSERT INTO movies(imdb_id,type,title,title_es,year,origin,source_status,synced_at,inclusion_origin) VALUES(${imdbId},${minimum.type},${minimum.title},${minimum.title},${minimum.year},'plex_manual',${JSON.stringify({staging:true,identity_source:'plex',plex_rating_key:minimum.ratingKey})}::jsonb,now(),'plex_manual')`;insertedStaging=true}}
await ensureImdbRating(imdbId,{timeoutMs:12000}).catch(()=>null);const r=await enrichTitle(imdbId);if(insertedStaging)await sql`UPDATE movies SET origin='plex_manual',inclusion_origin='plex_manual',source_status=COALESCE(source_status,'{}'::jsonb)-'staging' WHERE imdb_id=${imdbId}`;await recomputeLifecycleForIds([imdbId]);refresh(imdbId);await finishRun(run.id,'success',{processed:1,updated:1,summary:{stage:'done',imdb_id:imdbId,operation:r.operation,title:r.title,identity_complete:Boolean(r.tmdb?.id||r.tmdb?.rating!=null),imdb_status:r.imdb?.rating!=null?'complete':'pending_dataset'}});await audit('catalog','title',imdbId,insertedStaging?'plex_catalogue':'enrich',{enrichment:'complete',source:insertedStaging?'plex':'catalog'});const verb=r.operation==='add'?'Añadida':'Actualizada',fa=r.fa?.rating!=null?`FA ${r.fa.rating}`:(r.fa?.id?`FA ${r.fa.id} sin nota`:'FA sin nota'),imdb=r.imdb?.rating!=null?`IMDb ${r.imdb.rating}`:'IMDb pendiente de dataset';return{ok:true,message:`${verb}: ${r.title}. PikoScore ${r.pikoscore??'—'} · ${imdb} · ${fa} · TMDb ${r.tmdb.rating??'—'}`}}catch(error){const err=errorInfo(error);if(imdbId&&insertedStaging&&minimum){const partial={partial:true,enrichment_status:'pending',identity_source:'plex',plex_rating_key:minimum.ratingKey,last_enrichment_error:err?.message||String(error),last_enrichment_at:new Date().toISOString(),tmdb:'missing'};await sql`UPDATE movies SET origin='plex_manual',inclusion_origin='plex_manual',source_status=(COALESCE(source_status,'{}'::jsonb)-'staging')||${JSON.stringify(partial)}::jsonb,synced_at=now() WHERE imdb_id=${imdbId}`;await recomputeLifecycleForIds([imdbId]);refresh(imdbId);await finishRun(run.id,'success',{processed:1,added:1,errors:1,summary:{stage:'partial',imdb_id:imdbId,title:minimum.title,origin:'plex_manual',enrichment:'partial',pending_error:err}});await audit('catalog','title',imdbId,'plex_catalogue_partial',{plex_rating_key:minimum.ratingKey,error:err?.message||String(error)});return{ok:true,message:`Añadida parcialmente: ${minimum.title}. Falta completar metadatos (${err?.message||'enriquecimiento pendiente'}). Revísala en Calidad → Identidad.`}}
if(imdbId&&insertedStaging)await sql`DELETE FROM movies WHERE imdb_id=${imdbId} AND source_status->>'staging'='true'`;await finishRun(run.id,'failed',{processed:imdbId?1:0,errors:1,summary:{stage:'failed',imdb_id:imdbId,error:err}});if(imdbId)refresh(imdbId);return{ok:false,message:error?.message||'No se pudo procesar el título'}}}
export async function syncPlex(_prevState){const run=await startRun('plex_fast_sync','web',{stage:'connect'});try{const r=await syncPlexFast(),identityChanges=r.seriesIdentityChanges||[],news=await seedPlexNewsCandidates().catch(()=>({seeded:0,resolved:0,failed:0,pending:0}));await captureDashboardSnapshot().catch(()=>{});revalidatePath('/');revalidatePath('/catalogo');revalidatePath('/novedades');revalidatePath('/plex');revalidatePath('/sagas');revalidatePath('/calidad');revalidatePath('/admin');await finishRun(run.id,'success',{processed:r.total,added:r.new,updated:r.changed,errors:(r.errors||0)+(news.failed||0),summary:{stage:'done',total:r.total,new:r.new,changed:r.changed,missing:r.missing,plex_news:news,series_identity_invalidated:identityChanges.length,series_identity_changes:identityChanges.slice(0,25)}});return{ok:true,message:`Plex actualizado: ${r.total.toLocaleString('es-ES')} títulos · ${r.new} altas · ${r.changed} cambios · ${r.missing} bajas${news.seeded?` · ${news.seeded} enviados a Novedades (${news.pending} preparando datos)`:''}${identityChanges.length?` · ${identityChanges.length} referencias de series pendientes de reconstruir`:''}`}}catch(error){await finishRun(run.id,'failed',{errors:1,summary:{stage:'failed',error:errorInfo(error)}});return{ok:false,message:error?.message||'No se pudo actualizar Plex'}}}
export async function markAcquiring(formData){const imdbId=idOf(formData),sql=db();await sql`INSERT INTO acquisition_status(imdb_id,status,started_at,updated_at) VALUES(${imdbId},'acquiring',now(),now()) ON CONFLICT(imdb_id) DO UPDATE SET status='acquiring',updated_at=now(),completed_at=NULL`;await audit('catalog','title',imdbId,'mark_acquiring');refresh(imdbId)}
export async function clearAcquiring(formData){const imdbId=idOf(formData),sql=db();await sql`DELETE FROM acquisition_status WHERE imdb_id=${imdbId}`;await audit('catalog','title',imdbId,'clear_acquiring');refresh(imdbId)}
export async function excludeTitle(formData){const imdbId=idOf(formData),reason=String(formData.get('reason')||'Excluida manualmente').slice(0,300),returnTo=safeReturn(formData.get('returnTo')),sql=db();await sql`INSERT INTO catalog_exclusions(imdb_id,reason,excluded_at,excluded_by) VALUES(${imdbId},${reason},now(),'pikofilm-ui') ON CONFLICT(imdb_id) DO UPDATE SET reason=EXCLUDED.reason,excluded_at=now(),excluded_by='pikofilm-ui'`;await sql`DELETE FROM acquisition_status WHERE imdb_id=${imdbId}`;await sql`UPDATE movie_quality_findings SET status='resolved',resolved_at=now(),last_seen_at=now() WHERE imdb_id=${imdbId} AND status IN('pending','waiting_sync')`;await recomputeLifecycleForIds([imdbId]);await audit('catalog','title',imdbId,'exclude',{reason});refresh(imdbId);const sep=returnTo.includes('?')?'&':'?';redirect(`${returnTo}${sep}notice=excluded&undo=${imdbId}`)}
export async function restoreTitle(formData){const imdbId=idOf(formData),returnTo=safeReturn(formData.get('returnTo'),'/catalogo/excluidas'),sql=db();await sql`DELETE FROM catalog_exclusions WHERE imdb_id=${imdbId}`;await recomputeLifecycleForIds([imdbId]);await audit('catalog','title',imdbId,'restore');refresh(imdbId);redirect(returnTo)}
export async function validateMovieFileAction(formData){const imdbId=idOf(formData);await validateMovieFile(imdbId);refresh(imdbId)}
export async function qualityAction(formData){const id=Number(formData.get('id')),action=String(formData.get('action')||''),note=String(formData.get('note')||'');if(!Number.isFinite(id)||!['exception','waiting_sync','reopen'].includes(action))throw new Error('Acción inválida');const sql=db();const[f]=await sql`SELECT imdb_id FROM movie_quality_findings WHERE id=${id}`;await setMovieQualityFindingAction(id,action,note);await audit('quality','finding',String(id),action,{note});if(f?.imdb_id)await recomputeLifecycleForIds([f.imdb_id]);if(f?.imdb_id)refresh(f.imdb_id);else revalidatePath('/calidad/peliculas')}
export async function seasonAvailabilityAction(formData){const key=String(formData.get('showRatingKey')||''),season=Number(formData.get('season')),available=String(formData.get('available'))==='true';await setSeasonAvailability(key,season,available);await audit('series','season',`${key}:${season}`,available?'available_es':'not_available_es');revalidatePath('/calidad/series');revalidatePath(`/calidad/series/${key}`)}
export async function refreshSagasAction(){try{const r=await refreshSagas();revalidatePath('/sagas');revalidatePath('/admin');return{ok:true,message:`Sagas: ${r.collections} colecciones refrescadas · ${r.members} miembros`}}catch(e){return{ok:false,message:e.message}}}
export async function retryIdentityAction(_prevState,formData){try{const id=idOf(formData),r=await retryIdentity(id);await recomputeLifecycleForIds([id]);revalidatePath('/calidad/identidad');refresh(id);return{ok:true,message:`Identidad actualizada: ${r.title}`}}catch(e){return{ok:false,message:e.message}}}
export async function reanalyzeIdentityAction(){try{const r=await reanalyzeIdentity();revalidatePath('/calidad/identidad');revalidatePath('/admin');return{ok:true,message:`Identidad: ${r.fixed}/${r.processed} resueltas automáticamente`}}catch(e){return{ok:false,message:e.message}}}
export async function saveIdentityAction(formData){const old=idOf(formData),newId=await saveIdentity(old,{imdbId:formData.get('newImdbId'),tmdbId:formData.get('tmdbId'),faId:formData.get('faId')});await recomputeLifecycleForIds([newId]);refresh(old);refresh(newId);revalidatePath('/calidad/identidad');redirect(`/catalogo/${newId}?notice=identity_saved`)}
export async function savePlexIdentityAction(formData){const ratingKey=String(formData.get('ratingKey')||''),imdbId=String(formData.get('imdbId')||'').trim(),tmdbId=String(formData.get('tmdbId')||'').trim(),faId=String(formData.get('faId')||'').trim();await setPlexIdentity(ratingKey,{imdbId,tmdbId,faId});revalidatePath('/plex');revalidatePath('/calidad/identidad');if(imdbId){const sql=db();const[existing]=await sql`SELECT imdb_id FROM movies WHERE imdb_id=${imdbId} LIMIT 1`;if(!existing){await seedPlexNewsCandidates({resolveLimit:25});await audit('identity','plex',ratingKey,'routed_to_news',{imdb_id:imdbId});refresh(imdbId);redirect(`/novedades?q=${encodeURIComponent(imdbId)}&notice=plex_identity_saved`)}await recomputeLifecycleForIds([imdbId]);refresh(imdbId);redirect(`/catalogo/${imdbId}`)}redirect('/calidad/identidad?notice=plex_identity_saved')}
