'use server';
import {revalidatePath} from 'next/cache';import {db} from '@/lib/db';import {enrichTitle} from '@/lib/enrich-title';import {syncPlexFast} from '@/lib/plex-sync';
function idOf(formData){const id=String(formData.get('imdbId')||'');if(!/^tt\d+$/.test(id))throw new Error('IMDb ID inválido');return id}
function refresh(id){revalidatePath('/');revalidatePath('/catalogo');revalidatePath(`/catalogo/${id}`);revalidatePath('/catalogo/excluidas');revalidatePath('/sagas');revalidatePath('/plex')}
export async function processTitle(_prevState,formData){let imdbId='';try{imdbId=idOf(formData);const r=await enrichTitle(imdbId);refresh(imdbId);const verb=r.operation==='add'?'Añadida':'Actualizada';const fa=r.fa?.rating!=null?`FA ${r.fa.rating}`:'FA sin nota';return{ok:true,message:`${verb}: ${r.title}. PikoScore ${r.pikoscore??'—'} · IMDb ${r.imdb.rating} · ${fa} · TMDb ${r.tmdb.rating??'—'}`}}catch(error){if(imdbId)refresh(imdbId);return{ok:false,message:error?.message||'No se pudo procesar el título'}}}
export async function syncPlex(_prevState){try{const r=await syncPlexFast();revalidatePath('/');revalidatePath('/catalogo');revalidatePath('/plex');revalidatePath('/sagas');revalidatePath('/calidad');return{ok:true,message:`Plex actualizado: ${r.total.toLocaleString('es-ES')} títulos · ${r.new} altas · ${r.changed} cambios · ${r.missing} bajas`}}catch(error){return{ok:false,message:error?.message||'No se pudo actualizar Plex'}}}
export async function markAcquiring(formData){const imdbId=idOf(formData),sql=db();await sql`INSERT INTO acquisition_status (imdb_id,status,started_at,updated_at) VALUES (${imdbId},'acquiring',now(),now()) ON CONFLICT (imdb_id) DO UPDATE SET status='acquiring',updated_at=now(),completed_at=NULL`;refresh(imdbId)}
export async function clearAcquiring(formData){const imdbId=idOf(formData),sql=db();await sql`DELETE FROM acquisition_status WHERE imdb_id=${imdbId}`;refresh(imdbId)}
export async function excludeTitle(formData){const imdbId=idOf(formData),reason=String(formData.get('reason')||'Excluida manualmente').slice(0,300),sql=db();await sql`INSERT INTO catalog_exclusions(imdb_id,reason,excluded_at,excluded_by) VALUES(${imdbId},${reason},now(),'pikofilm-ui') ON CONFLICT(imdb_id) DO UPDATE SET reason=EXCLUDED.reason,excluded_at=now(),excluded_by='pikofilm-ui'`;await sql`DELETE FROM acquisition_status WHERE imdb_id=${imdbId}`;refresh(imdbId)}
export async function restoreTitle(formData){const imdbId=idOf(formData),sql=db();await sql`DELETE FROM catalog_exclusions WHERE imdb_id=${imdbId}`;refresh(imdbId)}
export async function resolveMovieReview(formData){const id=Number.parseInt(String(formData.get('id')||''),10),status=String(formData.get('status')||'');if(!Number.isFinite(id)||!['approved','incorrect','deferred'].includes(status))throw new Error('Resolución inválida');const note=String(formData.get('note')||'').slice(0,500),sql=db();await sql`UPDATE plex_review_tasks SET status=${status},resolution_note=${note||null},resolved_at=CASE WHEN ${status}='deferred' THEN NULL ELSE now() END,updated_at=now() WHERE id=${id}`;revalidatePath('/');revalidatePath('/calidad/peliculas')}
