import Link from 'next/link';
import Segmented from '@/components/Segmented';
import StatisticsExplorer from '@/components/home/StatisticsExplorer';
import HistoryChart from '@/components/home/HistoryChart';
import {getDashboardV2,captureDashboardSnapshot} from '@/lib/dashboard-v2';
import {nf,pct,statusLabel} from '@/lib/home-format';
import {mostCovered,leastCovered,bestScore} from '@/lib/home-statistics';

export const dynamic='force-dynamic';

function Pulse({d}){
  const integrityHelp=d.pulse.integrity_anomalies===0?'Sin huérfanos, estados desconocidos ni incompatibilidades estructurales':`${nf(d.pulse.integrity_anomalies)} anomalías estructurales`;
  const formula=`Salud = Calidad × 70% + Integridad × 30%. Calidad ${pct(d.pulse.quality)} · Integridad ${pct(d.pulse.integrity)}.`;
  return <section className="home-command"><div className="command-copy"><div className="eyebrow">Centro de control</div><h1>PikoFilm</h1><p>Estado global, evolución y estadísticas de tu filmoteca. El detalle operativo vive en cada módulo.</p><div className="command-status"><span className="live-dot"/> Datos canónicos del catálogo y Calidad</div></div><div className="pulse-wrap"><div className="pulse-ring" style={{'--pulse':Math.round(d.pulse.score)}} title={formula}><div><strong>{pct(d.pulse.score).replace(' %','')}</strong><span>{statusLabel(d.pulse.score)}</span><small>salud de PikoFilm</small></div></div><div className="pulse-legend"><div><span>Calidad</span><b>{pct(d.pulse.quality)}</b><small>avance canónico del flujo de Calidad</small></div><div title={integrityHelp}><span>Integridad</span><b>{pct(d.pulse.integrity)}</b><small>{integrityHelp}</small></div><div className="pulse-formula" title={formula}>ⓘ 70% Calidad · 30% Integridad</div></div></div></section>;
}

function Universe({d}){
  const k=d.kpi,owned=Math.max(0,Number(k.coverage||0)),missing=Math.max(0,100-owned);
  return <section className="dashboard-panel universe-panel"><div className="section-head home-section-head"><div><div className="eyebrow">Ahora</div><h2>Tu universo PikoFilm</h2><p>Foto descriptiva del catálogo objetivo y su presencia actual en Plex.</p></div></div><div className="universe-topline"><Link href="/catalogo" className="universe-total-v4"><span>Catálogo objetivo</span><strong>{nf(k.catalog_total)}</strong><small>{nf(k.movies)} películas · {nf(k.series)} series/miniseries</small></Link><Link href="/catalogo?status=in_plex" className="universe-coverage-kpi"><strong>{pct(owned)}</strong><span>en Plex</span></Link></div><div className="universe-progress-labels"><span>{pct(owned)} En Plex</span><span>{pct(missing)} Pendientes</span></div><div className="universe-progress" aria-label={`${pct(owned)} en Plex y ${pct(missing)} pendientes`}><Link href="/catalogo?status=in_plex" style={{width:`${owned}%`}} className="owned"/><Link href="/catalogo?status=missing" style={{width:`${missing}%`}} className="missing"/></div><div className="universe-legend-v4"><Link href="/catalogo?status=in_plex"><span>En Plex</span><b>{nf(k.in_plex)}</b></Link><Link href="/catalogo?status=missing"><span>Pendientes</span><b>{nf(k.missing)}</b></Link></div></section>;
}

function Radar({d}){
  const stages=(d.quality?.stages||[]).filter(s=>Number(s.count||0)>0);
  const critical=stages.find(s=>['recovery','identity','validation'].includes(s.id));
  const volume=[...stages].filter(s=>['movies','series','data','pikoquality'].includes(s.id)).sort((a,b)=>Number(b.count)-Number(a.count))[0];
  const opportunity=Number(d.sagas?.one||0)>0?{count:Number(d.sagas.one),href:'/sagas?state=one'}:null;
  const label=s=>s?.id==='data'?'Títulos con datos o PikoScore pendientes':s?.id==='movies'?'Películas que requieren revisión':s?.id==='series'?'Series que requieren revisión':s?.id==='pikoquality'?'Archivos pendientes de PikoQuality':s?.label;
  return <section className="dashboard-panel radar-panel"><div className="section-head home-section-head"><div><div className="eyebrow">Prioridades</div><h2>Radar PikoFilm</h2><p>Decisión ejecutiva: qué merece tu atención primero.</p></div><Link href="/calidad">Abrir Calidad →</Link></div><div className="radar-columns radar-executive"><div className="radar-group critical"><span>Prioridad</span>{critical?<Link href={critical.href}><b>{nf(critical.count)}</b><em>{label(critical)}</em><small>Resolver primero →</small></Link>:<small>Sin incidencias críticas</small>}</div><div className="radar-group attention"><span>Mayor volumen</span>{volume?<Link href={volume.href}><b>{nf(volume.count)}</b><em>{label(volume)}</em><small>Revisar →</small></Link>:<small>Sin áreas de atención</small>}</div><div className="radar-group opportunity"><span>Victoria rápida</span>{opportunity?<Link href={opportunity.href}><b>{nf(opportunity.count)}</b><em>Sagas a una película de completarse</em><small>Ver sagas →</small></Link>:<small>Sin oportunidades destacadas</small>}</div></div></section>;
}

function QualityMap({d}){const stages=(d.quality?.stages||[]).filter(s=>s.id!=='recovery');return <section className="dashboard-panel quality-map-panel"><div className="section-head home-section-head"><div><div className="eyebrow">Calidad</div><h2>Mapa de Calidad</h2><p>Diagnóstico completo: espejo de los agregados canónicos de cada subpágina.</p></div><Link href="/calidad">Ver detalle →</Link></div><div className="quality-map">{stages.map(s=>{const healthy=Number(s.count||0)===0;return <Link key={s.id} href={s.href} className={healthy?'ok':'needs'}><span>{s.label}</span><strong>{healthy?'✓':nf(s.count)}</strong><small>{healthy?'Completa / sin casos activos':'requieren acción'}</small></Link>})}</div></section>}

function History({d,period}){const rows=(d.history||[]).filter(x=>Number(x.metrics?.schema_version)===Number(d.snapshotSchemaVersion)).map(x=>({date:new Date(x.snapshot_date).toLocaleDateString('es-ES',{day:'2-digit',month:'short'}),catalog:x.metrics?.catalog_total==null?null:Number(x.metrics.catalog_total),plex:x.metrics?.in_plex==null?null:Number(x.metrics.in_plex),missing:x.metrics?.missing==null?null:Number(x.metrics.missing),quality:x.metrics?.quality_progress==null?(x.metrics?.pulse_quality==null?null:Number(x.metrics.pulse_quality)):Number(x.metrics.quality_progress)}));return <section className={`dashboard-panel history-panel ${rows.length<14?'young-history':''}`}><div className="section-head home-section-head"><div><div className="eyebrow">Evolución</div><h2>Historia de PikoFilm</h2><p>{rows.length<=1?'Histórico iniciado hoy. Cada día añadirá un punto real comparable.':'Evolución basada sólo en snapshots comparables.'}</p></div>{rows.length>=7&&<Segmented value={period} items={[['7','7 días'],['30','30 días'],['90','90 días'],['365','1 año'],['3650','Todo']].filter(([v])=>v==='7'||v==='3650'||rows.length>=Number(v)).map(([value,label])=>({value,label,href:`/?period=${value}`}))}/>}</div><HistoryChart rows={rows}/></section>}

function Highlights({d}){const best=mostCovered(d.genres||[],'genre'),gap=leastCovered(d.genres||[],'genre'),bestS=bestScore(d.genres||[],'genre');const insights=[best&&{title:`${best.label} destaca en cobertura`,body:`${pct(best.coverage)} · ${nf(best.owned)}/${nf(best.total)} títulos`,href:`/catalogo?genre=${encodeURIComponent(best.label)}`},gap&&{title:`${gap.label} es el mayor hueco representativo`,body:`${pct(gap.coverage)} de cobertura`,href:`/catalogo?genre=${encodeURIComponent(gap.label)}&status=missing`},Number(d.sagas?.one||0)>0&&{title:`${nf(d.sagas.one)} sagas están a una película`,body:'La victoria rápida más clara de tu colección.',href:'/sagas?state=one'}].filter(Boolean).slice(0,3);return <section className="dashboard-panel highlights-panel"><div className="section-head home-section-head"><div><div className="eyebrow">Síntesis</div><h2>Lo que dice tu filmoteca</h2><p>Conclusiones deterministas sobre segmentos representativos; nunca rellenamos por rellenar.</p></div></div><div className="filmoteca-insights">{insights.map((x,i)=><Link href={x.href} key={i}><span>{i===0?'Fortaleza':i===1?'Hueco':'Oportunidad'}</span><b>{x.title}</b><small>{x.body}</small></Link>)}</div>{bestS&&<p className="secondary-insight">Mejor PikoScore representativo: <b>{bestS.label}</b> · {Number(bestS.avg_score).toLocaleString('es-ES',{minimumFractionDigits:1,maximumFractionDigits:1})}</p>}</section>}

export default async function Home({searchParams}){const p=await searchParams,period=p.period||'30';let d=await getDashboardV2(period);const today=new Date().toISOString().slice(0,10),hasToday=(d.history||[]).some(x=>String(x.snapshot_date).slice(0,10)===today&&Number(x.metrics?.schema_version)===Number(d.snapshotSchemaVersion));if(!hasToday){try{await captureDashboardSnapshot();d=await getDashboardV2(period)}catch(e){console.error('home snapshot',e)}}return <div className="home-v3"><Pulse d={d}/><div className="home-now"><Universe d={d}/><Radar d={d}/></div><QualityMap d={d}/><History d={d} period={period}/><Highlights d={d}/><StatisticsExplorer data={{kpi:d.kpi,genres:d.genres,decades:d.decades,countries:d.countries,scoreBands:d.scoreBands,sagas:d.sagas,profile:d.profile,balance:d.balance}}/><p className="footnote">Última sincronización Plex: {d.kpi.last_plex_sync?new Date(d.kpi.last_plex_sync).toLocaleString('es-ES'):'sin registrar'}.</p></div>}
