import Link from 'next/link';
import {headers} from 'next/headers';
import {notFound} from 'next/navigation';
import {db} from '@/lib/db';
import {getSeriesDetailV2} from '@/lib/operational-queries';
import {seasonAvailabilityAction} from '@/app/actions';
import {reviewSeriesExtraAction} from '../actions';
import '../series-detail.css';
export const dynamic='force-dynamic';

const stateLabel={present:'En Plex',missing_actionable:'Falta en Plex',not_available_es:'No disponible ES',availability_unknown:'Por confirmar'};
const pct=(a,b)=>b?Math.round(100*a/b):0;
const qs=(base,patch)=>{const p=new URLSearchParams();Object.entries({...base,...patch}).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!==''&&v!==false)p.set(k,String(v))});return`?${p.toString()}`};

function catalogOriginFromReferer(referer=''){
  try{const u=new URL(referer);return u.pathname.startsWith('/catalogo/')?`${u.pathname}${u.search}`:''}catch{return''}
}

const extraDecisionLabel=d=>d==='special'?'Extra / especial válido':d==='not_needed'?'Ignorado manualmente':null;

export default async function SerieDetalle({params,searchParams}){
  const{ratingKey}=await params,q=await searchParams,s=await getSeriesDetailV2(ratingKey);if(!s)notFound();
  const sql=db();
  const overrides=await sql`SELECT season_number,episode_number,decision,note,updated_at FROM series_episode_overrides WHERE show_rating_key=${ratingKey} ORDER BY season_number,episode_number`;
  const overrideMap=new Map(overrides.map(o=>[`${o.season_number}:${o.episode_number}`,o]));
  const extras=(s.extras||[]).map(e=>({...e,override:overrideMap.get(`${e.season_number}:${e.episode_number}`)||null}));
  const unresolvedExtras=extras.filter(e=>!['special','not_needed'].includes(String(e.override?.decision||'')));
  const resolvedExtras=extras.filter(e=>['special','not_needed'].includes(String(e.override?.decision||'')));
  const seasonNums=[...new Set(s.episodes.map(e=>e.season_number))].filter(n=>n!=null).sort((a,b)=>a-b);
  const selected=q.season==='all'?'all':q.season!==undefined?Number(q.season):(seasonNums[0]??null);
  const status=String(q.status||'all');
  const missingOnly=q.missing==='1';
  const h=await headers();
  const inferredFrom=catalogOriginFromReferer(h.get('referer')||'');
  const from=String(q.from||inferredFrom||'');
  const back=from.startsWith('/catalogo')?from:'/calidad/series';
  const counts=seasonNums.map(n=>{const es=s.episodes.filter(e=>e.season_number===n),a=s.seasons.find(x=>x.season_number===n);return{n,total:es.length,present:es.filter(e=>e.effective_status==='present').length,missing:es.filter(e=>e.effective_status==='missing_actionable').length,unknown:es.filter(e=>e.effective_status==='availability_unknown').length,noes:es.filter(e=>e.effective_status==='not_available_es').length,availability:a?.status||'UNKNOWN'}});
  const scope=selected==='all'?s.episodes:s.episodes.filter(e=>e.season_number===selected);
  const filtered=scope.filter(e=>missingOnly?e.effective_status==='missing_actionable':status==='all'||e.effective_status===status);
  const present=s.episodes.filter(e=>e.effective_status==='present').length,missing=s.episodes.filter(e=>e.effective_status==='missing_actionable').length,unknown=s.episodes.filter(e=>e.effective_status==='availability_unknown').length,noes=s.episodes.filter(e=>e.effective_status==='not_available_es').length,total=s.episodes.length||s.official_episodes||0;
  const qv=s.quality||{},qscore=qv.score==null?null:Number(qv.score),qband=qscore==null?'Sin calcular':qscore>=85?'Excelente':qscore>=75?'Muy buena':qscore>=60?'Correcta':qscore>=40?'Mejorable':'Deficiente';
  const base={season:selected,status,missing:missingOnly?'1':undefined,from:from||undefined};
  return <>
    <div className="episode-topbar"><Link className="back-chip" href={back}>← Volver</Link><div><span>Origen</span><b>{from.startsWith('/catalogo')?'Catálogo':'Calidad · Series'}</b></div></div>
    <section className="episode-hero"><div><div className="eyebrow">REVISIÓN DE CAPÍTULOS</div><h1>{s.display_title||s.title}</h1><p>{s.year||'—'} · {(s.genres||[]).slice(0,3).join(' · ')||`${s.official_seasons||seasonNums.length} temporadas`}</p></div><div className="hero-metric"><span>PikoScore</span><strong>{s.final_rating?.toFixed?.(1)??s.final_rating??'—'}</strong></div><div className="hero-metric quality"><span>PikoQuality</span><strong>{qscore??'—'}</strong><small>{qband}</small></div><div className="hero-metric coverage"><span>Cobertura Plex</span><strong>{pct(present,total)}%</strong><small>{present}/{total} episodios</small></div></section>

    {unresolvedExtras.length>0&&<section className="review-card" style={{margin:'18px 0'}}><div className="section-head"><div><h2>⚠ Episodios extra que necesitan decisión</h2><p>{unresolvedExtras.length} episodio{unresolvedExtras.length===1?'':'s'} de Plex no tienen correspondencia oficial en TMDb.</p></div><strong className="bad">{unresolvedExtras.length} pendientes</strong></div><div style={{display:'grid',gap:10,marginTop:14}}>{unresolvedExtras.map(e=><div key={e.rating_key} style={{display:'grid',gridTemplateColumns:'110px minmax(180px,1fr) auto',gap:14,alignItems:'center',padding:'13px 0',borderTop:'1px solid rgba(255,255,255,.08)'}}><div><b>S{String(e.season_number??0).padStart(2,'0')}E{String(e.episode_number??0).padStart(2,'0')}</b><small style={{display:'block',opacity:.65}}>Plex #{e.rating_key}</small></div><div><b>{e.plex_title||'Sin título'}</b><small style={{display:'block',opacity:.7}}>No existe con esta numeración en la referencia oficial.</small></div><div className="availability-actions" style={{justifyContent:'flex-end'}}><form action={reviewSeriesExtraAction}><input type="hidden" name="ratingKey" value={ratingKey}/><input type="hidden" name="season" value={e.season_number}/><input type="hidden" name="episode" value={e.episode_number}/><input type="hidden" name="decision" value="special"/><button>Es especial / extra válido</button></form><form action={reviewSeriesExtraAction}><input type="hidden" name="ratingKey" value={ratingKey}/><input type="hidden" name="season" value={e.season_number}/><input type="hidden" name="episode" value={e.episode_number}/><input type="hidden" name="decision" value="not_needed"/><button>Ignorar</button></form></div></div>)}</div></section>}

    {resolvedExtras.length>0&&<details className="review-card" style={{margin:'18px 0'}}><summary><b>✓ Extras ya revisados ({resolvedExtras.length})</b></summary><div style={{display:'grid',gap:8,marginTop:12}}>{resolvedExtras.map(e=><div key={e.rating_key} style={{display:'grid',gridTemplateColumns:'100px 1fr auto',gap:12,alignItems:'center',padding:'10px 0',borderTop:'1px solid rgba(255,255,255,.08)'}}><b>S{String(e.season_number??0).padStart(2,'0')}E{String(e.episode_number??0).padStart(2,'0')}</b><div><span>{e.plex_title||'Sin título'}</span><small style={{display:'block',opacity:.65}}>{extraDecisionLabel(e.override?.decision)}{e.override?.note?` · ${e.override.note}`:''}</small></div><form action={reviewSeriesExtraAction}><input type="hidden" name="ratingKey" value={ratingKey}/><input type="hidden" name="season" value={e.season_number}/><input type="hidden" name="episode" value={e.episode_number}/><input type="hidden" name="decision" value="reopen"/><button>Reabrir</button></form></div>)}</div></details>}

    <section className="season-review"><div className="section-head"><div><h2>Temporadas</h2><p>{seasonNums.length} temporadas · {total} episodios oficiales</p></div><Link className={selected==='all'?'active-link':''} href={qs(base,{season:'all'})}>Todas las temporadas</Link></div><div className="season-strip">{counts.map(c=><Link key={c.n} href={qs(base,{season:c.n})} className={`season-tile ${selected===c.n?'active':''} ${c.missing?'has-missing':c.unknown?'has-unknown':'complete'}`}><div><b>T{c.n}</b><span>{c.missing?`${c.missing} faltan`:c.unknown?`${c.unknown} por confirmar`:'Completa'}</span></div><strong>{pct(c.present,c.total)}%</strong><small>{c.present}/{c.total} en Plex</small></Link>)}</div></section>

    <section className="episode-workbench"><div className="filter-bar"><div className="filter-pills"><Link className={status==='all'&&!missingOnly?'active':''} href={qs(base,{status:'all',missing:undefined})}>Todos <b>{scope.length}</b></Link><Link className={status==='present'&&!missingOnly?'active':''} href={qs(base,{status:'present',missing:undefined})}>En Plex <b>{scope.filter(e=>e.effective_status==='present').length}</b></Link><Link className={status==='missing_actionable'||missingOnly?'danger active':''} href={qs(base,{status:'missing_actionable',missing:undefined})}>Faltan <b>{scope.filter(e=>e.effective_status==='missing_actionable').length}</b></Link><Link className={status==='availability_unknown'?'warn active':''} href={qs(base,{status:'availability_unknown',missing:undefined})}>Por confirmar <b>{scope.filter(e=>e.effective_status==='availability_unknown').length}</b></Link><Link className={status==='not_available_es'?'muted active':''} href={qs(base,{status:'not_available_es',missing:undefined})}>No disp. ES <b>{scope.filter(e=>e.effective_status==='not_available_es').length}</b></Link></div><Link className={`missing-toggle ${missingOnly?'on':''}`} href={qs(base,{status:'all',missing:missingOnly?undefined:'1'})}><span>{missingOnly?'✓':'○'}</span> Solo capítulos faltantes</Link></div>

      <div className="episode-table-head"><div><h2>{selected==='all'?'Todas las temporadas':`Temporada ${selected}`}</h2><p>{filtered.length} episodio{filtered.length===1?'':'s'} mostrados</p></div><div className="scope-summary"><b>{scope.filter(e=>e.effective_status==='missing_actionable').length}</b><span>faltan</span></div></div>
      <div className="episode-table"><div className="episode-row header"><span>Episodio</span><span>Título / estreno</span><span>Estado Plex</span><span>Disponibilidad ES</span></div>{filtered.length?filtered.map(e=><div className={`episode-row ${e.effective_status}`} key={`${e.season_number}-${e.episode_number}`}><div className="episode-code">S{String(e.season_number).padStart(2,'0')}E{String(e.episode_number).padStart(2,'0')}</div><div className="episode-name"><b>{e.expected_name||e.name||'Sin título'}</b><span>{e.air_date?new Date(e.air_date).toLocaleDateString('es-ES'):'Sin fecha'} · {e.expected_runtime_minutes??e.runtime_minutes??'—'} min</span></div><div className="plex-state">{e.effective_status==='present'?'✓ En Plex':e.effective_status==='missing_actionable'?'✕ Falta en Plex':e.effective_status==='availability_unknown'?'? Por confirmar':'—'}</div><div className="es-state">{e.effective_status==='not_available_es'?'No disponible':e.effective_status==='availability_unknown'?'Por confirmar':e.effective_status==='present'||e.effective_status==='missing_actionable'?'Disponible':'—'}</div></div>):<div className="empty-state">No hay episodios con este filtro.</div>}</div>
    </section>

    <div className="review-bottom-grid"><section className="review-card"><h3>Resumen general</h3><div><span>Total oficiales</span><b>{total}</b></div><div><span>En Plex</span><b className="ok">{present}</b></div><div><span>Faltan en Plex</span><b className="bad">{missing}</b></div><div><span>Por confirmar</span><b className="warn">{unknown}</b></div><div><span>No disponibles ES</span><b>{noes}</b></div></section><section className="review-card"><h3>Disponibilidad en España</h3>{selected!=='all'&&counts.find(x=>x.n===selected)?<><p>Temporada {selected}: <b>{counts.find(x=>x.n===selected).availability}</b></p><div className="availability-actions"><form action={seasonAvailabilityAction}><input type="hidden" name="showRatingKey" value={ratingKey}/><input type="hidden" name="season" value={selected}/><input type="hidden" name="available" value="true"/><button>Sí emitida</button></form><form action={seasonAvailabilityAction}><input type="hidden" name="showRatingKey" value={ratingKey}/><input type="hidden" name="season" value={selected}/><input type="hidden" name="available" value="false"/><button>No disponible</button></form></div></>:<p>Selecciona una temporada para gestionar su disponibilidad.</p>}</section><section className="review-card"><h3>Incidencias de mapeo</h3>{unresolvedExtras.length?<><strong className="bad">⚠ {unresolvedExtras.length} episodio{unresolvedExtras.length===1?'':'s'} pendiente{unresolvedExtras.length===1?'':'s'} de revisar</strong><p>{resolvedExtras.length?`${resolvedExtras.length} extras ya tienen una decisión guardada.`:'Decide arriba si son especiales válidos o deben ignorarse.'}</p></>:<><strong className="ok">✓ Sin extras pendientes</strong><p>{resolvedExtras.length?`${resolvedExtras.length} extras revisados y aceptados manualmente.`:'Los episodios de Plex coinciden con la referencia oficial.'}</p></>}</section></div>
  </>;
}
