import Link from 'next/link';
import {headers} from 'next/headers';
import {notFound} from 'next/navigation';
import ActionButton from '@/components/ActionButton';
import {seasonAvailabilityAction} from '@/app/actions';
import {getSeriesDetailSummary,getSeriesEpisodeScope,seriesMaintenance} from '@/lib/series-detail-query';
import {syncPlexSeriesDetailAction,refreshOneSeriesAction,confirmEsAvailabilityAction,reviewSeriesExtraAction,resetSeasonAvailabilityAction} from '../actions';
import '../series-detail.css';
export const dynamic='force-dynamic';
export const maxDuration=60;

const pct=(a,b)=>b?Math.round(100*Number(a||0)/Number(b||0)):0;
const dateTime=v=>v?new Date(v).toLocaleString('es-ES',{dateStyle:'short',timeStyle:'short'}):'Nunca';
const dateOnly=v=>v?new Date(v).toLocaleDateString('es-ES'):'Sin fecha';
const qs=(base,patch={})=>{const p=new URLSearchParams();for(const[k,v]of Object.entries({...base,...patch}))if(v!==undefined&&v!==null&&v!==''&&v!==false)p.set(k,String(v));return`?${p.toString()}`};
const extraDecisionLabel=d=>d==='special'?'Extra / especial válido':d==='not_needed'?'Ignorado manualmente':null;
const availabilityLabel=s=>s==='ES_AVAILABLE'?'Disponible en España':s==='ES_PARTIAL'?'Parcialmente disponible':s==='ES_NOT_YET'?'Aún no estrenada':s==='EXCEPTION_AVAILABLE'?'Disponible · corrección manual':s==='EXCEPTION_NOT_AVAILABLE'?'No disponible · corrección manual':s==='PLEX_COMPLETE'?'No requiere comprobación':s==='UNKNOWN'||!s?'Por confirmar':s;
const stateText=s=>s==='present'?'✓ En Plex':s==='missing_actionable'?'⚠ Falta en Plex':s==='availability_unknown'?'? Por confirmar':s==='not_available_es'?'○ No disponible ES':s;
const availabilityText=s=>s==='present'?'No aplica · ya está en Plex':s==='missing_actionable'?'Disponible en España':s==='availability_unknown'?'Pendiente de confirmar':s==='not_available_es'?'No disponible / no exigible':'—';
const maintenanceAction=(key)=>key==='plex'?syncPlexSeriesDetailAction:key==='tmdb'?refreshOneSeriesAction:confirmEsAvailabilityAction;
const maintenancePending=key=>key==='plex'?'Leyendo Plex…':key==='tmdb'?'Consultando TMDb…':'Consultando España…';
const runLabel=t=>t==='plex_detail'?'Plex':t==='tmdb_refresh'?'TMDb':t==='es_availability'?'España':t;
function catalogOriginFromReferer(referer=''){try{const u=new URL(referer);return u.pathname.startsWith('/catalogo/')?`${u.pathname}${u.search}`:''}catch{return''}}

function Evidence({e}){
  const bits=[];
  bits.push({label:'TMDb',value:'Episodio oficial ✓'});
  bits.push({label:'Plex',value:e.effective_status==='present'?'Encontrado ✓':'No encontrado'});
  if(e.effective_status!=='present')bits.push({label:'España',value:availabilityText(e.effective_status)});
  if(e.diagnostic_status)bits.push({label:'Diagnóstico',value:`${e.diagnostic_status}${e.diagnostic_confidence?` · confianza ${e.diagnostic_confidence}`:''}`});
  if(e.diagnostic_reason)bits.push({label:'Evidencia',value:e.diagnostic_reason});
  if(e.covered_by_rating_key)bits.push({label:'Archivo Plex',value:`Cubierto por ${e.covered_by_rating_key}`});
  return <div className="episode-evidence">{bits.map(x=><div key={x.label}><span>{x.label}</span><b>{x.value}</b></div>)}</div>;
}

export default async function SerieDetalle({params,searchParams}){
  const{ratingKey}=await params,q=await searchParams,summary=await getSeriesDetailSummary(ratingKey);if(!summary)notFound();
  const h=await headers(),inferred=catalogOriginFromReferer(h.get('referer')||''),from=String(q.from||inferred||''),back=from.startsWith('/catalogo')?from:'/calidad/series';
  const seasons=summary.seasonCounts||[];
  const firstAttention=seasons.find(x=>Number(x.missing)>0||Number(x.unknown)>0),defaultSeason=firstAttention?.season_number??seasons[seasons.length-1]?.season_number??'all';
  const selected=q.season==='all'?'all':q.season!==undefined?Number(q.season):defaultSeason;
  const status=['all','present','missing_actionable','availability_unknown','not_available_es'].includes(String(q.status))?String(q.status):'all';
  const coverage=['all','present','absent'].includes(String(q.coverage))?String(q.coverage):'all';
  const episodes=await getSeriesEpisodeScope(ratingKey,{season:selected,status,coverage});
  const base={season:selected,status,coverage,from:from||undefined};
  const t=summary.totals||{},quality=summary.classification?.quality||{},qv=summary.quality||{},qscore=qv.score==null?null:Number(qv.score);
  const selectedSeason=selected==='all'?null:seasons.find(x=>Number(x.season_number)===Number(selected))||null;
  const scope=selected==='all'?t:selectedSeason||t;
  const maintenance=seriesMaintenance(summary);
  const actionRows=episodes.filter(e=>e.effective_status!=='present'&&e.effective_status!=='not_available_es');
  const actionIndex=new Map(actionRows.map((e,i)=>[`${e.season_number}:${e.episode_number}`,i]));
  const infoRatings=[['PikoScore',summary.final_rating==null?'—':Number(summary.final_rating).toFixed(1)],['PikoQuality',qscore??'—'],['IMDb',summary.imdb_rating==null?'—':Number(summary.imdb_rating).toFixed(1)],['TMDb',summary.tmdb_rating==null?'—':Number(summary.tmdb_rating).toFixed(1)]];
  const nextAction=summary.classification?.primaryState==='plex_sync'?'Actualizar Plex':summary.classification?.primaryState==='tmdb_refresh'?'Actualizar TMDb':Number(t.missing)>0?'Revisar faltantes':summary.unresolvedExtras.length?'Resolver anomalías':Number(t.unknown)>0?'Comprobar España':'No requiere ninguna acción';
  return <>
    <div className="episode-topbar"><Link className="back-chip" href={back}>← Volver</Link><div><span>Origen</span><b>{from.startsWith('/catalogo')?'Catálogo':'Calidad · Series'}</b></div><div className="topbar-ids"><span>Plex #{ratingKey}</span><span>TMDb {summary.tmdb_id||'—'}</span><span>IMDb {summary.imdb_id||'—'}</span></div></div>

    <section className={`episode-hero quality-${quality.state||'UNKNOWN'}`}><div className="hero-title"><div className="eyebrow">CALIDAD · SERIES · DETALLE</div><h1>{summary.display_title||summary.title}</h1><p>{summary.year||'—'} · {(summary.genres||[]).slice(0,3).join(' · ')||`${summary.official_seasons||seasons.length} temporadas`}</p><div className={`quality-state ${quality.severity||'warn'}`}><strong>{quality.label||'Diagnóstico pendiente'}</strong><span>{quality.reason||'Sin diagnóstico'}</span><small>Evaluado: {dateTime(quality.evaluated_at)}</small></div></div><div className="hero-metric"><span>Cobertura Plex</span><strong>{pct(t.present,t.total)}%</strong><small>{t.present}/{t.total} episodios</small></div><div className="hero-metric danger"><span>Incidencias</span><strong>{quality.attention_count??(Number(t.missing)+summary.unresolvedExtras.length)}</strong><small>{t.missing||0} faltan · {summary.unresolvedExtras.length} anomalías</small></div><div className="hero-metric pending"><span>Pendientes</span><strong>{quality.pending_count??t.unknown??0}</strong><small>por confirmar</small></div><div className="hero-next"><span>Siguiente acción</span><strong>{nextAction}</strong><small>{summary.runs?.[0]?`Último cambio/proceso: ${dateTime(summary.runs[0].finished_at||summary.runs[0].started_at)}`:'Sin actividad registrada'}</small></div></section>

    <section className="maintenance-card"><div className="section-head"><div><h2>Actualizar datos</h2><p>Cada fuente tiene una responsabilidad distinta. Puedes forzar cualquiera cuando quieras.</p></div></div><div className="maintenance-grid">{maintenance.map(m=><div className={`maintenance-source ${m.recommended?'recommended':''}`} key={m.key}><div><span>{m.label}</span>{m.recommended&&<b>Recomendado</b>}</div><p>{m.description}</p><small>Última: {dateTime(m.last?.finished_at||m.last?.started_at)}{m.last?` · ${m.last.status}`:''}</small><ActionButton action={maintenanceAction(m.key)} fields={m.key==='tmdb'?{ratingKey,imdbId:summary.imdb_id}:{ratingKey}} label={`Actualizar ${m.label}`} pendingLabel={maintenancePending(m.key)}/></div>)}</div></section>

    {(summary.unresolvedExtras.length>0||summary.combined.length>0)&&<section className="anomaly-card"><div className="section-head"><div><h2>⚠ Anomalías Plex ↔ TMDb</h2><p>Problemas de correspondencia separados de la disponibilidad territorial.</p></div><strong>{summary.unresolvedExtras.length+summary.combined.length}</strong></div>{summary.combined.length>0&&<div className="anomaly-list">{summary.combined.map(d=><div className="anomaly-line" key={`combined-${d.season_number}-${d.episode_number}`}><div><b>T{d.season_number}E{d.episode_number}</b><span>Incluido en archivo combinado</span></div><p>{d.reason||`Archivo Plex ${d.covered_by_rating_key} cubre varios episodios oficiales.`}</p><small>Confianza {d.confidence||'—'} · {dateTime(d.diagnosed_at)}</small></div>)}</div>}{summary.unresolvedExtras.length>0&&<div className="anomaly-list">{summary.unresolvedExtras.map(e=><div className="anomaly-line action" key={e.rating_key}><div><b>S{String(e.season_number??0).padStart(2,'0')}E{String(e.episode_number??0).padStart(2,'0')}</b><span>{e.plex_title||'Sin título'} · Plex #{e.rating_key}</span></div><p>No existe con esta numeración en la referencia oficial. Requiere una decisión.</p><div className="availability-actions"><form action={reviewSeriesExtraAction}><input type="hidden" name="ratingKey" value={ratingKey}/><input type="hidden" name="season" value={e.season_number}/><input type="hidden" name="episode" value={e.episode_number}/><input type="hidden" name="decision" value="special"/><button>Es especial / extra válido</button></form><form action={reviewSeriesExtraAction}><input type="hidden" name="ratingKey" value={ratingKey}/><input type="hidden" name="season" value={e.season_number}/><input type="hidden" name="episode" value={e.episode_number}/><input type="hidden" name="decision" value="not_needed"/><button>Ignorar</button></form></div></div>)}</div>}</section>}

    <section className="season-review"><div className="section-head"><div><h2>Temporadas</h2><p>{seasons.length} temporadas · {t.total} episodios oficiales. Cobertura y España se muestran por separado.</p></div><Link className={selected==='all'?'active-link':''} href={qs(base,{season:'all'})}>Todas</Link></div><div className="season-priority">{seasons.filter(c=>Number(c.missing)>0||Number(c.unknown)>0).map(c=><Link key={`a-${c.season_number}`} href={qs(base,{season:c.season_number,status:'all',coverage:'all'})} className={`season-tile attention ${selected===c.season_number?'active':''}`}><div><b>T{c.season_number}</b><span>{c.missing?`${c.missing} faltan`:`${c.unknown} por confirmar`}</span></div><strong>{c.present}/{c.total}</strong><small>Plex · España: {availabilityLabel(c.availability_status)}</small></Link>)}</div><div className="season-compact">{seasons.filter(c=>!Number(c.missing)&&!Number(c.unknown)).map(c=><Link key={`c-${c.season_number}`} href={qs(base,{season:c.season_number,status:'all',coverage:'all'})} className={`season-chip ${selected===c.season_number?'active':''} ${Number(c.present)===Number(c.total)?'complete':''}`}>T{c.season_number}<small>{c.present}/{c.total}</small></Link>)}</div></section>

    <section className="episode-workbench"><div className="filter-bar"><div className="filter-pills"><Link className={status==='all'?'active':''} href={qs(base,{status:'all'})}>Todos <b>{scope.total??0}</b></Link><Link className={status==='missing_actionable'?'danger active':'danger'} href={qs(base,{status:'missing_actionable',coverage:'absent'})}>⚠ Faltan <b>{scope.missing??0}</b></Link><Link className={status==='availability_unknown'?'warn active':'warn'} href={qs(base,{status:'availability_unknown',coverage:'absent'})}>? Por confirmar <b>{scope.unknown??0}</b></Link><Link className={status==='not_available_es'?'muted active':'muted'} href={qs(base,{status:'not_available_es',coverage:'absent'})}>No disponibles <b>{scope.noes??0}</b></Link></div><div className="coverage-filter"><span>Cobertura:</span><Link className={coverage==='all'?'active':''} href={qs(base,{coverage:'all'})}>Todos</Link><Link className={coverage==='present'?'active':''} href={qs(base,{coverage:'present',status:'all'})}>En Plex</Link><Link className={coverage==='absent'?'active':''} href={qs(base,{coverage:'absent',status:'all'})}>Fuera de Plex</Link></div></div>
      <div className="episode-table-head"><div><h2>{selected==='all'?'Serie completa':`Temporada ${selected}`}</h2><p>{episodes.length} episodios mostrados · Serie: {t.missing} faltan / {t.unknown} pendientes</p></div><div className="scope-summary"><b>{scope.missing??0}</b><span>faltan en este ámbito</span></div></div>
      <div className="episode-table"><div className="episode-row header"><span>Episodio</span><span>Título / estreno</span><span>Cobertura Plex</span><span>España</span><span>Diagnóstico</span></div>{episodes.length?episodes.map(e=>{const key=`${e.season_number}:${e.episode_number}`,idx=actionIndex.get(key),prev=idx>0?actionRows[idx-1]:null,next=idx!=null&&idx<actionRows.length-1?actionRows[idx+1]:null;return <details id={`ep-${e.season_number}-${e.episode_number}`} className={`episode-detail ${e.effective_status}`} key={key}><summary className="episode-row"><div className="episode-code">S{String(e.season_number).padStart(2,'0')}E{String(e.episode_number).padStart(2,'0')}</div><div className="episode-name"><b>{e.expected_name||e.name||'Sin título'}</b><span>{dateOnly(e.air_date)} · {e.expected_runtime_minutes??e.runtime_minutes??'—'} min</span></div><div className="plex-state">{stateText(e.effective_status)}</div><div className="es-state">{availabilityText(e.effective_status)}</div><div className="diag-link">Ver diagnóstico ▾</div></summary><div className="episode-expanded"><Evidence e={e}/>{idx!=null&&actionRows.length>1&&<nav className="incident-nav">{prev?<a href={`#ep-${prev.season_number}-${prev.episode_number}`}>← Anterior incidencia</a>:<span/>}<b>{idx+1} de {actionRows.length}</b>{next?<a href={`#ep-${next.season_number}-${next.episode_number}`}>Siguiente incidencia →</a>:<span/>}</nav>}</div></details>}):<div className="empty-state"><b>Sin episodios en este ámbito</b><p>{status==='availability_unknown'?'No quedan episodios por confirmar con este filtro.':status==='missing_actionable'?'No hay faltantes confirmados con este filtro.':'No hay episodios que cumplan la combinación actual.'}</p></div>}</div>
    </section>

    <div className="review-bottom-grid"><section className="review-card"><h3>Resumen operacional</h3><div><span>Total oficiales</span><b>{t.total}</b></div><div><span>En Plex</span><b className="ok">{t.present}</b></div><div><span>Faltan</span><b className="bad">{t.missing}</b></div><div><span>Por confirmar</span><b className="warn">{t.unknown}</b></div><div><span>No exigibles ES</span><b>{t.noes}</b></div></section><section className="review-card"><h3>{selected==='all'?'Disponibilidad España':'Temporada '+selected}</h3>{selectedSeason?<><p><b>Cobertura Plex:</b> {selectedSeason.present}/{selectedSeason.total}{Number(selectedSeason.present)===Number(selectedSeason.total)?' · completa':' · incompleta'}</p><p><b>Disponibilidad España:</b> {availabilityLabel(selectedSeason.availability_status)}</p><p>Fuente: <b>{selectedSeason.manual_override?'Corrección manual':selectedSeason.availability_source||'automática'}</b>{selectedSeason.availability_checked_at?` · ${dateTime(selectedSeason.availability_checked_at)}`:''}</p>{selectedSeason.manual_override?<form action={resetSeasonAvailabilityAction}><input type="hidden" name="ratingKey" value={ratingKey}/><input type="hidden" name="season" value={selected}/><button>Volver al dato automático</button></form>:Number(selectedSeason.present)!==Number(selectedSeason.total)&&<details><summary><b>Corregir manualmente</b></summary><div className="availability-actions"><form action={seasonAvailabilityAction}><input type="hidden" name="showRatingKey" value={ratingKey}/><input type="hidden" name="season" value={selected}/><input type="hidden" name="available" value="true"/><button>Marcar disponible</button></form><form action={seasonAvailabilityAction}><input type="hidden" name="showRatingKey" value={ratingKey}/><input type="hidden" name="season" value={selected}/><input type="hidden" name="available" value="false"/><button>Marcar no disponible</button></form></div></details>}</>:<p>Selecciona una temporada para ver cobertura y disponibilidad como dimensiones independientes.</p>}</section><section className="review-card"><h3>Estado canónico</h3><strong className={quality.severity||'warn'}>{quality.label}</strong><p>{quality.reason}</p><p><b>{quality.attention_count||0}</b> incidencias · <b>{quality.pending_count||0}</b> pendientes · fiable: <b>{quality.is_reliable?'sí':'no'}</b></p></section></div>

    <details className="context-card"><summary><b>Información de la serie</b><span>Contexto editorial y IDs técnicos</span></summary><div className="context-ratings">{infoRatings.map(([k,v])=><div key={k}><span>{k}</span><b>{v}</b></div>)}</div>{summary.overview&&<p>{summary.overview}</p>}<div className="context-ids"><code>IMDb {summary.imdb_id||'—'}</code><code>TMDb {summary.tmdb_id||'—'}</code><code>Plex #{ratingKey}</code></div></details>

    <details className="activity-card"><summary><b>Actividad reciente</b><span>{summary.runs.length} eventos/procesos recientes</span></summary><div className="activity-list">{summary.runs.length?summary.runs.map(r=><div key={r.id}><span>{dateTime(r.finished_at||r.started_at)}</span><b>{runLabel(r.run_type)} · {r.status}</b><p>{r.summary?.error||r.summary?.message||`${r.processed_count||0} procesados · ${r.changed_count||0} cambios`}</p></div>):<p>Sin actividad registrada para esta serie.</p>}</div></details>
  </>;
}
