import Link from 'next/link';
import ActionButton from './ActionButton';
import BatchAutoRefresh from './BatchAutoRefresh';
import {startMov001BatchAction,pauseMov001BatchAction,resumeMov001BatchAction,cancelMov001BatchAction} from '@/app/calidad/peliculas/batch-actions';

const nf=n=>Number(n||0).toLocaleString('es-ES');
const pct=(done,total)=>total?Math.min(100,Math.round((Number(done||0)*1000)/Number(total))/10):0;

export default function Mov001BatchPanel({state}){
 const active=state?.active||null,latest=state?.latest||null,enginePaused=state?.engine?.desired_state==='paused',run=active||latest;
 const total=Number(run?.items_total||0),processed=Number(run?.items_processed||0),succeeded=Number(run?.items_succeeded||0),failed=Number(run?.items_failed||0),pending=Number(run?.items_pending||0),paused=active?.desired_state==='paused'||enginePaused,cancelling=active?.desired_state==='cancel_requested';
 return <section className="batch-panel" aria-label="Batch validación de películas"><BatchAutoRefresh active={Boolean(active)} paused={paused}/><div className="batch-panel-head"><div><span className="cap">Batch · MOV-001</span><h2>Validar archivos pendientes</h2><p>Ejecuta el mismo análisis individual para todas las películas cuyo archivo físico actual está pendiente de validar.</p></div><span className={`batch-pill ${active?paused?'paused':'running':'idle'}`}>{active?(cancelling?'Cancelando':paused?'Pausado':'En curso'):'Disponible'}</span></div>{!active&&<div className="batch-idle"><div><strong>{nf(state?.eligibleCount)} pendientes</strong><small>Selección canónica: películas en Plex con Lifecycle MOVIE_FILE_PENDING.</small></div><ActionButton action={startMov001BatchAction} label="Iniciar Batch" pendingLabel="Preparando Batch…" className="button"/></div>}{active&&<><div className="batch-progress-line"><div className="batch-progress"><span style={{width:`${pct(processed,total)}%`}}/></div><b>{nf(processed)} / {nf(total)} · {pct(processed,total)} %</b></div><div className="batch-kpis"><span>✓ Procesadas <b>{nf(succeeded)}</b></span><span>⚠ Errores <b>{nf(failed)}</b></span><span>Pendientes <b>{nf(pending)}</b></span><span>Concurrencia <b>{nf(active.requested_concurrency)}</b></span></div>{enginePaused&&<p className="batch-warning">Pausa global activa desde Centro de Operaciones. No se reclamarán nuevas películas.</p>}<div className="batch-actions">{!cancelling&&(paused?<ActionButton action={resumeMov001BatchAction} fields={{runId:active.run_id}} label="Continuar" pendingLabel="Reanudando…" className="button"/>:<ActionButton action={pauseMov001BatchAction} fields={{runId:active.run_id}} label="Pausar" pendingLabel="Pausando…" className="button ghost"/>)}<ActionButton action={cancelMov001BatchAction} fields={{runId:active.run_id}} label="Cancelar" pendingLabel="Cancelando…" className="button ghost"/><Link className="button ghost" href={`/admin/runs/${active.run_id}`}>Ver en Centro de Operaciones</Link></div></>}{!active&&latest&&<div className="batch-last"><span>Última ejecución: <b>{latest.technical_status}</b> · {nf(processed)}/{nf(total)}</span><Link href={`/admin/runs/${latest.run_id}`}>Ver detalle →</Link></div>}</section>
}
