'use server';
import {revalidatePath} from 'next/cache';
import {db} from '@/lib/db';
import {recomputeLifecycleForIds} from '@/lib/lifecycle';
import {refreshSeriesUnitary} from '@/lib/series-unitary';
import {syncPlexSeriesFast,syncPlexSeriesDetail} from '@/lib/series-plex-sync-safe';
import {rebuildSeriesQualityReadModel} from '@/lib/series-quality-query';
const revalidate=(ratingKey,imdbId)=>{revalidatePath('/calidad');revalidatePath('/calidad/series');if(ratingKey)revalidatePath(`/calidad/series/${ratingKey}`);if(imdbId)revalidatePath(`/catalogo/${imdbId}`)};
async function runTracked(type,scope,fn){const sql=db();const[r]=await sql`INSERT INTO series_quality_runs(run_type,scope_key,status) VALUES(${type},${scope||null},'running') RETURNING id`;try{const out=await fn();await rebuildSeriesQualityReadModel(sql);await sql`UPDATE series_quality_runs SET status='success',finished_at=now(),processed_count=${Number(out.examined??out.episodes??1)},changed_count=${Number(out.changed??out.added??0)},summary=${JSON.stringify(out)}::jsonb WHERE id=${r.id}`;return out}catch(e){await sql`UPDATE series_quality_runs SET status='error',finished_at=now(),error_count=1,summary=${JSON.stringify({error:e?.message||String(e)})}::jsonb WHERE id=${r.id}`;throw e}}
export async function syncPlexSeriesFastAction(){try{const r=await runTracked('plex_fast',null,()=>syncPlexSeriesFast());revalidate();return{ok:true,message:`Plex: ${r.examined} series · ${r.changed} cambios · ${r.created} nuevas${r.partial?' · revisión parcial':''}`}}catch(e){return{ok:false,message:e?.message||'No se pudo sincronizar Plex'}}}
export async function syncPlexSeriesDetailAction(_previousState,formData){try{const ratingKey=String(formData.get('ratingKey')||'').trim();const r=await runTracked('plex_detail',ratingKey,()=>syncPlexSeriesDetail(ratingKey));revalidate(ratingKey);return{ok:true,message:`Plex actualizado: ${r.seasons} temporadas · ${r.episodes} episodios`}}catch(e){return{ok:false,message:e?.message||'No se pudo actualizar el detalle Plex'}}}
export async function refreshOneSeriesAction(_previousState,formData){try{const imdbId=String(formData.get('imdbId')||'').trim()||null,ratingKey=String(formData.get('ratingKey')||'').trim()||null;const r=await runTracked('tmdb_refresh',ratingKey||imdbId,()=>refreshSeriesUnitary({imdbId,ratingKey}));revalidate(r.ratingKey,r.imdbId);return{ok:true,message:`TMDb actualizado: ${r.seasons} temporadas · ${r.episodes} episodios`}}catch(e){return{ok:false,message:e?.message||'No se pudo actualizar TMDb'}}}
export async function resetSeasonAvailabilityAction(formData){const ratingKey=String(formData.get('ratingKey')||'').trim(),season=Number(formData.get('season'));if(!ratingKey||!Number.isInteger(season)||season<1)throw new Error('Temporada inválida');const sql=db();const[s]=await sql`SELECT imdb_id FROM series_reference WHERE show_rating_key=${ratingKey} LIMIT 1`;if(!s?.imdb_id)throw new Error('Serie no encontrada');await sql`UPDATE series_season_availability SET manual_override=false,status='UNKNOWN',source='manual_reset',confidence='unknown',checked_at=now(),note='Override manual retirado; pendiente de refresco automático' WHERE show_rating_key=${ratingKey} AND season_number=${season} AND country_code='ES'`;await refreshSeriesUnitary({ratingKey});await recomputeLifecycleForIds([s.imdb_id]);await rebuildSeriesQualityReadModel(sql);revalidate(ratingKey,s.imdb_id)}
export async function reviewSeriesExtraAction(formData){const ratingKey=String(formData.get('ratingKey')||'').trim(),season=Number(formData.get('season')),episode=Number(formData.get('episode')),decision=String(formData.get('decision')||'').trim(),note=String(formData.get('note')||'').trim().slice(0,300);if(!ratingKey||!Number.isInteger(season)||!Number.isInteger(episode)||season<0||episode<0)throw new Error('Episodio inválido');if(!['special','not_needed','reopen'].includes(decision))throw new Error('Decisión inválida');const sql=db();const[s]=await sql`SELECT imdb_id FROM series_reference WHERE show_rating_key=${ratingKey} LIMIT 1`;if(!s?.imdb_id)throw new Error('Serie no encontrada');if(decision==='reopen')await sql`DELETE FROM series_episode_overrides WHERE show_rating_key=${ratingKey} AND season_number=${season} AND episode_number=${episode}`;else await sql`INSERT INTO series_episode_overrides(show_rating_key,season_number,episode_number,decision,note,created_at,updated_at) VALUES(${ratingKey},${season},${episode},${decision},${note||null},now(),now()) ON CONFLICT(show_rating_key,season_number,episode_number) DO UPDATE SET decision=EXCLUDED.decision,note=EXCLUDED.note,updated_at=now()`;await recomputeLifecycleForIds([s.imdb_id]);await rebuildSeriesQualityReadModel(sql);revalidate(ratingKey,s.imdb_id)}
