import 'server-only';
import {db} from './db';

export const BATCH_STAGES=[
  'IDENTITY_PENDING','IDENTITY_VALIDATION','DATA_INCOMPLETE','PIKOSCORE_PENDING',
  'MOVIE_FILE_PENDING','SERIES_SYNC_PENDING','TECH_PENDING','PEOPLE_REFRESH'
];
export const RETRY_MODES=['new_only','new_and_technical','include_unresolved','all'];
const RUN_STATUSES=new Set(['queued','running','paused','completed','cancelled','failed']);
const SOURCES=new Set(['fast','tmdb','wikidata','omdb','plex','filmaffinity','mdblist']);

function clampInt(v,min,max,fallback){const n=Number.parseInt(v,10);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback}
function stageOf(v){const s=String(v||'').trim();if(!BATCH_STAGES.includes(s))throw new Error('Etapa batch no permitida');return s}
function retryModeOf(v){const s=String(v||'new_only');return RETRY_MODES.includes(s)?s:'new_only'}

export async function getBatchControlOverview(){
  const sql=db();
  const [control,limits,runs,jobs,outcomes,manual,sourceUsage]=await Promise.all([
    sql`SELECT paused,pause_reason,updated_at,updated_by FROM batch_runtime_control WHERE singleton=true LIMIT 1`,
    sql`SELECT source,enabled,max_concurrency,min_interval_ms,daily_budget,breaker_state,blocked_until,consecutive_errors,updated_at FROM batch_source_limits ORDER BY CASE source WHEN 'fast' THEN 0 WHEN 'tmdb' THEN 1 WHEN 'wikidata' THEN 2 WHEN 'omdb' THEN 3 WHEN 'plex' THEN 4 WHEN 'filmaffinity' THEN 5 WHEN 'mdblist' THEN 6 ELSE 99 END,source`,
    sql`SELECT r.id,r.mode,r.target_stage,r.status,r.requested_by,r.limits,r.stop_reason,r.created_at,r.started_at,r.finished_at,r.updated_at,count(j.*)::int jobs,count(j.*) FILTER(WHERE j.status='queued')::int queued,count(j.*) FILTER(WHERE j.status IN('leased','running'))::int active,count(j.*) FILTER(WHERE j.status='retry_wait')::int retry_wait,count(j.*) FILTER(WHERE j.status='review')::int review,count(j.*) FILTER(WHERE j.status='done')::int done,count(j.*) FILTER(WHERE j.status='failed')::int failed,count(j.*) FILTER(WHERE j.status='cancelled')::int cancelled,count(j.*) FILTER(WHERE j.status='skipped')::int skipped,count(j.*) FILTER(WHERE j.functional_outcome='CORREGIDO')::int corrected,count(j.*) FILTER(WHERE j.functional_outcome='ACTUALIZADO_SIN_AVANCE')::int updated_no_advance,count(j.*) FILTER(WHERE j.functional_outcome='SIN_CAMBIOS')::int no_change,count(j.*) FILTER(WHERE j.functional_outcome='NO_ENCONTRADO')::int not_found,count(j.*) FILTER(WHERE j.functional_outcome='INCOMPLETO')::int incomplete,count(j.*) FILTER(WHERE j.functional_outcome='REVISION_MANUAL')::int manual_review,count(j.*) FILTER(WHERE j.functional_outcome='ERROR')::int functional_error FROM batch_runs r LEFT JOIN batch_jobs j ON j.run_id=r.id GROUP BY r.id ORDER BY r.created_at DESC LIMIT 40`,
    sql`SELECT j.id,j.run_id,j.entity_type,j.entity_id,j.stage,j.status,j.attempt,j.priority,j.available_at,j.leased_until,j.worker_id,j.error_class,j.error_message,j.functional_outcome,j.lifecycle_before,j.lifecycle_after,j.manual_review_reason,j.result_summary,j.created_at,j.started_at,j.finished_at,j.updated_at,m.title_es,m.title,m.original_title,m.type,m.year,p.name AS person_name,ps.attempt_count,ps.no_progress_count,ps.last_outcome,ps.next_retry_at,ps.manual_review,ps.manual_review_reason AS process_review_reason FROM batch_jobs j LEFT JOIN movies m ON m.imdb_id=j.entity_id LEFT JOIN people p ON j.entity_type='person' AND p.tmdb_person_id::text=j.entity_id LEFT JOIN batch_process_state ps ON ps.entity_type=j.entity_type AND ps.entity_id=j.entity_id AND ps.stage=j.stage ORDER BY j.created_at DESC LIMIT 150`,
    sql`SELECT functional_outcome,count(*)::int total FROM batch_jobs WHERE functional_outcome IS NOT NULL GROUP BY functional_outcome ORDER BY total DESC`,
    sql`SELECT ps.entity_type,ps.entity_id,ps.stage,ps.attempt_count,ps.no_progress_count,ps.last_attempt_at,ps.last_outcome,ps.next_retry_at,ps.manual_review_reason,ps.last_job_id,ps.updated_at,m.title_es,m.title,m.type,m.year FROM batch_process_state ps LEFT JOIN movies m ON m.imdb_id=ps.entity_id WHERE ps.manual_review=true ORDER BY ps.updated_at DESC LIMIT 100`,
    sql`SELECT source,count(*) FILTER(WHERE attempted=true)::int attempts,count(*) FILTER(WHERE status='failed')::int failures,round(avg(duration_ms) FILTER(WHERE attempted=true))::int avg_ms,max(updated_at) last_at FROM batch_job_steps WHERE created_at>=date_trunc('day',now()) GROUP BY source ORDER BY source`
  ]);
  const summary=(runs||[]).reduce((a,r)=>{a.runs++;a.jobs+=r.jobs||0;a.queued+=r.queued||0;a.active+=r.active||0;a.retry+=r.retry_wait||0;a.review+=r.review||0;a.failed+=r.failed||0;return a},{runs:0,jobs:0,queued:0,active:0,retry:0,review:0,failed:0});const usageMap=new Map((sourceUsage||[]).map(x=>[x.source,x]));const enrichedLimits=(limits||[]).map(x=>({...x,usage:usageMap.get(x.source)||{attempts:0,failures:0,avg_ms:null,last_at:null}}));const activeRun=(runs||[]).find(r=>['running','queued','paused'].includes(r.status))||null;return{control:control[0]||{paused:true,pause_reason:'Sin configuración'},limits:enrichedLimits,runs,jobs,summary,outcomes,manualReview:manual,activeRun};
}
export async function getJobDetail(jobId){const id=Number(jobId);if(!Number.isFinite(id))return null;const sql=db();const[jobs,steps,history]=await Promise.all([sql`SELECT j.*,m.title_es,m.title,m.original_title,m.type,m.year,cl.blocking_reason,ps.attempt_count,ps.no_progress_count,ps.last_attempt_at,ps.last_outcome,ps.next_retry_at,ps.context_signature,ps.manual_review,ps.manual_review_reason AS process_review_reason,ps.last_result FROM batch_jobs j LEFT JOIN movies m ON m.imdb_id=j.entity_id LEFT JOIN catalog_lifecycle cl ON cl.imdb_id=j.entity_id LEFT JOIN batch_process_state ps ON ps.entity_type=j.entity_type AND ps.entity_id=j.entity_id AND ps.stage=j.stage WHERE j.id=${id} LIMIT 1`,sql`SELECT id,step_key,step_order,source,status,attempted,found,changed,before_value,after_value,result,reason,error_class,error_message,started_at,finished_at,duration_ms,created_at,updated_at FROM batch_job_steps WHERE job_id=${id} ORDER BY step_order,id`,sql`SELECT h.id,h.run_id,h.status,h.attempt,h.functional_outcome,h.lifecycle_before,h.lifecycle_after,h.error_class,h.error_message,h.created_at,h.started_at,h.finished_at FROM batch_jobs h WHERE h.entity_type=(SELECT entity_type FROM batch_jobs WHERE id=${id}) AND h.entity_id=(SELECT entity_id FROM batch_jobs WHERE id=${id}) AND h.stage=(SELECT stage FROM batch_jobs WHERE id=${id}) ORDER BY h.created_at DESC LIMIT 30`]);if(!jobs[0])return null;return{job:jobs[0],steps,history};}
export async function createEntityRun({stage,entityId,requestedBy='pikofilm-ui'}={}){const target=stageOf(stage),id=String(entityId||'').trim();if(!/^tt\d+$/.test(id))throw new Error('IMDb inválido');const sql=db();const[cl]=await sql`SELECT lifecycle_state FROM catalog_lifecycle WHERE imdb_id=${id}`;if(!cl)throw new Error('Título no encontrado');if(cl.lifecycle_state!==target)throw new Error(`El título ya está en ${cl.lifecycle_state}`);const limits={max_jobs:1,retry_mode:'all',orchestration:'lifecycle',forced_entity:id};const[run]=await sql`INSERT INTO batch_runs(mode,target_stage,status,requested_by,limits) VALUES('manual',${target},'queued',${String(requestedBy).slice(0,80)},${JSON.stringify(limits)}::jsonb) RETURNING id`;await sql`INSERT INTO batch_jobs(run_id,entity_type,entity_id,stage,status,priority,available_at,idempotency_key) VALUES(${run.id},'title',${id},${target},'queued',200,now(),${target}||':'||${id}||':'||${String(Date.now())})`;return{id:run.id,entityId:id,stage:target};}
export async function setManualReview({stage,entityId,enabled,reason=''}){const target=stageOf(stage),id=String(entityId||'').trim(),sql=db();await sql`INSERT INTO batch_process_state(entity_type,entity_id,stage,attempt_count,no_progress_count,manual_review,manual_review_reason,updated_at) VALUES('title',${id},${target},0,0,${Boolean(enabled)},${String(reason||'').slice(0,500)||null},now()) ON CONFLICT(entity_type,entity_id,stage) DO UPDATE SET manual_review=EXCLUDED.manual_review,manual_review_reason=EXCLUDED.manual_review_reason,updated_at=now()`;}
export async function setGlobalPause(paused,reason=''){const sql=db();await sql`UPDATE batch_runtime_control SET paused=${Boolean(paused)},pause_reason=${String(reason||'').slice(0,300)||null},updated_at=now(),updated_by='pikofilm-ui' WHERE singleton=true`}
export async function setRunStatus(id,status){const runId=Number(id),next=String(status||'');if(!Number.isFinite(runId)||!RUN_STATUSES.has(next))throw new Error('Estado de run inválido');const sql=db();if(next==='cancelled'){await sql`UPDATE batch_jobs SET status='cancelled',finished_at=COALESCE(finished_at,now()),updated_at=now() WHERE run_id=${runId} AND status IN('queued','retry_wait','leased')`;await sql`UPDATE batch_runs SET status='cancelled',finished_at=COALESCE(finished_at,now()),updated_at=now() WHERE id=${runId}`}else if(next==='paused')await sql`UPDATE batch_runs SET status='paused',updated_at=now() WHERE id=${runId} AND status IN('queued','running')`;else if(next==='queued')await sql`UPDATE batch_runs SET status='queued',finished_at=NULL,updated_at=now() WHERE id=${runId} AND status='paused'`;else await sql`UPDATE batch_runs SET status=${next},updated_at=now() WHERE id=${runId}`;}
export async function updateSourceLimit({source,enabled,maxConcurrency,minIntervalMs,dailyBudget}){const s=String(source||'').toLowerCase();if(!SOURCES.has(s))throw new Error('Fuente no permitida');const sql=db();await sql`UPDATE batch_source_limits SET enabled=${Boolean(enabled)},max_concurrency=${clampInt(maxConcurrency,1,50,1)},min_interval_ms=${clampInt(minIntervalMs,0,60000,0)},daily_budget=${dailyBudget===''||dailyBudget==null?null:clampInt(dailyBudget,0,1000000,0)},updated_at=now() WHERE source=${s}`;}
