import 'server-only';
import {db} from './db';

export async function getDashboardV2(period='30'){const sql=db(),days=Math.max(7,Math.min(3650,Number(period)||30));const [kpi,decades,resolutions,codecs,genres,countries,history,processes]=await Promise.all([
  sql`SELECT (SELECT count(*)::int FROM movies m LEFT JOIN catalog_exclusions e USING(imdb_id) WHERE e.imdb_id IS NULL) catalog_total,(SELECT count(*)::int FROM movies m LEFT JOIN catalog_exclusions e USING(imdb_id) WHERE e.imdb_id IS NULL AND m.type='Película') movies,(SELECT count(*)::int FROM movies m LEFT JOIN catalog_exclusions e USING(imdb_id) WHERE e.imdb_id IS NULL AND m.type IN('Serie','Miniserie')) series,(SELECT count(*)::int FROM catalog_read_model WHERE effective_status='in_plex') in_plex,(SELECT count(*)::int FROM catalog_read_model WHERE effective_status='acquiring') acquiring,(SELECT count(*)::int FROM catalog_read_model WHERE effective_status IS NULL OR effective_status NOT IN('in_plex','acquiring')) missing,(SELECT count(*)::int FROM catalog_exclusions) excluded,(SELECT count(*)::int FROM plex_not_in_catalog) plex_outside,(SELECT count(*)::int FROM movie_quality_findings WHERE status='pending') quality_open,(SELECT count(*)::int FROM movies WHERE tmdb_id IS NULL OR fa_id IS NULL OR imdb_id!~'^tt[0-9]+$') identity_issues,(SELECT count(*)::int FROM series_episode_effective_status WHERE effective_status='missing_actionable') missing_eps,(SELECT count(*)::int FROM series_episode_effective_status WHERE effective_status='availability_unknown') unknown_eps,(SELECT count(*)::int FROM pipeline_runs WHERE status='failed' AND started_at>now()-interval '7 days') failed_runs,(SELECT max(finished_at) FROM plex_sync_runs WHERE status='success') last_plex_sync`,
  sql`SELECT (floor(year/10)*10)::int bucket,count(*)::int total,count(*) FILTER(WHERE effective_status='in_plex')::int owned FROM catalog_read_model WHERE year IS NOT NULL GROUP BY 1 ORDER BY 1`,
  sql`SELECT COALESCE(NULLIF(pm.resolution,''),CASE WHEN pm.height>=1000 THEN '1080p' WHEN pm.height>=700 THEN '720p' ELSE 'SD' END,'Desconocida') label,count(*)::int total FROM plex_items p JOIN plex_media pm ON pm.rating_key=p.rating_key WHERE p.active AND p.item_type='movie' GROUP BY 1 ORDER BY total DESC`,
  sql`SELECT COALESCE(pm.video_codec,'Desconocido') label,count(*)::int total FROM plex_items p JOIN plex_media pm ON pm.rating_key=p.rating_key WHERE p.active AND p.item_type='movie' GROUP BY 1 ORDER BY total DESC LIMIT 8`,
  sql`SELECT mg.genre label,count(*)::int total FROM movie_genres mg JOIN movies m USING(imdb_id) LEFT JOIN catalog_exclusions e USING(imdb_id) WHERE e.imdb_id IS NULL GROUP BY mg.genre ORDER BY total DESC LIMIT 10`,
  sql`SELECT COALESCE(NULLIF(split_part(country,',',1),''),'Desconocido') label,count(*)::int total FROM movies m LEFT JOIN catalog_exclusions e USING(imdb_id) WHERE e.imdb_id IS NULL GROUP BY 1 ORDER BY total DESC LIMIT 10`,
  sql`SELECT snapshot_date,metrics FROM dashboard_snapshots WHERE snapshot_date>=current_date-${days}::int ORDER BY snapshot_date`,
  sql`SELECT job_type,status,count(*)::int total,round(avg(extract(epoch from(COALESCE(finished_at,now())-started_at))::numeric),1) avg_seconds FROM pipeline_runs WHERE started_at>=now()-(${days}::text||' days')::interval GROUP BY job_type,status ORDER BY total DESC LIMIT 20`
]);
  const [saga]=await sql`SELECT count(*) FILTER(WHERE owned>0 AND missing>0)::int incomplete,count(*) FILTER(WHERE owned>0 AND missing=1)::int one_missing,count(*) FILTER(WHERE total>0 AND missing=0)::int complete FROM (SELECT sc.tmdb_collection_id,count(sm.*)::int total,count(sm.*) FILTER(WHERE c.effective_status='in_plex')::int owned,count(sm.*) FILTER(WHERE c.effective_status IS DISTINCT FROM 'in_plex')::int missing FROM saga_collections sc LEFT JOIN saga_collection_members sm USING(tmdb_collection_id) LEFT JOIN catalog_read_model c ON c.imdb_id=sm.imdb_id GROUP BY sc.tmdb_collection_id)x`;
  return{kpi:{...kpi[0],...saga},decades,resolutions,codecs,genres,countries,history,processes,days};}

export async function captureDashboardSnapshot(){const sql=db();const [m]=await sql`SELECT (SELECT count(*)::int FROM movies x LEFT JOIN catalog_exclusions e USING(imdb_id) WHERE e.imdb_id IS NULL) catalog_total,(SELECT count(*)::int FROM catalog_read_model WHERE effective_status='in_plex') in_plex,(SELECT count(*)::int FROM catalog_read_model WHERE effective_status='acquiring') acquiring,(SELECT count(*)::int FROM catalog_read_model WHERE effective_status IS NULL OR effective_status NOT IN('in_plex','acquiring')) missing,(SELECT count(*)::int FROM catalog_exclusions) excluded,(SELECT count(*)::int FROM movie_quality_findings WHERE status='pending') quality_open,(SELECT count(*)::int FROM series_episode_effective_status WHERE effective_status='missing_actionable') missing_eps`;
  const coverage=m.catalog_total?Number((m.in_plex/m.catalog_total*100).toFixed(2)):0;await sql`INSERT INTO dashboard_snapshots(snapshot_date,metrics,created_at) VALUES(current_date,${JSON.stringify({...m,coverage})}::jsonb,now()) ON CONFLICT(snapshot_date) DO UPDATE SET metrics=EXCLUDED.metrics,created_at=now()`;return{...m,coverage}}
