import 'server-only';
import {db} from './db';

export async function getDashboardV2(period='30'){
  const sql=db(),days=Math.max(7,Math.min(3650,Number(period)||30));
  const kpi=await sql`SELECT (SELECT count(*)::int FROM movies m LEFT JOIN catalog_exclusions e USING(imdb_id) WHERE e.imdb_id IS NULL) catalog_total,(SELECT count(*)::int FROM movies m LEFT JOIN catalog_exclusions e USING(imdb_id) WHERE e.imdb_id IS NULL AND m.type='Película') movies,(SELECT count(*)::int FROM movies m LEFT JOIN catalog_exclusions e USING(imdb_id) WHERE e.imdb_id IS NULL AND m.type IN('Serie','Miniserie')) series,(SELECT count(*)::int FROM catalog_read_model WHERE effective_status='in_plex') in_plex,(SELECT count(*)::int FROM catalog_read_model WHERE effective_status='acquiring') acquiring,(SELECT count(*)::int FROM catalog_read_model WHERE effective_status IS NULL OR effective_status NOT IN('in_plex','acquiring')) missing,(SELECT count(*)::int FROM catalog_exclusions) excluded,(SELECT count(*)::int FROM plex_not_in_catalog) plex_outside,(SELECT count(*)::int FROM movie_quality_findings f LEFT JOIN catalog_exclusions e ON e.imdb_id=f.imdb_id WHERE f.status='pending' AND e.imdb_id IS NULL) quality_open,(SELECT count(*)::int FROM catalog_lifecycle cl JOIN movies m USING(imdb_id) LEFT JOIN catalog_exclusions e USING(imdb_id) WHERE e.imdb_id IS NULL AND cl.lifecycle_state IN('IDENTITY_PENDING','IDENTITY_VALIDATION','IDENTITY_REVIEW_REQUIRED')) identity_issues,(SELECT count(*)::int FROM series_episode_effective_status s JOIN series_reference r USING(show_rating_key) JOIN plex_items show ON show.rating_key=r.show_rating_key AND show.active AND show.item_type='show' LEFT JOIN catalog_exclusions e ON e.imdb_id=r.imdb_id WHERE s.effective_status='missing_actionable' AND e.imdb_id IS NULL) missing_eps,(SELECT count(*)::int FROM series_episode_effective_status s JOIN series_reference r USING(show_rating_key) JOIN plex_items show ON show.rating_key=r.show_rating_key AND show.active AND show.item_type='show' LEFT JOIN catalog_exclusions e ON e.imdb_id=r.imdb_id WHERE s.effective_status='availability_unknown' AND e.imdb_id IS NULL) unknown_eps,(SELECT count(*)::int FROM pipeline_runs WHERE status='failed' AND started_at>now()-interval '7 days') failed_runs,(SELECT max(finished_at) FROM plex_sync_runs WHERE status='success') last_plex_sync`;
  const decades=await sql`SELECT (floor(year/10)*10)::int bucket,count(*)::int total,count(*) FILTER(WHERE effective_status='in_plex')::int owned FROM catalog_read_model WHERE year IS NOT NULL GROUP BY 1 ORDER BY 1`;
  const resolutions=await sql`SELECT COALESCE(NULLIF(pm.resolution,''),CASE WHEN pm.height>=1000 THEN '1080p' WHEN pm.height>=700 THEN '720p' ELSE 'SD' END,'Desconocida') label,count(*)::int total FROM plex_items p JOIN plex_media pm ON pm.rating_key=p.rating_key LEFT JOIN LATERAL(SELECT external_id imdb_id FROM plex_external_ids x WHERE x.rating_key=p.rating_key AND x.provider='imdb' LIMIT 1)x ON true LEFT JOIN catalog_exclusions ex ON ex.imdb_id=x.imdb_id WHERE p.active AND p.item_type='movie' AND ex.imdb_id IS NULL GROUP BY 1 ORDER BY total DESC`;
  const codecs=await sql`SELECT COALESCE(pm.video_codec,'Desconocido') label,count(*)::int total FROM plex_items p JOIN plex_media pm ON pm.rating_key=p.rating_key LEFT JOIN LATERAL(SELECT external_id imdb_id FROM plex_external_ids x WHERE x.rating_key=p.rating_key AND x.provider='imdb' LIMIT 1)x ON true LEFT JOIN catalog_exclusions ex ON ex.imdb_id=x.imdb_id WHERE p.active AND p.item_type='movie' AND ex.imdb_id IS NULL GROUP BY 1 ORDER BY total DESC LIMIT 8`;
  const genres=await sql`SELECT g.name_es label,count(*)::int total FROM movie_genres_canonical mg JOIN genres g ON g.id=mg.genre_id JOIN movies m ON m.imdb_id=mg.imdb_id LEFT JOIN catalog_exclusions e ON e.imdb_id=mg.imdb_id WHERE e.imdb_id IS NULL GROUP BY g.name_es ORDER BY total DESC LIMIT 10`;
  const countries=await sql`SELECT c.name_es label,count(*)::int total FROM movie_countries mc JOIN countries c ON c.code=mc.country_code JOIN movies m ON m.imdb_id=mc.imdb_id LEFT JOIN catalog_exclusions e ON e.imdb_id=mc.imdb_id WHERE e.imdb_id IS NULL GROUP BY c.name_es ORDER BY total DESC LIMIT 10`;
  const history=await sql`SELECT snapshot_date,metrics FROM dashboard_snapshots WHERE snapshot_date>=current_date-${days}::int ORDER BY snapshot_date`;
  const processes=await sql`SELECT job_type,status,count(*)::int total,round(avg(extract(epoch from(COALESCE(finished_at,now())-started_at))::numeric),1) avg_seconds FROM pipeline_runs WHERE started_at>=now()-(${days}::text||' days')::interval GROUP BY job_type,status ORDER BY total DESC LIMIT 20`;
  const [saga]=await sql`SELECT count(*) FILTER(WHERE owned>0 AND missing>0)::int incomplete,count(*) FILTER(WHERE owned>0 AND missing=1)::int one_missing,count(*) FILTER(WHERE total>0 AND missing=0)::int complete FROM (SELECT sc.tmdb_collection_id,count(sm.*)::int total,count(sm.*) FILTER(WHERE c.effective_status='in_plex')::int owned,count(sm.*) FILTER(WHERE c.effective_status IS DISTINCT FROM 'in_plex')::int missing FROM saga_collections sc LEFT JOIN saga_collection_members sm USING(tmdb_collection_id) LEFT JOIN catalog_exclusions ex ON ex.imdb_id=sm.imdb_id LEFT JOIN catalog_read_model c ON c.imdb_id=sm.imdb_id WHERE ex.imdb_id IS NULL GROUP BY sc.tmdb_collection_id)x`;
  return{kpi:{...kpi[0],...saga},decades,resolutions,codecs,genres,countries,history,processes,days};
}

export async function captureDashboardSnapshot(){const sql=db();const [m]=await sql`SELECT (SELECT count(*)::int FROM movies x LEFT JOIN catalog_exclusions e USING(imdb_id) WHERE e.imdb_id IS NULL) catalog_total,(SELECT count(*)::int FROM catalog_read_model WHERE effective_status='in_plex') in_plex,(SELECT count(*)::int FROM catalog_read_model WHERE effective_status='acquiring') acquiring,(SELECT count(*)::int FROM catalog_read_model WHERE effective_status IS NULL OR effective_status NOT IN('in_plex','acquiring')) missing,(SELECT count(*)::int FROM catalog_exclusions) excluded,(SELECT count(*)::int FROM movie_quality_findings f LEFT JOIN catalog_exclusions e ON e.imdb_id=f.imdb_id WHERE f.status='pending' AND e.imdb_id IS NULL) quality_open,(SELECT count(*)::int FROM series_episode_effective_status s JOIN series_reference r USING(show_rating_key) JOIN plex_items show ON show.rating_key=r.show_rating_key AND show.active AND show.item_type='show' LEFT JOIN catalog_exclusions e ON e.imdb_id=r.imdb_id WHERE s.effective_status='missing_actionable' AND e.imdb_id IS NULL) missing_eps`;
  const coverage=m.catalog_total?Number((m.in_plex/m.catalog_total*100).toFixed(2)):0;await sql`INSERT INTO dashboard_snapshots(snapshot_date,metrics,created_at) VALUES(current_date,${JSON.stringify({...m,coverage})}::jsonb,now()) ON CONFLICT(snapshot_date) DO UPDATE SET metrics=EXCLUDED.metrics,created_at=now()`;return{...m,coverage}}
