import 'server-only';
import {db} from './db';

export const DATA_FIELDS={
  imdb_id:{label:'IMDb ID',source:'IMDb',level:'critical'},tmdb_id:{label:'TMDb ID',source:'TMDb',level:'critical'},fa_id:{label:'FilmAffinity ID',source:'FilmAffinity',level:'critical'},type:{label:'Tipo',source:'PikoFilm',level:'critical'},title_es:{label:'Título español',source:'FilmAffinity/TMDb',level:'critical'},original_title:{label:'Título original',source:'TMDb/OMDb',level:'critical'},year:{label:'Año',source:'IMDb/TMDb',level:'critical'},imdb_rating:{label:'IMDb rating',source:'IMDb',level:'critical'},imdb_votes:{label:'IMDb votos',source:'IMDb',level:'critical'},fa_rating:{label:'FA rating',source:'FilmAffinity',level:'critical'},fa_votes:{label:'FA votos',source:'FilmAffinity',level:'critical'},tmdb_rating:{label:'TMDb rating',source:'TMDb',level:'critical'},tmdb_votes:{label:'TMDb votos',source:'TMDb',level:'critical'},final_rating:{label:'PikoScore',source:'PikoFilm',level:'critical'},runtime:{label:'Duración',source:'TMDb/OMDb',level:'important'},country:{label:'País',source:'TMDb/OMDb',level:'important'},genres:{label:'Géneros',source:'TMDb/OMDb',level:'important'},overview:{label:'Sinopsis',source:'TMDb/OMDb',level:'important'},poster_path:{label:'Póster',source:'TMDb',level:'important'},release_date:{label:'Fecha de estreno',source:'TMDb',level:'important'},director:{label:'Director',source:'TMDb',level:'important'},cast:{label:'Reparto',source:'TMDb',level:'important'},backdrop_path:{label:'Backdrop',source:'TMDb',level:'optional'},original_language:{label:'Idioma original',source:'TMDb',level:'optional'}
};
const keys=Object.keys(DATA_FIELDS),critical=keys.filter(k=>DATA_FIELDS[k].level==='critical'),important=keys.filter(k=>DATA_FIELDS[k].level==='important'),optional=keys.filter(k=>DATA_FIELDS[k].level==='optional'),rank={critical:0,incomplete:1,partial:2,complete:3};
const truthy=(k,v)=>{if(k.endsWith('_rating'))return v!=null&&Number(v)>0;if(k.endsWith('_votes'))return v!=null&&Number(v)>0;if(k==='year')return Number(v)>1800;if(k==='runtime')return Number(v)>0;return v!==null&&v!==undefined&&v!==''&&v!==false&&(!(Array.isArray(v))||v.length>0)};
export function assessDataQuality(row){const missing=keys.filter(k=>!truthy(k,row[k]));const mc=missing.filter(k=>critical.includes(k)),mi=missing.filter(k=>important.includes(k)),mo=missing.filter(k=>optional.includes(k));const status=mc.length?'critical':mi.length?'incomplete':mo.length?'partial':'complete';const required=critical.length+important.length,covered=required-mc.length-mi.length,coverage=Math.round(covered*1000/required)/10;return{...row,status,coverage,missing,missingCritical:mc,missingImportant:mi,missingOptional:mo};}
function baseSql(sql){return sql`SELECT m.imdb_id,m.tmdb_id,m.fa_id,m.type,m.title_es,m.original_title,m.year,m.imdb_rating,m.imdb_votes,m.fa_rating,m.fa_votes,m.tmdb_rating,m.tmdb_votes,m.final_rating,m.runtime,m.country,m.poster_path,m.backdrop_path,m.source_status,mm.overview,mm.original_language,mm.release_date,
  EXISTS(SELECT 1 FROM movie_genres g WHERE g.imdb_id=m.imdb_id) genres,
  EXISTS(SELECT 1 FROM movie_credits c WHERE c.imdb_id=m.imdb_id AND c.credit_type='crew' AND c.job='Director') director,
  EXISTS(SELECT 1 FROM movie_credits c WHERE c.imdb_id=m.imdb_id AND c.credit_type='cast') cast
  FROM movies m LEFT JOIN movie_metadata mm USING(imdb_id) LEFT JOIN catalog_exclusions ex USING(imdb_id) WHERE ex.imdb_id IS NULL`}
export async function getDataQualityOverview(){const sql=db(),rows=await baseSql(sql);const assessed=rows.map(assessDataQuality),counts={complete:0,partial:0,incomplete:0,critical:0};for(const r of assessed)counts[r.status]++;const byField={};for(const k of keys)byField[k]=assessed.filter(r=>r.missing.includes(k)).length;const total=assessed.length,requiredTotal=total*(critical.length+important.length),requiredPresent=assessed.reduce((n,r)=>n+(critical.length+important.length-r.missingCritical.length-r.missingImportant.length),0);return{total,counts,coverage:requiredTotal?Math.round(requiredPresent*1000/requiredTotal)/10:100,byField,fields:DATA_FIELDS};}
export async function getDataQualityPage(filters={}){const sql=db(),rows=await baseSql(sql),q=String(filters.q||'').trim().toLowerCase(),status=String(filters.status||''),field=String(filters.field||''),source=String(filters.source||''),type=String(filters.type||''),page=Math.max(1,Number(filters.page)||1),pageSize=50;let assessed=rows.map(assessDataQuality).filter(r=>(!q||String(r.title_es||r.original_title||'').toLowerCase().includes(q)||String(r.imdb_id).includes(q))&&(!status||r.status===status)&&(!field||r.missing.includes(field))&&(!source||r.missing.some(k=>DATA_FIELDS[k].source.toLowerCase().includes(source.toLowerCase())))&&(!type||(type==='movie'?r.type==='Película':r.type!=='Película')));assessed.sort((a,b)=>(rank[a.status]-rank[b.status])||a.coverage-b.coverage||Number(b.year||0)-Number(a.year||0));const total=assessed.length,start=(page-1)*pageSize;return{rows:assessed.slice(start,start+pageSize),total,page,pages:Math.max(1,Math.ceil(total/pageSize)),pageSize};}
export async function getDataQualityTitle(imdbId){const sql=db(),rows=await baseSql(sql);const row=rows.find(r=>r.imdb_id===imdbId);return row?assessDataQuality(row):null;}
