import 'server-only';
import {db} from './db';
import {enrichTitle} from './enrich-title';
import {startRun,finishRun,audit,errorInfo} from './runlog';
const imdbOk=x=>/^tt\d+$/.test(String(x||''));
const tmdbOk=x=>/^\d+$/.test(String(x||''));

export async function getIdentityIssues(filters={}){const sql=db(),type=String(filters.type||''),q=String(filters.q||'').trim().toLowerCase();return sql`SELECT m.imdb_id,m.type,COALESCE(m.title_es,m.title,m.original_title) display_title,m.original_title,m.year,m.tmdb_id,m.fa_id,m.fa_url,m.source_status,m.poster_path,CASE WHEN m.imdb_id IS NULL OR m.imdb_id!~'^tt[0-9]+$' THEN 'missing_imdb' WHEN m.tmdb_id IS NULL THEN 'missing_tmdb' WHEN m.fa_id IS NULL THEN 'missing_fa' WHEN COALESCE((m.source_status->>'tmdb'),'')='mismatch' OR COALESCE((m.source_status->>'filmaffinity'),'')='mismatch' THEN 'doubtful' ELSE NULL END issue_type FROM movies m WHERE (m.imdb_id IS NULL OR m.imdb_id!~'^tt[0-9]+$' OR m.tmdb_id IS NULL OR m.fa_id IS NULL OR COALESCE((m.source_status->>'tmdb'),'')='mismatch' OR COALESCE((m.source_status->>'filmaffinity'),'')='mismatch') AND (${type}='' OR (${type}='movie' AND m.type='Película') OR (${type}='series' AND m.type IN ('Serie','Miniserie'))) AND (${q}='' OR lower(COALESCE(m.title_es,m.title,m.original_title,'')) LIKE ${'%'+q+'%'}) ORDER BY CASE WHEN m.imdb_id IS NULL THEN 0 WHEN m.tmdb_id IS NULL THEN 1 WHEN m.fa_id IS NULL THEN 2 ELSE 3 END,m.year DESC NULLS LAST LIMIT 300`}

export async function retryIdentity(imdbId){if(!imdbOk(imdbId))throw new Error('IMDb ID inválido');const run=await startRun('identity_retry','web',{imdb_id:imdbId,stage:'enrich'});try{const r=await enrichTitle(imdbId);await finishRun(run.id,'success',{processed:1,updated:1,summary:{stage:'done',imdb_id:imdbId,result:r}});return r}catch(e){await finishRun(run.id,'failed',{processed:1,errors:1,summary:{stage:'failed',imdb_id:imdbId,error:errorInfo(e)}});throw e}}

export async function reanalyzeIdentity({limit=25}={}){const sql=db(),run=await startRun('identity_scan','web',{stage:'scan'});try{const rows=await sql`SELECT imdb_id FROM movies WHERE imdb_id~'^tt[0-9]+$' AND (tmdb_id IS NULL OR fa_id IS NULL) ORDER BY synced_at NULLS FIRST LIMIT ${limit}`;let fixed=0,errors=0;for(const r of rows){try{await enrichTitle(r.imdb_id);fixed++}catch{errors++}}await finishRun(run.id,'success',{processed:rows.length,updated:fixed,errors,summary:{stage:'done',fixed,errors}});return{processed:rows.length,fixed,errors}}catch(e){await finishRun(run.id,'failed',{errors:1,summary:{stage:'failed',error:errorInfo(e)}});throw e}}

export async function saveIdentity(oldImdbId,{imdbId,tmdbId,faId}){const sql=db(),newImdb=String(imdbId||oldImdbId).trim(),newTmdb=String(tmdbId||'').trim()||null,newFa=String(faId||'').trim()||null;if(!imdbOk(oldImdbId)||!imdbOk(newImdb))throw new Error('IMDb ID inválido');if(newTmdb&&!tmdbOk(newTmdb))throw new Error('TMDb ID inválido');const [old]=await sql`SELECT * FROM movies WHERE imdb_id=${oldImdbId}`;if(!old)throw new Error('Título no encontrado');if(newImdb!==oldImdbId){const exists=await sql`SELECT 1 FROM movies WHERE imdb_id=${newImdb}`;if(exists.length)throw new Error('El nuevo IMDb ID ya existe en el catálogo');const cols=['type','title','title_es','original_title','year','runtime','country','origin','final_rating','imdb_rating','imdb_votes','fa_rating','fa_votes','wikidata_id','source_status','source_generated_at','synced_at','poster_path','backdrop_path','artwork_synced_at','manual_poster_url','artwork_source','inclusion_origin'];const v=Object.fromEntries(cols.map(k=>[k,old[k]]));await sql`INSERT INTO movies(imdb_id,type,title,title_es,original_title,year,runtime,country,origin,final_rating,imdb_rating,imdb_votes,imdb_url,fa_id,fa_rating,fa_votes,fa_url,tmdb_id,tmdb_rating,tmdb_votes,tmdb_url,wikidata_id,source_status,source_generated_at,synced_at,poster_path,backdrop_path,artwork_synced_at,manual_poster_url,artwork_source,inclusion_origin) VALUES(${newImdb},${v.type},${v.title},${v.title_es},${v.original_title},${v.year},${v.runtime},${v.country},${v.origin},${v.final_rating},${v.imdb_rating},${v.imdb_votes},${`https://www.imdb.com/title/${newImdb}/`},${newFa},${v.fa_rating},${v.fa_votes},${newFa?`https://www.filmaffinity.com/es/film${newFa}.html`:null},${newTmdb},${old.tmdb_rating},${old.tmdb_votes},${newTmdb?`https://www.themoviedb.org/${old.type==='Película'?'movie':'tv'}/${newTmdb}`:null},${v.wikidata_id},${JSON.stringify({...v.source_status,manual_identity:true})}::jsonb,${v.source_generated_at},now(),${v.poster_path},${v.backdrop_path},${v.artwork_synced_at},${v.manual_poster_url},${v.artwork_source},${v.inclusion_origin})`;
      const tables=['movie_metadata','movie_genres','movie_credits','movie_collections','acquisition_status','acquisition_priority_snapshots','saga_universe_titles'];for(const t of tables)await sql.unsafe(`UPDATE ${t} SET imdb_id=$1 WHERE imdb_id=$2`,[newImdb,oldImdbId]);for(const t of ['catalog_exclusions','catalog_candidates','plex_catalog_status','plex_manual_overrides','series_reference','saga_collection_members']){try{await sql.unsafe(`UPDATE ${t} SET imdb_id=$1 WHERE imdb_id=$2`,[newImdb,oldImdbId])}catch{}}await sql`DELETE FROM movies WHERE imdb_id=${oldImdbId}`;
    }else await sql`UPDATE movies SET tmdb_id=${newTmdb},tmdb_url=${newTmdb?`https://www.themoviedb.org/${old.type==='Película'?'movie':'tv'}/${newTmdb}`:null},fa_id=${newFa},fa_url=${newFa?`https://www.filmaffinity.com/es/film${newFa}.html`:null},source_status=COALESCE(source_status,'{}'::jsonb)||'{"manual_identity":true}'::jsonb,synced_at=now() WHERE imdb_id=${oldImdbId}`;
    await audit('identity','title',newImdb,'manual_edit',{old_imdb_id:oldImdbId,new_imdb_id:newImdb,tmdb_id:newTmdb,fa_id:newFa});return newImdb}
