import 'server-only';
import {db} from './db';
import {startProcessRun,addProcessEvent,finishProcessRun} from './process-runtime';
import {getActiveBatch,getLatestBatch} from './batch-engine';
const SPECS={
 'PROC-IV-001':{pool:'api',executor:'railway_batch_api',concurrency:2,operation:'batch_refresh_identity_evidence',selection:'evidence_pending'},
 'PROC-IV-002':{pool:'fast',executor:'railway_batch_fast',concurrency:8,operation:'batch_validate_identity',selection:'evidence_ready'},
};
const readySql=`v.tmdb_id=m.tmdb_id AND ((v.imdb_original_title IS NOT NULL AND v.imdb_year IS NOT NULL AND v.tmdb_original_title IS NOT NULL AND v.tmdb_year IS NOT NULL) OR COALESCE((v.validation_details #>> '{link_evidence,forward_match}')::boolean,false) OR COALESCE((v.validation_details #>> '{link_evidence,reverse_match}')::boolean,false))`;
export async function selectIvBatchEligibleIds(processCode,sql=db()){
 if(processCode==='PROC-IV-001'){const rows=await sql.query(`SELECT m.imdb_id FROM catalog_lifecycle cl JOIN movies m USING(imdb_id) LEFT JOIN identity_validation v USING(imdb_id) LEFT JOIN catalog_exclusions ex USING(imdb_id) WHERE ex.imdb_id IS NULL AND cl.lifecycle_state='IDENTITY_VALIDATION' AND m.tmdb_id IS NOT NULL AND NOT(${readySql}) ORDER BY m.imdb_id`);return rows.map(r=>r.imdb_id)}
 if(processCode==='PROC-IV-002'){const rows=await sql.query(`SELECT m.imdb_id FROM catalog_lifecycle cl JOIN movies m USING(imdb_id) JOIN identity_validation v USING(imdb_id) LEFT JOIN catalog_exclusions ex USING(imdb_id) WHERE ex.imdb_id IS NULL AND cl.lifecycle_state='IDENTITY_VALIDATION' AND ${readySql} ORDER BY m.imdb_id`);return rows.map(r=>r.imdb_id)}
 throw new Error('Proceso IV Batch no soportado');
}
export async function getIvBatchPanelState(processCode){const sql=db(),spec=SPECS[processCode];if(!spec)throw new Error('Proceso IV Batch no soportado');const[ids,active,latest,[engine],sources]=await Promise.all([selectIvBatchEligibleIds(processCode,sql),getActiveBatch(processCode,sql),getLatestBatch(processCode,sql),sql.query(`SELECT desired_state,pause_reason,changed_at FROM batch_engine_control WHERE singleton_id=1`),processCode==='PROC-IV-001'?sql.query(`SELECT l.*,u.batch_calls,u.manual_calls,u.rate_limited,u.errors FROM batch_api_source_limits l LEFT JOIN batch_api_source_usage u ON u.source=l.source AND u.usage_date=(now() AT TIME ZONE 'UTC')::date WHERE l.source IN('tmdb','omdb') ORDER BY l.source`):Promise.resolve([])]);return{processCode,eligibleCount:ids.length,active,latest,engine:engine||{desired_state:'running'},sources,defaultConcurrency:spec.concurrency}}
export async function startIvBatch(processCode,{limit=null}={}){const sql=db(),spec=SPECS[processCode];if(!spec)throw new Error('Proceso IV Batch no soportado');const active=await getActiveBatch(processCode,sql);if(active)return{run:active,reused:true,eligibleCount:Number(active.items_pending||0)};let ids=await selectIvBatchEligibleIds(processCode,sql);if(limit!=null)ids=ids.slice(0,Math.max(1,Math.min(Number(limit)||1,10000)));if(!ids.length)return{run:null,reused:false,empty:true,eligibleCount:0};const correlationKey=`${processCode}:batch:${Date.now()}`,started=await startProcessRun({processCode,runKind:'batch',triggerSource:'calidad_validacion_identidad_batch',executor:spec.executor,entityType:'title_set',entityId:spec.selection,correlationKey,idempotencyKey:correlationKey,context:{surface:'/calidad/validacion-identidad',operation:spec.operation,worker_pool:spec.pool,selection:spec.selection,requested_concurrency:spec.concurrency}}),runId=started.run.run_id;try{await sql.query(`INSERT INTO batch_run_control(run_id,process_code,worker_pool,desired_state,requested_concurrency) VALUES($1::uuid,$2,$3,'running',$4)`,[runId,processCode,spec.pool,spec.concurrency]);await sql.query(`INSERT INTO batch_run_items(batch_run_id,entity_type,entity_id,position,status) SELECT $1::uuid,'title',x.entity_id,(x.ord-1)::int,'queued' FROM unnest($2::text[]) WITH ORDINALITY AS x(entity_id,ord)`,[runId,ids]);await sql.query(`UPDATE process_runs SET items_total=$2,items_processed=0,items_succeeded=0,items_failed=0,items_pending=$2,updated_at=now() WHERE run_id=$1::uuid`,[runId,ids.length]);await addProcessEvent(runId,{eventType:'batch_queued',message:`Batch ${processCode} preparado`,data:{items_total:ids.length,worker_pool:spec.pool,requested_concurrency:spec.concurrency,selection:spec.selection}});return{run:await getActiveBatch(processCode,sql),reused:false,empty:false,eligibleCount:ids.length}}catch(error){await finishProcessRun(runId,{technicalStatus:'failed',message:`No se pudo preparar la cola Batch ${processCode}`}).catch(()=>{});if(error?.code==='23505'){const existing=await getActiveBatch(processCode,sql);if(existing)return{run:existing,reused:true,eligibleCount:Number(existing.items_pending||0)}}throw error}}
