import 'server-only';
import {db} from './db';
import {LIFECYCLE,classifyLifecycle,recomputeLifecycleWithSql} from './lifecycle-recompute-core.mjs';
export {LIFECYCLE,classifyLifecycle};
export async function recomputeLifecycleForIds(ids=[]){return recomputeLifecycleWithSql(db(),ids)}
export async function getLifecycleForIds(ids=[]){const clean=[...new Set(ids.filter(Boolean))];if(!clean.length)return new Map();const sql=db();const rows=await sql`SELECT imdb_id,lifecycle_state,previous_state,blocking_reason,state_changed_at,computed_at FROM catalog_lifecycle WHERE imdb_id=ANY(${clean}::text[])`;return new Map(rows.map(r=>[r.imdb_id,{...r,state:r.lifecycle_state,...LIFECYCLE[r.lifecycle_state]}]))}
export async function attachLifecycle(rows=[]){const map=await getLifecycleForIds(rows.map(r=>r.imdb_id).filter(Boolean));return rows.map(r=>({...r,lifecycle:map.get(r.imdb_id)||{state:'IDENTITY_PENDING',...LIFECYCLE.IDENTITY_PENDING}}))}
export async function reconcileLifecycleBatch({after=null,limit=500}={}){const sql=db();const rows=await sql`SELECT imdb_id FROM movies WHERE (${after}::text IS NULL OR imdb_id>${after} ORDER BY imdb_id LIMIT ${Math.max(1,Math.min(Number(limit)||500,2000))}`;const ids=rows.map(r=>r.imdb_id);await recomputeLifecycleWithSql(sql,ids);return{processed:ids.length,last:ids.at(-1)||null,done:ids.length===0}}
export async function getLifecycleSnapshot(){const sql=db(),counts={};const rows=await sql`SELECT lifecycle_state,count(*)::int count FROM catalog_lifecycle GROUP BY lifecycle_state`;for(const r of rows)counts[r.lifecycle_state]=Number(r.count||0);const[totals]=await sql`SELECT count(*)::int total FROM movies`;const materialized=Object.values(counts).reduce((a,b)=>a+Number(b||0),0);return{total:Number(totals?.total||0),materialized,missing:Math.max(0,Number(totals?.total||0)-materialized),counts,states:Object.entries(LIFECYCLE).map(([state,meta])=>({state,...meta,count:counts[state]||0}))}}
