import 'server-only';
import {db} from './db';

export const DEFAULT_NEWS_SETTINGS={version:1,movie:{general:{minRating:6,minVotes:10000},spain:{minRating:6,minVotes:7500}},series:{general:{minRating:7,minVotes:5000},spain:{minRating:6.5,minVotes:4000}},excludedCountries:['Q668','IN'],excludeAdult:true};
function mergeSettings(raw={}){return {...DEFAULT_NEWS_SETTINGS,...raw,movie:{general:{...DEFAULT_NEWS_SETTINGS.movie.general,...raw?.movie?.general},spain:{...DEFAULT_NEWS_SETTINGS.movie.spain,...raw?.movie?.spain}},series:{general:{...DEFAULT_NEWS_SETTINGS.series.general,...raw?.series?.general},spain:{...DEFAULT_NEWS_SETTINGS.series.spain,...raw?.series?.spain}},excludedCountries:Array.isArray(raw?.excludedCountries)?raw.excludedCountries:DEFAULT_NEWS_SETTINGS.excludedCountries}}
export async function getNewsSettings(){const sql=db();const[row]=await sql`SELECT value,updated_at FROM app_settings WHERE key='imdb_discovery_v1' LIMIT 1`;return{...mergeSettings(row?.value||{}),updatedAt:row?.updated_at||null}}

function originsOf(row){if(row.row_kind==='plex_unidentified')return['plex'];const s=row.source_snapshot||{};if(Array.isArray(s.origins)&&s.origins.length)return [...new Set(s.origins.map(String))];const out=[];if(s.manual===true||s.manual==='true'||row.matched_rule==='manual'||s.restoredFromExclusion===true||s.restoredFromExclusion==='true')out.push('manual');if(s.origin==='plex'||row.matched_rule==='plex')out.push('plex');if(s.origin==='saga'||row.matched_rule==='saga_manual')out.push('saga');if(s.origin==='person')out.push('person');if(!out.length)out.push('discovery');return out}
function contextOf(row){const s=row.source_snapshot||{},ev=Array.isArray(s.intakeEvidence)?s.intakeEvidence:[];return ev.map(x=>x?.context).filter(Boolean).slice(-3)}
function isReady(row){return row.row_kind!=='plex_unidentified'&&row.eligibility_status==='eligible'&&/^tt\d+$/.test(String(row.imdb_id||''))&&String(row.title||'').trim()&&row.title!==row.imdb_id&&Boolean(row.candidate_type)}
function stateOf(row,active){if(isReady(row))return'ready';if(active.has(String(row.imdb_id||row.rating_key||'')))return'processing';return'attention'}

export async function getNewsV1(filters={}){
 const sql=db(),type=String(filters.type||'all'),q=String(filters.q||'').trim().toLowerCase(),source=String(filters.source||'all'),state=String(filters.state||'all');
 const allowedSizes=[24,48,96],pageSize=allowedSizes.includes(Number(filters.pageSize))?Number(filters.pageSize):24,page=Math.max(1,Number(filters.page)||1),offset=(page-1)*pageSize;
 const candidateRows=await sql`SELECT 'candidate'::text row_kind,c.imdb_id,NULL::text rating_key,c.candidate_type,c.year,c.first_seen_at,c.became_eligible_at,c.last_seen_at,c.eligibility_status,c.source_snapshot,COALESCE(c.source_snapshot->>'title',c.source_snapshot->>'originalTitle',c.imdb_id) title,COALESCE(c.source_snapshot->>'matchedRule',c.source_snapshot->>'origin','general') matched_rule FROM catalog_candidates c LEFT JOIN movies m ON m.imdb_id=c.imdb_id LEFT JOIN catalog_exclusions ex ON ex.imdb_id=c.imdb_id WHERE m.imdb_id IS NULL AND ex.imdb_id IS NULL AND c.eligibility_status IN('eligible','processing')`;
 const plexPending=await sql`SELECT 'plex_unidentified'::text row_kind,NULL::text imdb_id,p.rating_key,CASE WHEN p.item_type='movie' THEN 'movie' ELSE 'tvSeries' END candidate_type,p.plex_year AS "year",p.added_at first_seen_at,NULL::timestamptz became_eligible_at,COALESCE(p.plex_updated_at,p.last_seen_at,p.synced_at) last_seen_at,'processing'::text eligibility_status,jsonb_build_object('origin','plex','origins',jsonb_build_array('plex'),'title',p.plex_title,'plexRatingKey',p.rating_key) source_snapshot,COALESCE(NULLIF(p.plex_title,''),p.rating_key) title,'plex'::text matched_rule FROM plex_items p LEFT JOIN plex_external_ids imdb ON imdb.rating_key=p.rating_key AND imdb.provider='imdb' WHERE p.active AND p.item_type IN('movie','show') AND imdb.external_id IS NULL`;
 const activeRows=await sql`SELECT DISTINCT entity_id FROM process_runs WHERE technical_status IN('queued','running') AND entity_type='title' AND process_code LIKE 'PROC-NOV-%'`;
 const active=new Set(activeRows.map(x=>String(x.entity_id)));
 let all=[...candidateRows,...plexPending].map(r=>({...r,origins:originsOf(r),origin:originsOf(r)[0],origin_context:contextOf(r),news_state:stateOf(r,active)}));
 if(type==='movie')all=all.filter(r=>r.candidate_type==='movie');if(type==='series')all=all.filter(r=>['tvSeries','tvMiniSeries'].includes(r.candidate_type));if(q)all=all.filter(r=>String(r.title||r.imdb_id||r.rating_key||'').toLowerCase().includes(q));if(['manual','plex','saga','person','discovery'].includes(source))all=all.filter(r=>r.origins.includes(source));if(['ready','attention','processing'].includes(state))all=all.filter(r=>r.news_state===state);
 const priority={ready:0,attention:1,processing:2};all.sort((a,b)=>(priority[a.news_state]-priority[b.news_state])||(new Date(b.became_eligible_at||b.first_seen_at||0)-new Date(a.became_eligible_at||a.first_seen_at||0)));
 const raw=[...candidateRows,...plexPending].map(r=>({...r,origins:originsOf(r),news_state:stateOf(r,active)}));
 const stats={total:raw.length,ready:raw.filter(r=>r.news_state==='ready').length,attention:raw.filter(r=>r.news_state==='attention').length,processing:raw.filter(r=>r.news_state==='processing').length,manual:raw.filter(r=>r.origins.includes('manual')).length,plex:raw.filter(r=>r.origins.includes('plex')).length,saga:raw.filter(r=>r.origins.includes('saga')).length,person:raw.filter(r=>r.origins.includes('person')).length,discovery:raw.filter(r=>r.origins.includes('discovery')).length};
 const[excludedStats]=await sql`SELECT count(*)::int total FROM catalog_exclusions`;
 return{rows:all.slice(offset,offset+pageSize),stats,filteredTotal:all.length,excludedCount:excludedStats?.total||0,page,pageSize};
}
export async function getNewsCandidate(imdbId){const sql=db();const[r]=await sql`SELECT * FROM catalog_candidates WHERE imdb_id=${imdbId} LIMIT 1`;return r||null}
