import 'server-only';
import {db} from './db';
import {executeObservedProcess} from './process-runtime';
import {ensurePeopleSchemaWithSql,refreshPersonFilmographyCanonical} from './people-refresh-core.mjs';

export async function ensurePeopleSchema(){return ensurePeopleSchemaWithSql(db())}

export async function getPeopleDashboard(filters={}){await ensurePeopleSchema();const sql=db(),q=String(filters.q||'').trim(),role=String(filters.role||'acting'),sort=String(filters.sort||'titles'),page=Math.max(1,Number(filters.page)||1),pageSize=50;const rows=await sql`WITH base AS (SELECT p.tmdb_person_id,p.name,p.profile_path,p.known_for_department,p.birthday,p.deathday,p.place_of_birth,p.popularity,count(DISTINCT mc.imdb_id) FILTER(WHERE mc.credit_type='cast')::int catalog_movies,count(DISTINCT mc.imdb_id) FILTER(WHERE mc.credit_type='crew' AND lower(COALESCE(mc.job,''))='director')::int directed_movies,count(DISTINCT mc.imdb_id) FILTER(WHERE c.effective_status='in_plex' AND mc.credit_type='cast')::int plex_movies,round(avg(c.final_rating) FILTER(WHERE mc.credit_type='cast' AND c.final_rating IS NOT NULL)::numeric,2) avg_score,count(c.final_rating) FILTER(WHERE mc.credit_type='cast')::int scored,prs.filmography_refreshed_at,prs.filmography_count FROM people p JOIN movie_credits mc ON mc.tmdb_person_id=p.tmdb_person_id JOIN catalog_read_model c ON c.imdb_id=mc.imdb_id LEFT JOIN person_refresh_state prs ON prs.tmdb_person_id=p.tmdb_person_id GROUP BY p.tmdb_person_id,p.name,p.profile_path,p.known_for_department,p.birthday,p.deathday,p.place_of_birth,p.popularity,prs.filmography_refreshed_at,prs.filmography_count) SELECT * FROM base WHERE (${q}='' OR lower(name) LIKE lower(${'%'+q+'%'})) AND ((${role}='acting' AND catalog_movies>5) OR (${role}='directing' AND directed_movies>5)) ORDER BY CASE WHEN ${sort}='score' THEN avg_score END DESC NULLS LAST,CASE WHEN ${sort}='plex' THEN plex_movies END DESC NULLS LAST,CASE WHEN ${sort}='coverage' THEN (plex_movies::numeric/NULLIF(catalog_movies,0)) END DESC NULLS LAST,CASE WHEN ${role}='directing' THEN directed_movies ELSE catalog_movies END DESC,name LIMIT ${pageSize} OFFSET ${(page-1)*pageSize}`;const[count]=await sql`WITH b AS (SELECT p.tmdb_person_id,count(DISTINCT mc.imdb_id) FILTER(WHERE mc.credit_type='cast') a,count(DISTINCT mc.imdb_id) FILTER(WHERE mc.credit_type='crew' AND lower(COALESCE(mc.job,''))='director') d FROM people p JOIN movie_credits mc ON mc.tmdb_person_id=p.tmdb_person_id GROUP BY p.tmdb_person_id) SELECT count(*)::int total FROM b WHERE ((${role}='acting' AND a>5) OR (${role}='directing' AND d>5))`;return{rows,total:count.total,page,pages:Math.max(1,Math.ceil(count.total/pageSize)),role}}

export async function refreshPersonFilmography(id,{requestKey}={}){const personId=String(id);if(!/^\d+$/.test(personId))throw new Error('Persona inválida');const key=requestKey||`person-refresh:${personId}:${Math.floor(Date.now()/3000)}`;const observed=await executeObservedProcess({processCode:'PROC-PER-001',runKind:'individual',triggerSource:'personas_manual',executor:'vercel',entityType:'person',entityId:personId,correlationKey:key,idempotencyKey:`PROC-PER-001:${key}`,context:{surface:`/personas/${personId}`,operation:'refresh_person_profile_filmography',concurrency:8}},trace=>refreshPersonFilmographyCanonical(db(),personId,{trace}));if(observed.reused)return{reused:true,count:Number(observed.run?.metrics?.credits||0),runId:observed.runId};return{reused:false,count:observed.result?.metrics?.credits||0,relevant:observed.result?.metrics?.relevant||0,other:observed.result?.metrics?.other||0,runId:observed.runId}}

export async function getPersonV2(id){await ensurePeopleSchema();const sql=db();const[p]=await sql`SELECT p.*,s.filmography_refreshed_at,s.filmography_count FROM people p LEFT JOIN person_refresh_state s USING(tmdb_person_id) WHERE p.tmdb_person_id=${String(id)} LIMIT 1`;if(!p)return null;const titles=await sql`SELECT f.*,m.imdb_id IS NOT NULL in_catalog,c.display_title,c.effective_status,c.resolution,c.final_rating,c.poster_path catalog_poster,cc.eligibility_status novedades_status,pq.score pikoquality_score,pq.band pikoquality_band,CASE WHEN f.release_date>current_date THEN 'upcoming' WHEN f.release_date>current_date-interval '90 days' THEN 'recent' ELSE 'available' END availability_phase FROM person_filmography f LEFT JOIN movies m ON m.imdb_id=f.imdb_id LEFT JOIN catalog_read_model c ON c.imdb_id=f.imdb_id LEFT JOIN catalog_candidates cc ON cc.imdb_id=f.imdb_id LEFT JOIN LATERAL (SELECT q.score,q.band FROM piko_quality q WHERE q.rating_key=c.rating_key AND q.status='evaluated' ORDER BY q.updated_at DESC NULLS LAST LIMIT 1) pq ON true WHERE f.tmdb_person_id=${String(id)} ORDER BY f.year DESC NULLS LAST,f.popularity DESC NULLS LAST`;return{...p,titles}}
