import 'server-only';
import {db} from './db';
import {ensureQualitySchema,scoreMovie,band,QUALITY_VERSION} from './pikoquality';
import {audit} from './runlog';
import {recomputeLifecycleForIds} from './lifecycle';

const CLIENT='pikofilm-quality';
const attrs=s=>Object.fromEntries([...s.matchAll(/([\w:-]+)="([^"]*)"/g)].map(m=>[m[1],m[2]]));
const dyn=s=>s.DOVIPresent?'Dolby Vision':s.HDR10PlusPresent?'HDR10+':s.HDR10Present?'HDR10':s.dynamicRange||s.videoDynamicRange||null;
async function baseUrl(token){if(process.env.PLEX_URL||process.env.PLEX_BASE_URL)return String(process.env.PLEX_URL||process.env.PLEX_BASE_URL).replace(/\/$/,'');const r=await fetch('https://plex.tv/api/resources?includeHttps=1',{headers:{'X-Plex-Token':token,'X-Plex-Client-Identifier':CLIENT},cache:'no-store'});if(!r.ok)throw new Error(`No se pudo descubrir Plex (${r.status})`);const xml=await r.text();for(const d of xml.matchAll(/<Device\b([^>]*)>([\s\S]*?)<\/Device>/g)){const a=attrs(d[1]);if(!String(a.provides||'').includes('server'))continue;const c=[...d[2].matchAll(/<Connection\b([^>]*)\/?\s*>/g)].map(x=>attrs(x[1]));const b=c.find(x=>x.local==='0'&&x.relay!=='1'&&String(x.uri||'').startsWith('https://'))||c.find(x=>x.local==='0'&&x.relay!=='1')||c.find(x=>x.relay==='1')||c[0];if(b?.uri)return b.uri.replace(/\/$/,'')}throw new Error('Sin conexión Plex remota')}
async function detail(base,token,key){const r=await fetch(`${base}/library/metadata/${key}`,{headers:{Accept:'application/json','X-Plex-Token':token,'X-Plex-Client-Identifier':CLIENT,'X-Plex-Product':'PikoFilm','X-Plex-Version':'3'},cache:'no-store',signal:AbortSignal.timeout(30000)});if(!r.ok)throw new Error(`Plex respondió ${r.status}`);const b=await r.json();return (b?.MediaContainer?.Metadata||[])[0]||null}
function audioRank(s){const x=String((s.codec||'')+' '+(s.profile||'')).toLowerCase();let n=x.includes('truehd')||x.includes('atmos')||x.includes('dts-hd')||x.includes('dca-ma')?100:x.includes('eac3')||x.includes('dts')?80:x.includes('ac3')?60:x.includes('aac')?50:30;return n+Number(s.channels||0)*2+Number(s.bitrate||0)/1000}
function streamShape(item){let bestV=null,bestA=null,count=0;for(const m of(item.Media||[]))for(const p of(m.Part||[]))for(const s of(p.Stream||[])){count++;const type=Number(s.streamType||0),bitrate=Number(s.bitrate||0)||null,bitDepth=Number(s.bitDepth||s.bit_depth||0)||null,dynamicRange=dyn(s);if(type===1&&(!bestV||(bitrate||0)>(bestV.bitrate||0)))bestV={codec:s.codec,profile:s.profile,bitrate,bit_depth:bitDepth,dynamic_range:dynamicRange};if(type===2&&(!bestA||audioRank(s)>audioRank(bestA)))bestA={codec:s.codec,profile:s.profile,bitrate,channels:Number(s.channels||0)||null}}return{bestV,bestA,count}}

export async function analyzeMoviePikoQuality(imdbId){
  if(!/^tt\d+$/.test(String(imdbId||'')))throw new Error('IMDb ID inválido');
  await ensureQualitySchema();const token=process.env.PLEX_TOKEN;if(!token)throw new Error('PLEX_TOKEN no configurado');const sql=db();
  const[row]=await sql`SELECT p.rating_key,p.fingerprint,p.item_type,m.resolution,m.width,m.height,m.bitrate,m.video_codec,m.video_profile,m.video_frame_rate,m.audio_codec,m.audio_profile,m.audio_channels,m.container,f.file_size_bytes,f.duration_ms FROM plex_items p JOIN plex_external_ids x ON x.rating_key=p.rating_key AND x.provider='imdb' AND x.external_id=${imdbId} JOIN plex_media m ON m.rating_key=p.rating_key AND m.media_index=0 LEFT JOIN plex_files f ON f.rating_key=p.rating_key AND f.media_index=0 AND f.part_index=0 WHERE p.active AND p.item_type='movie' ORDER BY p.rating_key LIMIT 1`;
  if(!row)throw new Error('No hay archivo físico activo en Plex');
  const[v]=await sql`SELECT source_fingerprint,status FROM movie_file_validation WHERE rating_key=${row.rating_key}`;if(!v||v.status!=='checked'||v.source_fingerprint!==row.fingerprint)throw new Error('Primero debes validar el archivo de la película');
  await audit('pikoquality','title',imdbId,'unitary_analysis_started',{rating_key:row.rating_key,fingerprint:row.fingerprint});
  try{const base=await baseUrl(token),item=await detail(base,token,row.rating_key);if(!item)throw new Error('Plex no devolvió detalle del archivo');const s=streamShape(item),scored={...row,video_stream_bitrate:s.bestV?.bitrate,bit_depth:s.bestV?.bit_depth,dynamic_range:s.bestV?.dynamic_range,audio_stream_codec:s.bestA?.codec,audio_stream_profile:s.bestA?.profile,audio_stream_bitrate:s.bestA?.bitrate,audio_stream_channels:s.bestA?.channels};const score=scoreMovie(scored),b=band(score);await sql`INSERT INTO piko_quality(rating_key,item_type,score,band,confidence,formula_version,status,source_fingerprint,enriched_at,last_error,evaluated_at,updated_at) VALUES(${row.rating_key},'movie',${score},${b},'high',${QUALITY_VERSION},'evaluated',${row.fingerprint},now(),NULL,now(),now()) ON CONFLICT(rating_key) DO UPDATE SET item_type='movie',score=EXCLUDED.score,band=EXCLUDED.band,confidence='high',formula_version=EXCLUDED.formula_version,status='evaluated',source_fingerprint=EXCLUDED.source_fingerprint,enriched_at=now(),last_error=NULL,evaluated_at=now(),updated_at=now()`;const lifecycle=(await recomputeLifecycleForIds([imdbId])).get(imdbId);await audit('pikoquality','title',imdbId,'unitary_analysis_completed',{rating_key:row.rating_key,score,band:b,streams:s.count,lifecycle:lifecycle?.state});return{score,band:b,streams:s.count,lifecycle};}catch(e){await audit('pikoquality','title',imdbId,'unitary_analysis_failed',{rating_key:row.rating_key,error:e?.message||String(e)});throw e}
}
