export const PIKOSCORE_VERSION='2.0.0';
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
const spanishCountry=country=>/\b(spain|españa)\b/i.test(String(country||''));
function ageYears(row){const now=new Date();if(row.release_date){const d=new Date(row.release_date);if(!Number.isNaN(d.getTime()))return Math.max(0,(now-d)/(365.25*86400000));}const y=Number(row.year);return y>1800?Math.max(0,now.getUTCFullYear()-y):10;}
function ageFactor(row){const a=ageYears(row);return a<=0.25?0.25:a<=1?0.35:a<=3?0.55:a<=10?0.8:1;}
export function freshnessDays(row){const a=ageYears(row);return a<0.25?14:a<1?30:a<3?90:a<10?180:365;}
function sourceParams(isSpanish){return isSpanish?{prior:{imdb:5.72,fa:5.12,tmdb:5.91},median:{imdb:807,fa:2160,tmdb:39},weight:{imdb:0.30,fa:0.45,tmdb:0.25}}:{prior:{imdb:6.54,fa:5.72,tmdb:6.63},median:{imdb:21969,fa:2340,tmdb:490},weight:{imdb:0.40,fa:0.35,tmdb:0.25}};}
function adjustedRating(rating,votes,prior,median,ageMult){const v=Math.max(0,Number(votes)||0),m=Math.max(1,median*ageMult),r=Number(rating)||prior,confidence=v/(v+m);return{value:(v*r+m*prior)/(v+m),confidence};}
function criticsModifier(rt,meta){const signals=[];if(Number.isFinite(Number(meta)))signals.push(clamp((Number(meta)-60)/40,-1,1));if(Number.isFinite(Number(rt)))signals.push(clamp((Number(rt)-60)/40,-1,1));if(!signals.length)return 0;return clamp(signals.reduce((a,b)=>a+b,0)/signals.length*0.35,-0.35,0.35);}
function std(values){const m=values.reduce((a,b)=>a+b,0)/values.length;return Math.sqrt(values.reduce((s,x)=>s+(x-m)**2,0)/values.length);}
export function computePikoScore(row){const required=['imdb_rating','imdb_votes','fa_rating','fa_votes','tmdb_rating','tmdb_votes'];if(required.some(k=>!(Number(row[k])>0)))throw new Error('Faltan notas o votos obligatorios para calcular PikoScore');const isSpanish=spanishCountry(row.country),p=sourceParams(isSpanish),af=ageFactor(row),a={imdb:adjustedRating(row.imdb_rating,row.imdb_votes,p.prior.imdb,p.median.imdb,af),fa:adjustedRating(row.fa_rating,row.fa_votes,p.prior.fa,p.median.fa,af),tmdb:adjustedRating(row.tmdb_rating,row.tmdb_votes,p.prior.tmdb,p.median.tmdb,af)};const core=a.imdb.value*p.weight.imdb+a.fa.value*p.weight.fa+a.tmdb.value*p.weight.tmdb,critic=criticsModifier(row.rotten_tomatoes_score,row.metacritic_score),score=Number(clamp(core+critic,0,10).toFixed(2));const voteConfidence=a.imdb.confidence*p.weight.imdb+a.fa.confidence*p.weight.fa+a.tmdb.confidence*p.weight.tmdb,dispersion=std([a.imdb.value,a.fa.value,a.tmdb.value]),consensusFactor=Math.max(0.55,1-Math.min(0.45,dispersion/3)),confidence=Number((100*(0.15+0.85*voteConfidence)*consensusFactor).toFixed(1));return{score,confidence,criticsModifier:Number(critic.toFixed(3)),isSpanish,adjusted:{imdb:Number(a.imdb.value.toFixed(3)),fa:Number(a.fa.value.toFixed(3)),tmdb:Number(a.tmdb.value.toFixed(3))},sourceConfidence:{imdb:Number(a.imdb.confidence.toFixed(3)),fa:Number(a.fa.confidence.toFixed(3)),tmdb:Number(a.tmdb.confidence.toFixed(3))},expiryDays:freshnessDays(row)};}
