import 'server-only';
import {db} from './db';

export const QUALITY_VERSION='1.0.0';
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const norm=s=>String(s||'').toLowerCase();
function resolutionPoints(r){const w=Number(r.width||0),h=Number(r.height||0),label=norm(r.resolution);if(label==='4k'||w>=3000||h>=1800)return 30;if(label==='1080'||w>=1800||h>=790)return 24;if(label==='720'||w>=1200||h>=650)return 18;if(label==='576'||h>=540)return 13;if(label==='480'||h>=430)return 10;return 6}
function videoCodecPoints(c){c=norm(c);if(c.includes('av1'))return 7;if(c.includes('hevc')||c.includes('h265'))return 7;if(c.includes('h264')||c.includes('avc'))return 6;if(c.includes('mpeg4'))return 3;if(c.includes('mpeg2'))return 2;return 1}
function audioCodecPoints(c,profile=''){const x=norm(c+' '+profile);if(x.includes('truehd')||x.includes('dts-hd')||x.includes('dca-ma')||x.includes('flac')||x.includes('pcm'))return 13;if(x.includes('atmos'))return 13;if(x.includes('eac3')||x.includes('dts')||x.includes('dca'))return 11;if(x.includes('ac3'))return 9;if(x.includes('aac'))return 8;if(x.includes('mp3')||x.includes('mp2'))return 5;return 4}
function channelPoints(n){n=Number(n||0);if(n>=8)return 8;if(n>=6)return 7;if(n>=2)return 5;if(n===1)return 4;return 2}
function targetBitrate(r){const w=Number(r.width||0),h=Number(r.height||0),c=norm(r.video_codec),efficient=c.includes('hevc')||c.includes('h265')||c.includes('av1');if(w>=3000||h>=1800)return efficient?10000:18000;if(w>=1800||h>=790)return efficient?3500:6500;if(w>=1200||h>=650)return efficient?2200:3500;if(h>=430)return efficient?1000:1600;return efficient?700:1100}
export function scoreMovie(r){const bp=Number(r.video_stream_bitrate||r.bitrate||0),target=targetBitrate(r);const bitrate=clamp(Math.round(18*(bp/target)),3,18);const bitDepth=Number(r.bit_depth||0)>=10?3:1;const hdr=r.dynamic_range?2:0;const image=resolutionPoints(r)+bitrate+videoCodecPoints(r)+bitDepth+hdr;const audio=audioCodecPoints(r.audio_stream_codec||r.audio_codec,r.audio_stream_profile||r.audio_profile)+channelPoints(r.audio_stream_channels||r.audio_channels)+clamp(Math.round(Number(r.audio_stream_bitrate||0)/256),0,4);const integrity=(Number(r.file_size_bytes||0)>0?4:0)+(Number(r.duration_ms||0)>0?4:0)+(r.rating_key?2:0);const extras=(r.container?2:0)+(r.video_profile?1:0)+(r.video_frame_rate?1:0)+(r.bit_depth?1:0);return clamp(image+audio+integrity+extras,0,100)}
export function scoreEpisode(r,seasonMedian=null){let base=scoreMovie(r);/* Episodios: resolución pesa menos; una captura TV antigua coherente no es un defecto. */const res=resolutionPoints(r);base+=Math.round((24-res)*0.45);if(seasonMedian!=null){const delta=Number(r.bitrate||0)/(Number(seasonMedian)||1);if(delta<.45)base-=10;else if(delta<.65)base-=5;}return clamp(base,0,100)}
export function band(s){return s>=85?'excellent':s>=75?'very_good':s>=60?'correct':s>=40?'improvable':'deficient'}
export async function ensureQualitySchema(){const sql=db();await sql`CREATE TABLE IF NOT EXISTS piko_quality (rating_key text PRIMARY KEY,item_type text NOT NULL,score integer,band text,confidence text NOT NULL DEFAULT 'medium',formula_version text NOT NULL,status text NOT NULL DEFAULT 'pending',components jsonb NOT NULL DEFAULT '{}'::jsonb,source_fingerprint text,enriched_at timestamptz,evaluated_at timestamptz,updated_at timestamptz NOT NULL DEFAULT now())`;await sql`CREATE TABLE IF NOT EXISTS plex_streams (rating_key text NOT NULL,media_index integer NOT NULL,part_index integer NOT NULL,stream_index integer NOT NULL,stream_type integer,codec text,profile text,bitrate integer,bit_depth integer,dynamic_range text,color_space text,chroma text,channels integer,language text,is_selected boolean,is_default boolean,is_forced boolean,raw jsonb NOT NULL DEFAULT '{}'::jsonb,updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(rating_key,media_index,part_index,stream_index))`;await sql`CREATE INDEX IF NOT EXISTS idx_piko_quality_status ON piko_quality(status)`;await sql`CREATE INDEX IF NOT EXISTS idx_plex_streams_rating ON plex_streams(rating_key)`}
export async function qualitySummary(){await ensureQualitySchema();const sql=db();const [r]=await sql`SELECT count(*)::int total,count(*) FILTER(WHERE status='evaluated')::int evaluated,count(*) FILTER(WHERE status='pending')::int pending,count(*) FILTER(WHERE status='stale')::int stale,count(*) FILTER(WHERE confidence='high')::int high,max(evaluated_at) last_eval FROM piko_quality`;return r}
export async function backfillA(){await ensureQualitySchema();const sql=db();const rows=await sql`SELECT p.rating_key,p.item_type,m.resolution,m.width,m.height,m.bitrate,m.video_codec,m.video_profile,m.video_frame_rate,m.audio_codec,m.audio_profile,m.audio_channels,m.container,f.file_size_bytes,f.duration_ms FROM plex_items p JOIN plex_media m ON m.rating_key=p.rating_key AND m.media_index=0 LEFT JOIN plex_files f ON f.rating_key=p.rating_key AND f.media_index=0 AND f.part_index=0 WHERE p.active AND p.item_type IN ('movie','episode')`;let n=0;for(const r of rows){const score=r.item_type==='episode'?scoreEpisode(r):scoreMovie(r);await sql`INSERT INTO piko_quality(rating_key,item_type,score,band,confidence,formula_version,status,evaluated_at,updated_at) VALUES(${r.rating_key},${r.item_type},${score},${band(score)},'medium',${QUALITY_VERSION},'evaluated',now(),now()) ON CONFLICT(rating_key) DO UPDATE SET item_type=excluded.item_type,score=excluded.score,band=excluded.band,formula_version=excluded.formula_version,status='evaluated',evaluated_at=now(),updated_at=now()`;n++}return{processed:n}}
