import 'server-only';
import {db} from './db';
import {syncPlexFastCore,discoverPlexUrlCore} from './plex-sync-core.mjs';
import {recomputeLifecycleForIds} from './lifecycle';

const headers=token=>({'Accept':'application/json','X-Plex-Token':token,'X-Plex-Client-Identifier':'pikofilm-fast-sync','X-Plex-Product':'PikoFilm','X-Plex-Version':'2'});
const list=body=>body?.MediaContainer?.Metadata||body?.MediaContainer?.Video||body?.MediaContainer?.Directory||[];
const gids=item=>{const out={};for(const g of item?.Guid||[]){const m=String(g?.id||'').match(/^(imdb|tmdb|tvdb):\/\/(.+)$/);if(m)out[m[1]]=m[2]}return out};
async function get(base,token,path){const r=await fetch(base+path,{headers:headers(token),cache:'no-store',signal:AbortSignal.timeout(120000)});if(!r.ok)throw new Error(`Plex ${path} respondió ${r.status}`);return r.json()}

async function reviewIdentitiesSince(sql,token,baseUrl,reviewFrom){
 const base=await discoverPlexUrlCore(token,baseUrl),cutoff=new Date(reviewFrom);if(Number.isNaN(cutoff.getTime()))throw new Error('Fecha de revisión Plex inválida');const sections=list(await get(base,token,'/library/sections')).filter(s=>s.type==='movie'||s.type==='show'),candidates=[];
 for(const section of sections){const kind=section.type==='show'?'show':'movie',items=list(await get(base,token,`/library/sections/${section.key}/all?includeGuids=1&X-Plex-Container-Start=0&X-Plex-Container-Size=20000`)).filter(x=>x.type===kind);for(const i of items){const updated=i.updatedAt?new Date(Number(i.updatedAt)*1000):null;if(updated&&updated>=cutoff)candidates.push({ratingKey:String(i.ratingKey),updatedAt:updated.toISOString()})}}
 const keys=candidates.map(x=>x.ratingKey),beforeRows=keys.length?await sql`SELECT p.rating_key,p.plex_title,p.plex_year,p.item_type,x.external_id AS imdb,o.imdb_id AS manual_imdb FROM plex_items p LEFT JOIN plex_external_ids x ON x.rating_key=p.rating_key AND x.provider='imdb' LEFT JOIN plex_manual_overrides o ON o.rating_key=p.rating_key WHERE p.rating_key=ANY(${keys})`:[],before=new Map(beforeRows.map(r=>[String(r.rating_key),r])),observations=[];
 for(let pos=0;pos<candidates.length;pos+=8){const chunk=candidates.slice(pos,pos+8),details=await Promise.all(chunk.map(async c=>{const d=list(await get(base,token,`/library/metadata/${c.ratingKey}?includeGuids=1`))[0]||{};return{candidate:c,item:d,ids:gids(d)}}));for(const d of details){const old=before.get(d.candidate.ratingKey),storedImdb=old?.imdb||null,manualImdb=old?.manual_imdb||null,plexImdb=d.ids.imdb||null,manualProtected=Boolean(manualImdb),conflict=Boolean(manualProtected&&plexImdb&&manualImdb!==plexImdb),plexEmptyManual=Boolean(manualProtected&&!plexImdb),effectiveBefore=manualImdb||storedImdb||null,effectiveAfter=manualProtected?manualImdb:plexImdb,changed=Boolean(!manualProtected&&storedImdb&&plexImdb&&storedImdb!==plexImdb);observations.push({rating_key:d.candidate.ratingKey,plex_updated_at:d.candidate.updatedAt,imdb_before:effectiveBefore,imdb_after:effectiveAfter,plex_imdb:plexImdb,manual_imdb:manualImdb,manual_protected:manualProtected,manual_conflict:conflict,plex_empty_manual:plexEmptyManual,changed,imdb_removed:Boolean(old&&!manualProtected&&storedImdb&&!plexImdb),imdb_added:Boolean(old&&!storedImdb&&plexImdb&&!manualProtected),new_plex_item:Boolean(!old)});if(!old)continue;if(conflict){await sql`INSERT INTO admin_events(event_type,entity_type,entity_id,action,payload,created_at) VALUES('identity_conflict','plex_rating_key',${d.candidate.ratingKey},'manual_vs_plex',${JSON.stringify({manual_imdb:manualImdb,plex_imdb:plexImdb,plex_updated_at:d.candidate.updatedAt})}::jsonb,now())`;continue}if(plexEmptyManual||storedImdb===plexImdb)continue;await sql`DELETE FROM plex_external_ids WHERE rating_key=${d.candidate.ratingKey} AND provider IN('imdb','tmdb','tvdb')`;const rows=Object.entries(d.ids).map(([provider,external_id])=>({rating_key:d.candidate.ratingKey,provider,external_id}));if(rows.length)await sql`WITH x AS (SELECT * FROM jsonb_to_recordset(${JSON.stringify(rows)}::jsonb) AS t(rating_key text,provider text,external_id text)) INSERT INTO plex_external_ids(rating_key,provider,external_id) SELECT rating_key,provider,external_id FROM x ON CONFLICT DO NOTHING`}}
 const changes=observations.filter(x=>x.changed),oldImdbIds=[];for(const c of changes){await sql`UPDATE plex_catalog_status SET status='missing',rating_key=NULL,updated_at=now() WHERE imdb_id=${c.imdb_before} AND rating_key=${c.rating_key}`;if(c.imdb_before)oldImdbIds.push(c.imdb_before);const[existing]=await sql`SELECT imdb_id FROM movies WHERE imdb_id=${c.imdb_after} LIMIT 1`;if(existing)await sql`INSERT INTO catalog_lifecycle(imdb_id,lifecycle_state,previous_state,blocking_reason,state_changed_at,computed_at) VALUES(${c.imdb_after},'IDENTITY_PENDING',NULL,'Plex: IMDb corregido; reprocesado completo solicitado',now(),now()) ON CONFLICT(imdb_id) DO UPDATE SET previous_state=catalog_lifecycle.lifecycle_state,lifecycle_state='IDENTITY_PENDING',blocking_reason='Plex: IMDb corregido; reprocesado completo solicitado',state_changed_at=now(),computed_at=now()`}if(oldImdbIds.length)await recomputeLifecycleForIds(oldImdbIds);
 return{review_from:cutoff.toISOString(),reviewed:candidates.length,imdb_changed:changes.length,imdb_removed:observations.filter(x=>x.imdb_removed).length,imdb_added:observations.filter(x=>x.imdb_added).length,new_plex_items:observations.filter(x=>x.new_plex_item).length,manual_preserved:observations.filter(x=>x.plex_empty_manual).length,manual_conflicts:observations.filter(x=>x.manual_conflict).length,changes,old_lifecycle_recomputed:[...new Set(oldImdbIds)].length,conflicts:observations.filter(x=>x.manual_conflict)};
}

async function recomputePhysicalMovieChanges(sql){const rows=await sql`SELECT pcs.imdb_id FROM plex_catalog_status pcs JOIN movies m ON m.imdb_id=pcs.imdb_id AND m.type='Película' JOIN plex_items p ON p.rating_key=pcs.rating_key AND p.active AND p.item_type='movie' LEFT JOIN movie_file_validation mfv ON mfv.rating_key=p.rating_key WHERE pcs.status='in_plex' AND (mfv.rating_key IS NULL OR mfv.status<>'checked' OR mfv.source_fingerprint IS DISTINCT FROM (SELECT md5(string_agg(lower(COALESCE(pf.file_path,''))||'|'||COALESCE(pf.file_size_bytes::text,'')||'|'||COALESCE(pf.duration_ms::text,'')||'|'||COALESCE(pf.plex_part_id,''),',' ORDER BY pf.media_index,pf.part_index)) FROM plex_files pf WHERE pf.rating_key=p.rating_key AND COALESCE(pf.exists_on_server,true)<>false))`;const ids=[...new Set(rows.map(r=>r.imdb_id).filter(Boolean))];if(ids.length)await recomputeLifecycleForIds(ids);return ids}

export async function syncPlexFast({reviewFrom}={}){const token=process.env.PLEX_TOKEN;if(!token)throw new Error('PLEX_TOKEN no está configurado en Vercel');const baseUrl=process.env.PLEX_URL||process.env.PLEX_BASE_URL||'',sql=db(),started=Date.now();let cutoff=reviewFrom?new Date(reviewFrom):null;if(!cutoff||Number.isNaN(cutoff.getTime())){const[last]=await sql`SELECT started_at FROM pipeline_runs WHERE job_type='plex_fast_sync' AND status='success' AND finished_at IS NOT NULL ORDER BY finished_at DESC LIMIT 1`;cutoff=last?.started_at?new Date(last.started_at):new Date(Date.now()-24*3600*1000)}const identityReview=await reviewIdentitiesSince(sql,token,baseUrl,cutoff.toISOString()),result=await syncPlexFastCore({sql,token,baseUrl}),physicalPending=await recomputePhysicalMovieChanges(sql);return{...result,identityReview,physicalMovieChanges:{detected:physicalPending.length,recomputed:physicalPending.length,imdb_ids:physicalPending.slice(0,100)},identityChangeProbe:{trigger:'IMDB_ONLY',limit:null,detected:identityReview.imdb_changed,processed:identityReview.imdb_changed,deferred:0,changes:identityReview.changes,reviewed:identityReview.reviewed,review_from:identityReview.review_from,manual_preserved:identityReview.manual_preserved,manual_conflicts:identityReview.manual_conflicts,new_plex_items:identityReview.new_plex_items,old_lifecycle_recomputed:identityReview.old_lifecycle_recomputed,elapsed_ms:Date.now()-started}}}
