import 'server-only';
import {db} from './db';
import {startRun,finishRun,errorInfo} from './runlog';

const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\.[a-z0-9]{2,4}$/,'').replace(/\b(2160p|1080p|720p|576p|480p|4k|uhd|bluray|blu-ray|bdrip|brrip|webrip|web-dl|webdl|hdtv|dvdrip|x264|x265|h264|h265|hevc|av1|aac|dts|ac3|truehd|remux|hdr10|hdr|dolby|atmos|dual|multi|proper|repack)\b/g,' ').replace(/[^a-z0-9ñ]+/g,' ').replace(/\s+/g,' ').trim();
const yearIn=s=>{const m=String(s||'').match(/\b(19\d{2}|20\d{2})\b/);return m?Number(m[1]):null};
const filenameTitle=s=>norm(String(s||'').split('/').pop());
function qualityThreshold(height,codec){const c=String(codec||'').toLowerCase();const hevc=c.includes('hevc')||c.includes('265')||c.includes('av1');if((height||0)>=1000)return hevc?1400:2500;if((height||0)>=700)return hevc?900:1400;return hevc?600:700}
function severity(r){return r>=85?'critical':r>=65?'high':r>=40?'medium':'low'}

async function upsertFinding(sql,f){const [r]=await sql`INSERT INTO movie_quality_findings(finding_key,rating_key,imdb_id,finding_type,severity,risk_score,fingerprint,details,status,first_seen_at,last_seen_at) VALUES(${f.key},${f.rating_key},${f.imdb_id||null},${f.type},${severity(f.risk)},${Math.round(f.risk)},${f.fingerprint},${JSON.stringify(f.details)}::jsonb,'pending',now(),now()) ON CONFLICT(finding_key) DO UPDATE SET imdb_id=EXCLUDED.imdb_id,severity=EXCLUDED.severity,risk_score=EXCLUDED.risk_score,fingerprint=EXCLUDED.fingerprint,details=EXCLUDED.details,last_seen_at=now(),status=CASE WHEN movie_quality_findings.status='exception' AND movie_quality_findings.fingerprint=EXCLUDED.fingerprint THEN 'exception' ELSE 'pending' END,resolved_at=NULL RETURNING id,status`;return r}

export async function analyzeMovieQuality(){
  const sql=db(),run=await startRun('movie_quality_analysis','web',{stage:'load'});let qrun=null;
  try{
    [qrun]=await sql`INSERT INTO movie_quality_runs(pipeline_run_id,status,started_at) VALUES(${run.id},'running',now()) RETURNING id`;
    const rows=await sql`SELECT p.rating_key,p.plex_title,p.plex_year,p.fingerprint,x.external_id imdb_id,m.runtime catalog_runtime,pm.media_index,pm.duration_ms,pm.bitrate,pm.width,pm.height,pm.resolution,pm.video_codec,pm.audio_codec,pf.part_index,pf.file_path,pf.file_size_bytes,pf.duration_ms file_duration_ms FROM plex_items p LEFT JOIN LATERAL(SELECT external_id FROM plex_external_ids WHERE rating_key=p.rating_key AND provider='imdb' LIMIT 1)x ON true LEFT JOIN movies m ON m.imdb_id=x.external_id LEFT JOIN LATERAL(SELECT * FROM plex_media z WHERE z.rating_key=p.rating_key ORDER BY z.media_index LIMIT 1)pm ON true LEFT JOIN LATERAL(SELECT * FROM plex_files f WHERE f.rating_key=p.rating_key ORDER BY f.media_index,f.part_index LIMIT 1)pf ON true WHERE p.active AND p.item_type='movie'`;
    const seen=[],findings=[];let comparable=0;
    for(const r of rows){const plexMin=Number(r.file_duration_ms||r.duration_ms||0)/60000,cat=Number(r.catalog_runtime||0);if(cat>0&&plexMin>0){comparable++;const diff=Math.abs(plexMin-cat),pct=diff/cat*100;if(diff>10&&pct>15){const risk=Math.min(100,55+(pct-15)*1.7+(diff>25?10:0));findings.push({key:`duration:${r.rating_key}`,rating_key:r.rating_key,imdb_id:r.imdb_id,type:'duration',risk,fingerprint:r.fingerprint||`${r.file_path}:${r.file_size_bytes}`,details:{plex_minutes:Number(plexMin.toFixed(1)),catalog_minutes:cat,diff_minutes:Number(diff.toFixed(1)),diff_pct:Number(pct.toFixed(1))}})}}
      if(r.file_path){const f=filenameTitle(r.file_path),a=norm(r.plex_title),b=norm((await Promise.resolve(r.plex_title))),fy=yearIn(r.file_path),year=Number(r.plex_year||0),titleOk=(a&&f.includes(a))||(a&&a.includes(f));const yearOk=!fy||!year||Math.abs(fy-year)<=1;if(!titleOk&&!yearOk){findings.push({key:`filename:${r.rating_key}:${r.part_index||0}`,rating_key:r.rating_key,imdb_id:r.imdb_id,type:'filename',risk:78,fingerprint:r.fingerprint||`${r.file_path}:${r.file_size_bytes}`,details:{file:r.file_path,plex_title:r.plex_title,plex_year:r.plex_year,file_year:fy,normalized_file:f,normalized_title:a}})}}
      const br=Number(r.bitrate||0),thr=qualityThreshold(Number(r.height||0),r.video_codec);if(br>0&&br<thr){const ratio=br/thr,risk=Math.min(90,45+(1-ratio)*55);if(ratio<.78)findings.push({key:`quality:${r.rating_key}:${r.media_index||0}`,rating_key:r.rating_key,imdb_id:r.imdb_id,type:'quality',risk,fingerprint:r.fingerprint||`${r.file_path}:${r.file_size_bytes}`,details:{bitrate:br,threshold:thr,height:r.height,width:r.width,resolution:r.resolution,video_codec:r.video_codec,audio_codec:r.audio_codec,file_size_bytes:r.file_size_bytes}})}
    }
    const dups=await sql`SELECT x.external_id imdb_id,array_agg(DISTINCT p.rating_key) rating_keys,count(DISTINCT pm.plex_media_id)::int media_count,min(pm.duration_ms)::bigint min_duration,max(pm.duration_ms)::bigint max_duration FROM plex_items p JOIN plex_external_ids x ON x.rating_key=p.rating_key AND x.provider='imdb' JOIN plex_media pm ON pm.rating_key=p.rating_key WHERE p.active AND p.item_type='movie' GROUP BY x.external_id HAVING count(DISTINCT pm.plex_media_id)>1`;
    for(const d of dups){const min=Number(d.min_duration||0),max=Number(d.max_duration||0),pct=min?Math.abs(max-min)/min*100:0,risk=pct<=2?72:pct<=10?52:30;const rk=d.rating_keys?.[0];if(rk)findings.push({key:`duplicate:${d.imdb_id}`,rating_key:rk,imdb_id:d.imdb_id,type:'duplicate',risk,fingerprint:`${d.imdb_id}:${d.media_count}:${min}:${max}`,details:{rating_keys:d.rating_keys,media_count:d.media_count,duration_diff_pct:Number(pct.toFixed(1)),recommendation:pct<=2?'Comparar calidad y conservar la mejor copia':'Revisar manualmente: podría ser un montaje distinto'}})}
    for(const f of findings){await upsertFinding(sql,f);seen.push(f.key)}
    await sql`UPDATE movie_quality_findings SET status='resolved',resolved_at=now(),last_seen_at=now() WHERE status='pending' AND NOT(finding_key=ANY(${seen.length?seen:['__none__']}))`;
    const [stats]=await sql`SELECT count(*) FILTER(WHERE status='pending')::int pending,count(*) FILTER(WHERE status='exception')::int exceptions,count(*) FILTER(WHERE status='resolved')::int resolved FROM movie_quality_findings`;
    const byType=await sql`SELECT finding_type,count(*)::int total FROM movie_quality_findings WHERE status='pending' GROUP BY finding_type ORDER BY finding_type`;
    await sql`UPDATE movie_quality_runs SET status='success',finished_at=now(),scanned_count=${rows.length},comparable_duration_count=${comparable},findings_count=${findings.length},exceptions_count=${stats.exceptions||0},resolved_count=${stats.resolved||0},summary=${JSON.stringify({byType})}::jsonb WHERE id=${qrun.id}`;
    await finishRun(run.id,'success',{processed:rows.length,updated:findings.length,summary:{stage:'done',quality_run_id:qrun.id,comparable_duration:comparable,pending:stats.pending,by_type:byType}});
    return{ok:true,scanned:rows.length,comparable,findings:findings.length,pending:stats.pending,byType};
  }catch(e){if(qrun)await sql`UPDATE movie_quality_runs SET status='failed',finished_at=now(),error_count=1,summary=${JSON.stringify(errorInfo(e))}::jsonb WHERE id=${qrun.id}`;await finishRun(run.id,'failed',{errors:1,summary:{stage:'failed',error:errorInfo(e)}});throw e}
}

export async function setQualityAction(id,action,note=''){const sql=db();const [f]=await sql`SELECT id,fingerprint FROM movie_quality_findings WHERE id=${id}`;if(!f)throw new Error('Incidencia no encontrada');const status=action==='exception'?'exception':action==='waiting_sync'?'waiting_sync':'pending';await sql.transaction([sql`UPDATE movie_quality_findings SET status=${status},resolved_at=CASE WHEN ${status}='exception' THEN now() ELSE NULL END WHERE id=${id}`,sql`INSERT INTO movie_quality_actions(finding_id,action,note,fingerprint,created_at) VALUES(${id},${action},${note||null},${f.fingerprint},now())`]);}
