import 'server-only';
import {db} from './db';

function parse(filters={}){const q=String(filters.q||'').trim().toLowerCase(),type=String(filters.type||''),status=String(filters.status||''),genre=String(filters.genre||'');const y=Number.parseInt(filters.year,10);return{q,type,status,genre,year:Number.isFinite(y)?y:null}}
const movieType='Película';
const seriesTypes=['Serie','Miniserie'];

export async function getDashboard(){const sql=db();const [row,decades]=await Promise.all([sql`SELECT (SELECT count(*)::int FROM catalog_read_model) catalog_total,(SELECT count(*)::int FROM catalog_read_model WHERE effective_status='in_plex') catalog_in_plex,(SELECT count(*)::int FROM catalog_read_model WHERE effective_status='acquiring') catalog_acquiring,(SELECT count(*)::int FROM catalog_read_model WHERE effective_status NOT IN ('in_plex','acquiring') OR effective_status IS NULL) catalog_missing,(SELECT count(*)::int FROM catalog_exclusions) catalog_excluded,(SELECT count(*)::int FROM plex_review_tasks WHERE status='pending') movie_review_pending,(SELECT count(DISTINCT show_rating_key)::int FROM series_episode_effective_status WHERE effective_status<>'present') series_with_issues,(SELECT count(*)::int FROM series_episode_effective_status WHERE effective_status='missing_actionable') missing_episodes_actionable,(SELECT count(*)::int FROM series_episode_effective_status WHERE effective_status='availability_unknown') missing_episodes_unknown,(SELECT count(*)::int FROM plex_not_in_catalog) plex_not_in_catalog`,sql`SELECT (floor(year/10)*10)::int decade,count(*)::int total,count(*) FILTER(WHERE effective_status='in_plex')::int in_plex,count(*) FILTER(WHERE effective_status NOT IN ('in_plex','acquiring') OR effective_status IS NULL)::int missing FROM catalog_read_model WHERE year IS NOT NULL GROUP BY 1 ORDER BY 1`]);return{...row,decades}}

export async function getCatalog(filters={}){const sql=db(),{q,type,status,genre,year}=parse(filters);return sql`SELECT imdb_id,type,display_title,original_title,year,runtime,country,final_rating,imdb_rating,imdb_votes,fa_rating,fa_votes,tmdb_rating,tmdb_votes,genres,effective_status,plex_status,resolution,collection_name,poster_path FROM catalog_read_model WHERE (${q}='' OR lower(display_title) LIKE ${'%'+q+'%'} OR lower(COALESCE(original_title,'')) LIKE ${'%'+q+'%'}) AND (${type}='' OR (${type}='movie' AND type=${movieType}) OR (${type}='series' AND type=ANY(${seriesTypes}))) AND (${year}::int IS NULL OR year=${year}) AND (${genre}='' OR ${genre}=ANY(genres)) AND (${status}='' OR (${status}='in_plex' AND effective_status='in_plex') OR (${status}='acquiring' AND effective_status='acquiring') OR (${status}='missing' AND (effective_status NOT IN ('in_plex','acquiring') OR effective_status IS NULL))) ORDER BY final_rating DESC NULLS LAST,imdb_votes DESC NULLS LAST LIMIT 150`}
export async function getCatalogStats(filters={}){const sql=db(),{q,type,status,genre,year}=parse(filters);const[row]=await sql`SELECT count(*)::int total,count(*) FILTER(WHERE effective_status='in_plex')::int in_plex,count(*) FILTER(WHERE effective_status='acquiring')::int acquiring,count(*) FILTER(WHERE effective_status NOT IN ('in_plex','acquiring') OR effective_status IS NULL)::int missing FROM catalog_read_model WHERE (${q}='' OR lower(display_title) LIKE ${'%'+q+'%'} OR lower(COALESCE(original_title,'')) LIKE ${'%'+q+'%'}) AND (${type}='' OR (${type}='movie' AND type=${movieType}) OR (${type}='series' AND type=ANY(${seriesTypes}))) AND (${year}::int IS NULL OR year=${year}) AND (${genre}='' OR ${genre}=ANY(genres)) AND (${status}='' OR (${status}='in_plex' AND effective_status='in_plex') OR (${status}='acquiring' AND effective_status='acquiring') OR (${status}='missing' AND (effective_status NOT IN ('in_plex','acquiring') OR effective_status IS NULL)))`;return row}
export async function getCatalogFilters(){const sql=db();const[genres,years]=await Promise.all([sql`SELECT DISTINCT unnest(genres) value FROM catalog_read_model WHERE genres IS NOT NULL ORDER BY value`,sql`SELECT DISTINCT year value FROM catalog_read_model WHERE year IS NOT NULL ORDER BY year DESC`]);return{genres:genres.map(x=>x.value),years:years.map(x=>x.value)}}
export async function getCatalogItem(imdbId){const sql=db();const[item]=await sql`SELECT c.*,m.overview,m.tagline,m.certification,m.original_language,m.release_date,m.budget,m.revenue,m.trailer_key,m.trailer_site FROM catalog_read_model c LEFT JOIN movie_metadata m ON m.imdb_id=c.imdb_id WHERE c.imdb_id=${imdbId} LIMIT 1`;if(!item)return null;const credits=await sql`SELECT p.tmdb_person_id,p.name,p.profile_path,c.credit_type,c.character_name,c.job,c.credit_order FROM movie_credits c JOIN people p ON p.tmdb_person_id=c.tmdb_person_id WHERE c.imdb_id=${imdbId} ORDER BY CASE WHEN c.credit_type='cast' THEN 0 ELSE 1 END,c.credit_order NULLS LAST LIMIT 36`;return{...item,credits}}
export async function getPerson(id){const sql=db();const[person]=await sql`SELECT tmdb_person_id,name,profile_path FROM people WHERE tmdb_person_id=${id} LIMIT 1`;if(!person)return null;const titles=await sql`SELECT c.imdb_id,c.display_title,c.year,c.poster_path,c.final_rating,c.effective_status,mc.character_name,mc.job FROM movie_credits mc JOIN catalog_read_model c ON c.imdb_id=mc.imdb_id WHERE mc.tmdb_person_id=${id} ORDER BY c.year DESC NULLS LAST,c.final_rating DESC NULLS LAST`;return{...person,titles}}
export async function getExcluded(){const sql=db();return sql`SELECT m.imdb_id,COALESCE(m.title_es,m.title,m.original_title) display_title,m.year,m.type,m.poster_path,ce.reason,ce.created_at FROM catalog_exclusions ce JOIN movies m USING(imdb_id) ORDER BY ce.created_at DESC LIMIT 300`}

export async function getPlexSummary(){const sql=db();const[row]=await sql`SELECT count(*) FILTER(WHERE active AND item_type='movie')::int movies,count(*) FILTER(WHERE active AND item_type='show')::int shows,(SELECT count(DISTINCT rating_key)::int FROM plex_review_tasks WHERE status='pending') review_items,(SELECT max(finished_at) FROM plex_sync_runs WHERE status='success') last_sync FROM plex_items`;return row}
export async function getPlexLibrary(filters={}){const sql=db();const q=String(filters.q||'').trim().toLowerCase(),type=String(filters.type||''),mode=String(filters.mode||'missing');const y=Number.parseInt(filters.year,10),year=Number.isFinite(y)?y:null;if(mode==='owned')return sql`SELECT rating_key,plex_title,plex_year,item_type,added_at,watched,NULL::text imdb_id,NULL::text effective_status,NULL::text resolution FROM plex_items WHERE active AND item_type IN ('movie','show') AND (${q}='' OR lower(COALESCE(plex_title,'')) LIKE ${'%'+q+'%'}) AND (${type}='' OR (${type}='movie' AND item_type='movie') OR (${type}='series' AND item_type='show')) AND (${year}::int IS NULL OR plex_year=${year}) ORDER BY added_at DESC NULLS LAST LIMIT 200`;return sql`SELECT rating_key,display_title AS plex_title,year AS plex_year,CASE WHEN type=${movieType} THEN 'movie' ELSE 'show' END item_type,NULL::timestamptz added_at,NULL::boolean watched,imdb_id,effective_status,resolution,final_rating,imdb_votes FROM catalog_read_model WHERE effective_status<>'in_plex' AND (${q}='' OR lower(display_title) LIKE ${'%'+q+'%'}) AND (${type}='' OR (${type}='movie' AND type=${movieType}) OR (${type}='series' AND type=ANY(${seriesTypes}))) AND (${year}::int IS NULL OR year=${year}) ORDER BY final_rating DESC NULLS LAST LIMIT 200`}
export async function getPlexOutsideCatalog(filters={}){const sql=db();const q=String(filters.q||'').trim().toLowerCase();return sql`SELECT rating_key,plex_title,plex_year,added_at,imdb_id,catalog_state FROM plex_not_in_catalog WHERE (${q}='' OR lower(COALESCE(plex_title,'')) LIKE ${'%'+q+'%'}) ORDER BY added_at DESC NULLS LAST LIMIT 150`}

export async function getMovieQuality(filters={}){const sql=db();const q=String(filters.q||'').trim().toLowerCase(),task=String(filters.task||''),status=String(filters.status||'pending');return sql`SELECT t.id,t.rating_key,t.task_type,t.reasons,t.risk_score,t.status,t.created_at,t.resolution_note,p.plex_title,p.plex_year,p.resolution,p.duration_ms,p.file_size,p.video_codec,p.audio_codec FROM plex_review_tasks t JOIN plex_items p ON p.rating_key=t.rating_key WHERE (${status}='' OR t.status=${status}) AND (${task}='' OR t.task_type=${task}) AND (${q}='' OR lower(COALESCE(p.plex_title,'')) LIKE ${'%'+q+'%'}) ORDER BY CASE WHEN t.status='pending' THEN 0 ELSE 1 END,t.risk_score DESC,t.created_at DESC LIMIT 150`}
export async function getMovieQualityTypes(){const sql=db();return sql`SELECT DISTINCT task_type FROM plex_review_tasks ORDER BY task_type`}
export async function getSeriesQuality(filters={}){const sql=db();const q=String(filters.q||'').trim().toLowerCase(),state=String(filters.state||'issues');return sql`SELECT r.show_rating_key,r.title,r.year,r.official_seasons,r.official_episodes,c.poster_path,count(*) FILTER(WHERE e.effective_status='present')::int present,count(*) FILTER(WHERE e.effective_status='missing_actionable')::int actionable_missing,count(*) FILTER(WHERE e.effective_status='not_yet_available')::int not_yet_available,count(*) FILTER(WHERE e.effective_status='availability_unknown')::int availability_unknown,count(*) FILTER(WHERE e.effective_status='exception')::int exceptions,count(*)::int diagnosed FROM series_reference r JOIN series_episode_effective_status e ON e.show_rating_key=r.show_rating_key LEFT JOIN catalog_read_model c ON c.imdb_id=r.imdb_id WHERE (${q}='' OR lower(r.title) LIKE ${'%'+q+'%'}) GROUP BY r.show_rating_key,r.title,r.year,r.official_seasons,r.official_episodes,c.poster_path HAVING (${state}='all') OR (${state}='actionable' AND count(*) FILTER(WHERE e.effective_status='missing_actionable')>0) OR (${state}='unknown' AND count(*) FILTER(WHERE e.effective_status='availability_unknown')>0) OR (${state}='uptodate' AND count(*) FILTER(WHERE e.effective_status IN ('missing_actionable','availability_unknown'))=0) OR (${state}='issues' AND count(*) FILTER(WHERE e.effective_status<>'present')>0) ORDER BY actionable_missing DESC,availability_unknown DESC,r.title LIMIT 200`}
export async function getSeriesDetail(k){const sql=db();const[s]=await sql`SELECT show_rating_key,tmdb_id,imdb_id,tvdb_id,title,original_title,year,official_seasons,official_episodes,avg_runtime_minutes,reference_source,refreshed_at FROM series_reference WHERE show_rating_key=${k} LIMIT 1`;if(!s)return null;const episodes=await sql`SELECT e.*,r.overview FROM series_episode_effective_status e LEFT JOIN series_reference_episodes r ON r.show_rating_key=e.show_rating_key AND r.season_number=e.season_number AND r.episode_number=e.episode_number WHERE e.show_rating_key=${k} ORDER BY e.season_number,e.episode_number`;return{...s,episodes}}

export async function getSagas(filters={}){const sql=db();const q=String(filters.q||'').trim().toLowerCase(),state=String(filters.state||'');return sql`SELECT collection_name,count(*)::int total_selected,count(*) FILTER(WHERE effective_status='in_plex')::int in_plex,count(*) FILTER(WHERE effective_status='acquiring')::int acquiring,count(*) FILTER(WHERE effective_status NOT IN ('in_plex','acquiring') OR effective_status IS NULL)::int missing,max(collection_poster_path) collection_poster_path FROM catalog_read_model WHERE collection_name IS NOT NULL AND (${q}='' OR lower(collection_name) LIKE ${'%'+q+'%'}) GROUP BY collection_name HAVING count(*)>=2 AND (${state}='' OR (${state}='complete' AND count(*) FILTER(WHERE effective_status NOT IN ('in_plex','acquiring') OR effective_status IS NULL)=0) OR (${state}='incomplete' AND count(*) FILTER(WHERE effective_status NOT IN ('in_plex','acquiring') OR effective_status IS NULL)>0)) ORDER BY missing DESC,total_selected DESC,collection_name LIMIT 150`}
export async function getSagaDetail(name){const sql=db();return sql`SELECT imdb_id,display_title,original_title,year,final_rating,effective_status,resolution,poster_path FROM catalog_read_model WHERE collection_name=${name} ORDER BY year NULLS LAST,display_title`}
export async function getAdminOverview(){const sql=db();const[counts,pipeline,syncs,jobs]=await Promise.all([sql`SELECT (SELECT count(*)::int FROM movies) movies,(SELECT count(*)::int FROM plex_items WHERE active) plex_active,(SELECT count(*)::int FROM series_reference) series,(SELECT count(*)::int FROM series_episode_availability WHERE country_code='ES') availability_es`,sql`SELECT id,job_type,source,status,started_at,finished_at,processed_count,error_count FROM pipeline_runs ORDER BY created_at DESC LIMIT 20`,sql`SELECT id,started_at,finished_at,sync_mode,library_count,new_count,changed_count,missing_count,error_count,status FROM plex_sync_runs ORDER BY started_at DESC LIMIT 10`,sql`SELECT id,job_type,status,requested_at,finished_at,error FROM admin_job_requests ORDER BY requested_at DESC LIMIT 15`]);return{counts:counts[0],pipeline,syncs,jobs}}
