import 'server-only';
import {db} from './db';
import {ensureImdbRating} from './imdb-rating-on-demand';
import {audit} from './runlog';

const omdbKey=()=>process.env.OMDB_API_KEY||process.env.OMDB_APIKEY||'';
const faHeaders={'User-Agent':'Mozilla/5.0 (compatible; PikoFilm/1.0; personal non-commercial)','Accept-Language':'es-ES,es;q=0.9'};
async function step(imdbId,source,fn){const started=Date.now();await audit('pikoscore','title',imdbId,'ratings_source_started',{source});try{const data=await fn();await audit('pikoscore','title',imdbId,'ratings_source_completed',{source,duration_ms:Date.now()-started,...data});return{source,ok:true,...data};}catch(e){const error=e?.message||String(e);await audit('pikoscore','title',imdbId,'ratings_source_failed',{source,error,duration_ms:Date.now()-started});return{source,ok:false,error};}}

async function refreshTmdb(imdbId){const sql=db();const[m]=await sql`SELECT tmdb_id,type FROM movies WHERE imdb_id=${imdbId}`;if(!m?.tmdb_id)throw new Error('Falta TMDb ID');const token=process.env.TMDB_API_TOKEN;if(!token)throw new Error('Falta TMDB_API_TOKEN');const media=m.type==='Serie'||m.type==='Miniserie'?'tv':'movie';const r=await fetch(`https://api.themoviedb.org/3/${media}/${m.tmdb_id}?language=es-ES`,{headers:{Authorization:`Bearer ${token}`,Accept:'application/json'},cache:'no-store'});if(!r.ok)throw new Error(`TMDb HTTP ${r.status}`);const d=await r.json(),rating=Number(d.vote_average)||null,votes=Number(d.vote_count)||null;if(!(rating>0&&votes>0))throw new Error('TMDb no devolvió nota/votos válidos');await sql`UPDATE movies SET tmdb_rating=${rating},tmdb_votes=${votes},synced_at=now() WHERE imdb_id=${imdbId}`;return{rating,votes};}

async function refreshOmdb(imdbId){const sql=db(),key=omdbKey();if(!key)throw new Error('Falta OMDB_API_KEY');const r=await fetch(`https://www.omdbapi.com/?apikey=${encodeURIComponent(key)}&i=${encodeURIComponent(imdbId)}`,{cache:'no-store'});if(!r.ok)throw new Error(`OMDb HTTP ${r.status}`);const j=await r.json();if(j.Response==='False')throw new Error(j.Error||'OMDb no encontró el título');const rating=j.imdbRating&&j.imdbRating!=='N/A'?Number(j.imdbRating):null,votes=j.imdbVotes&&j.imdbVotes!=='N/A'?Number(String(j.imdbVotes).replace(/[^0-9]/g,'')):null,rt=Number(String((j.Ratings||[]).find(x=>x.Source==='Rotten Tomatoes')?.Value||'').replace('%',''))||null,meta=Number(j.Metascore)||null;if(!(rating>0&&votes>0))throw new Error('OMDb no devolvió IMDb nota/votos válidos');await sql`UPDATE movies SET imdb_rating=${rating},imdb_votes=${votes},rotten_tomatoes_score=COALESCE(${rt},rotten_tomatoes_score),metacritic_score=COALESCE(${meta},metacritic_score),synced_at=now() WHERE imdb_id=${imdbId}`;return{rating,votes,rotten_tomatoes:rt,metacritic:meta};}

async function refreshImdbFallback(imdbId){const sql=db();const before=(await sql`SELECT imdb_rating,imdb_votes FROM movies WHERE imdb_id=${imdbId}`)[0];const r=await ensureImdbRating(imdbId,{timeoutMs:20000});const after=(await sql`SELECT imdb_rating,imdb_votes FROM movies WHERE imdb_id=${imdbId}`)[0];if(!(Number(after?.imdb_rating)>0&&Number(after?.imdb_votes)>0))throw new Error('IMDb fallback no devolvió nota/votos válidos');return{rating:Number(after.imdb_rating),votes:Number(after.imdb_votes),changed:Boolean(r||Number(before?.imdb_votes)!==Number(after?.imdb_votes)||Number(before?.imdb_rating)!==Number(after?.imdb_rating))};}

function parseFa(html){const out={};for(const m of html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const d=JSON.parse(m[1].trim()),arr=Array.isArray(d)?d:[d];for(const n of arr){const a=n?.aggregateRating;if(a?.ratingValue!=null)out.rating=Number(String(a.ratingValue).replace(',','.'));if(a?.ratingCount!=null)out.votes=Number(String(a.ratingCount).replace(/[^0-9]/g,''));}}catch{}}return out;}
async function refreshFa(imdbId){const sql=db();const[m]=await sql`SELECT fa_id FROM movies WHERE imdb_id=${imdbId}`;if(!m?.fa_id)throw new Error('Falta FilmAffinity ID');const r=await fetch(`https://www.filmaffinity.com/es/film${m.fa_id}.html`,{headers:faHeaders,cache:'no-store'});if(!r.ok)throw new Error(`FilmAffinity HTTP ${r.status}`);const p=parseFa(await r.text());if(!(Number(p.rating)>0&&Number(p.votes)>0))throw new Error('FilmAffinity no devolvió nota/votos válidos');await sql`UPDATE movies SET fa_rating=${p.rating},fa_votes=${p.votes},synced_at=now() WHERE imdb_id=${imdbId}`;return{rating:p.rating,votes:p.votes};}

export async function refreshRatingsForTitle(imdbId){if(!/^tt\d+$/.test(String(imdbId||'')))throw new Error('IMDb ID inválido');const sql=db();const[m]=await sql`SELECT imdb_id FROM movies WHERE imdb_id=${imdbId}`;if(!m)throw new Error('Título no encontrado');await audit('pikoscore','title',imdbId,'ratings_refresh_started',{});const tmdb=await step(imdbId,'TMDb',()=>refreshTmdb(imdbId)),omdb=await step(imdbId,'OMDb',()=>refreshOmdb(imdbId));let imdbFallback=null;if(!omdb.ok)imdbFallback=await step(imdbId,'IMDb fallback',()=>refreshImdbFallback(imdbId));const fa=await step(imdbId,'FilmAffinity',()=>refreshFa(imdbId));const imdbOk=omdb.ok||Boolean(imdbFallback?.ok),verified=Boolean(tmdb.ok&&imdbOk&&fa.ok);if(verified)await sql`UPDATE movies SET ratings_refreshed_at=now(),synced_at=now() WHERE imdb_id=${imdbId}`;await audit('pikoscore','title',imdbId,'ratings_refresh_completed',{verified,results:[tmdb,omdb,...(imdbFallback?[imdbFallback]:[]),fa]});return{verified,results:[tmdb,omdb,...(imdbFallback?[imdbFallback]:[]),fa]};}
