import 'server-only';
import {db} from './db';
import {startRun,finishRun,errorInfo} from './runlog';
const api='https://api.themoviedb.org/3';
async function tmdb(path){const token=process.env.TMDB_API_TOKEN;if(!token)throw new Error('TMDB_API_TOKEN no está configurado');const r=await fetch(`${api}${path}`,{headers:{Authorization:`Bearer ${token}`,Accept:'application/json'},cache:'no-store'});if(!r.ok)throw new Error(`TMDb ${r.status}: ${path}`);return r.json()}
async function pool(items,n,fn){let i=0;const out=[];await Promise.all(Array.from({length:Math.min(n,items.length)},async()=>{while(i<items.length){const x=items[i++];try{out.push(await fn(x))}catch(e){out.push({error:e,item:x})}}}));return out}

export async function refreshSagas({limit=120}={}){const sql=db(),run=await startRun('saga_refresh','web',{stage:'select'});try{
  const ids=await sql`SELECT DISTINCT mc.tmdb_collection_id FROM movie_collections mc LEFT JOIN saga_collections sc ON sc.tmdb_collection_id=mc.tmdb_collection_id WHERE mc.tmdb_collection_id IS NOT NULL AND (sc.tmdb_collection_id IS NULL OR sc.refreshed_at<now()-interval '30 days') ORDER BY mc.tmdb_collection_id LIMIT ${limit}`;
  let added=0,updated=0,members=0,errors=0;
  const results=await pool(ids,6,async row=>{const d=await tmdb(`/collection/${row.tmdb_collection_id}?language=es-ES`),parts=[...(d.parts||[])].sort((a,b)=>String(a.release_date||'9999').localeCompare(String(b.release_date||'9999')));const exists=await sql`SELECT 1 FROM saga_collections WHERE tmdb_collection_id=${row.tmdb_collection_id}`;if(exists.length)updated++;else added++;
    await sql`INSERT INTO saga_collections(tmdb_collection_id,name,poster_path,backdrop_path,member_count,refreshed_at) VALUES(${row.tmdb_collection_id},${d.name||'Colección'},${d.poster_path||null},${d.backdrop_path||null},${parts.length},now()) ON CONFLICT(tmdb_collection_id) DO UPDATE SET name=EXCLUDED.name,poster_path=EXCLUDED.poster_path,backdrop_path=EXCLUDED.backdrop_path,member_count=EXCLUDED.member_count,refreshed_at=now()`;
    const ops=[sql`DELETE FROM saga_collection_members WHERE tmdb_collection_id=${row.tmdb_collection_id}`];let pos=0;for(const p of parts){pos++;members++;const [m]=await sql`SELECT imdb_id FROM movies WHERE tmdb_id=${String(p.id)} LIMIT 1`;ops.push(sql`INSERT INTO saga_collection_members(tmdb_collection_id,tmdb_movie_id,imdb_id,title,original_title,year,poster_path,position,updated_at) VALUES(${row.tmdb_collection_id},${String(p.id)},${m?.imdb_id||null},${p.title||p.name||null},${p.original_title||p.original_name||null},${Number(String(p.release_date||'').slice(0,4))||null},${p.poster_path||null},${pos},now())`)}await sql.transaction(ops);return{ok:true}});
  errors=results.filter(x=>x?.error).length;const [stats]=await sql`SELECT count(*) FILTER(WHERE owned>0 AND missing>0)::int incomplete,count(*) FILTER(WHERE missing=1 AND owned>0)::int one_missing,count(*) FILTER(WHERE missing=0 AND total>0)::int complete FROM (SELECT sc.tmdb_collection_id,count(sm.*)::int total,count(sm.*) FILTER(WHERE c.effective_status='in_plex')::int owned,count(sm.*) FILTER(WHERE c.effective_status IS DISTINCT FROM 'in_plex')::int missing FROM saga_collections sc JOIN saga_collection_members sm USING(tmdb_collection_id) LEFT JOIN catalog_read_model c ON c.imdb_id=sm.imdb_id GROUP BY sc.tmdb_collection_id)x`;
  await finishRun(run.id,'success',{processed:ids.length,added,updated,errors,summary:{stage:'done',collections_refreshed:ids.length,members,errors,...stats}});return{collections:ids.length,members,errors,...stats};
}catch(e){await finishRun(run.id,'failed',{errors:1,summary:{stage:'failed',error:errorInfo(e)}});throw e}}
