import 'server-only';
import {db} from './db';
import {startProcessRun,addProcessEvent,finishProcessRun} from './process-runtime';
import {getActiveBatch,getLatestBatch} from './batch-engine';
const CONFIG={
 'PROC-SER-003':{pool:'api',concurrency:2,trigger:'calidad_series_batch_tmdb',operation:'batch_refresh_series_reference'},
 'PROC-SER-004':{pool:'api',concurrency:2,trigger:'calidad_series_batch_es',operation:'batch_confirm_es_availability'}
};
export async function selectSer003BatchEligible(sql=db()){const rows=await sql`SELECT DISTINCT r.show_rating_key entity_id FROM series_reference r JOIN identity_validation iv ON iv.imdb_id=r.imdb_id AND iv.validation_status='valid' LEFT JOIN catalog_exclusions ex ON ex.imdb_id=r.imdb_id WHERE ex.imdb_id IS NULL AND r.tmdb_id IS NOT NULL AND (r.refreshed_at IS NULL OR r.next_check_at IS NULL OR r.next_check_at<=now() OR r.plex_invalidated_at IS NOT NULL) ORDER BY r.show_rating_key`;return rows.map(r=>String(r.entity_id))}
export async function selectSer004BatchEligible(sql=db()){const rows=await sql`SELECT DISTINCT e.show_rating_key entity_id FROM series_episode_effective_status e JOIN series_reference r ON r.show_rating_key=e.show_rating_key LEFT JOIN series_season_availability a ON a.show_rating_key=e.show_rating_key AND a.season_number=e.season_number AND a.country_code='ES' LEFT JOIN catalog_exclusions ex ON ex.imdb_id=r.imdb_id WHERE ex.imdb_id IS NULL AND r.tmdb_id IS NOT NULL AND e.effective_status='availability_unknown' AND e.season_number>0 AND (a.checked_at IS NULL OR a.checked_at<=now()-interval '14 days') ORDER BY e.show_rating_key`;return rows.map(r=>String(r.entity_id))}
const selector=(process,sql)=>process==='PROC-SER-003'?selectSer003BatchEligible(sql):selectSer004BatchEligible(sql);
export async function getSeriesBatchState(process){const sql=db(),ids=await selector(process,sql),[active,latest,[engine]]=await Promise.all([getActiveBatch(process,sql),getLatestBatch(process,sql),sql`SELECT desired_state,pause_reason,changed_at FROM batch_engine_control WHERE singleton_id=1`]);return{eligibleCount:ids.length,active,latest,engine:engine||{desired_state:'running'}}}
export async function startSeriesBatch(process,{limit=null}={}){const cfg=CONFIG[process];if(!cfg)throw new Error('Proceso Batch de Series no soportado');const sql=db(),active=await getActiveBatch(process,sql);if(active)return{run:active,reused:true,eligibleCount:Number(active.items_pending||0)};let ids=await selector(process,sql);if(limit!=null)ids=ids.slice(0,Math.max(1,Math.min(Number(limit)||1,10000)));if(!ids.length)return{run:null,reused:false,empty:true,eligibleCount:0};const correlationKey=`${process}:batch:${Date.now()}`,started=await startProcessRun({processCode:process,runKind:'batch',triggerSource:cfg.trigger,executor:'railway_batch_api',entityType:'series_set',entityId:process,correlationKey,idempotencyKey:correlationKey,context:{surface:'/calidad/series',operation:cfg.operation,worker_pool:cfg.pool,requested_concurrency:cfg.concurrency}}),runId=started.run.run_id;try{await sql`INSERT INTO batch_run_control(run_id,process_code,worker_pool,desired_state,requested_concurrency) VALUES(${runId}::uuid,${process},${cfg.pool},'running',${cfg.concurrency})`;await sql`INSERT INTO batch_run_items(batch_run_id,entity_type,entity_id,position,status) SELECT ${runId}::uuid,'series',x.entity_id,(x.ord-1)::int,'queued' FROM unnest(${ids}::text[]) WITH ORDINALITY AS x(entity_id,ord)`;await sql`UPDATE process_runs SET items_total=${ids.length},items_processed=0,items_succeeded=0,items_failed=0,items_pending=${ids.length},updated_at=now() WHERE run_id=${runId}::uuid`;await addProcessEvent(runId,{eventType:'batch_queued',message:`Batch ${process} preparado`,data:{items_total:ids.length,worker_pool:cfg.pool,requested_concurrency:cfg.concurrency}});return{run:await getActiveBatch(process,sql),reused:false,eligibleCount:ids.length}}catch(error){await finishProcessRun(runId,{technicalStatus:'failed',message:`No se pudo preparar ${process}`}).catch(()=>{});throw error}}
