import 'server-only';
import {db} from './db';
import {createBatchRun,getBatchRunSummary} from './batch-engine';
const SER004_RECHECK_DAYS=14;
const CFG={
 'PROC-SER-002':{pool:'plex',concurrency:1,label:'SER-002 · Refrescar detalle Plex',selector:selectSer002BatchEligible},
 'PROC-SER-003':{pool:'api',concurrency:2,label:'SER-003 · Actualizar referencia TMDb',selector:selectSer003BatchEligible},
 'PROC-SER-004':{pool:'api',concurrency:2,label:'SER-004 · Comprobar disponibilidad España',selector:selectSer004BatchEligible},
};
const normLimit=v=>{const n=Number(v);return Number.isInteger(n)&&n>0?Math.min(n,5000):null};
export async function selectSer002BatchEligible({limit=null}={}){const sql=db(),lim=normLimit(limit);const rows=await sql`SELECT r.show_rating_key entity_id FROM series_reference r JOIN plex_items p ON p.rating_key=r.show_rating_key AND p.item_type='show' AND p.active WHERE r.show_rating_key IS NOT NULL AND (r.plex_detail_refreshed_at IS NULL OR r.plex_invalidated_at IS NOT NULL) ORDER BY COALESCE(r.plex_invalidated_at,'1970-01-01'::timestamptz) DESC,r.show_rating_key ASC ${lim?sql`LIMIT ${lim}`:sql``}`;return rows.map(x=>String(x.entity_id))}
export async function selectSer003BatchEligible({limit=null}={}){const sql=db(),lim=normLimit(limit);const rows=await sql`SELECT r.show_rating_key entity_id FROM series_reference r JOIN plex_items p ON p.rating_key=r.show_rating_key AND p.item_type='show' AND p.active WHERE r.show_rating_key IS NOT NULL AND (r.reference_refreshed_at IS NULL OR r.next_check_at IS NULL OR r.next_check_at<=now()) ORDER BY COALESCE(r.next_check_at,'1970-01-01'::timestamptz) ASC,r.show_rating_key ASC ${lim?sql`LIMIT ${lim}`:sql``}`;return rows.map(x=>String(x.entity_id))}
export async function selectSer004BatchEligible({limit=null}={}){const sql=db(),lim=normLimit(limit);const rows=await sql`SELECT DISTINCT e.show_rating_key entity_id FROM series_episode_effective_status e LEFT JOIN series_season_availability a ON a.show_rating_key=e.show_rating_key AND a.season_number=e.season_number WHERE e.effective_status='availability_unknown' AND e.season_number>0 AND (a.checked_at IS NULL OR a.checked_at<=now()-(${SER004_RECHECK_DAYS} * interval '1 day')) ORDER BY e.show_rating_key ASC ${lim?sql`LIMIT ${lim}`:sql``}`;return rows.map(x=>String(x.entity_id))}
export async function startSeriesBatch(processCode,{limit=null}={}){const cfg=CFG[processCode];if(!cfg)throw new Error(`Batch Series no soportado: ${processCode}`);const sql=db();const active=await sql`SELECT run_id FROM batch_runs WHERE process_code=${processCode} AND status IN ('queued','running','paused','cancelling') ORDER BY created_at DESC LIMIT 1`;if(active[0])return{reused:true,runId:active[0].run_id,eligibleCount:0};const ids=await cfg.selector({limit});if(!ids.length)return{empty:true,runId:null,eligibleCount:0};const run=await createBatchRun({processCode,runKind:'batch',triggerSource:'calidad_series_batch',executor:'railway',pool:cfg.pool,requestedConcurrency:cfg.concurrency,entityType:'series',entityIds:ids,context:{surface:'/calidad/series',label:cfg.label,selection_limit:normLimit(limit),selection_count:ids.length}});return{...run,eligibleCount:ids.length}}
export async function getSeriesBatchState(processCode){const cfg=CFG[processCode];if(!cfg)throw new Error(`Batch Series no soportado: ${processCode}`);const sql=db();const [eligible,active,latest]=await Promise.all([cfg.selector({}),sql`SELECT * FROM batch_runs WHERE process_code=${processCode} AND status IN ('queued','running','paused','cancelling') ORDER BY created_at DESC LIMIT 1`,sql`SELECT * FROM batch_runs WHERE process_code=${processCode} ORDER BY created_at DESC LIMIT 1`]);const run=active[0]||latest[0]||null;return{processCode,label:cfg.label,pool:cfg.pool,concurrency:cfg.concurrency,eligibleCount:eligible.length,active:active[0]||null,latest:latest[0]||null,summary:run?await getBatchRunSummary(run.run_id):null,engine:null}}
