import 'server-only';
import {db} from './db';
import {startProcessRun,addProcessEvent,finishProcessRun} from './process-runtime';
import {getActiveBatch,getLatestBatch} from './batch-engine';
import {SER004_RECHECK_DAYS} from './series-quality-domain.mjs';
const CONFIG={
 'PROC-SER-002':{pool:'plex',concurrency:1,trigger:'calidad_series_batch_plex',operation:'batch_sync_plex_series_detail'},
 'PROC-SER-003':{pool:'api',concurrency:2,trigger:'calidad_series_batch_tmdb',operation:'batch_refresh_series_reference'},
 'PROC-SER-004':{pool:'api',concurrency:2,trigger:'calidad_series_batch_es',operation:'batch_confirm_es_availability'}
};
export async function selectSer002BatchEligible(sql=db()){const rows=await sql`SELECT DISTINCT r.show_rating_key entity_id FROM series_reference r JOIN plex_items p ON p.rating_key=r.show_rating_key AND p.item_type='show' AND p.active LEFT JOIN catalog_exclusions ex ON ex.imdb_id=r.imdb_id WHERE ex.imdb_id IS NULL AND r.show_rating_key IS NOT NULL AND (r.plex_detail_refreshed_at IS NULL OR r.plex_invalidated_at IS NOT NULL) ORDER BY r.show_rating_key`;return rows.map(r=>String(r.entity_id))}
export async function selectSer003BatchEligible(sql=db()){const rows=await sql`SELECT DISTINCT r.show_rating_key entity_id FROM series_reference r JOIN identity_validation iv ON iv.imdb_id=r.imdb_id AND iv.validation_status='valid' LEFT JOIN catalog_exclusions ex ON ex.imdb_id=r.imdb_id WHERE ex.imdb_id IS NULL AND r.tmdb_id IS NOT NULL AND (r.refreshed_at IS NULL OR r.next_check_at IS NULL OR r.next_check_at<=now() OR r.plex_invalidated_at IS NOT NULL) ORDER BY r.show_rating_key`;return rows.map(r=>String(r.entity_id))}
export async function selectSer004BatchEligible(sql=db()){const rows=await sql`SELECT DISTINCT e.show_rating_key entity_id FROM series_episode_effective_status e JOIN series_reference r ON r.show_rating_key=e.show_rating_key LEFT JOIN series_season_availability a ON a.show_rating_key=e.show_rating_key AND a.season_number=e.season_number AND a.country_code='ES' LEFT JOIN catalog_exclusions ex ON ex.imdb_id=r.imdb_id WHERE ex.imdb_id IS NULL AND r.tmdb_id IS NOT NULL AND e.effective_status='availability_unknown' AND e.season_number>0 AND (a.checked_at IS NULL OR a.checked_at<=now()-(${SER004_RECHECK_DAYS} * interval '1 day')) ORDER BY e.show_rating_key`;return rows.map(r=>String(r.entity_id))}
const selector=(process,sql)=>process==='PROC-SER-002'?selectSer002BatchEligible(sql):process==='PROC-SER-003'?selectSer003BatchEligible(sql):selectSer004BatchEligible(sql);
const normalizeEntityIds=ids=>[...new Set((Array.isArray(ids)?ids:[]).map(x=>String(x||'').trim()).filter(Boolean))];
async function selectExplicitSer002(sql,ids){const requested=normalizeEntityIds(ids);if(!requested.length)throw new Error('Serie Plex inválida');const rows=await sql`SELECT DISTINCT r.show_rating_key entity_id FROM series_reference r JOIN plex_items p ON p.rating_key=r.show_rating_key AND p.item_type='show' AND p.active LEFT JOIN catalog_exclusions ex ON ex.imdb_id=r.imdb_id WHERE ex.imdb_id IS NULL AND r.show_rating_key=ANY(${requested})`;const valid=new Set(rows.map(r=>String(r.entity_id)));if(requested.some(id=>!valid.has(id)))throw new Error('La serie ya no está disponible para actualizar su detalle Plex');return requested.filter(id=>valid.has(id))}
async function appendEligible(sql,process,runId,ids){if(!ids.length)return 0;const existing=await sql`SELECT entity_id FROM batch_run_items WHERE batch_run_id=${runId}::uuid AND entity_type='series'`,have=new Set(existing.map(x=>String(x.entity_id))),missing=ids.filter(id=>!have.has(String(id)));if(!missing.length)return 0;const[maxRow]=await sql`SELECT COALESCE(max(position),-1)::int max_position FROM batch_run_items WHERE batch_run_id=${runId}::uuid`,base=Number(maxRow?.max_position??-1)+1;await sql`INSERT INTO batch_run_items(batch_run_id,entity_type,entity_id,position,status) SELECT ${runId}::uuid,'series',x.entity_id,${base}+(x.ord-1)::int,'queued' FROM unnest(${missing}::text[]) WITH ORDINALITY AS x(entity_id,ord) ON CONFLICT(batch_run_id,entity_type,entity_id) DO NOTHING`;const[counts]=await sql`SELECT count(*)::int total,count(*) FILTER(WHERE status IN('queued','leased','running'))::int pending FROM batch_run_items WHERE batch_run_id=${runId}::uuid`;await sql`UPDATE process_runs SET items_total=${Number(counts?.total||0)},items_pending=${Number(counts?.pending||0)},updated_at=now() WHERE run_id=${runId}::uuid`;await addProcessEvent(runId,{eventType:'batch_items_appended',message:`${missing.length} series añadidas a ${process}`,data:{items_added:missing.length,items_total:Number(counts?.total||0)}});return missing.length}
export async function getSeriesBatchState(process){const cfg=CONFIG[process];if(!cfg)throw new Error('Proceso Batch de Series no soportado');const sql=db(),ids=await selector(process,sql),[active,latest,[engine]]=await Promise.all([getActiveBatch(process,sql),getLatestBatch(process,sql),sql`SELECT desired_state,pause_reason,changed_at FROM batch_engine_control WHERE singleton_id=1`]);return{processCode:process,pool:cfg.pool,concurrency:cfg.concurrency,eligibleCount:ids.length,active,latest,engine:engine||{desired_state:'running'}}}
export async function startSeriesBatch(process,{limit=null,triggerSource=null,entityIds=null}={}){const cfg=CONFIG[process];if(!cfg)throw new Error('Proceso Batch de Series no soportado');const sql=db(),targeted=entityIds!==null;let ids;if(targeted){if(process!=='PROC-SER-002')throw new Error('La selección explícita sólo está habilitada para SER-002');ids=await selectExplicitSer002(sql,entityIds)}else ids=await selector(process,sql);if(limit!=null)ids=ids.slice(0,Math.max(1,Math.min(Number(limit)||1,10000)));const active=await getActiveBatch(process,sql);if(active){const appended=active.desired_state==='cancel_requested'?0:await appendEligible(sql,process,active.run_id,ids);return{run:await getActiveBatch(process,sql),reused:true,appended,eligibleCount:Number(active.items_pending||0)+appended,targeted}}if(!ids.length)return{run:null,reused:false,empty:true,eligibleCount:0,targeted};const correlationKey=`${process}:batch:${Date.now()}`,source=triggerSource||cfg.trigger,started=await startProcessRun({processCode:process,runKind:'batch',triggerSource:source,executor:cfg.pool==='plex'?'railway_batch_plex':'railway_batch_api',entityType:'series_set',entityId:targeted?ids.join(','):process,correlationKey,idempotencyKey:correlationKey,context:{surface:'/calidad/series',operation:cfg.operation,worker_pool:cfg.pool,requested_concurrency:cfg.concurrency,automatic:source==='quality_scheduler'||source==='plex_sync_continuation',targeted}}),runId=started.run.run_id;try{await sql`INSERT INTO batch_run_control(run_id,process_code,worker_pool,desired_state,requested_concurrency) VALUES(${runId}::uuid,${process},${cfg.pool},'running',${cfg.concurrency})`;await sql`INSERT INTO batch_run_items(batch_run_id,entity_type,entity_id,position,status) SELECT ${runId}::uuid,'series',x.entity_id,(x.ord-1)::int,'queued' FROM unnest(${ids}::text[]) WITH ORDINALITY AS x(entity_id,ord)`;await sql`UPDATE process_runs SET items_total=${ids.length},items_processed=0,items_succeeded=0,items_failed=0,items_pending=${ids.length},updated_at=now() WHERE run_id=${runId}::uuid`;await addProcessEvent(runId,{eventType:'batch_queued',message:`Batch ${process} preparado`,data:{items_total:ids.length,worker_pool:cfg.pool,requested_concurrency:cfg.concurrency,automatic:source==='quality_scheduler'||source==='plex_sync_continuation',targeted}});return{run:await getActiveBatch(process,sql),reused:false,eligibleCount:ids.length,targeted}}catch(error){await finishProcessRun(runId,{technicalStatus:'failed',message:`No se pudo preparar ${process}`}).catch(()=>{});if(error?.code==='23505'){const existing=await getActiveBatch(process,sql);if(existing){const appended=await appendEligible(sql,process,existing.run_id,ids);return{run:await getActiveBatch(process,sql),reused:true,appended,eligibleCount:Number(existing.items_pending||0)+appended,targeted}}}throw error}}
