import {neon} from '@neondatabase/serverless';
import {recipeFor} from '../lib/lifecycle-processes.mjs';
import {beginLifecycleJob,finishLifecycleJob,markLifecycleJobError,markLifecycleJobSkipped,runLifecycleStep,skipLifecycleStep} from './lifecycle-runtime.mjs';
import {dataTmdb,dataOmdb,dataFilmAffinity,finalizeDataStage} from './lifecycle-data-executor.mjs';
import {ratingsMDBList,finalizeRatings,calculatePikoScore} from './lifecycle-pikoscore-executor.mjs';
import {freshnessDays} from '../lib/pikoscore-core.mjs';
import {validateMovieFileLifecycle} from './lifecycle-movie-file-executor.mjs';
import {calculateMoviePikoQuality} from './lifecycle-tech-executor.mjs';
import {reconcileSeriesReferenceTarget,refreshSeriesTmdbTarget,finalizeSeriesLifecycle} from './lifecycle-series-executor.mjs';
import {resolveTmdbIdentity,finalizeIdentity} from './lifecycle-identity-executor.mjs';
import {imdbEvidence,tmdbEvidence,scoreIdentity} from './lifecycle-validation-executor.mjs';

const DATABASE_URL=process.env.DATABASE_URL;if(!DATABASE_URL)throw new Error('DATABASE_URL no está configurada');
const sql=neon(DATABASE_URL),WORKER_ID=String(process.env.BATCH_LIFECYCLE_WORKER_ID||`lifecycle-${process.pid}`).slice(0,80),POLL_MS=Math.max(250,Number(process.env.BATCH_POLL_MS)||1000),LEASE_SECONDS=180,MAX_IN_FLIGHT=Math.max(1,Math.min(8,Number(process.env.BATCH_LIFECYCLE_CONCURRENCY)||4));
let stopping=false;const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const sourceRuntime=new Map();
function sourceState(source){if(!sourceRuntime.has(source))sourceRuntime.set(source,{active:0,lastStartedAt:0});return sourceRuntime.get(source)}
async function runtimeOpen(){const[r]=await sql`SELECT paused FROM batch_runtime_control WHERE singleton=true`;return Boolean(r&&!r.paused)}
async function sourceGate(source){const[r]=await sql`SELECT l.source,l.enabled,l.max_concurrency,l.min_interval_ms,l.daily_budget,l.breaker_state,l.blocked_until,l.consecutive_errors,l.updated_at,c.paused,(SELECT count(*)::int FROM batch_job_steps s WHERE s.source=${source} AND s.attempted=true AND s.started_at>=date_trunc('day',now()) AND NOT(s.status='failed' AND (s.error_message='Motor pausado' OR s.error_message LIKE 'Fuente % deshabilitada' OR s.error_message LIKE 'Circuit breaker abierto para %' OR s.error_message LIKE 'Presupuesto diario agotado para %'))) usage_today FROM batch_source_limits l CROSS JOIN batch_runtime_control c WHERE l.source=${source} AND c.singleton=true`;return r||null}
async function acquireSource(source){if(source==='internal'||source==='plex')return()=>{};const state=sourceState(source);while(!stopping){const cfg=await sourceGate(source);if(!cfg||cfg.paused)throw Object.assign(new Error('Motor pausado'),{paused:true});if(!cfg.enabled)throw Object.assign(new Error(`Fuente ${source} deshabilitada`),{sourceDisabled:true});if(cfg.breaker_state==='open'&&cfg.blocked_until&&new Date(cfg.blocked_until)>new Date())throw Object.assign(new Error(`Circuit breaker abierto para ${source}`),{sourceDisabled:true});if(cfg.daily_budget!=null&&Number(cfg.usage_today||0)>=Number(cfg.daily_budget))throw Object.assign(new Error(`Presupuesto diario agotado para ${source}`),{sourceBudget:true});const max=Math.max(1,Number(cfg.max_concurrency)||1);if(state.active>=max){await sleep(20);continue}const minInterval=Math.max(0,Number(cfg.min_interval_ms)||0),dbUpdated=cfg.updated_at?new Date(cfg.updated_at).getTime():0,nextAllowed=Math.max(state.lastStartedAt+minInterval,dbUpdated+minInterval),wait=nextAllowed-Date.now();if(wait>0){await sleep(Math.min(wait,250));continue}state.active+=1;state.lastStartedAt=Date.now();let released=false;return()=>{if(!released){released=true;state.active=Math.max(0,state.active-1)}}}throw Object.assign(new Error('Worker detenido'),{paused:true})}
async function sourceSuccess(source){if(source==='internal'||source==='plex')return;await sql`UPDATE batch_source_limits SET consecutive_errors=0,breaker_state='closed',blocked_until=NULL,updated_at=now() WHERE source=${source}`}
async function sourceFailure(source,error){if(source==='internal'||source==='plex')return;const status=Number(error?.status||0);if([400,404,409,422].includes(status)){await sql`UPDATE batch_source_limits SET updated_at=now() WHERE source=${source}`;return}const hard=[401,403,429].includes(status);const[r]=await sql`UPDATE batch_source_limits SET consecutive_errors=consecutive_errors+1,updated_at=now() WHERE source=${source} RETURNING consecutive_errors`;const n=Number(r?.consecutive_errors||1);if(hard||n>=5){const mins=status===429?60:15;await sql`UPDATE batch_source_limits SET breaker_state='open',blocked_until=now()+(${mins}||' minutes')::interval,updated_at=now() WHERE source=${source}`}}
async function guardedStep(job,step,fn){let release;try{release=await acquireSource(step.source)}catch(e){return runLifecycleStep(sql,job,step,async()=>{throw e})}try{const r=await runLifecycleStep(sql,job,step,fn);if(r.ok)await sourceSuccess(step.source);else await sourceFailure(step.source,r.error);return r}finally{release?.()}}
async function leaseOne(){const rows=await sql`WITH candidate AS (SELECT q.id,COALESCE(r.limits->>'retry_mode','new_only') retry_mode FROM batch_jobs q JOIN batch_runs r ON r.id=q.run_id CROSS JOIN batch_runtime_control c WHERE c.singleton=true AND NOT c.paused AND q.status IN('queued','retry_wait') AND q.available_at<=now() AND (q.leased_until IS NULL OR q.leased_until<now()) AND r.status IN('queued','running') AND COALESCE(r.limits->>'orchestration','')='lifecycle' AND q.stage IN('IDENTITY_PENDING','IDENTITY_VALIDATION','DATA_INCOMPLETE','PIKOSCORE_PENDING','MOVIE_FILE_PENDING','SERIES_SYNC_PENDING','TECH_PENDING') AND EXISTS(SELECT 1 FROM catalog_lifecycle cl WHERE cl.imdb_id=q.entity_id AND cl.lifecycle_state=q.stage) ORDER BY q.priority DESC,q.created_at,q.id LIMIT 1 FOR UPDATE OF q SKIP LOCKED),leased AS (UPDATE batch_jobs j SET status='leased',worker_id=${WORKER_ID},leased_until=now()+(${LEASE_SECONDS}||' seconds')::interval,attempt=j.attempt+1,started_at=COALESCE(j.started_at,now()),updated_at=now() FROM candidate c WHERE j.id=c.id RETURNING j.id,j.run_id,j.entity_type,j.entity_id,j.stage,j.attempt,c.retry_mode),run_started AS (UPDATE batch_runs r SET status='running',started_at=COALESCE(started_at,now()),updated_at=now() WHERE r.id=(SELECT run_id FROM leased) AND r.status='queued' RETURNING r.id) SELECT id,run_id,entity_type,entity_id,stage,attempt,retry_mode FROM leased`;const job=rows[0];return job?{...job,retryMode:job.retry_mode||'new_only'}:null}
async function finishPhysical(job,status){await sql`WITH done AS (UPDATE batch_jobs SET status=${status},finished_at=now(),leased_until=NULL,updated_at=now() WHERE id=${job.id} RETURNING run_id) UPDATE batch_runs r SET status=CASE WHEN EXISTS(SELECT 1 FROM batch_jobs f WHERE f.run_id=r.id AND f.status='failed') THEN 'failed' ELSE 'completed' END,finished_at=now(),updated_at=now() WHERE r.id=(SELECT run_id FROM done) AND r.status IN('queued','running') AND NOT EXISTS(SELECT 1 FROM batch_jobs p WHERE p.run_id=r.id AND p.status IN('queued','retry_wait','leased','running'))`}
async function executeIdentity(job){const recipe=recipeFor(job.stage),begin=await beginLifecycleJob(sql,job,{retryMode:job.retryMode});if(!begin.eligible){await markLifecycleJobSkipped(sql,job,begin);return}const byKey=Object.fromEntries(recipe.steps.map((s,i)=>[s.key,{...s,order:i+1}])),steps=[];const[current]=await sql`SELECT tmdb_id FROM movies WHERE imdb_id=${job.entity_id}`;if(current?.tmdb_id)steps.push(await skipLifecycleStep(sql,job,byKey.tmdb_identity,'TMDb ya estaba resuelto; no consume presupuesto'));else steps.push(await guardedStep(job,byKey.tmdb_identity,()=>resolveTmdbIdentity(sql,job.entity_id)));const final=await guardedStep(job,{key:'finalize_identity',source:'internal',order:2},()=>finalizeIdentity(sql,job.entity_id));steps.push(final);const complete=Boolean(final.ok&&final.result?.complete),result=await finishLifecycleJob(sql,job,{before:begin.before,steps,complete,extra:{recipe:'IDENTITY_PENDING',unitary_reference:'resolveIdentityUnitary',identity:final.result||null}});await finishPhysical(job,result.outcome==='ERROR'?'failed':result.outcome==='REVISION_MANUAL'?'review':'done')}
async function executeIdentityValidation(job){const recipe=recipeFor(job.stage),begin=await beginLifecycleJob(sql,job,{retryMode:job.retryMode});if(!begin.eligible){await markLifecycleJobSkipped(sql,job,begin);return}const byKey=Object.fromEntries(recipe.steps.map((s,i)=>[s.key,{...s,order:i+1}])),steps=[];const[local]=await sql`SELECT (EXISTS(SELECT 1 FROM identity_validation v WHERE v.imdb_id=${job.entity_id} AND v.imdb_original_title IS NOT NULL AND v.imdb_year IS NOT NULL) OR EXISTS(SELECT 1 FROM catalog_candidates c WHERE c.imdb_id=${job.entity_id} AND c.source_snapshot->>'originalTitle' IS NOT NULL AND c.year IS NOT NULL) OR EXISTS(SELECT 1 FROM movies m WHERE m.imdb_id=${job.entity_id} AND m.original_title IS NOT NULL AND m.year IS NOT NULL)) AS available`;const imdbPromise=local?.available?runLifecycleStep(sql,job,{...byKey.imdb_evidence,source:'internal'},()=>imdbEvidence(sql,job.entity_id)):guardedStep(job,byKey.imdb_evidence,()=>imdbEvidence(sql,job.entity_id));const tmdbPromise=guardedStep(job,byKey.tmdb_evidence,()=>tmdbEvidence(sql,job.entity_id));const[imdbStep,tmdbStep]=await Promise.all([imdbPromise,tmdbPromise]);steps.push(imdbStep,tmdbStep);if(!imdbStep.ok||!tmdbStep.ok){const result=await finishLifecycleJob(sql,job,{before:begin.before,steps,complete:false,extra:{recipe:'IDENTITY_VALIDATION',unitary_reference:'refreshIdentityEvidence + validateOne',parallel_evidence:true}});await finishPhysical(job,result.outcome==='ERROR'?'failed':'done');return}const scored=await guardedStep(job,byKey.score_identity,()=>scoreIdentity(sql,job.entity_id));steps.push(scored);const state=scored.result?.lifecycle,review=state==='IDENTITY_REVIEW_REQUIRED',complete=Boolean(scored.ok&&state&&state!=='IDENTITY_VALIDATION');const result=await finishLifecycleJob(sql,job,{before:begin.before,steps,complete,review,extra:{recipe:'IDENTITY_VALIDATION',unitary_reference:'refreshIdentityEvidence + validateOne',validation:scored.result||null,parallel_evidence:true}});await finishPhysical(job,result.outcome==='ERROR'?'failed':result.outcome==='REVISION_MANUAL'?'review':'done')}
async function executeData(job){const recipe=recipeFor(job.stage),begin=await beginLifecycleJob(sql,job,{retryMode:job.retryMode});if(!begin.eligible){await markLifecycleJobSkipped(sql,job,begin);return}const steps=[],byKey=Object.fromEntries(recipe.steps.map((s,i)=>[s.key,{...s,order:i+1}]));steps.push(await guardedStep(job,byKey.data_tmdb,()=>dataTmdb(sql,job.entity_id)));const omdb=await guardedStep(job,byKey.data_omdb,()=>dataOmdb(sql,job.entity_id));steps.push(omdb);steps.push(await skipLifecycleStep(sql,job,byKey.data_imdb_fallback,omdb.ok?'OMDb ya cubre IMDb en el proceso unitario; fallback no necesario':'Fallback IMDb pertenece al proceso de ratings; datos conservan el valor existente'));steps.push(await guardedStep(job,byKey.data_filmaffinity,()=>dataFilmAffinity(sql,job.entity_id)));steps.push(await guardedStep(job,byKey.finalize_ratings,()=>finalizeDataStage(sql,job.entity_id)));const criticalFailed=steps.some(s=>!s.ok&&['data_tmdb','data_filmaffinity','finalize_ratings'].includes(s.key));const result=await finishLifecycleJob(sql,job,{before:begin.before,steps,complete:!criticalFailed,extra:{recipe:'DATA_INCOMPLETE',unitary_reference:'updateDataQualityTitle'}});await finishPhysical(job,result.outcome==='ERROR'?'failed':result.outcome==='REVISION_MANUAL'?'review':'done')}
async function executePikoScore(job){const recipe=recipeFor(job.stage),begin=await beginLifecycleJob(sql,job,{retryMode:job.retryMode});if(!begin.eligible){await markLifecycleJobSkipped(sql,job,begin);return}const steps=[],byKey=Object.fromEntries(recipe.steps.map((s,i)=>[s.key,{...s,order:i+1}]));const[freshRow]=await sql`SELECT m.year,m.ratings_refreshed_at,mm.release_date,(SELECT count(*)::int FROM title_ratings tr WHERE tr.imdb_id=m.imdb_id AND tr.status='available' AND tr.normalized_rating>0) rating_count FROM movies m LEFT JOIN movie_metadata mm USING(imdb_id) WHERE m.imdb_id=${job.entity_id}`;const refreshed=freshRow?.ratings_refreshed_at?new Date(freshRow.ratings_refreshed_at):null;const fresh=Boolean(Number(freshRow?.rating_count||0)>=2&&refreshed&&!Number.isNaN(refreshed.getTime())&&(Date.now()-refreshed.getTime())<freshnessDays(freshRow)*86400000);let verified=false;if(fresh){steps.push(await skipLifecycleStep(sql,job,byKey.ratings_tmdb,`Ratings MDBList vigentes: ${Number(freshRow.rating_count)} fuentes; no consume presupuesto`));verified=true}else{const mdblist=await guardedStep(job,byKey.ratings_tmdb,()=>ratingsMDBList(sql,job.entity_id));steps.push(mdblist);verified=Boolean(mdblist.ok&&Number(mdblist.result?.saved||0)>=2)}const finalized=await guardedStep(job,byKey.finalize_ratings,()=>finalizeRatings(sql,job.entity_id,verified));steps.push(finalized);if(verified&&finalized.ok&&finalized.result?.pikoscore_enabled)steps.push(await guardedStep(job,byKey.calculate_pikoscore,()=>calculatePikoScore(sql,job.entity_id)));else steps.push(await skipLifecycleStep(sql,job,byKey.calculate_pikoscore,'No se calcula hasta disponer de al menos 2 ratings válidos de MDBList'));const criticalFailed=!verified||!finalized.ok||steps.some(s=>s.key==='calculate_pikoscore'&&!s.ok&&!s.skipped);const result=await finishLifecycleJob(sql,job,{before:begin.before,steps,complete:!criticalFailed,extra:{recipe:'PIKOSCORE_PENDING',unitary_reference:'MDBList + PikoScore 3.0',sources_verified:verified,reused_fresh_ratings:fresh,source_count:Number(finalized.result?.source_count||freshRow?.rating_count||0)}});await finishPhysical(job,result.outcome==='ERROR'?'failed':result.outcome==='REVISION_MANUAL'?'review':'done')}
async function executeMovieFile(job){const recipe=recipeFor(job.stage),begin=await beginLifecycleJob(sql,job,{retryMode:job.retryMode});if(!begin.eligible){await markLifecycleJobSkipped(sql,job,begin);return}const step={...recipe.steps[0],order:1},validation=await guardedStep(job,step,()=>validateMovieFileLifecycle(sql,job.entity_id)),steps=[validation],review=validation.ok&&validation.result?.lifecycle==='MOVIE_FILE_REVIEW',complete=validation.ok&&['TECH_PENDING','COMPLETE','MOVIE_FILE_REVIEW'].includes(validation.result?.lifecycle);const result=await finishLifecycleJob(sql,job,{before:begin.before,steps,complete,review,extra:{recipe:'MOVIE_FILE_PENDING',unitary_reference:'movie quality validation',issues:validation.result?.issues??null}});await finishPhysical(job,result.outcome==='ERROR'?'failed':result.outcome==='REVISION_MANUAL'?'review':'done')}
async function executeSeries(job){const recipe=recipeFor(job.stage),begin=await beginLifecycleJob(sql,job,{retryMode:job.retryMode});if(!begin.eligible){await markLifecycleJobSkipped(sql,job,begin);return}const byKey=Object.fromEntries(recipe.steps.map((s,i)=>[s.key,{...s,order:i+1}])),steps=[];const ref=await guardedStep(job,byKey.reconcile_series_reference,()=>reconcileSeriesReferenceTarget(sql,job.entity_id));steps.push(ref);if(ref.ok)steps.push(await guardedStep(job,byKey.refresh_series_tmdb,()=>refreshSeriesTmdbTarget(sql,job.entity_id)));else steps.push(await skipLifecycleStep(sql,job,byKey.refresh_series_tmdb,'No se consulta TMDb hasta disponer de referencia de serie'));let final=null;if(steps.every(s=>s.ok||s.skipped)&&steps[1]?.ok)final=await guardedStep(job,{key:'finalize_series',source:'internal',order:3},()=>finalizeSeriesLifecycle(sql,job.entity_id));else final=await skipLifecycleStep(sql,job,{key:'finalize_series',source:'internal',order:3},'Refresco de serie incompleto');steps.push(final);const state=final.result?.lifecycle,review=state==='SERIES_REVIEW',complete=Boolean(final.ok&&['SERIES_REVIEW','TECH_PENDING','COMPLETE'].includes(state));const result=await finishLifecycleJob(sql,job,{before:begin.before,steps,complete,review,extra:{recipe:'SERIES_SYNC_PENDING',unitary_reference:'refreshSeriesUnitary',series_result:final.result||null}});await finishPhysical(job,result.outcome==='ERROR'?'failed':result.outcome==='REVISION_MANUAL'?'review':'done')}
async function executeTech(job){const recipe=recipeFor(job.stage),begin=await beginLifecycleJob(sql,job,{retryMode:job.retryMode});if(!begin.eligible){await markLifecycleJobSkipped(sql,job,begin);return}const step={...recipe.steps[0],order:1},quality=await guardedStep(job,step,()=>calculateMoviePikoQuality(sql,job.entity_id)),steps=[quality],complete=quality.ok&&quality.result?.lifecycle==='COMPLETE';const result=await finishLifecycleJob(sql,job,{before:begin.before,steps,complete,extra:{recipe:'TECH_PENDING',unitary_reference:'analyzeMoviePikoQuality',formula_version:quality.result?.formula_version||null}});await finishPhysical(job,result.outcome==='ERROR'?'failed':'done')}
async function processJob(job){try{if(job.stage==='IDENTITY_PENDING')return await executeIdentity(job);if(job.stage==='IDENTITY_VALIDATION')return await executeIdentityValidation(job);if(job.stage==='DATA_INCOMPLETE')return await executeData(job);if(job.stage==='PIKOSCORE_PENDING')return await executePikoScore(job);if(job.stage==='MOVIE_FILE_PENDING')return await executeMovieFile(job);if(job.stage==='SERIES_SYNC_PENDING')return await executeSeries(job);if(job.stage==='TECH_PENDING')return await executeTech(job);throw Object.assign(new Error(`Etapa aún no conectada al worker Lifecycle: ${job.stage}`),{permanent:true})}catch(e){await markLifecycleJobError(sql,job,{error:e});await sql`UPDATE batch_jobs SET status=${e?.paused||e?.sourceDisabled||e?.sourceBudget?'retry_wait':'failed'},available_at=CASE WHEN ${Boolean(e?.paused||e?.sourceDisabled||e?.sourceBudget)} THEN now()+interval '10 minutes' ELSE available_at END,error_class=${e?.permanent?'permanent':'technical'},error_message=${String(e?.message||e).slice(0,1000)},finished_at=CASE WHEN ${Boolean(e?.paused||e?.sourceDisabled||e?.sourceBudget)} THEN NULL ELSE now() END,leased_until=NULL,updated_at=now() WHERE id=${job.id}`}}
process.on('SIGTERM',()=>{stopping=true});process.on('SIGINT',()=>{stopping=true});
const inFlight=new Set();
function launch(job){let task;task=processJob(job).catch(e=>console.error('[lifecycle-worker job]',job?.id,e?.message||e)).finally(()=>inFlight.delete(task));inFlight.add(task)}
console.log(`[lifecycle-worker] ${WORKER_ID} listo; concurrency=${MAX_IN_FLIGHT}; etapas=IDENTITY_PENDING,IDENTITY_VALIDATION,DATA_INCOMPLETE,PIKOSCORE_PENDING,MOVIE_FILE_PENDING,SERIES_SYNC_PENDING,TECH_PENDING`);
while(!stopping){try{let leased=0;while(!stopping&&inFlight.size<MAX_IN_FLIGHT){const job=await leaseOne();if(!job)break;launch(job);leased+=1}if(inFlight.size===0){await sleep(POLL_MS);continue}if(!leased)await Promise.race([Promise.race([...inFlight]),sleep(100)])}catch(e){console.error('[lifecycle-worker]',e?.message||e);await sleep(POLL_MS)}}
await Promise.allSettled([...inFlight]);
