'use server';
import {revalidatePath} from 'next/cache';
import {db} from '@/lib/db';
import {dispatchIdentityRefresh,cancelIdentityRefresh} from '@/lib/identity-run-control';
import {saveIdentity} from '@/lib/identity';
import {markIdentityRefreshPending,refreshKnownIdentity} from '@/lib/identity-refresh';
import {resolveTmdbOnly,wikidataFaBatch,wikidataFaByTmdbBatch,wikidataFaRetryBatch,saveIdentity as saveResolvedIdentity} from '@/lib/identity-resolver';

function refresh(imdbId){revalidatePath('/calidad/identidad');revalidatePath('/calidad');revalidatePath('/admin');if(imdbId){revalidatePath('/catalogo');revalidatePath(`/catalogo/${imdbId}`)}}
function imdb(formData,name='imdbId'){const id=String(formData.get(name)||'').trim();if(!/^tt\d+$/.test(id))throw new Error('IMDb ID inválido');return id}
const searchHeaders={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36','Accept-Language':'es-ES,es;q=0.9,en;q=0.7','Accept':'text/html,application/xhtml+xml'};
function decodeSearchHtml(s=''){let x=String(s||'').replace(/&amp;/g,'&');for(let i=0;i<2;i++){try{x=decodeURIComponent(x)}catch{break}}return x}
function extractFaIds(html=''){const sources=[String(html||''),decodeSearchHtml(html)],out=[];for(const src of sources){for(const re of [/filmaffinity\.com\/(?:[a-z]{2}\/)?film(\d{4,9})\.html/gi,/filmaffinity\.com[^\s"'<>]{0,160}\bfilm(\d{4,9})\b/gi,/film(\d{4,9})\.html/gi]){for(const m of src.matchAll(re)){const id=String(m[1]);if(!out.includes(id))out.push(id)}}}return out}
async function searchEngineHtml(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000),started=Date.now();try{const r=await fetch(url,{headers:searchHeaders,signal:c.signal,cache:'no-store',redirect:'follow'}),html=await r.text();return{ok:r.ok,status:r.status,html,ms:Date.now()-started,finalUrl:r.url}}catch(e){return{ok:false,status:null,html:'',ms:Date.now()-started,finalUrl:null,error:e?.message||String(e)}}finally{clearTimeout(t)}}
async function searchFaViaWeb(row,trace){const titles=[row.title_es,row.original_title,row.title].filter(Boolean).map(x=>String(x).trim()).filter((x,i,a)=>x&&a.indexOf(x)===i),year=Number(row.year||0),queries=[];for(const title of titles){queries.push(`${title}${year?` ${year}`:''} filmaffinity`);queries.push(`site:filmaffinity.com ${title}${year?` ${year}`:''}`)}const seen=new Set(),engines=[['google',q=>`https://www.google.com/search?hl=es&num=10&q=${encodeURIComponent(q)}`],['bing',q=>`https://www.bing.com/search?q=${encodeURIComponent(q)}&count=10&setlang=es`],['duckduckgo',q=>`https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`]];for(const q of queries.slice(0,6)){if(seen.has(q))continue;seen.add(q);for(const[engine,makeUrl]of engines){const r=await searchEngineHtml(makeUrl(q)),ids=extractFaIds(r.html);trace.push({step:'web_search',engine,query:q,http_status:r.status,ok:r.ok,elapsed_ms:r.ms,html_bytes:r.html.length,final_host:r.finalUrl?new URL(r.finalUrl).hostname:null,candidates:ids.slice(0,5),error:r.error||null});if(ids.length)return{faId:ids[0],method:`fa_web_${engine}`,query:q,candidates:ids.slice(0,5),engine}}}return{faId:null,method:'fa_web_not_found',query:null,candidates:[],engine:null}}
async function persistTrace(sql,id,trace,result){const payload={imdb_id:id,at:new Date().toISOString(),result,trace};try{await sql`INSERT INTO admin_events(event_type,entity_type,entity_id,action,payload,created_at) VALUES('identity','movie',${id},'single_retry_trace',${JSON.stringify(payload)}::jsonb,now())`}catch{}try{await sql`UPDATE movies SET source_status=COALESCE(source_status,'{}'::jsonb)||${JSON.stringify({identity_single_retry_last:{at:payload.at,result}})}::jsonb WHERE imdb_id=${id}`}catch{}}

export async function startIdentityRefreshAction(){const r=await dispatchIdentityRefresh('identity_page');refresh();if(!r.ok)return r;if(r.alreadyRunning)return{ok:true,message:`Ya hay una reevaluación en curso: ${Number(r.processed||0).toLocaleString('es-ES')} / ${Number(r.total||0).toLocaleString('es-ES')}`};return{ok:true,message:`Reevaluación lanzada para ${Number(r.total||0).toLocaleString('es-ES')} títulos. El progreso aparecerá aquí.`}}
export async function stopIdentityRefreshAction(_prev,formData){const r=await cancelIdentityRefresh(formData.get('runId'));refresh();return r}
export async function saveIdentityPageAction(formData){const old=imdb(formData),newId=await saveIdentity(old,{imdbId:formData.get('newImdbId'),tmdbId:formData.get('tmdbId'),faId:formData.get('faId')});await markIdentityRefreshPending(newId,'manual_identity_edit');refresh(old);refresh(newId)}
export async function refreshIdentityDataAction(_prev,formData){try{const id=imdb(formData),r=await refreshKnownIdentity(id);refresh(id);return{ok:true,message:`Datos refrescados: ${r?.title||id}`}}catch(e){return{ok:false,message:e?.message||'No se pudieron refrescar los datos'}}}
export async function retryMissingIdentityAction(_prev,formData){const trace=[];let id=null,sql=null;try{id=imdb(formData);sql=db();let[row]=await sql`SELECT imdb_id,type,title,title_es,original_title,year,tmdb_id,fa_id FROM movies WHERE imdb_id=${id}`;if(!row)throw new Error('Título no encontrado');trace.push({step:'start',imdb_id:id,type:row.type,title_es:row.title_es,title:row.title,original_title:row.original_title,year:row.year,tmdb_id:row.tmdb_id,fa_id:row.fa_id});let tmdbId=null,faId=null,methods=[],web=null;if(!row.tmdb_id){const st=Date.now();tmdbId=await resolveTmdbOnly(id,row.type);trace.push({step:'tmdb_from_imdb',found:tmdbId||null,elapsed_ms:Date.now()-st});if(tmdbId){methods.push('tmdb_imdb');await saveResolvedIdentity(id,{tmdbId,faId:null,method:'tmdb_imdb'});row={...row,tmdb_id:tmdbId}}}else trace.push({step:'tmdb_from_imdb',skipped:'already_present',tmdb_id:row.tmdb_id});
if(!row.fa_id){const w1=await wikidataFaBatch([id]);faId=w1.map[id]||null;trace.push({step:'wikidata_imdb_to_fa',found:faId,error:w1.error||null,elapsed_ms:w1.ms||0});if(faId)methods.push('wikidata_imdb');if(!faId&&row.tmdb_id){const wikiRow=row.type==='Miniserie'?{...row,type:'Serie'}:row,w2=await wikidataFaByTmdbBatch([wikiRow]);faId=w2.map[String(row.tmdb_id)]||null;trace.push({step:'wikidata_tmdb_to_fa',tmdb_id:row.tmdb_id,type_used:wikiRow.type,found:faId,error:w2.error||null,elapsed_ms:w2.ms||0,requests:w2.requests||0});if(faId)methods.push('wikidata_tmdb')}if(!faId){const wr=await wikidataFaRetryBatch([id]);faId=wr.map[id]||null;trace.push({step:'wikidata_retry',found:faId,error:wr.error||null,elapsed_ms:wr.ms||0});if(faId)methods.push('wikidata_retry')}if(!faId){web=await searchFaViaWeb(row,trace);faId=web.faId;trace.push({step:'web_search_result',found:faId,engine:web.engine,query:web.query,candidates:web.candidates});if(faId)methods.push(web.method)}if(faId)await saveResolvedIdentity(id,{tmdbId:null,faId,method:methods.join('+')||'fa_web_search'})}else trace.push({step:'fa_search',skipped:'already_present',fa_id:row.fa_id});
await markIdentityRefreshPending(id,'single_identity_retry');refresh(id);const[after]=await sql`SELECT tmdb_id,fa_id,source_status FROM movies WHERE imdb_id=${id}`;const result={tmdb_id:after?.tmdb_id||null,fa_id:after?.fa_id||null,methods,complete:Boolean(after?.tmdb_id&&after?.fa_id)};await persistTrace(sql,id,trace,result);if(result.complete){const source=methods.find(x=>x.startsWith('fa_web_'));return{ok:true,message:source?`Identidad completa. FA ${result.fa_id} encontrado por ${source.replace('fa_web_','')}. Traza individual guardada. Ya puedes refrescar los datos.`:'Identidad completa. Traza individual guardada. Ya puedes refrescar los datos.'}}return{ok:true,message:'Reintento completado; aún falta algún ID. Traza individual guardada para diagnóstico.'}}catch(e){if(sql&&id)await persistTrace(sql,id,trace,{complete:false,error:e?.message||String(e)});return{ok:false,message:e?.message||'No se pudo reintentar la identidad'}}}
