'use server';
import {revalidatePath} from 'next/cache';
import {db} from '@/lib/db';
import {dispatchIdentityRefresh,cancelIdentityRefresh} from '@/lib/identity-run-control';
import {saveIdentity} from '@/lib/identity';
import {markIdentityRefreshPending,refreshKnownIdentity} from '@/lib/identity-refresh';
import {resolveTmdbOnly,wikidataFaBatch,wikidataFaByTmdbBatch,wikidataFaRetryBatch,saveIdentity as saveResolvedIdentity} from '@/lib/identity-resolver';

function refresh(imdbId){revalidatePath('/calidad/identidad');revalidatePath('/calidad');revalidatePath('/admin');if(imdbId){revalidatePath('/catalogo');revalidatePath(`/catalogo/${imdbId}`)}}
function imdb(formData,name='imdbId'){const id=String(formData.get(name)||'').trim();if(!/^tt\d+$/.test(id))throw new Error('IMDb ID inválido');return id}
const searchHeaders={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36','Accept-Language':'es-ES,es;q=0.9,en;q=0.7'};
function decodeSearchHtml(s=''){let x=String(s||'').replace(/&amp;/g,'&');for(let i=0;i<2;i++){try{x=decodeURIComponent(x)}catch{break}}return x}
function extractFaIds(html=''){const sources=[String(html||''),decodeSearchHtml(html)],out=[];for(const src of sources){for(const re of [/filmaffinity\.com\/(?:[a-z]{2}\/)?film(\d{4,9})\.html/gi,/filmaffinity\.com[^\s"'<>]{0,120}\bfilm(\d{4,9})\b/gi]){for(const m of src.matchAll(re)){const id=String(m[1]);if(!out.includes(id))out.push(id)}}}return out}
async function searchEngineHtml(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(url,{headers:searchHeaders,signal:c.signal,cache:'no-store',redirect:'follow'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text()}finally{clearTimeout(t)}}
async function searchFaViaWeb(row){const titles=[row.title_es,row.original_title,row.title].filter(Boolean).map(x=>String(x).trim()).filter((x,i,a)=>x&&a.indexOf(x)===i),year=Number(row.year||0);const queries=[];for(const title of titles){queries.push(`site:filmaffinity.com/es/film "${title}"${year?` "${year}"`:''}`);queries.push(`site:filmaffinity.com "${title}"${year?` "${year}"`:''} FilmAffinity`)}const seen=new Set();for(const q of queries.slice(0,6)){if(seen.has(q))continue;seen.add(q);const endpoints=[`https://www.bing.com/search?q=${encodeURIComponent(q)}&count=10&setlang=es`,`https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`];for(const endpoint of endpoints){try{const html=await searchEngineHtml(endpoint),ids=extractFaIds(html);if(ids.length)return{faId:ids[0],method:endpoint.includes('bing.com')?'fa_web_bing':'fa_web_duckduckgo',query:q,candidates:ids.slice(0,5)}}catch{}}}return{faId:null,method:'fa_web_not_found',query:null,candidates:[]}}

export async function startIdentityRefreshAction(){const r=await dispatchIdentityRefresh('identity_page');refresh();if(!r.ok)return r;if(r.alreadyRunning)return{ok:true,message:`Ya hay una reevaluación en curso: ${Number(r.processed||0).toLocaleString('es-ES')} / ${Number(r.total||0).toLocaleString('es-ES')}`};return{ok:true,message:`Reevaluación lanzada para ${Number(r.total||0).toLocaleString('es-ES')} títulos. El progreso aparecerá aquí.`}}
export async function stopIdentityRefreshAction(_prev,formData){const r=await cancelIdentityRefresh(formData.get('runId'));refresh();return r}
export async function saveIdentityPageAction(formData){const old=imdb(formData),newId=await saveIdentity(old,{imdbId:formData.get('newImdbId'),tmdbId:formData.get('tmdbId'),faId:formData.get('faId')});await markIdentityRefreshPending(newId,'manual_identity_edit');refresh(old);refresh(newId)}
export async function refreshIdentityDataAction(_prev,formData){try{const id=imdb(formData),r=await refreshKnownIdentity(id);refresh(id);return{ok:true,message:`Datos refrescados: ${r?.title||id}`}}catch(e){return{ok:false,message:e?.message||'No se pudieron refrescar los datos'}}}
export async function retryMissingIdentityAction(_prev,formData){try{const id=imdb(formData),sql=db();let[row]=await sql`SELECT imdb_id,type,title,title_es,original_title,year,tmdb_id,fa_id FROM movies WHERE imdb_id=${id}`;if(!row)throw new Error('Título no encontrado');let tmdbId=null,faId=null,methods=[];if(!row.tmdb_id){tmdbId=await resolveTmdbOnly(id,row.type);if(tmdbId){methods.push('tmdb_imdb');await saveResolvedIdentity(id,{tmdbId,faId:null,method:'tmdb_imdb'});row={...row,tmdb_id:tmdbId}}}
if(!row.fa_id){const w1=await wikidataFaBatch([id]);faId=w1.map[id]||null;if(faId)methods.push('wikidata_imdb');if(!faId&&row.tmdb_id){const wikiRow=row.type==='Miniserie'?{...row,type:'Serie'}:row,w2=await wikidataFaByTmdbBatch([wikiRow]);faId=w2.map[String(row.tmdb_id)]||null;if(faId)methods.push('wikidata_tmdb')}if(!faId){const wr=await wikidataFaRetryBatch([id]);faId=wr.map[id]||null;if(faId)methods.push('wikidata_retry')}if(!faId){const web=await searchFaViaWeb(row);faId=web.faId;if(faId)methods.push(web.method)}if(faId)await saveResolvedIdentity(id,{tmdbId:null,faId,method:methods.join('+')||'fa_web_search'})}
await markIdentityRefreshPending(id,'single_identity_retry');refresh(id);const[after]=await sql`SELECT tmdb_id,fa_id,source_status FROM movies WHERE imdb_id=${id}`;if(after?.tmdb_id&&after?.fa_id){const source=methods.find(x=>x.startsWith('fa_web_'));return{ok:true,message:source?`Identidad completa. FA ${after.fa_id} encontrado por búsqueda web (${source==='fa_web_bing'?'Bing':'DuckDuckGo'}). Ya puedes refrescar los datos.`:'Identidad completa. Ya puedes refrescar los datos.'}}return{ok:true,message:'Reintento completado; aún falta algún ID.'}}catch(e){return{ok:false,message:e?.message||'No se pudo reintentar la identidad'}}}
