'use server';
import {revalidatePath} from 'next/cache';
import {db} from '@/lib/db';
import {dispatchIdentityRefresh,cancelIdentityRefresh} from '@/lib/identity-run-control';
import {saveIdentity} from '@/lib/identity';
import {markIdentityRefreshPending,refreshKnownIdentity} from '@/lib/identity-refresh';
import {resolveTmdbOnly,wikidataFaBatch,wikidataFaByTmdbBatch,wikidataFaRetryBatch,saveIdentity as saveResolvedIdentity} from '@/lib/identity-resolver';

function refresh(imdbId){revalidatePath('/calidad/identidad');revalidatePath('/calidad');revalidatePath('/admin');if(imdbId){revalidatePath('/catalogo');revalidatePath(`/catalogo/${imdbId}`)}}
function imdb(formData,name='imdbId'){const id=String(formData.get(name)||'').trim();if(!/^tt\d+$/.test(id))throw new Error('IMDb ID inválido');return id}
const searchHeaders={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36','Accept-Language':'es-ES,es;q=0.9,en;q=0.7','Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'};
function decodeDeep(s=''){let x=String(s||'').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"');for(let i=0;i<3;i++){try{const y=decodeURIComponent(x);if(y===x)break;x=y}catch{break}}return x}
function extractFaCandidates(body=''){const srcs=[String(body||''),decodeDeep(body)],found=[];const add=(id,context,raw)=>{id=String(id||'');if(!/^\d{4,9}$/.test(id))return;if(!found.some(x=>x.id===id))found.push({id,context:String(context||'').slice(0,900),raw:String(raw||'').slice(0,900)})};for(const src of srcs){for(const re of [/https?:\/\/(?:www\.)?filmaffinity\.com\/(?:[a-z]{2}\/)?film(\d{4,9})\.html[^\s"'<>]*/gi,/filmaffinity\.com\/(?:[a-z]{2}\/)?film(\d{4,9})\.html/gi,/filmaffinity\.com[^\s"'<>]{0,220}\bfilm(\d{4,9})\.html/gi]){for(const m of src.matchAll(re)){add(m[1],src.slice(Math.max(0,m.index-350),Math.min(src.length,m.index+900)),m[0])}}}return found}
function diagnosticBody(body=''){const raw=String(body||''),decoded=decodeDeep(raw),lower=decoded.toLowerCase(),needles=['filmaffinity','film'],snippets=[];for(const needle of needles){let from=0;while(snippets.length<20){const i=lower.indexOf(needle,from);if(i<0)break;snippets.push(decoded.slice(Math.max(0,i-350),Math.min(decoded.length,i+900)).replace(/\s+/g,' ').slice(0,1300));from=i+needle.length}}const hrefs=[...decoded.matchAll(/(?:href|url|link)\s*[=:]\s*["']?([^"'<>\s]{1,1200})/gi)].map(m=>m[1]).filter(x=>/filmaffinity|film\d{4,9}/i.test(x)).slice(0,40);const tokens=[...decoded.matchAll(/film\d{4,9}(?:\.html)?/gi)].slice(0,40).map(m=>m[0]);return{contains_filmaffinity:lower.includes('filmaffinity'),filmaffinity_occurrences:(lower.match(/filmaffinity/g)||[]).length,film_tokens:[...new Set(tokens)],interesting_links:[...new Set(hrefs)],snippets:[...new Set(snippets)].slice(0,20)}}
async function fetchSearch(url,extraHeaders={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),10000),started=Date.now();try{const r=await fetch(url,{headers:{...searchHeaders,...extraHeaders},signal:c.signal,cache:'no-store',redirect:'follow'}),body=await r.text(),headers={};for(const k of ['content-type','content-length','server','via','x-cache']){const v=r.headers.get(k);if(v)headers[k]=v}return{ok:r.ok,status:r.status,body,ms:Date.now()-started,finalUrl:r.url,headers}}catch(e){return{ok:false,status:null,body:'',ms:Date.now()-started,finalUrl:null,headers:{},error:e?.message||String(e)}}finally{clearTimeout(t)}}
function buildQueries(row){const titles=[row.title_es,row.original_title,row.title].filter(Boolean).map(x=>String(x).trim()).filter((x,i,a)=>x&&a.indexOf(x)===i),year=Number(row.year||0),type=String(row.type||'').trim(),q=[];for(const title of titles){q.push(`${title}${year?` ${year}`:''} filmaffinity`);q.push(`"${title}"${year?` ${year}`:''} filmaffinity`);q.push(`site:filmaffinity.com "${title}"${year?` ${year}`:''}`);q.push(`site:filmaffinity.com/es/film "${title}"${year?` ${year}`:''}`);if(type)q.push(`"${title}"${year?` ${year}`:''} ${type} filmaffinity`)}q.push(`${row.imdb_id} filmaffinity`);if(row.tmdb_id)q.push(`${row.tmdb_id} TMDb filmaffinity`);return[...new Set(q)].slice(0,10)}
const engines=[
 ['google_html',q=>`https://www.google.com/search?hl=es&num=10&filter=0&q=${encodeURIComponent(q)}`],
 ['google_basic',q=>`https://www.google.com/search?hl=es&gbv=1&num=10&q=${encodeURIComponent(q)}`],
 ['bing_html',q=>`https://www.bing.com/search?setlang=es&count=10&q=${encodeURIComponent(q)}`],
 ['bing_rss',q=>`https://www.bing.com/search?format=rss&setlang=es&count=10&q=${encodeURIComponent(q)}`],
 ['yahoo',q=>`https://search.yahoo.com/search?p=${encodeURIComponent(q)}`],
 ['brave',q=>`https://search.brave.com/search?q=${encodeURIComponent(q)}&source=web`],
 ['mojeek',q=>`https://www.mojeek.com/search?q=${encodeURIComponent(q)}`],
 ['duckduckgo_html',q=>`https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`],
 ['duckduckgo_lite',q=>`https://lite.duckduckgo.com/lite/?q=${encodeURIComponent(q)}`]
];
async function persistRawSearch(sql,id,entry){try{await sql`INSERT INTO admin_events(event_type,entity_type,entity_id,action,payload,created_at) VALUES('identity','movie',${id},'single_retry_search_raw',${JSON.stringify(entry)}::jsonb,now())`}catch{}}
async function searchFaLab(row,trace,sql){const queries=buildQueries(row),all=[];for(const query of queries){const batch=await Promise.all(engines.map(async([engine,makeUrl])=>{const r=await fetchSearch(makeUrl(query)),candidates=extractFaCandidates(r.body),diag=diagnosticBody(r.body),entry={at:new Date().toISOString(),imdb_id:row.imdb_id,engine,query,request_url:makeUrl(query),http_status:r.status,ok:r.ok,elapsed_ms:r.ms,final_url:r.finalUrl,response_headers:r.headers,html_bytes:r.body.length,error:r.error||null,candidates,diagnostic:diag,raw_body:r.body};await persistRawSearch(sql,row.imdb_id,entry);return{engine,query,status:r.status,ok:r.ok,elapsed_ms:r.ms,bytes:r.body.length,candidates:candidates.map(x=>x.id),error:r.error||null,diag}}));for(const x of batch){trace.push({step:'web_search_lab',...x});all.push(x)}}const hits=all.filter(x=>x.candidates.length);const priority=['google_html','google_basic','bing_rss','bing_html','yahoo','brave','mojeek','duckduckgo_html','duckduckgo_lite'];hits.sort((a,b)=>priority.indexOf(a.engine)-priority.indexOf(b.engine));const best=hits[0]||null;trace.push({step:'web_search_lab_summary',queries:queries.length,requests:all.length,hits:hits.map(x=>({engine:x.engine,query:x.query,candidates:x.candidates})),selected:best?{engine:best.engine,query:best.query,fa_id:best.candidates[0]}:null});return best?{faId:best.candidates[0],method:`fa_lab_${best.engine}`,query:best.query,engine:best.engine}:{faId:null,method:'fa_lab_not_found',query:null,engine:null}}
async function persistTrace(sql,id,trace,result){const payload={imdb_id:id,at:new Date().toISOString(),result,trace};try{await sql`INSERT INTO admin_events(event_type,entity_type,entity_id,action,payload,created_at) VALUES('identity','movie',${id},'single_retry_trace',${JSON.stringify(payload)}::jsonb,now())`}catch{}try{await sql`UPDATE movies SET source_status=COALESCE(source_status,'{}'::jsonb)||${JSON.stringify({identity_single_retry_last:{at:payload.at,result}})}::jsonb WHERE imdb_id=${id}`}catch{}}

export async function startIdentityRefreshAction(){const r=await dispatchIdentityRefresh('identity_page');refresh();if(!r.ok)return r;if(r.alreadyRunning)return{ok:true,message:`Ya hay una reevaluación en curso: ${Number(r.processed||0).toLocaleString('es-ES')} / ${Number(r.total||0).toLocaleString('es-ES')}`};return{ok:true,message:`Reevaluación lanzada para ${Number(r.total||0).toLocaleString('es-ES')} títulos. El progreso aparecerá aquí.`}}
export async function stopIdentityRefreshAction(_prev,formData){const r=await cancelIdentityRefresh(formData.get('runId'));refresh();return r}
export async function saveIdentityPageAction(formData){const old=imdb(formData),newId=await saveIdentity(old,{imdbId:formData.get('newImdbId'),tmdbId:formData.get('tmdbId'),faId:formData.get('faId')});await markIdentityRefreshPending(newId,'manual_identity_edit');refresh(old);refresh(newId)}
export async function refreshIdentityDataAction(_prev,formData){try{const id=imdb(formData),r=await refreshKnownIdentity(id);refresh(id);return{ok:true,message:`Datos refrescados: ${r?.title||id}`}}catch(e){return{ok:false,message:e?.message||'No se pudieron refrescar los datos'}}}
export async function retryMissingIdentityAction(_prev,formData){const trace=[];let id=null,sql=null;try{id=imdb(formData);sql=db();let[row]=await sql`SELECT imdb_id,type,title,title_es,original_title,year,tmdb_id,fa_id FROM movies WHERE imdb_id=${id}`;if(!row)throw new Error('Título no encontrado');trace.push({step:'start',imdb_id:id,type:row.type,title_es:row.title_es,title:row.title,original_title:row.original_title,year:row.year,tmdb_id:row.tmdb_id,fa_id:row.fa_id});let tmdbId=null,faId=null,methods=[],web=null;if(!row.tmdb_id){const st=Date.now();tmdbId=await resolveTmdbOnly(id,row.type);trace.push({step:'tmdb_from_imdb',found:tmdbId||null,elapsed_ms:Date.now()-st});if(tmdbId){methods.push('tmdb_imdb');await saveResolvedIdentity(id,{tmdbId,faId:null,method:'tmdb_imdb'});row={...row,tmdb_id:tmdbId}}}else trace.push({step:'tmdb_from_imdb',skipped:'already_present',tmdb_id:row.tmdb_id});
if(!row.fa_id){const w1=await wikidataFaBatch([id]);faId=w1.map[id]||null;trace.push({step:'wikidata_imdb_to_fa',found:faId,error:w1.error||null,elapsed_ms:w1.ms||0});if(faId)methods.push('wikidata_imdb');if(!faId&&row.tmdb_id){const wikiRow=row.type==='Miniserie'?{...row,type:'Serie'}:row,w2=await wikidataFaByTmdbBatch([wikiRow]);faId=w2.map[String(row.tmdb_id)]||null;trace.push({step:'wikidata_tmdb_to_fa',tmdb_id:row.tmdb_id,type_used:wikiRow.type,found:faId,error:w2.error||null,elapsed_ms:w2.ms||0,requests:w2.requests||0});if(faId)methods.push('wikidata_tmdb')}if(!faId){const wr=await wikidataFaRetryBatch([id]);faId=wr.map[id]||null;trace.push({step:'wikidata_retry',found:faId,error:wr.error||null,elapsed_ms:wr.ms||0});if(faId)methods.push('wikidata_retry')}if(!faId){web=await searchFaLab(row,trace,sql);faId=web.faId;if(faId)methods.push(web.method)}if(faId)await saveResolvedIdentity(id,{tmdbId:null,faId,method:methods.join('+')||'fa_search_lab'})}else trace.push({step:'fa_search',skipped:'already_present',fa_id:row.fa_id});
await markIdentityRefreshPending(id,'single_identity_retry');refresh(id);const[after]=await sql`SELECT tmdb_id,fa_id,source_status FROM movies WHERE imdb_id=${id}`;const result={tmdb_id:after?.tmdb_id||null,fa_id:after?.fa_id||null,methods,complete:Boolean(after?.tmdb_id&&after?.fa_id)};await persistTrace(sql,id,trace,result);if(result.complete){const source=methods.find(x=>x.startsWith('fa_lab_'));return{ok:true,message:source?`Identidad completa. FA ${result.fa_id} encontrado por laboratorio ${source.replace('fa_lab_','')}. Trazas completas guardadas.`:'Identidad completa. Trazas completas guardadas.'}}return{ok:true,message:'Reintento completado; aún falta algún ID. Laboratorio unitario ejecutado y trazas completas guardadas.'}}catch(e){if(sql&&id)await persistTrace(sql,id,trace,{complete:false,error:e?.message||String(e)});return{ok:false,message:e?.message||'No se pudo reintentar la identidad'}}}
