import Link from 'next/link';
import Kpi from '@/components/Kpi';
import Segmented from '@/components/Segmented';
import IdentityRetryButton from '@/components/IdentityRetryButton';
import {getIdentityCatalogPage,getPlexIdentityPage,getIdentityWorkflowStats} from '@/lib/identity-page';
import {savePlexIdentityAction} from '@/app/actions';
import {saveIdentityPageAction} from './actions';
import './identity.css';
export const dynamic='force-dynamic';
const nf=n=>Number(n||0).toLocaleString('es-ES');
function qs(p,patch={}){const x=new URLSearchParams();for(const[k,v]of Object.entries({...p,...patch}))if(v!==undefined&&v!==null&&v!=='')x.set(k,String(v));return x.toString()}
function badges(r){return <div className="identity-badges">{r.missing_tmdb&&<span className="ib orange">Sin TMDb</span>}{r.missing_fa&&<span className="ib green">Sin FA</span>}{r.doubtful&&<span className="ib amber">Dudosa</span>}{!r.missing_tmdb&&!r.missing_fa&&<span className="ib refresh">Identidad completa</span>}</div>}
function Pager({p,page,pages}){if(pages<=1)return null;const prev=Math.max(1,page-1),next=Math.min(pages,page+1);return <div className="identity-pager"><Link className={page<=1?'disabled':''} href={'/calidad/identidad?'+qs(p,{page:prev})}>← Anterior</Link><span>Página <b>{page}</b> de <b>{pages}</b></span><Link className={page>=pages?'disabled':''} href={'/calidad/identidad?'+qs(p,{page:next})}>Siguiente →</Link></div>}
export default async function Identidad({searchParams}){
  const p=await searchParams,mode=p.mode==='plex'?'plex':'catalog',issue=p.issue||'',type=p.type||'',q=p.q||'',page=Math.max(1,Number(p.page)||1),pageSize=50;
  const [stats,catalog,plex]=await Promise.all([getIdentityWorkflowStats(),getIdentityCatalogPage({issue,type,q,page,pageSize}),getPlexIdentityPage({q,page,pageSize})]);
  const data=mode==='catalog'?catalog:plex;
  return <><div className="breadcrumbs"><Link href="/calidad">Calidad</Link><span>›</span><b>Identidad</b></div>
  <div className="identity-head"><div><div className="eyebrow">Integridad maestra</div><h1>Identidad</h1><p>Resuelve cada título de forma individual. PikoFilm busca solo los IDs de identidad que falten y te informa del resultado y del siguiente paso.</p></div></div>
  <div className="identity-kpis"><Kpi label="Pendientes de identidad" value={stats.affected_catalog||0} hint={`Plex sin IMDb ${stats.missing_plex_imdb||0}`}/><Kpi label="Sin TMDb" value={stats.missing_tmdb}/><Kpi label="Sin FilmAffinity" value={stats.missing_fa}/></div>
  <div className="identity-tabs"><Link className={mode==='catalog'?'active':''} href={'/calidad/identidad?'+qs(p,{mode:'catalog',page:1})}>CATÁLOGO ({nf(stats.affected_catalog)})</Link><Link className={mode==='plex'?'active':''} href={'/calidad/identidad?'+qs(p,{mode:'plex',page:1})}>PLEX ({nf(stats.missing_plex_imdb)})</Link></div>
  <div className="identity-toolbar"><form method="get"><input type="hidden" name="mode" value={mode}/><input type="hidden" name="issue" value={issue}/><input type="hidden" name="type" value={type}/><input name="q" defaultValue={q} placeholder="Buscar título…"/><button>Buscar</button>{q&&<Link href={`/calidad/identidad?mode=${mode}`}>Limpiar</Link>}</form>{mode==='catalog'&&<Segmented value={issue} items={[{value:'',label:'Todos',href:'/calidad/identidad?'+qs(p,{issue:'',page:1})},{value:'missing_tmdb',label:'Sin TMDb',href:'/calidad/identidad?'+qs(p,{issue:'missing_tmdb',page:1})},{value:'missing_fa',label:'Sin FA',href:'/calidad/identidad?'+qs(p,{issue:'missing_fa',page:1})},{value:'doubtful',label:'Dudosas',href:'/calidad/identidad?'+qs(p,{issue:'doubtful',page:1})}]}/>}</div>
  <section className="identity-table-wrap"><div className="identity-panel-head"><div><b>{mode==='catalog'?'Catálogo: obtener identidad':'Plex: elementos sin IMDb'}</b><span>{nf(data.total)} resultados · 50 por página</span></div></div>
  {mode==='catalog'?<table className="identity-table"><thead><tr><th>Título</th><th>Estado</th><th>IMDb</th><th>TMDb</th><th>FilmAffinity</th><th>Acciones</th></tr></thead><tbody>{catalog.rows.map(r=><tr key={r.imdb_id}><td><b>{r.display_title}</b><small>{r.type} · {r.year||'—'}{r.original_title&&r.original_title!==r.display_title?` · ${r.original_title}`:''}</small></td><td>{badges(r)}</td><td className="id-ok">{r.imdb_id||'—'}</td><td className={r.missing_tmdb?'id-bad':'id-ok'}>{r.tmdb_id||'—'}</td><td className={r.missing_fa?'id-bad':'id-ok'}>{r.fa_id||'—'}</td><td><div className="table-actions"><IdentityRetryButton imdbId={r.imdb_id}/><details><summary className="button ghost">✎ Corregir</summary><form action={saveIdentityPageAction} className="identity-edit"><input type="hidden" name="imdbId" value={r.imdb_id}/><label>IMDb<input name="newImdbId" defaultValue={r.imdb_id}/></label><label>TMDb<input name="tmdbId" defaultValue={r.tmdb_id||''}/></label><label>FilmAffinity<input name="faId" defaultValue={r.fa_id||''}/></label><button>Guardar IDs</button></form></details><Link className="button ghost" href={`/catalogo/${r.imdb_id}?from=${encodeURIComponent('/calidad/identidad')}`}>Abrir</Link></div></td></tr>)}</tbody></table>:<table className="identity-table"><thead><tr><th>Título Plex</th><th>Tipo</th><th>TMDb</th><th>FA</th><th>Asignar identidad</th></tr></thead><tbody>{plex.rows.map(r=><tr key={r.rating_key}><td><b>{r.display_title}</b><small>{r.year||'—'} · Plex #{r.rating_key}</small></td><td>{r.item_type==='show'?'Serie':'Película'}</td><td>{r.tmdb_id||'—'}</td><td>{r.fa_id||'—'}</td><td><form action={savePlexIdentityAction} className="plex-save"><input type="hidden" name="ratingKey" value={r.rating_key}/><input name="imdbId" placeholder="IMDb · tt1234567"/><input name="tmdbId" defaultValue={r.tmdb_id||''} placeholder="TMDb"/><input name="faId" defaultValue={r.fa_id||''} placeholder="FA"/><button>Guardar</button></form></td></tr>)}</tbody></table>}</section>
  <Pager p={{...p,mode}} page={data.page} pages={data.pages}/>
  <div className="identity-note"><span>ⓘ “Obtener identidad” procesa solo ese título.</span><span>Busca TMDb y después FilmAffinity con la misma lógica segura del antiguo proceso global: Wikidata primero y Python como fallback.</span><span>Si consigue IMDb + TMDb + FilmAffinity, recalcula el estado y el título pasa a Validación de identidad. Si no, permanece aquí y muestra qué falta.</span><span>Ya no existe ejecución masiva desde esta pantalla.</span></div></>}
