'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {runC6BatchChunkAction} from './actions';
import styles from './pikoquality.module.css';
const nf=n=>Number(n||0).toLocaleString('es-ES');
const pct=(n,d)=>d?Math.round(Number(n||0)*1000/Number(d))/10:0;
const fmtMs=ms=>{const s=Math.max(0,Number(ms||0))/1000;return s<60?`${s.toFixed(1)} s`:`${Math.floor(s/60)}m ${Math.round(s%60)}s`};
export default function C6BatchRunner({initial}){const router=useRouter(),[running,setRunning]=useState(false),[current,setCurrent]=useState(Number(initial.current||0)),[remaining,setRemaining]=useState(Number(initial.pending||0)),[processed,setProcessed]=useState(0),[speed,setSpeed]=useState(0),[elapsed,setElapsed]=useState(0),[error,setError]=useState('');const total=Number(initial.total||0);async function runAll(){if(running||remaining<=0)return;setRunning(true);setError('');setProcessed(0);setSpeed(0);setElapsed(0);const started=performance.now();let left=remaining,done=0;try{while(left>0){const r=await runC6BatchChunkAction();done+=Number(r.processed||0);left=Number(r.remaining||0);const ms=performance.now()-started;setProcessed(done);setRemaining(left);setCurrent(total-left);setElapsed(ms);setSpeed(ms?Math.round(done/(ms/1000)):0);if(Number(r.processed||0)===0)break}router.refresh()}catch(e){setError(e?.message||'Error ejecutando PikoQuality C6')}finally{setRunning(false)}}const progress=pct(current,total);return <section className={styles.syncPanel}><div className={styles.syncHeader}><div><span className={styles.kicker}>PIKOQUALITY 2.0 · REGLA DE ORO</span><h2>Cálculo C6</h2><p>Batch interno sobre snapshots técnicos ya persistidos. No consulta Plex.</p></div><div className={`${styles.syncState} ${remaining===0?styles.syncState_completed:''}`}>{initial.version}</div></div><div className={styles.syncProgress}><div className={styles.syncProgressHead}><span>Progreso C6 vigente</span><b>{nf(current)} / {nf(total)} · {progress}%</b></div><div className={styles.progressTrack}><span style={{width:`${Math.min(100,progress)}%`}}/></div><small>{nf(remaining)} pendientes · {nf(initial.changed)} por archivo cambiado · {nf(initial.errors)} errores</small></div><div className={styles.syncSummary}><div><span>Pendientes</span><strong>{nf(remaining)}</strong><small>de {nf(total)} calculables</small></div><div><span>Procesados esta ejecución</span><strong>{nf(processed)}</strong><small>bloques de 10.000</small></div><div><span>Velocidad</span><strong>{running?`${nf(speed)} / s`:'—'}</strong><small>solo CPU + Neon</small></div><div><span>Tiempo</span><strong>{processed?fmtMs(elapsed):'—'}</strong><small>sin llamadas a Plex</small></div></div>{error?<div className={styles.syncError}>{error}</div>:null}<div className={styles.syncActions}><button className={styles.primaryButton} onClick={runAll} disabled={running||remaining<=0}>{running?'Calculando C6…':remaining>0?'Calcular pendientes C6':'PikoQuality C6 al día'}</button><div className={styles.syncActionNote}>{running?`Procesando · ${nf(remaining)} pendientes`:`Nunca C6: ${nf(initial.neverC6)}. Solo se recalcula si falta C6 o cambia el technical_fingerprint.`}</div></div></section>}
