import Link from '@/components/NoPrefetchLink';
import PendingSubmitButton from '@/components/PendingSubmitButton';
import {db} from '../../../lib/db';
import {PIKOQUALITY_ACTIVE_VERSION} from '../../../lib/pikoquality-version.mjs';
import {getPikoQualityState} from '../../../lib/pikoquality-state';
import {getPikoQualityLibrary} from '../../../lib/pikoquality-library';
import {recalculatePikoQualityEntityAction} from './actions';
import styles from './pikoquality.module.css';
export const dynamic='force-dynamic';
const nf=n=>Number(n||0).toLocaleString('es-ES');
const labels={fail:'Suspenso',sufficient:'Suficiente',good:'Bien',notable:'Notable',outstanding:'Sobresaliente',honors:'Matrícula'};
const ranges={fail:'< 5,0',sufficient:'5,0–5,9',good:'6,0–6,9',notable:'7,0–8,4',outstanding:'8,5–9,4',honors:'≥ 9,5'};
const pct=(n,t)=>t?Math.round(Number(n||0)*1000/Number(t))/10:0;
const coveragePct=(n,t)=>t?Math.round(Number(n||0)*10000/Number(t))/100:100;
function href(sp,patch){const p=new URLSearchParams();for(const[k,v]of Object.entries({...sp,...patch})){if(v!==''&&v!=null&&!(k==='page'&&Number(v)===1))p.set(k,String(v))}const q=p.toString();return`/calidad/pikoquality${q?`?${q}`:''}`}
export default async function Page({searchParams}){
  const raw=await searchParams||{};
  const f={q:String(raw.q||''),kind:String(raw.kind||''),band:String(raw.band||''),priority:String(raw.priority||''),sort:String(raw.sort||'priority'),page:Math.max(1,Number(raw.page)||1)};
  const load=raw.view==='library'||Boolean(f.q||f.kind||f.band||f.priority),sql=db();
  const[s,library,[capture],[activeMaintenance]]=await Promise.all([
    getPikoQualityState(),
    getPikoQualityLibrary({...f,load}),
    sql`SELECT count(*)::int physical,count(*) FILTER(WHERE pts.snapshot_status='ready' AND pts.technical_fingerprint IS NOT NULL)::int ready,count(*) FILTER(WHERE pts.rating_key IS NULL)::int missing_state,count(*) FILTER(WHERE pts.snapshot_status='pending')::int pending,count(*) FILTER(WHERE pts.snapshot_status='error')::int errors,count(*) FILTER(WHERE pts.snapshot_status='ready' AND pts.technical_fingerprint IS NULL)::int invalid_ready FROM plex_items p LEFT JOIN plex_technical_state pts ON pts.rating_key=p.rating_key WHERE p.active AND p.item_type IN('movie','episode')`,
    sql`SELECT run_id,process_code,technical_status FROM process_runs WHERE process_code IN('PROC-PQ-001','PROC-PQ-002') AND technical_status IN('queued','running') ORDER BY requested_at DESC LIMIT 1`
  ]);
  const physical=Number(capture?.physical||0),technicalReady=Number(capture?.ready||0),technicalErrors=Number(capture?.errors||0),captureWaiting=Number(capture?.missing_state||0)+Number(capture?.pending||0)+Number(capture?.invalid_ready||0),capturePending=Math.max(0,physical-technicalReady),coverage=coveragePct(s.evaluated,physical),sum=library.summary||{},dist=sum.distribution||{};
  const c6Errors=Number(s.errors||0),c6Pending=Number(s.pending_a||0),maintenanceActive=Boolean(activeMaintenance),allDone=c6Pending===0&&c6Errors===0&&capturePending===0;
  const heroTitle=allDone?'Biblioteca evaluada y al día':maintenanceActive?'PikoFilm está actualizando calidad técnica':technicalErrors+c6Errors>0?'Hay errores técnicos pendientes de revisión':'Hay mantenimiento técnico pendiente';
  const maintenanceParts=[];if(technicalErrors)maintenanceParts.push(`${nf(technicalErrors)} error(es) de captura técnica`);if(captureWaiting)maintenanceParts.push(`${nf(captureWaiting)} archivo(s) pendientes de captura`);if(c6Errors)maintenanceParts.push(`${nf(c6Errors)} error(es) C6`);if(c6Pending)maintenanceParts.push(`${nf(c6Pending)} archivo(s) pendientes de C6`);
  const maintenanceLabel=maintenanceParts.length?maintenanceParts.join(' · '):'Sin mantenimiento pendiente';
  const maintenanceCopy=technicalErrors>0?'La evidencia técnica de esos archivos falló. No se presentan como “en actualización” salvo que exista una ejecución activa; el diagnóstico y reintento viven en Operaciones.':captureWaiting>0?'Hay archivos físicos activos que todavía esperan captura técnica válida; no se contabilizan como evaluados hasta disponer de esa evidencia.':c6Errors>0?'La captura técnica existe, pero el cálculo C6 dejó errores pendientes. Revísalos en Operaciones.':c6Pending>0?'La evidencia técnica ya existe y queda cálculo C6 pendiente.':'La captura técnica y C6 están vigentes para todos los archivos físicos calculables.';
  const bands=['fail','sufficient','good','notable','outstanding','honors'];
  return <div className={styles.page}>
<div className={styles.topline}><div className={styles.titleWrap}><div className={styles.logo}>☆</div><div><h1>PikoQuality <span className={styles.version}>v{PIKOQUALITY_ACTIVE_VERSION}</span></h1><p className={styles.subtitle}>Salud de la biblioteca y prioridades para decidir qué copias merece la pena mejorar.</p></div></div><Link className="btn" href="/calidad/centro">← Centro de Calidad</Link></div>
<section className={styles.healthHero}><div><span className={styles.kicker}>SALUD DE LA BIBLIOTECA</span><h2>{heroTitle}</h2><p>La vista de decisión trabaja con <b>películas y temporadas</b>. Los capítulos se analizan internamente, pero no aparecen como unidades de trabajo.</p></div><div className={styles.healthStats}><div><span>PikoQuality media</span><strong>{sum.avg_quality?Number(sum.avg_quality).toLocaleString('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2}):'—'}</strong><small>sobre películas + temporadas</small></div><div><span>Candidatos suspensos</span><strong>{nf(sum.fail)}</strong><small>{pct(sum.fail,sum.total)}% de la vista</small></div><div><span>Prioridad alta</span><strong>{nf(sum.high_priority)}</strong><small>PikoScore²·² × déficit PikoQuality</small></div><div><span>Cobertura vigente</span><strong>{coverage.toLocaleString('es-ES',{minimumFractionDigits:coverage===100?0:2,maximumFractionDigits:2})}%</strong><small>{nf(s.evaluated)} evaluados · {nf(technicalErrors)} error(es) de captura</small></div></div></section>
<section className={styles.panel}><div className={styles.sectionHead}><div><h2>Distribución de calidad</h2><p className={styles.subtitle}>Pulsa una categoría para consultar directamente sus películas y temporadas.</p></div><span className={styles.range}>{nf(sum.movies)} películas · {nf(sum.seasons)} temporadas</span></div><div className={styles.distribution}>{bands.map(k=><Link key={k} className={`${styles.band} ${styles.bandLink} ${styles[k==='fail'?'deficient':k==='sufficient'?'improvable':k==='good'?'correct':k==='notable'?'verygood':k==='outstanding'?'excellent':'honors']}`} href={href(f,{view:'library',band:k,page:1})}><span>{labels[k]}</span><strong>{pct(dist[k],sum.total)}%</strong><small>{nf(dist[k])} obras/temporadas · {ranges[k]}</small></Link>)}</div></section>
<section className={styles.panel}><div className={styles.sectionHead}><div><span className={styles.kicker}>¿QUÉ DEBERÍA MEJORAR?</span><h2>Prioridad de mejora</h2><p className={styles.subtitle}>PikoScore pondera el valor de la obra y PikoQuality el margen de mejora. Una obra excelente con una copia floja sube antes que una obra poco valiosa.</p></div>{!load?<Link className={styles.primaryLink} href="/calidad/pikoquality?view=library&priority=high">Ver prioridades altas</Link>:null}</div>
<form className={styles.decisionFilters} method="get"><input type="hidden" name="view" value="library"/><label><span>Buscar</span><input name="q" defaultValue={f.q} placeholder="Película o serie"/></label><label><span>Tipo</span><select name="kind" defaultValue={f.kind}><option value="">Películas + temporadas</option><option value="movie">Películas</option><option value="season">Temporadas</option></select></label><label><span>Calidad</span><select name="band" defaultValue={f.band}><option value="">Todas</option>{bands.map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label><label><span>Prioridad</span><select name="priority" defaultValue={f.priority}><option value="">Todas</option><option value="high">Alta (≥40)</option><option value="medium">Media (30–39,9)</option><option value="low">Baja (&lt;30)</option></select></label><label><span>Orden</span><select name="sort" defaultValue={f.sort}><option value="priority">Prioridad recomendada</option><option value="quality">Peor PikoQuality</option><option value="pikoscore">Mejor PikoScore</option><option value="title">Título</option></select></label><button className={styles.primaryButton}>Consultar</button>{load?<Link className={styles.clearFilters} href="/calidad/pikoquality">Cerrar consulta</Link>:null}</form>
{load?<><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Obra</th><th>Tipo</th><th>PikoScore</th><th>PikoQuality</th><th>Prioridad</th><th>Lectura rápida</th><th>Acción</th></tr></thead><tbody>{library.rows.length?library.rows.map(r=><tr key={`${r.kind}:${r.entity_key}`}><td><strong>{r.title}</strong><br/><span className={styles.muted}>{r.item_year||'—'}</span></td><td>{r.kind==='movie'?'Película':`Temporada ${r.season_index}`}</td><td><b>{r.pikoscore!=null?Number(r.pikoscore).toLocaleString('es-ES',{minimumFractionDigits:1,maximumFractionDigits:1}):'—'}</b></td><td><b>{Number(r.pikoquality).toLocaleString('es-ES',{minimumFractionDigits:1,maximumFractionDigits:1})}</b><br/><span className={styles.muted}>{labels[r.band]||r.band}</span></td><td><span className={`${styles.priorityBadge} ${styles[`priority${r.priority_label}`]||''}`}>{r.priority_label}</span><br/><small>{r.priority_score!=null?`${r.priority_score}/100`:'Sin PikoScore'}</small></td><td>{r.pikoscore==null?'Falta PikoScore':r.priority_label==='Alta'?'Merece revisión prioritaria':r.priority_label==='Media'?'Mejorable, sin urgencia':'Baja prioridad de sustitución'}</td><td><form action={recalculatePikoQualityEntityAction}><input type="hidden" name="kind" value={r.kind}/><input type="hidden" name="ratingKey" value={r.href_key}/>{r.kind==='season'?<input type="hidden" name="seasonIndex" value={r.season_index}/>:null}<PendingSubmitButton className={styles.rowAction} pendingLabel="Recalculando…">↻ Recalcular ahora</PendingSubmitButton></form></td></tr>):<tr><td colSpan="7"><div className={styles.emptyState}><b>No hay resultados.</b><span>Prueba otros filtros.</span></div></td></tr>}</tbody></table></div>{library.pageCount>1?<nav className={styles.pagination} aria-label="Paginación PikoQuality">{library.page>1?<Link href={href({...f,view:'library'},{page:library.page-1})}>← Anterior</Link>:<span className={styles.pageDisabled} aria-disabled="true">← Anterior</span>}<span>Página {library.page} de {library.pageCount} · {nf(library.total)} resultados</span>{library.page<library.pageCount?<Link href={href({...f,view:'library'},{page:library.page+1})}>Siguiente →</Link>:<span className={styles.pageDisabled} aria-disabled="true">Siguiente →</span>}</nav>:null}</>:<div className={styles.queryEmpty}><b>No cargamos miles de filas al entrar.</b><span>Usa los filtros, pulsa una banda o abre las prioridades altas. La portada solo ejecuta agregados ligeros.</span></div>}</section>
<section className={styles.maintenanceInfo}><div><span className={styles.kicker}>{maintenanceActive?'MANTENIMIENTO EN CURSO':'SEGUIMIENTO TÉCNICO'}</span><b>{maintenanceLabel}</b><p>{maintenanceCopy}</p></div><Link className={styles.primaryLink} href="/admin/pikoquality">Abrir mantenimiento técnico →</Link></section>
<div className={styles.adminNote}>ⓘ Prioridad = 100 × (PikoScore/10)^2,2 × ((10 − PikoQuality)/10). Es una ayuda de decisión y no modifica PikoScore ni PikoQuality. Los episodios siguen siendo la base técnica; esta pantalla los resume por temporada.</div></div>}
